// P1-6 人工整理清单：术语、代码片段类选项无法机械续写，逐条改写。
//
// 约定：
//   · oldAnswerText/newAnswerText：把过长的正确项改成同等正确但更凝练的表达；
//   · oldDistractorText/newDistractorText：把过短的错误项补成自然、仍然错误的表达；
//   · 只写需要改的一侧，两侧都写表示同题同时调整；
//   · 改动后必须让「正确项 - 最长干扰项」小于 5 个字符，否则工具会拒绝写回。
class CuratedRewrite {
  const CuratedRewrite({
    required this.lessonId,
    required this.questionKeyword,
    this.oldDistractorText,
    this.newDistractorText,
    this.oldAnswerText,
    this.newAnswerText,
  });

  final String lessonId;
  final String questionKeyword;
  final String? oldDistractorText;
  final String? newDistractorText;
  final String? oldAnswerText;
  final String? newAnswerText;

  bool get rewritesAnswer => oldAnswerText != null && newAnswerText != null;

  bool get rewritesDistractor =>
      oldDistractorText != null && newDistractorText != null;
}

const List<CuratedRewrite> curatedRewrites = <CuratedRewrite>[
  CuratedRewrite(
    lessonId: 'flutter_state',
    questionKeyword: 'dispose 中释放控制器',
    oldDistractorText: 'UI 卡顿',
    newDistractorText: '只引起一次性的 UI 卡顿',
  ),
  CuratedRewrite(
    lessonId: 'flutter_state',
    questionKeyword: 'ChangeNotifier 子类中通知界面刷新',
    oldDistractorText: 'setState',
    newDistractorText: '只属于 State 的 setState',
  ),
  CuratedRewrite(
    lessonId: 'flutter_release',
    questionKeyword: 'minSdk / targetSdk',
    oldDistractorText: 'AndroidManifest.xml 的 application 标签',
    newDistractorText: 'AndroidManifest.xml 的 application 标签，用于声明权限与组件',
  ),
  CuratedRewrite(
    lessonId: 'mobile_swift',
    questionKeyword: '管理共享模型状态',
    oldDistractorText: 'UserDefaults',
    newDistractorText: '把模型存进 UserDefaults',
  ),
  CuratedRewrite(
    lessonId: 'html_basics',
    questionKeyword: 'meta viewport',
    oldDistractorText: '引入样式',
    newDistractorText: '只负责引入页面的全局样式',
  ),
  CuratedRewrite(
    lessonId: 'css_layout',
    questionKeyword: '做动画时应优先修改',
    oldDistractorText: 'width 和 height',
    newDistractorText: 'width 和 height 这类会触发布局的属性',
  ),
  CuratedRewrite(
    lessonId: 'html_css_project',
    questionKeyword: '累积布局偏移',
    oldDistractorText: '用 background-image',
    newDistractorText: '只用 background-image 展示图片，而它无法提前预留占位空间',
  ),
  CuratedRewrite(
    lessonId: 'html_css_project',
    questionKeyword: '跟随系统深色模式',
    oldDistractorText: 'orientation',
    newDistractorText: 'orientation 这类设备方向查询',
  ),
  CuratedRewrite(
    lessonId: 'python_basics',
    questionKeyword: '混用 Tab 和空格',
    oldDistractorText: 'SyntaxError',
    newDistractorText: '抛出 SyntaxError',
  ),
  CuratedRewrite(
    lessonId: 'python_oop',
    questionKeyword: '@classmethod 与 @staticmethod',
    oldDistractorText: 'staticmethod 能访问实例属性',
    newDistractorText: 'staticmethod 能访问实例属性，也会自动接收 self，所以在任何场景下都可以互换',
  ),
  CuratedRewrite(
    lessonId: 'python_errors_files',
    questionKeyword: '读取一个不存在的文件',
    oldDistractorText: 'IndexError',
    newDistractorText: '抛出 IndexError',
  ),
  CuratedRewrite(
    lessonId: 'python_modules_stdlib',
    questionKeyword: '统计词频最方便',
    oldDistractorText: 'subprocess',
    newDistractorText: '改用 subprocess 处理词频',
  ),
  CuratedRewrite(
    lessonId: 'python_project',
    questionKeyword: '按作者分组求均值',
    oldDistractorText: 'df.sort_values',
    newDistractorText: 'df.sort_values 先按作者排序，再求均值',
  ),
  CuratedRewrite(
    lessonId: 'python_project',
    questionKeyword: '保存成 CSV',
    oldAnswerText: "df.to_csv('out.csv', index=False)",
    newAnswerText: "df.to_csv('out.csv')",
  ),
  CuratedRewrite(
    lessonId: 'python_project_api',
    questionKeyword: 'Pydantic 模型最适合',
    oldDistractorText: '数据库迁移',
    newDistractorText: '负责数据库迁移',
  ),
  CuratedRewrite(
    lessonId: 'cpp_modern',
    questionKeyword: 'T&& 通常被称为',
    oldAnswerText: '转发引用（universal reference），配合 std::forward 实现完美转发',
    newAnswerText: '转发引用（universal reference）',
    oldDistractorText: '右值引用，只能绑定右值',
    newDistractorText: '右值引用，只能绑定右值，完全无法绑定左值表达式',
  ),
  CuratedRewrite(
    lessonId: 'cpp_project',
    questionKeyword: '开启 AddressSanitizer',
    oldAnswerText:
        '在 Debug/CI 构建中加入 -fsanitize=address,undefined 并链接 sanitizer 运行时',
    newAnswerText: '在 Debug/CI 构建中开启并链接运行时',
    oldDistractorText: '只在 Release 构建中开启',
    newDistractorText: '只在 Release 构建中开启，并且不需要链接运行时',
  ),
  CuratedRewrite(
    lessonId: 'java_basics',
    questionKeyword: 'Java 程序入口方法的正确签名',
    oldDistractorText: 'public void main(String[] args)',
    newDistractorText: 'public void main(String[] args) 即可',
  ),
  CuratedRewrite(
    lessonId: 'java_project',
    questionKeyword: '@RestController 与 @Controller 的差别',
    oldAnswerText:
        '@RestController 默认把返回值序列化为 JSON（相当于 @Controller + @ResponseBody）',
    newAnswerText: '@RestController 默认返回 JSON',
  ),
  CuratedRewrite(
    lessonId: 'java_project_inventory',
    questionKeyword: '集成测试相比单元测试',
    oldDistractorText: 'UI 颜色',
    newDistractorText: '只覆盖 UI 颜色',
  ),
  CuratedRewrite(
    lessonId: 'swift_loops',
    questionKeyword: '以步长 2 遍历 0 到 10',
    oldDistractorText: 'for (i = 0; i <= 10; i += 2)',
    newDistractorText: 'for (i = 0; i <= 10; i += 2)，但 Swift 不支持这种写法',
  ),
  CuratedRewrite(
    lessonId: 'js_objects',
    questionKeyword: 'const { a = 1 }',
    oldDistractorText: 'undefined',
    newDistractorText: '结果仍然是 undefined，不会取默认值',
  ),
  CuratedRewrite(
    lessonId: 'js_arrays',
    questionKeyword: 'reduce 的典型用途',
    oldDistractorText: '筛选元素',
    newDistractorText: '筛选元素并保持数组长度不变',
  ),
  CuratedRewrite(
    lessonId: 'js_modules_tooling',
    questionKeyword: '导出模块默认值的语法',
    oldDistractorText: "export * from './a'",
    newDistractorText: "export * from './a'，用于重导出模块",
  ),
  CuratedRewrite(
    lessonId: 'js_project',
    questionKeyword: '列表渲染时 key 的作用',
    oldDistractorText: '声明类型',
    newDistractorText: '只在列表渲染时声明元素的数据类型信息',
  ),
  CuratedRewrite(
    lessonId: 'js_project',
    questionKeyword: 'npm run build 之后产物',
    oldDistractorText: 'Docker 镜像',
    newDistractorText: 'Docker 镜像，可以直接部署到集群',
  ),
  CuratedRewrite(
    lessonId: 'csharp_project',
    questionKeyword: '使用 DTO 而不是直接暴露实体',
    oldDistractorText: '减少代码量',
    newDistractorText: '只是为了减少重复代码量',
  ),
  CuratedRewrite(
    lessonId: 'go_basics',
    questionKeyword: '向 nil map 写入',
    oldDistractorText: '返回 error',
    newDistractorText: '返回一个 error 值',
  ),
  CuratedRewrite(
    lessonId: 'go_concurrency',
    questionKeyword: '检测数据竞争的官方手段',
    oldDistractorText: 'go fmt',
    newDistractorText: 'go fmt 格式化代码',
  ),
  CuratedRewrite(
    lessonId: 'go_project',
    questionKeyword: '交叉编译到 Linux amd64',
    oldDistractorText: 'CGO_ENABLED=1',
    newDistractorText: 'CGO_ENABLED=1 与 -race 一起设置',
  ),
  CuratedRewrite(
    lessonId: 'go_microservice',
    questionKeyword: 'gRPC 相比 REST + JSON',
    oldAnswerText:
        '基于 HTTP/2 多路复用与 Protobuf，强类型、序列化体积小、支持流式调用',
    newAnswerText: '多路复用、强类型、序列化体积小、支持流式调用',
    oldDistractorText: '只能用于浏览器',
    newDistractorText: '只能用于浏览器，需要额外的代理与转换层',
  ),
  CuratedRewrite(
    lessonId: 'go_grpc',
    questionKeyword: '参数非法',
    oldAnswerText: '使用标准 status code（InvalidArgument / Internal）',
    newAnswerText: '返回 InvalidArgument 或 Internal 状态码',
    oldDistractorText: '都返回 nil 让客户端判断数据',
    newDistractorText: '都返回 nil，让客户端根据数据内容自己判断',
  ),
  CuratedRewrite(
    lessonId: 'go_project_rest_api',
    questionKeyword: 'httptest 主要用于什么',
    oldDistractorText: '编译 C++',
    newDistractorText: '编译 C++ 代码并生成可执行文件输出',
  ),
  CuratedRewrite(
    lessonId: 'go_project_rest_api',
    questionKeyword: 'context 在服务中通常传递什么',
    oldDistractorText: '磁盘容量',
    newDistractorText: '只用于传递磁盘容量',
  ),
  CuratedRewrite(
    lessonId: 'rust_ownership',
    questionKeyword: 'Rust 中把变量赋值给另一个变量',
    oldDistractorText: '浅拷贝',
    newDistractorText: '理解为浅拷贝',
  ),
  CuratedRewrite(
    lessonId: 'rust_ownership',
    questionKeyword: '为什么把 String 赋给另一个变量',
    oldAnswerText: 'i32 等实现了 Copy 的类型按位复制，String 持有堆内存只能移动所有权',
    newAnswerText: 'i32 实现了 Copy，String 只能移动所有权',
    oldDistractorText: 'String 是特殊语法',
    newDistractorText: 'String 是特殊语法，所以赋值时会复制数据',
  ),
  CuratedRewrite(
    lessonId: 'rust_types_traits',
    questionKeyword: 'dyn Trait 与泛型 T: Trait',
    oldAnswerText: 'dyn 是运行时动态分发（trait object，需指针），泛型是编译期单态化静态分发',
    newAnswerText: 'dyn 运行时动态分发，泛型编译期单态化',
    oldDistractorText: 'dyn 不能在集合中使用',
    newDistractorText: 'dyn 不能在集合中使用，需要装箱',
  ),
  CuratedRewrite(
    lessonId: 'rust_types_traits',
    questionKeyword: '孤儿规则',
    oldAnswerText: '只有 trait 或目标类型至少有一个定义在当前 crate 时才能实现该 trait',
    newAnswerText: 'trait 或类型至少要有一个定义在当前 crate',
    oldDistractorText: '任何类型都能实现任何 trait',
    newDistractorText: '任何类型都能实现任何 trait，不需要考虑所属 crate',
  ),
  CuratedRewrite(
    lessonId: 'rust_errors_iterators',
    questionKeyword: 'collect::<Result<Vec<_>, _>>',
    oldAnswerText: '把一组 Result 收集成 Result<Vec<_>, _>，遇到 Err 就短路返回错误',
    newAnswerText: '收集成 Result<Vec<_>, _>，遇 Err 短路',
    oldDistractorText: '把 Result 转成字符串',
    newDistractorText: '把 Result 转成字符串，再逐个手动拼接成结果输出',
  ),
  CuratedRewrite(
    lessonId: 'rust_async_tokio',
    questionKeyword: 'CPU 密集计算',
    oldDistractorText: '直接 await',
    newDistractorText: '直接在异步任务里 await 这个普通 future',
  ),
  CuratedRewrite(
    lessonId: 'rust_project_axum_api',
    questionKeyword: 'SQLx 参数绑定主要防止什么',
    oldDistractorText: '内存泄漏',
    newDistractorText: '只防止内存泄漏',
  ),
  CuratedRewrite(
    lessonId: 'rust_project_downloader',
    questionKeyword: '下载写入为什么先写临时文件',
    oldDistractorText: '提高颜色',
    newDistractorText: '只是为了减少磁盘写入次数',
  ),
  CuratedRewrite(
    lessonId: 'ts_utility_types',
    questionKeyword: '.d.ts 文件的作用',
    oldDistractorText: '压缩代码',
    newDistractorText: '用来压缩、混淆并优化代码体积',
  ),
  CuratedRewrite(
    lessonId: 'ts_project',
    questionKeyword: '团队禁止 any 后',
    oldDistractorText: 'object',
    newDistractorText: '统一改用 object 类型',
  ),
  CuratedRewrite(
    lessonId: 'ts_build_test',
    questionKeyword: '同时产出 ESM 与 CJS',
    oldDistractorText: '只用 Babel',
    newDistractorText: '只用 Babel 转译，再手动补齐两份类型声明文件',
  ),
  CuratedRewrite(
    lessonId: 'ts_build_test',
    questionKeyword: '能拦掉漏写 await',
    oldDistractorText: 'no-explicit-any',
    newDistractorText: 'no-explicit-any 规则',
  ),
  CuratedRewrite(
    lessonId: 'ts_narrowing_generics',
    questionKeyword: 'infer 关键字用于',
    oldDistractorText: '推断变量值',
    newDistractorText: '推断变量的具体值',
  ),
  CuratedRewrite(
    lessonId: 'ts_project_cli',
    questionKeyword: '判别联合最适合表达什么',
    oldDistractorText: '无限数值',
    newDistractorText: '表示无限多个数值',
  ),
  CuratedRewrite(
    lessonId: 'ts_project_cli',
    questionKeyword: 'tsup 在项目中的作用',
    oldDistractorText: '管理数据库',
    newDistractorText: '管理项目数据库',
  ),
  CuratedRewrite(
    lessonId: 'ts_project_cli',
    questionKeyword: 'dry-run 的主要价值',
    oldDistractorText: '提升类型',
    newDistractorText: '用来提升类型推断的准确性',
  ),
  CuratedRewrite(
    lessonId: 'shell_loops',
    questionKeyword: '逐行读取文件内容时',
    oldDistractorText: r'for line in "$(cat file)"; do ... done',
    newDistractorText: r'for line in "$(cat file)"; do ... done，但会读入整个文件',
  ),
  CuratedRewrite(
    lessonId: 'shell_process_cron',
    questionKeyword: '终止进程时推荐的顺序',
    oldDistractorText: '直接 kill -9',
    newDistractorText: '直接 kill -9 强制结束',
  ),
  CuratedRewrite(
    lessonId: 'shell_container',
    questionKeyword: 'K8s 排查问题的推荐顺序',
    oldDistractorText: 'exec → describe → get',
    newDistractorText: 'exec → describe → get，顺序反过来',
  ),
  CuratedRewrite(
    lessonId: 'shell_project_deploy',
    questionKeyword: '部署脚本为什么需要锁',
    oldDistractorText: '减少日志',
    newDistractorText: '只为了减少日志输出',
  ),
  CuratedRewrite(
    lessonId: 'shell_project_log_analysis',
    questionKeyword: '日志分析要流式处理',
    oldDistractorText: '减少字段',
    newDistractorText: '只是为了减少字段数量',
  ),
  CuratedRewrite(
    lessonId: 'encoding',
    questionKeyword: '乱码的最常见原因',
    oldDistractorText: '内存不足',
    newDistractorText: '因为运行机器内存不足',
  ),
  CuratedRewrite(
    lessonId: 'assembly',
    questionKeyword: '属于 RISC 架构',
    oldDistractorText: 'IBM 360',
    newDistractorText: 'IBM 360 也是 RISC',
  ),
  CuratedRewrite(
    lessonId: 'assembly',
    questionKeyword: '阅读汇编代码时应重点关注',
    oldDistractorText: '变量名长度',
    newDistractorText: '只关注变量名长度',
  ),
  CuratedRewrite(
    lessonId: 'discrete_math',
    questionKeyword: '鸽巢原理在计算机中的典型应用',
    oldDistractorText: '计算复杂度',
    newDistractorText: '用来计算复杂度',
  ),
  CuratedRewrite(
    lessonId: 'interrupt_exception',
    questionKeyword: 'IOMMU 的主要作用',
    oldDistractorText: '加密网络',
    newDistractorText: '只用来加密网络流量',
  ),
  CuratedRewrite(
    lessonId: 'bubble_sort',
    questionKeyword: '冒泡排序是稳定排序的原因',
    oldAnswerText: '只在 nums[j] > nums[j+1] 时交换，相等元素不互换位置',
    newAnswerText: '只在相邻元素严格逆序时才交换',
    oldDistractorText: '使用了额外数组',
    newDistractorText: '使用了额外数组做辅助存储',
  ),
  CuratedRewrite(
    lessonId: 'two_pointers',
    questionKeyword: '滑动窗口适用于哪类问题',
    oldDistractorText: '任意子序列',
    newDistractorText: '适用于任意子序列的组合',
  ),
  CuratedRewrite(
    lessonId: 'backtracking',
    questionKeyword: '收集结果时写 path[:] 拷贝的原因',
    oldDistractorText: '类型要求',
    newDistractorText: '只是语言层面的类型要求',
  ),
  CuratedRewrite(
    lessonId: 'bit_manipulation',
    questionKeyword: '判断正整数 n 是否为 2 的幂',
    oldDistractorText: 'n >> 1 == 0',
    newDistractorText: 'n >> 1 == 0 就是这类判断题的正确写法',
  ),
  CuratedRewrite(
    lessonId: 'trie',
    questionKeyword: '节点上的 is_end 标记表示',
    oldDistractorText: '子节点数量',
    newDistractorText: '表示子节点数量',
  ),
  CuratedRewrite(
    lessonId: 'binary_answer',
    questionKeyword: '求「最大可行值」时',
    oldDistractorText: '把上界压低',
    newDistractorText: '把上界直接压低',
  ),
  CuratedRewrite(
    lessonId: 'algorithms_project',
    questionKeyword: '这类实战的验收重点',
    oldDistractorText: '注释数量',
    newDistractorText: '统计代码里注释的数量',
  ),
  CuratedRewrite(
    lessonId: 'segment_tree',
    questionKeyword: '线段树支持区间修改的关键',
    oldDistractorText: '排序',
    newDistractorText: '先做一次排序',
  ),
  CuratedRewrite(
    lessonId: 'string_matching',
    questionKeyword: 'KMP 算法的核心',
    oldDistractorText: '排序',
    newDistractorText: '对字符串先做一次排序',
  ),
  CuratedRewrite(
    lessonId: 'probabilistic_structures',
    questionKeyword: '布隆过滤器的误差特征',
    oldDistractorText: '双向误差',
    newDistractorText: '会同时出现双向误差',
  ),
  CuratedRewrite(
    lessonId: 'network_flow',
    questionKeyword: '匈牙利算法用于解决什么问题',
    oldDistractorText: '最小生成树',
    newDistractorText: '用来解决加权无向图的最小生成树问题',
  ),
  CuratedRewrite(
    lessonId: 'pentest_basics',
    questionKeyword: '渗透测试开始前最重要的一步',
    oldDistractorText: '收集子域名',
    newDistractorText: '先收集目标子域名',
  ),
  CuratedRewrite(
    lessonId: 'link_layer',
    questionKeyword: 'ARP 协议的作用',
    oldDistractorText: 'MAC 转端口',
    newDistractorText: '把 MAC 转成端口',
  ),
  CuratedRewrite(
    lessonId: 'link_layer',
    questionKeyword: 'VLAN 主要解决什么问题',
    oldDistractorText: '提高带宽',
    newDistractorText: '只是为了提高带宽',
  ),
  CuratedRewrite(
    lessonId: 'websocket',
    questionKeyword: 'WebSocket 与 HTTP 的关键区别',
    oldDistractorText: '不需要 TCP',
    newDistractorText: '说明它在传输层连 TCP 都不需要',
  ),
  CuratedRewrite(
    lessonId: 'websocket',
    questionKeyword: '断线后必须实现',
    oldDistractorText: '更换协议',
    newDistractorText: '直接更换一套新的通信协议',
  ),
  CuratedRewrite(
    lessonId: 'network_project',
    questionKeyword: 'TLS 证书链与协议版本用',
    oldDistractorText: 'nslookup',
    newDistractorText: 'nslookup 只查询 DNS 记录',
  ),
  CuratedRewrite(
    lessonId: 'network_project',
    questionKeyword: 'tcpdump 的 -w 参数作用',
    oldAnswerText: '把抓到的原始报文写入 pcap 文件，供 Wireshark 等工具离线分析',
    newAnswerText: '把抓到的原始报文写入 pcap 文件',
    oldDistractorText: '只抓取指定主机',
    newDistractorText: '只抓取指定主机的报文并直接打印',
  ),
  CuratedRewrite(
    lessonId: 'ip_transport',
    questionKeyword: 'TIME_WAIT 状态的主要作用',
    oldDistractorText: '等待重传',
    newDistractorText: '为了等待丢失报文重传',
  ),
  CuratedRewrite(
    lessonId: 'distributed_transaction',
    questionKeyword: '本地消息表方案解决的核心问题',
    oldAnswerText: '业务数据修改与消息发送的原子性（借助本地事务 + 轮询投递实现最终一致）',
    newAnswerText: '业务数据修改与消息发送的原子性',
    oldDistractorText: '减少数据库连接',
    newDistractorText: '为了减少数据库连接的占用',
  ),
  CuratedRewrite(
    lessonId: 'olap_columnar',
    questionKeyword: '列式存储快的主要原因',
    oldDistractorText: '不需要索引',
    newDistractorText: '因为它完全不需要索引',
  ),
  CuratedRewrite(
    lessonId: 'search_index',
    questionKeyword: '深分页',
    oldDistractorText: '增大内存',
    newDistractorText: '通过不断增大节点内存来兜住',
  ),
  CuratedRewrite(
    lessonId: 'database_project',
    questionKeyword: '验证索引是否生效最直接的手段',
    oldDistractorText: '重启数据库',
    newDistractorText: '先重启数据库，再观察执行计划与索引的使用情况',
  ),
  CuratedRewrite(
    lessonId: 'database_project',
    questionKeyword: '用条件更新（乐观锁）扣库存失败后',
    oldDistractorText: '忽略返回值',
    newDistractorText: '直接忽略这次返回值',
  ),
  CuratedRewrite(
    lessonId: 'mysql_lock_mvcc',
    questionKeyword: '快照读与当前读的区别',
    oldAnswerText:
        '快照读读 MVCC 历史版本（普通 SELECT），当前读读最新版本并加锁（FOR UPDATE / UPDATE）',
    newAnswerText: '快照读读历史版本，当前读读最新并加锁',
    oldDistractorText: '快照读会阻塞写入',
    newDistractorText: '快照读会阻塞其它事务的写入操作',
  ),
  CuratedRewrite(
    lessonId: 'process_thread',
    questionKeyword: 'CPU 调度的基本单位',
    oldAnswerText: '线程（进程是资源分配的基本单位）',
    newAnswerText: '线程',
  ),
  CuratedRewrite(
    lessonId: 'scheduling',
    questionKeyword: '上下文切换的开销主要来自哪里',
    oldDistractorText: '磁盘 IO',
    newDistractorText: '来自磁盘 IO 的等待',
  ),
  CuratedRewrite(
    lessonId: 'file_system',
    questionKeyword: '日志文件系统的主要作用',
    oldDistractorText: '提高网速',
    newDistractorText: '主要用来提高网速',
  ),
  CuratedRewrite(
    lessonId: 'os_boot_security',
    questionKeyword: 'Secure Boot 的核心作用',
    oldDistractorText: '加快启动',
    newDistractorText: '主要作用是为了加快开机启动速度',
  ),
  CuratedRewrite(
    lessonId: 'os_project',
    questionKeyword: '复现竞态条件最直接的方式',
    oldDistractorText: '加锁后压测',
    newDistractorText: '先给代码加锁再压测',
  ),
  CuratedRewrite(
    lessonId: 'git_basics',
    questionKeyword: 'git rebase 与 git merge 的区别',
    oldAnswerText: 'rebase 把提交搬到新基底上得到线性历史，merge 生成合并提交保留分支结构',
    newAnswerText: 'rebase 得到线性历史，merge 保留分支结构',
    oldDistractorText: 'rebase 会产生合并提交',
    newDistractorText: 'rebase 会产生合并提交，让历史变得更复杂',
  ),
  CuratedRewrite(
    lessonId: 'observability',
    questionKeyword: '把日志、指标与链路串联起来的关键',
    oldDistractorText: '时间戳',
    newDistractorText: '用时间戳对齐',
  ),
  CuratedRewrite(
    lessonId: 'toolchain_project',
    questionKeyword: '密钥应该放在',
    oldDistractorText: '代码仓库',
    newDistractorText: '随手把密钥写进代码仓库里',
  ),
  CuratedRewrite(
    lessonId: 'toolchain_project',
    questionKeyword: '灰度发布期间主要观察什么',
    oldDistractorText: '镜像大小',
    newDistractorText: '重点观察镜像体积的变化',
  ),
  CuratedRewrite(
    lessonId: 'kubernetes',
    questionKeyword: 'Kubernetes 中 Service 的作用',
    oldAnswerText: '为一组 Pod 提供稳定的虚拟 IP 与负载均衡，屏蔽 Pod 重建带来的地址变化',
    newAnswerText: '为一组 Pod 提供稳定虚拟 IP 与负载均衡',
    oldDistractorText: '限制 Pod 的资源使用',
    newDistractorText: '限制 Pod 的资源使用与调度范围上限',
  ),
  CuratedRewrite(
    lessonId: 'gitops_argocd',
    questionKeyword: 'GitOps 与传统 CD 的关键区别',
    oldDistractorText: '不需要 CI',
    newDistractorText: '最大的区别就是完全不需要任何 CI',
  ),
  CuratedRewrite(
    lessonId: 'gitops_argocd',
    questionKeyword: 'ArgoCD 的 prune 开关作用',
    oldDistractorText: '重启 Pod',
    newDistractorText: '自动滚动重启所有 Pod',
  ),
  CuratedRewrite(
    lessonId: 'ai_deep_learning_llm',
    questionKeyword: '大模型产生幻觉的根本原因',
    oldDistractorText: '上下文太长',
    newDistractorText: '主要是因为输入的上下文过长所导致的',
  ),
  CuratedRewrite(
    lessonId: 'ai_embeddings_rag',
    questionKeyword: '嵌入（Embedding）的作用',
    oldDistractorText: '翻译语言',
    newDistractorText: '把文本翻译成语言',
  ),
  CuratedRewrite(
    lessonId: 'multimodal_rag',
    questionKeyword: '多模态 RAG 的核心难点',
    oldDistractorText: '编码格式',
    newDistractorText: '难点在于统一各种文件与接口的编码格式',
  ),
  CuratedRewrite(
    lessonId: 'vector_db',
    questionKeyword: '召回率与延迟如何权衡',
    oldAnswerText: '增大 efSearch / nprobe 等参数提高召回，但会明显增加延迟',
    newAnswerText: '调大检索参数会提高召回但增加延迟',
    oldDistractorText: '降低维度必然提高召回',
    newDistractorText: '降低向量维度必然提高召回',
  ),
  CuratedRewrite(
    lessonId: 'ai_realtime_voice',
    questionKeyword: 'Barge-in',
    oldDistractorText: '模型拒答',
    newDistractorText: '模型在听不清内容时直接拒绝回答',
  ),
  CuratedRewrite(
    lessonId: 'agent_cost_performance',
    questionKeyword: 'Agent 成本远高于普通问答的根本原因',
    oldDistractorText: '必须用 GPU',
    newDistractorText: '因为它必须一直占用大量 GPU',
  ),
  CuratedRewrite(
    lessonId: 'ai_training',
    questionKeyword: '梯度累积与梯度检查点的区别',
    oldAnswerText:
        '累积用多个小批量等效大批量（不省显存但改变有效批大小），检查点用重算激活换显存',
    newAnswerText: '累积等效大批量，检查点用重算换显存',
    oldDistractorText: '梯度累积需要更多显存',
    newDistractorText: '梯度累积会需要占用更多显存',
  ),
  CuratedRewrite(
    lessonId: 'microservices',
    questionKeyword: '微服务拆分的合理依据',
    oldDistractorText: '按代码行数',
    newDistractorText: '按代码行数来拆分',
  ),
  CuratedRewrite(
    lessonId: 'high_availability',
    questionKeyword: '错误预算用完之后应该',
    oldDistractorText: '降低 SLO',
    newDistractorText: '先把 SLO 降低',
  ),
  CuratedRewrite(
    lessonId: 'distributed_short_url_project',
    questionKeyword: '估算实例数应使用',
    oldAnswerText: '利特尔法则：并发约等于 QPS 乘平均响应时间，再留 30% 到 50% 余量',
    newAnswerText: '并发量乘平均响应时间，再留出余量',
    oldDistractorText: '按源码行数',
    newDistractorText: '只按项目源码行数来估算就够了',
  ),
  CuratedRewrite(
    lessonId: 'design_patterns',
    questionKeyword: '下面哪项属于反模式',
    oldDistractorText: '接口隔离',
    newDistractorText: '严格坚持接口隔离原则',
  ),
  CuratedRewrite(
    lessonId: 'math_calculus_gradient',
    questionKeyword: '学习率过大会导致',
    oldDistractorText: '模型变小',
    newDistractorText: '让模型的参数总量变小',
  ),
  CuratedRewrite(
    lessonId: 'cross_i18n',
    questionKeyword: 'RTL',
    oldAnswerText: 'padding-inline-start 与 margin-inline-end 等逻辑属性',
    newAnswerText: 'padding-inline-start 等逻辑属性',
    oldDistractorText: 'padding-left 与 margin-right',
    newDistractorText: 'padding-left 与 margin-right 等物理属性',
  ),
  CuratedRewrite(
    lessonId: 'visual_git_states',
    questionKeyword: '解决合并冲突的正确顺序',
    oldAnswerText: '看清两边意图 → 改成正确结果 → 删除标记 → 测试 → git add 后继续',
    newAnswerText: '看清两边意图 → 改成正确结果 → 删除标记 → 测试',
    oldDistractorText: '直接删掉冲突标记 → 提交',
    newDistractorText: '直接删掉冲突标记 → 提交，先合入主干再慢慢修吧',
  ),
  CuratedRewrite(
    lessonId: 'visual_cdn_cache',
    questionKeyword: '缓存刚过期时大量请求同时回源',
    oldAnswerText: 'stale-while-revalidate 与请求合并（collapse）',
    newAnswerText: 'stale-while-revalidate + 请求合并',
    oldDistractorText: '增加源站线程数',
    newDistractorText: '直接在源站上不断增加线程数、连接数与带宽来硬扛回源压力',
  ),
  CuratedRewrite(
    lessonId: 'project_deploy_ops',
    questionKeyword: '评估接口延迟时，应该重点看哪个指标',
    oldDistractorText: '最大延迟',
    newDistractorText: '只盯住单次请求的最大延迟',
  ),
  CuratedRewrite(
    lessonId: 'project_concurrency_runtime',
    questionKeyword: '验证内存可见性与数据竞争',
    oldDistractorText: '只看 CPU 使用率，忽略内存模型与竞态复现条件，认为指标正常就没有问题。',
    newDistractorText: '只看 CPU 使用率，忽略内存模型与竞态复现条件，认为指标正常就没有问题，直接给出结论',
  ),
];
