// P0 数据库与分布式配图数据。
module.exports = {
  sql_basics: {
    image: 'diagram_sql_join.webp',
    alt: 'SQL JOIN 四种连接方式',
    title: 'SQL JOIN：四种连接方式',
    type: 'grid',
    rows: 2,
    cols: 2,
    cells: [
      { r: 0, c: 0, text: 'INNER JOIN\n只保留两表都匹配的行', fill: '#e7eeff', stroke: '#6c8ff8', bold: true },
      { r: 0, c: 1, text: 'LEFT JOIN\n保留左表全部，右表缺失补 NULL', fill: '#e0f2fe', stroke: '#0ea5e9', bold: true },
      { r: 1, c: 0, text: 'RIGHT JOIN\n保留右表全部，左表缺失补 NULL', fill: '#dcfce7', stroke: '#16a34a', bold: true },
      { r: 1, c: 1, text: 'FULL JOIN\n两表全部保留，缺失侧补 NULL', fill: '#fef3c7', stroke: '#f59e0b', bold: true },
    ],
    caption: 'JOIN 按关联条件合并行；WHERE 与 ON 的位置会影响外连接结果，GROUP BY 在 JOIN 之后执行。',
  },
  index: {
    image: 'diagram_database_index.webp',
    alt: 'B+ 树索引结构',
    title: 'B+ 树索引：范围查询友好的多路平衡树',
    type: 'tree',
    root: {
      text: '根节点 [30 | 70]',
      children: [
        { text: '内部节点 [10 | 20]', children: [{ text: '叶子 1-20' }, { text: '叶子 21-30' }] },
        { text: '内部节点 [40 | 60]', children: [{ text: '叶子 31-60' }, { text: '叶子 61-70' }] },
        { text: '内部节点 [80 | 90]', children: [{ text: '叶子 71-90' }, { text: '叶子 91-99' }] },
      ],
    },
    notes: ['叶子节点按顺序链表连接，范围扫描只需顺序读取', '树高通常 3 到 4 层，千万级数据只需几次磁盘访问'],
    caption: '聚簇索引决定数据物理顺序；二级索引通常需要回表，覆盖索引可以避免回表。',
  },
  db_query_optimization: {
    image: 'diagram_query_optimization.webp',
    alt: '查询优化器从 SQL 到执行计划',
    title: '查询优化器：从 SQL 到执行计划',
    type: 'flow',
    steps: [
      { title: '解析与校验', desc: '语法树与权限检查' },
      { title: '逻辑优化', desc: '谓词下推、连接重排' },
      { title: '物理计划', desc: '选择索引与连接算法' },
      { title: '执行与反馈', desc: '统计信息影响后续计划' },
    ],
    notes: ['EXPLAIN 看访问类型、行数估算和额外排序', '统计信息过期会导致优化器选错索引'],
    caption: '优化器基于统计信息估算代价；EXPLAIN 看到的是计划，真实代价还要看数据分布与缓存。',
  },
  mysql_lock_mvcc: {
    image: 'diagram_mvcc.webp',
    alt: 'MVCC 版本链与 Read View',
    title: 'MVCC 与锁：读不加锁，写不阻塞读',
    type: 'flow',
    steps: [
      { title: '事务开始', desc: '分配事务 ID' },
      { title: '生成 Read View', desc: '记录活跃事务列表' },
      { title: '沿版本链查找', desc: '找到可见的历史版本' },
      { title: '提交或回滚', desc: '清理 undo 日志' },
    ],
    notes: ['快照读走 MVCC，当前读加 next-key lock', '间隙锁防止幻读，也更容易产生死锁'],
    caption: 'Read View 判断版本可见性；RR 隔离级别下快照读重复执行结果一致，当前读仍会看到最新提交。',
  },
  redis: {
    image: 'diagram_redis.webp',
    alt: 'Redis 事件循环、数据结构与持久化',
    title: 'Redis：事件循环、数据结构与持久化',
    type: 'compare',
    columns: [
      { title: 'RDB 快照', items: ['定时生成二进制快照', '恢复速度快', '故障可能丢最后一次快照', '适合备份与全量恢复'] },
      { title: 'AOF 日志', items: ['追加写命令日志', '可按秒或每次 fsync', '恢复速度较慢', '体积通常更大'] },
    ],
    notes: ['命令在单线程顺序执行，慢命令会阻塞所有客户端', '大 key、热 key 和集中过期是常见性能陷阱'],
    caption: 'Redis 用事件循环处理网络与命令；持久化在性能和数据安全之间取舍，生产环境通常两者结合。',
  },
  distributed_transaction: {
    image: 'diagram_distributed_transaction.webp',
    alt: '两阶段提交时序',
    title: '两阶段提交：准备阶段与提交阶段',
    type: 'sequence',
    actors: ['协调者', '参与者 A', '参与者 B'],
    messages: [
      { from: 0, to: 1, label: 'prepare：写入并锁定资源' },
      { from: 0, to: 2, label: 'prepare：写入并锁定资源' },
      { from: 1, to: 0, label: '投票：可以提交' },
      { from: 2, to: 0, label: '投票：可以提交' },
      { from: 0, to: 1, label: 'commit：全部提交' },
      { from: 0, to: 2, label: 'commit：全部提交' },
    ],
    caption: '2PC 在协调者故障时可能阻塞；SAGA 用本地事务加补偿换取可用性，TCC 需要预留资源。',
  },
  olap_columnar: {
    image: 'diagram_columnar.webp',
    alt: '行存与列存对比',
    title: '行存与列存：OLTP 和 OLAP 的存储取舍',
    type: 'compare',
    columns: [
      { title: '行存', items: ['一行数据连续存储', '点查与更新友好', '适合 OLTP 事务', '扫描宽表时读入多余列'] },
      { title: '列存', items: ['同一列连续存储', '压缩率高', '只读需要的列', '适合 OLAP 聚合分析'] },
    ],
    notes: ['列存常配向量化执行与谓词下推', 'ClickHouse、Doris、Parquet 都是典型列式实现'],
    caption: '列存按列压缩，扫描宽表时只读需要的列；向量化执行和谓词下推进一步加速分析。',
  },
  search_index: {
    image: 'diagram_search_index.webp',
    alt: '倒排索引与相关性打分',
    title: '倒排索引：从文档到检索结果',
    type: 'flow',
    steps: [
      { title: '分词', desc: '切词、归一化、去停用词' },
      { title: '建倒排表', desc: '词项到文档 ID 列表' },
      { title: '查询求交', desc: '合并候选文档集合' },
      { title: '打分排序', desc: 'BM25 计算相关性' },
    ],
    notes: ['正排索引按文档查字段，倒排索引按词查文档', '词典、跳表、压缩编码决定索引体积与查询速度'],
    caption: '倒排表记录词到文档列表；BM25 综合词频、文档频率和长度归一化计算相关性。',
  },
  microservices: {
    image: 'diagram_microservices.webp',
    alt: '微服务调用拓扑与数据边界',
    title: '微服务调用拓扑：网关、服务与数据边界',
    type: 'tree',
    root: {
      text: 'API 网关',
      children: [
        { text: '用户服务', children: [{ text: '用户库' }, { text: '缓存' }] },
        { text: '订单服务', children: [{ text: '订单库' }, { text: '消息队列' }] },
        { text: '支付服务', children: [{ text: '支付库' }, { text: '对账任务' }] },
      ],
    },
    notes: ['一个服务只拥有自己的数据，其他服务通过 API 或事件访问', '跨服务查询用组合或读模型，分布式事务优先最终一致性'],
    caption: '服务按业务能力拆分；网关负责路由、鉴权和限流，服务间调用需要超时、重试与熔断。',
  },
  high_availability: {
    image: 'diagram_high_availability.webp',
    alt: '高可用的冗余、故障域与容量水位',
    title: '高可用设计：冗余、故障域与容量水位',
    type: 'layers',
    layers: [
      { title: '多可用区部署', desc: '单机房故障时流量自动切换' },
      { title: '多副本与选主', desc: '数据至少三副本，多数派确认' },
      { title: '健康检查与摘除', desc: '探针发现异常实例并从负载均衡摘除' },
      { title: '容量水位与降级', desc: '预留突发容量，过载时关闭非核心功能' },
    ],
    caption: '高可用不是不出故障，而是故障时仍能服务；容量需要预留突发和故障转移空间。',
  },
  distributed_consensus: {
    image: 'diagram_consensus.webp',
    alt: 'Raft 日志复制时序',
    title: 'Raft 日志复制：多数派确认后提交',
    type: 'sequence',
    actors: ['客户端', 'Leader', 'Follower A', 'Follower B'],
    messages: [
      { from: 0, to: 1, label: '提交写请求' },
      { from: 1, to: 0, label: '追加日志并返回等待' },
      { from: 1, to: 2, label: 'AppendEntries 复制日志' },
      { from: 1, to: 3, label: 'AppendEntries 复制日志' },
      { from: 2, to: 1, label: '确认收到' },
      { from: 1, to: 0, label: '多数派确认，提交并返回' },
    ],
    caption: 'Raft 用任期和日志匹配保证一致性；选举需要多数派，分区少数派无法提交。',
  },
  distributed_cache: {
    image: 'diagram_cache_problems.webp',
    alt: '缓存穿透、击穿与雪崩',
    title: '缓存三大问题：穿透、击穿与雪崩',
    type: 'compare',
    columns: [
      { title: '缓存穿透', items: ['查询不存在的数据', '请求每次都打到数据库', '布隆过滤器拦截', '缓存空值并设短过期'] },
      { title: '缓存击穿', items: ['热点 key 突然过期', '大量请求同时回源', '互斥锁重建缓存', '热点 key 不过期或预热'] },
      { title: '缓存雪崩', items: ['大量 key 同时过期', '数据库瞬时压力飙升', '过期时间加随机值', '多级缓存与限流降级'] },
    ],
    caption: '穿透是数据不存在，击穿是单个热点失效，雪崩是大面积同时失效；三者防护手段不同。',
  },
  distributed_multisite: {
    image: 'diagram_multisite.webp',
    alt: '单元化多活流量路由与数据同步',
    title: '单元化多活：流量路由与数据同步',
    type: 'flow',
    steps: [
      { title: '流量接入', desc: '就近接入与全局负载均衡' },
      { title: '单元路由', desc: '按用户或租户维度路由' },
      { title: '单元内闭环', desc: '读写在本地单元完成' },
      { title: '跨单元同步', desc: '异步复制与冲突处理' },
    ],
    notes: ['路由维度必须贯穿所有服务与数据分片', '跨单元强一致代价高，通常选择最终一致'],
    caption: '单元化把请求限制在一个单元内；跨单元数据异步复制，需要处理冲突和一致性。',
  },
};
