// P0 网络配图数据。
module.exports = {
  http_basics: {
    image: 'diagram_http_basics.webp',
    alt: 'HTTP 请求与响应报文结构',
    title: 'HTTP 请求与响应：报文结构对照',
    type: 'compare',
    columns: [
      { title: '请求报文', items: ['请求行：方法、路径、版本', '请求头：Host、Cookie、Accept', '空行：分隔头部与正文', '请求体：表单、JSON、文件'] },
      { title: '响应报文', items: ['状态行：版本、状态码、原因', '响应头：Content-Type、Cache-Control', '空行：分隔头部与正文', '响应体：HTML、JSON、二进制'] },
    ],
    notes: ['1xx 信息、2xx 成功、3xx 重定向、4xx 客户端错误、5xx 服务端错误'],
    caption: 'HTTP 是无状态文本协议；方法、状态码、缓存头和连接复用构成基本语义。',
  },
  tls: {
    image: 'diagram_tls.webp',
    alt: 'TLS 1.3 握手时序',
    title: 'TLS 1.3 握手：加密通道如何建立',
    type: 'sequence',
    actors: ['客户端', '服务端', 'CA 证书'],
    messages: [
      { from: 0, to: 1, label: 'ClientHello + 密钥共享' },
      { from: 1, to: 0, label: 'ServerHello + 证书 + Finished' },
      { from: 0, to: 2, label: '校验证书链与域名' },
      { from: 0, to: 1, label: 'Finished，开始加密传输' },
    ],
    caption: '证书把域名绑定到公钥；会话密钥用非对称协商，之后用对称加密传输数据。',
  },
  ip_transport: {
    image: 'diagram_ip_transport.webp',
    alt: 'TCP IP 协议栈分层',
    title: 'IP 与传输层：TCP、UDP 在协议栈中的位置',
    type: 'layers',
    layers: [
      { title: '应用层', desc: 'HTTP、DNS、SMTP、WebSocket' },
      { title: '传输层', desc: 'TCP 可靠有序，UDP 低开销无连接' },
      { title: '网络层', desc: 'IP 寻址与路由，ICMP 差错报告' },
      { title: '链路层', desc: '以太网、Wi-Fi、ARP、MAC 地址' },
    ],
    caption: 'IP 负责寻址与路由，TCP 负责可靠传输，UDP 负责低开销传输；CIDR 决定子网范围。',
  },
  link_layer: {
    image: 'diagram_link_layer.webp',
    alt: 'ARP 与交换机转发时序',
    title: '以太网与 ARP：同一局域网内的寻址',
    type: 'sequence',
    actors: ['主机 A', '交换机', '主机 B'],
    messages: [
      { from: 0, to: 1, label: '广播 ARP：谁是 192.168.1.2' },
      { from: 2, to: 1, label: 'ARP 应答：我的 MAC 是 ...' },
      { from: 0, to: 1, label: '发送以太网帧，目的 MAC' },
      { from: 1, to: 2, label: '查 MAC 表并转发' },
    ],
    caption: 'ARP 把 IP 映射到 MAC；交换机根据 MAC 表转发，VLAN 用于隔离广播域。',
  },
  socket_programming: {
    image: 'diagram_socket_programming.webp',
    alt: 'TCP Socket 客户端服务端调用时序',
    title: 'Socket 编程：TCP 客户端与服务端调用时序',
    type: 'sequence',
    actors: ['客户端', '服务端'],
    messages: [
      { from: 1, to: 1, label: 'socket、bind、listen' },
      { from: 0, to: 1, label: 'connect 三次握手' },
      { from: 1, to: 0, label: 'accept 返回新连接' },
      { from: 0, to: 1, label: 'send / recv 字节流' },
      { from: 0, to: 1, label: 'close 四次挥手' },
    ],
    caption: '服务端 bind/listen/accept，客户端 connect；TCP 是字节流，需要自己处理消息边界。',
  },
  network_nat_vpn: {
    image: 'diagram_nat_vpn.webp',
    alt: 'NAT 与 VPN 的地址和隧道对比',
    title: 'NAT 与 VPN：地址转换和隧道封装',
    type: 'compare',
    columns: [
      { title: 'NAT 地址转换', items: ['私网地址共享公网地址', 'NAPT 用端口区分连接', '外部无法直接访问内部', 'P2P 需要打洞或中继'] },
      { title: 'VPN 隧道', items: ['在公网中封装加密流量', '远程接入或站点互联', '常见协议 IPsec、WireGuard', '需要处理 MTU 与路由'] },
    ],
    caption: 'NAT 让私网共享公网地址；VPN 在公网上建立加密隧道，两者都会影响端到端连接。',
  },
  network_bgp: {
    image: 'diagram_network_bgp.webp',
    alt: 'BGP 路由选择顺序',
    title: 'BGP 选路：从 Local Pref 到 AS Path',
    type: 'flow',
    direction: 'vertical',
    steps: [
      { title: 'LOCAL_PREF', desc: '本自治域内优先级最高，先比较' },
      { title: 'AS_PATH', desc: '路径越短越优先，同时防止环路' },
      { title: 'ORIGIN', desc: 'IGP 优于 EGP，EGP 优于 Incomplete' },
      { title: 'MED', desc: '向邻居提示入口偏好，影响入站流量' },
      { title: 'eBGP / IGP 度量', desc: '最后比较下一跳可达性与内部代价' },
    ],
    caption: 'BGP 以策略为中心；AS Path 防止环路，LOCAL_PREF 优先于 AS Path 长度。',
  },
  network_performance: {
    image: 'diagram_network_performance.webp',
    alt: '网页请求延迟分解瀑布图',
    title: '一次请求的延迟分解：从 DNS 到首字节',
    type: 'timeline',
    total: 10,
    tasks: [
      { label: 'DNS 解析', start: 0, duration: 1, desc: '缓存命中更快' },
      { label: 'TCP 握手', start: 1, duration: 1, desc: '1 个 RTT' },
      { label: 'TLS 握手', start: 2, duration: 2, desc: '证书与密钥协商' },
      { label: '发送请求', start: 4, duration: 1, desc: '上传请求' },
      { label: '服务端处理', start: 5, duration: 2, desc: 'TTFB' },
      { label: '内容传输', start: 7, duration: 3, desc: '下载与渲染' },
    ],
    caption: '减少 RTT、复用连接、启用缓存和 CDN 是降低延迟的主要手段。',
  },
};
