// P0 计算机基础与操作系统配图数据。
module.exports = {
  cpu: {
    image: 'diagram_cpu.webp',
    alt: 'CPU 指令周期的五个阶段',
    title: 'CPU 指令周期：取指、译码、执行、访存、写回',
    type: 'flow',
    steps: [
      { title: '取指', desc: 'PC 从内存取指令' },
      { title: '译码', desc: '识别操作与操作数' },
      { title: '执行', desc: 'ALU 完成运算' },
      { title: '访存', desc: '读写数据内存' },
      { title: '写回', desc: '结果写回寄存器' },
    ],
    caption: '流水线让多条指令重叠执行；数据冒险、控制冒险和结构冒险会打断流水线。',
  },
  compiler: {
    image: 'diagram_compiler.webp',
    alt: '从源码到可执行文件的编译四阶段',
    title: '从源码到可执行文件：编译四阶段',
    type: 'flow',
    steps: [
      { title: '预处理', desc: '展开宏与头文件' },
      { title: '编译', desc: '生成汇编代码' },
      { title: '汇编', desc: '翻译成机器码' },
      { title: '链接', desc: '合并目标文件与库' },
    ],
    notes: ['前端：词法与语法分析', '中端：IR 与优化', '后端：寄存器分配与代码生成'],
    caption: '编译把高级语言降到机器码；链接负责符号解析与地址重定位。',
  },
  linking_loading: {
    image: 'diagram_linking_loading.webp',
    alt: '静态链接与动态链接对比',
    title: '静态链接与动态链接：地址绑定时机不同',
    type: 'compare',
    columns: [
      { title: '静态链接', items: ['库代码复制进可执行文件', '启动不依赖共享库', '体积更大', '升级库需要重新链接'] },
      { title: '动态链接', items: ['运行时加载共享库', '多个程序共享内存页', '体积更小', '需要处理库版本与路径'] },
    ],
    caption: '加载器把可执行文件映射进虚拟地址空间；动态库在加载或首次调用时完成符号解析。',
  },
  float_and_check: {
    image: 'diagram_float_and_check.webp',
    alt: 'IEEE 754 浮点数与校验码',
    title: 'IEEE 754 浮点数：符号、阶码与尾数',
    type: 'grid',
    rows: 1,
    cols: 3,
    colLabels: ['符号位 1 bit', '阶码 8 bit', '尾数 23 bit'],
    cells: [
      { r: 0, c: 0, text: '0 为正\n1 为负', fill: '#e7eeff', stroke: '#6c8ff8', bold: true },
      { r: 0, c: 1, text: '偏移 127\n决定数量级', fill: '#e0f2fe', stroke: '#0ea5e9', bold: true },
      { r: 0, c: 2, text: '有效数字\n决定精度', fill: '#dcfce7', stroke: '#16a34a', bold: true },
    ],
    notes: ['浮点是近似表示，0.1 + 0.2 不等于 0.3', '校验码用冗余位发现或纠正传输错误'],
    caption: '舍入误差来自二进制无法精确表示十进制小数；海明码和 CRC 分别用于纠错与检错。',
  },
  interrupt_exception: {
    image: 'diagram_interrupt_exception.webp',
    alt: '中断处理时序与外设 DMA',
    title: '中断处理时序：外设、CPU 与内核',
    type: 'sequence',
    actors: ['外设', 'CPU', '中断处理程序'],
    messages: [
      { from: 0, to: 1, label: '发出中断请求' },
      { from: 1, to: 2, label: '保存现场并查向量表' },
      { from: 2, to: 0, label: '读取设备状态' },
      { from: 2, to: 1, label: '执行处理逻辑' },
      { from: 1, to: 0, label: '恢复现场并返回' },
    ],
    caption: '中断由外设异步触发，异常由当前指令触发；DMA 让设备直接访问内存，减少 CPU 搬运。',
  },
  digital_logic: {
    image: 'diagram_digital_logic.webp',
    alt: '从逻辑门到全加器',
    title: '从真值表到全加器：组合逻辑的搭建过程',
    type: 'flow',
    steps: [
      { title: '真值表', desc: '列出所有输入输出' },
      { title: '逻辑门', desc: '与、或、非、异或' },
      { title: '半加器', desc: '两位相加产生进位' },
      { title: '全加器', desc: '串联进位链' },
    ],
    caption: '组合逻辑没有记忆，时序逻辑引入触发器保存状态；时钟决定状态更新的节拍。',
  },
  encoding: {
    image: 'diagram_encoding.webp',
    alt: 'ASCII、UTF-8 与 UTF-16 编码对比',
    title: 'ASCII、UTF-8 与 UTF-16：字符编码对比',
    type: 'compare',
    columns: [
      { title: 'ASCII', items: ['7 位编码 128 个字符', '只覆盖英文与符号', '每个字符 1 字节', '兼容性最好'] },
      { title: 'UTF-8', items: ['变长 1 到 4 字节', '英文 1 字节', '中文通常 3 字节', '互联网事实标准'] },
      { title: 'UTF-16', items: ['基本平面 2 字节', '辅助平面 4 字节', 'Java 与 Windows 常用', '需要处理字节序'] },
    ],
    caption: 'Unicode 是字符集，UTF-8/UTF-16 是编码方式；乱码通常来自编码与解码方式不一致。',
  },
  bus_io: {
    image: 'diagram_bus_io.webp',
    alt: '总线、内存控制器与 IO 设备互连',
    title: '总线与 I/O：CPU、内存和外设如何互连',
    type: 'layers',
    layers: [
      { title: 'CPU 与缓存', desc: '发出读写请求，访问寄存器与缓存' },
      { title: '系统总线', desc: '地址总线、数据总线、控制总线' },
      { title: '内存控制器', desc: '连接 DRAM，处理刷新与带宽调度' },
      { title: 'I/O 总线与外设', desc: 'PCIe、USB、网卡、磁盘与 DMA' },
    ],
    caption: '地址总线决定寻址范围，数据总线决定单次传输宽度，控制总线负责读写、中断和握手信号。',
  },
  fundamentals_cache_coherence: {
    image: 'diagram_cache_coherence.webp',
    alt: 'MESI 缓存一致性与 NUMA',
    title: 'MESI 缓存一致性：四种状态与转换',
    type: 'cycle',
    nodes: [
      { title: 'Modified', desc: '已修改，内存过期' },
      { title: 'Exclusive', desc: '独占且与内存一致' },
      { title: 'Shared', desc: '多核共享只读' },
      { title: 'Invalid', desc: '副本失效' },
    ],
    center: 'MESI 状态机',
    backLabel: '写操作让其他副本失效，再进入 Modified',
    caption: '伪共享会让无关变量互相踢缓存；NUMA 跨节点访问延迟明显更高。',
  },
  fundamentals_storage_stack: {
    image: 'diagram_storage_stack.webp',
    alt: '从文件 API 到闪存颗粒的存储栈',
    title: '存储栈：从文件 API 到闪存颗粒',
    type: 'layers',
    layers: [
      { title: '应用与文件 API', desc: 'open、read、write、fsync' },
      { title: '文件系统', desc: '目录、inode、页缓存与日志' },
      { title: '块层与 I/O 调度', desc: '合并请求、排序、队列深度' },
      { title: 'SSD 控制器与 FTL', desc: '磨损均衡、垃圾回收、TRIM' },
      { title: '闪存颗粒', desc: '按页读写、按块擦除' },
    ],
    caption: 'SSD 先写日志再擦除；垃圾回收和写放大决定寿命与随机写性能。',
  },
  scheduling: {
    image: 'diagram_scheduling.webp',
    alt: '时间片轮转调度甘特图',
    title: '时间片轮转调度：任务轮流占用 CPU',
    type: 'timeline',
    total: 12,
    tasks: [
      { label: '任务 A', start: 0, duration: 2, desc: '运行' },
      { label: '任务 B', start: 2, duration: 2, desc: '运行' },
      { label: '任务 C', start: 4, duration: 2, desc: '运行' },
      { label: '任务 A', start: 6, duration: 2, desc: '再次调度' },
      { label: '任务 B', start: 8, duration: 2, desc: '再次调度' },
      { label: '任务 C', start: 10, duration: 2, desc: '收尾' },
    ],
    caption: '调度器在响应时间、吞吐量和公平性之间权衡；优先级反转需要优先级继承来缓解。',
  },
  os_synchronization: {
    image: 'diagram_os_synchronization.webp',
    alt: '生产者消费者信号量时序',
    title: '生产者-消费者：信号量协调缓冲区',
    type: 'sequence',
    actors: ['生产者', '缓冲区', '消费者'],
    messages: [
      { from: 0, to: 1, label: 'wait(empty) 后写入' },
      { from: 1, to: 2, label: 'signal(full) 唤醒' },
      { from: 2, to: 1, label: 'wait(full) 后取出' },
      { from: 1, to: 0, label: 'signal(empty) 唤醒' },
    ],
    caption: '互斥量保护共享变量，信号量表示资源数量；加锁顺序不当会导致死锁或饥饿。',
  },
  file_system: {
    image: 'diagram_file_system.webp',
    alt: '文件系统目录树与 inode 映射',
    title: '文件系统目录树与 inode 映射',
    type: 'tree',
    root: {
      text: '根目录 /',
      children: [
        { text: 'bin', children: [{ text: 'ls' }, { text: 'sh' }] },
        { text: 'home', children: [{ text: 'alice', children: [{ text: 'notes.txt' }, { text: 'photo.jpg' }] }] },
        { text: 'tmp', children: [{ text: 'cache' }, { text: 'socket' }] },
      ],
    },
    caption: '目录项保存文件名到 inode 的映射；inode 记录权限、大小、时间戳和数据块指针。',
  },
  ipc_io: {
    image: 'diagram_ipc_io.webp',
    alt: '管道、共享内存与消息队列对比',
    title: '进程间通信：管道、共享内存与消息队列',
    type: 'compare',
    columns: [
      { title: '管道', items: ['字节流，半双工', '父子进程常用', '内核缓冲区', '需要约定消息边界'] },
      { title: '共享内存', items: ['映射同一块物理页', '速度最快', '必须配合锁或信号量', '适合大数据量'] },
      { title: '消息队列', items: ['按消息传递', '天然有边界', '支持异步与解耦', '内核负责排队'] },
    ],
    caption: 'I/O 多路复用用 select/poll/epoll 统一等待；阻塞、非阻塞、信号驱动和异步 I/O 的差别在数据就绪通知时机。',
  },
  os_io_scheduling: {
    image: 'diagram_io_scheduling.webp',
    alt: '磁盘 IO 电梯调度顺序',
    title: '磁盘 I/O 调度：电梯算法减少寻道',
    type: 'timeline',
    total: 10,
    tasks: [
      { label: '请求 98 柱面', start: 0, duration: 2, desc: '同向' },
      { label: '请求 183 柱面', start: 2, duration: 2, desc: '同向' },
      { label: '请求 37 柱面', start: 4, duration: 2, desc: '折返' },
      { label: '请求 122 柱面', start: 6, duration: 2, desc: '折返' },
      { label: '请求 14 柱面', start: 8, duration: 2, desc: '继续' },
    ],
    caption: 'FIFO 公平但寻道长，SCAN/电梯按方向服务，CFQ 按进程分配时间片；SSD 更关心队列深度与并行度。',
  },
  os_cgroups_namespaces: {
    image: 'diagram_cgroups_namespaces.webp',
    alt: 'namespace 与 cgroup 的容器隔离边界',
    title: '容器隔离：namespaces 与 cgroups',
    type: 'compare',
    columns: [
      { title: 'namespaces 隔离视图', items: ['PID：看不到宿主进程', 'NET：独立网络栈', 'MNT：独立挂载点', 'UTS：独立主机名', 'USER：独立用户映射'] },
      { title: 'cgroups 限制资源', items: ['CPU：配额与权重', 'memory：内存上限', 'blkio：磁盘带宽', 'pids：进程数量', '统计与审计'] },
    ],
    caption: 'namespace 决定进程能看到什么，cgroup 决定进程能用多少；两者共同构成容器边界。',
  },
  os_io_uring: {
    image: 'diagram_io_uring.webp',
    alt: 'io_uring 提交与完成队列',
    title: 'io_uring：提交队列与完成队列的异步 I/O',
    type: 'flow',
    steps: [
      { title: '提交 SQE', desc: '用户态写入提交队列' },
      { title: '内核取出', desc: '批量读取请求' },
      { title: '设备执行', desc: '磁盘或网络完成 I/O' },
      { title: '写回 CQE', desc: '完成队列通知用户态' },
    ],
    notes: ['提交队列 SQ 与完成队列 CQ 由用户态和内核共享', '减少系统调用与内存拷贝，适合高并发 I/O'],
    caption: 'io_uring 支持批量提交、轮询和注册缓冲区；需要处理队列满、取消和错误完成。',
  },
  os_boot_security: {
    image: 'diagram_boot_security.webp',
    alt: '从 UEFI 到用户态的启动链',
    title: '系统启动链：从 UEFI 到用户态',
    type: 'flow',
    direction: 'vertical',
    steps: [
      { title: '固件 UEFI', desc: '自检硬件，按启动项加载引导程序' },
      { title: '引导加载程序', desc: '加载内核与 initramfs' },
      { title: '内核初始化', desc: '建立内存管理、驱动与调度器' },
      { title: 'init / systemd', desc: '挂载根文件系统并启动服务' },
      { title: '用户态服务', desc: '登录、网络、容器运行时就绪' },
    ],
    caption: '安全启动校验引导链签名；initramfs 负责加载根文件系统所需驱动，启动失败优先看内核日志与服务依赖。',
  },
};
