// P1 AI 与 Agent 配图数据。
module.exports = {
  ml_fundamentals: {
    image: 'diagram_ml_fundamentals.webp',
    alt: '欠拟合、过拟合与数据划分',
    title: '机器学习：欠拟合、过拟合与数据划分',
    type: 'compare',
    columns: [
      { title: '欠拟合', items: ['模型太简单', '训练误差和验证误差都高', '增加特征或模型容量', '减少正则化强度'] },
      { title: '过拟合', items: ['模型记住了噪声', '训练误差低、验证误差高', '增加数据或正则化', '早停与交叉验证'] },
    ],
    notes: ['训练集：拟合参数', '验证集：选择模型与超参数', '测试集：只做最终评估'],
    caption: '训练集调参数，验证集选模型，测试集只评估一次；正则化和更多数据缓解过拟合。',
  },
  ai_training: {
    image: 'diagram_ai_training.webp',
    alt: '数据并行、模型并行与流水线并行',
    title: '大模型训练并行策略',
    type: 'compare',
    columns: [
      { title: '数据并行', items: ['每张卡一份完整模型', '切分训练数据', '梯度全量同步', '受单卡显存限制'] },
      { title: '模型并行', items: ['按层或张量切分参数', '单卡放不下完整模型', '通信量大', '适合超大模型'] },
      { title: '流水线并行', items: ['模型按层分段', '微批次流水执行', '存在气泡空闲', '常与数据并行组合'] },
    ],
    caption: '数据并行复制模型切分数据，模型并行切分参数，流水线并行按层分段；显存和通信是主要瓶颈。',
  },
  ai_fine_tuning_deployment: {
    image: 'diagram_fine_tuning.webp',
    alt: 'LoRA、QLoRA 与量化部署',
    title: '微调与部署：LoRA、QLoRA 与量化',
    type: 'compare',
    columns: [
      { title: 'LoRA 微调', items: ['冻结原模型权重', '训练低秩适配矩阵', '显存占用小', '可以多任务切换适配器'] },
      { title: 'QLoRA / 量化', items: ['4bit 量化基础模型', '显存进一步降低', '训练速度较慢', '精度有少量损失'] },
    ],
    notes: ['全量微调成本最高，适合数据充足场景', '推理量化有 GPTQ、AWQ、llama.cpp 等方案'],
    caption: 'LoRA 冻结原权重只训练低秩矩阵；4bit 量化大幅降显存，但会损失部分精度。',
  },
  ai_model_serving: {
    image: 'diagram_model_serving.webp',
    alt: '大模型推理服务批处理与 KV 缓存',
    title: '大模型推理服务：批处理与 KV 缓存',
    type: 'flow',
    steps: [
      { title: '请求入队', desc: '调度器排队与优先级' },
      { title: '连续批处理', desc: '新请求动态插入批次' },
      { title: 'GPU 推理', desc: 'Prefill 与 Decode 阶段' },
      { title: '流式返回', desc: '逐 token 返回结果' },
    ],
    notes: ['KV Cache 复用历史键值，显存是主要瓶颈', 'PagedAttention 减少缓存碎片', '吞吐与首 token 延迟需要权衡'],
    caption: '连续批处理让新请求插队，PagedAttention 减少 KV 缓存碎片；吞吐和延迟需要权衡。',
  },
  ai_multimodal: {
    image: 'diagram_multimodal.webp',
    alt: '多模态模型编码、对齐与生成',
    title: '多模态模型：编码、对齐与生成',
    type: 'layers',
    layers: [
      { title: '模态编码器', desc: '图像、文本、音频分别编码成向量' },
      { title: '跨模态对齐', desc: '对比学习或注意力把模态映射到同一空间' },
      { title: '融合与推理', desc: '跨模态注意力交换信息' },
      { title: '生成解码', desc: '按目标模态生成文本、图像或语音' },
    ],
    caption: '对比学习把图像和文本映射到同一空间；跨模态注意力让模型对齐不同模态。',
  },
  ai_vlm: {
    image: 'diagram_vlm.webp',
    alt: '视觉语言模型结构与投影层',
    title: '视觉语言模型 VLM：从图像到文本',
    type: 'flow',
    steps: [
      { title: '图像分块', desc: '切分 patch 并线性投影' },
      { title: '视觉编码器', desc: 'ViT 提取图像特征' },
      { title: '投影层', desc: '对齐到语言模型维度' },
      { title: 'LLM 生成', desc: '结合文本提示自回归输出' },
    ],
    notes: ['图像 token 与文本 token 拼接后送入 LLM', '高分辨率图像需要更多视觉 token 和显存'],
    caption: '视觉编码器提取图像特征，投影层对齐到语言模型维度，LLM 自回归生成回答。',
  },
  ai_diffusion: {
    image: 'diagram_diffusion.webp',
    alt: '扩散模型加噪与去噪过程',
    title: '扩散模型：加噪与去噪',
    type: 'flow',
    steps: [
      { title: '前向加噪', desc: '逐步加入高斯噪声' },
      { title: '学习去噪', desc: '训练网络预测噪声' },
      { title: '逆向采样', desc: '从随机噪声逐步还原' },
      { title: '生成图像', desc: 'CFG 控制提示词强度' },
    ],
    notes: ['训练目标通常是预测噪声 epsilon', '采样步数越多质量越高但越慢', 'Latent Diffusion 在潜空间去噪，降低计算量'],
    caption: '训练学习预测噪声，推理从随机噪声逐步去噪；CFG 控制提示词影响强度。',
  },
  agent_memory: {
    image: 'diagram_agent_memory.webp',
    alt: 'Agent 记忆分层结构',
    title: 'Agent 记忆分层：从上下文到向量库',
    type: 'layers',
    layers: [
      { title: '工作记忆', desc: '当前任务目标、计划和中间结果' },
      { title: '短期记忆', desc: '最近几轮对话与工具调用结果' },
      { title: '长期记忆', desc: '用户偏好、历史事实和可复用经验' },
      { title: '外部存储', desc: '向量库、关系库或知识图谱按需检索' },
    ],
    caption: '工作记忆放当前任务，短期记忆保存会话，长期记忆写入向量库或知识图谱并按需检索。',
  },
  ai_tool_calling: {
    image: 'diagram_tool_calling.webp',
    alt: '模型工具调用时序',
    title: '工具调用：模型生成结构化调用',
    type: 'sequence',
    actors: ['用户', '模型', '工具'],
    messages: [
      { from: 0, to: 1, label: '提出问题与可用工具' },
      { from: 1, to: 0, label: '决定调用哪个工具' },
      { from: 1, to: 2, label: '生成 JSON 参数并执行' },
      { from: 2, to: 1, label: '返回结构化结果或错误' },
      { from: 1, to: 0, label: '结合结果生成最终回答' },
    ],
    caption: '工具名和参数用 JSON Schema 约束；执行结果回填上下文后再生成最终回答。',
  },
  ai_mcp: {
    image: 'diagram_mcp.webp',
    alt: 'MCP Host Client Server 架构',
    title: 'MCP：Host、Client 与 Server 的连接',
    type: 'layers',
    layers: [
      { title: 'Host 宿主应用', desc: 'IDE、聊天客户端或 Agent 运行时' },
      { title: 'Client 连接器', desc: '维护与 Server 的会话和权限' },
      { title: 'Server 能力端', desc: '暴露资源、工具和提示模板' },
      { title: '外部系统', desc: '文件、数据库、API 与业务服务' },
    ],
    caption: 'MCP 统一模型与外部能力的连接协议；Server 暴露资源、工具和提示模板。',
  },
  ai_a2a: {
    image: 'diagram_a2a.webp',
    alt: 'A2A Agent 任务委派时序',
    title: 'A2A：Agent 之间的任务委派',
    type: 'sequence',
    actors: ['Agent A', '协调者', 'Agent B'],
    messages: [
      { from: 0, to: 1, label: '发布任务与能力要求' },
      { from: 1, to: 2, label: '发现并委派给 Agent B' },
      { from: 2, to: 1, label: '返回进度与产物' },
      { from: 1, to: 0, label: '汇总结果或继续追问' },
    ],
    caption: 'A2A 定义 Agent 发现、任务委派和结果回传；需要处理超时、权限和幂等。',
  },
  ai_graphrag: {
    image: 'diagram_graphrag.webp',
    alt: 'GraphRAG 知识图谱增强检索',
    title: 'GraphRAG：知识图谱增强检索',
    type: 'flow',
    steps: [
      { title: '文档解析', desc: '切块并抽取实体关系' },
      { title: '构建图谱', desc: '节点、边与社区聚类' },
      { title: '社区摘要', desc: '为每个社区生成摘要' },
      { title: '混合检索', desc: '向量加图关系召回' },
      { title: '生成回答', desc: '依据子图与摘要作答' },
    ],
    caption: '图谱补足向量检索的全局关系；社区摘要适合回答跨文档的宏观问题。',
  },
  ai_agent_security: {
    image: 'diagram_agent_security.webp',
    alt: 'Agent 攻击面与防护措施',
    title: 'Agent 安全：攻击面与防护边界',
    type: 'compare',
    columns: [
      { title: '主要攻击面', items: ['提示注入污染工具输入', '工具越权访问敏感数据', '恶意网页或文档注入指令', '无限循环消耗预算', '输出泄露系统提示'] },
      { title: '防护措施', items: ['最小权限与工具白名单', '沙箱隔离执行环境', '高风险操作人工确认', '输入输出双向过滤', '全链路审计与回滚'] },
    ],
    caption: '提示注入、工具越权和数据外泄是主要风险；最小权限、沙箱、人工确认和审计缺一不可。',
  },
  ai_realtime_voice: {
    image: 'diagram_realtime_voice.webp',
    alt: '实时语音链路 VAD ASR LLM TTS',
    title: '实时语音链路：VAD、ASR、LLM 与 TTS',
    type: 'flow',
    steps: [
      { title: 'VAD', desc: '检测说话开始与结束' },
      { title: 'ASR', desc: '流式语音转文字' },
      { title: 'LLM', desc: '理解并生成回复文本' },
      { title: 'TTS', desc: '流式合成语音播放' },
    ],
    notes: ['端到端延迟决定体验', '需要处理打断、回声消除和网络抖动', '流式输出可以边生成边播放'],
    caption: '端到端延迟决定体验；打断、回声消除和流式输出是实时语音的关键。',
  },
};
