// P1 算法配图数据。
module.exports = {
  linked_list: {
    image: 'diagram_linked_list.webp',
    alt: '单链表、双链表与环形链表',
    title: '链表家族：单链表、双链表与环形链表',
    type: 'compare',
    columns: [
      { title: '单链表', items: ['每个节点一个 next 指针', '只能单向遍历', '插入删除需要前驱', '空间开销最小'] },
      { title: '双链表', items: ['prev 与 next 两个指针', '可以双向遍历', '删除节点更方便', '空间开销更大'] },
      { title: '环形链表', items: ['尾节点指向某个节点', '适合循环调度', '遍历需要终止条件', '快慢指针判断环'] },
    ],
    caption: '链表插入删除 O(1)（已知前驱），随机访问 O(n)；双链表多一个前驱指针，环形链表要小心死循环。',
  },
  tree_bst: {
    image: 'diagram_bst.webp',
    alt: '二叉搜索树结构',
    title: '二叉搜索树：左小右大的有序结构',
    type: 'tree',
    root: {
      text: '50',
      children: [
        { text: '30', children: [{ text: '20' }, { text: '40' }] },
        { text: '70', children: [{ text: '60' }, { text: '80' }] },
      ],
    },
    notes: ['中序遍历得到递增序列', '查找路径从根节点逐层比较'],
    caption: 'BST 查找平均 O(log n)，退化成链时 O(n)；AVL 和红黑树通过旋转保持平衡。',
  },
  graph: {
    image: 'diagram_graph.webp',
    alt: '邻接矩阵与邻接表对比',
    title: '图的表示：邻接矩阵与邻接表',
    type: 'compare',
    columns: [
      { title: '邻接矩阵', items: ['二维数组表示边', '判断边 O(1)', '空间 O(V²)', '适合稠密图'] },
      { title: '邻接表', items: ['每个顶点存邻居列表', '遍历邻居高效', '空间 O(V+E)', '适合稀疏图'] },
    ],
    notes: ['BFS 按层扩展，适合无权图最短路', 'DFS 适合连通性、环检测和拓扑排序', 'Dijkstra 处理非负权最短路'],
    caption: '稠密图用邻接矩阵，稀疏图用邻接表；BFS 找最短路，DFS 用于连通性和拓扑。',
  },
  dynamic_programming: {
    image: 'diagram_dp.webp',
    alt: '0/1 背包动态规划状态表',
    title: '动态规划：0/1 背包的状态表',
    type: 'grid',
    rows: 3,
    cols: 5,
    colLabels: ['容量 0', '容量 1', '容量 2', '容量 3', '容量 4'],
    rowLabels: ['物品 A 重 1 价 2', '物品 B 重 2 价 4', '物品 C 重 3 价 5'],
    cells: [
      { r: 0, c: 0, text: '0', fill: '#e7eeff', stroke: '#6c8ff8' },
      { r: 0, c: 1, text: '2', fill: '#e7eeff', stroke: '#6c8ff8' },
      { r: 0, c: 2, text: '2', fill: '#e7eeff', stroke: '#6c8ff8' },
      { r: 0, c: 3, text: '2', fill: '#e7eeff', stroke: '#6c8ff8' },
      { r: 0, c: 4, text: '2', fill: '#e7eeff', stroke: '#6c8ff8' },
      { r: 1, c: 0, text: '0', fill: '#e0f2fe', stroke: '#0ea5e9' },
      { r: 1, c: 1, text: '2', fill: '#e0f2fe', stroke: '#0ea5e9' },
      { r: 1, c: 2, text: '4', fill: '#e0f2fe', stroke: '#0ea5e9' },
      { r: 1, c: 3, text: '6', fill: '#e0f2fe', stroke: '#0ea5e9' },
      { r: 1, c: 4, text: '6', fill: '#e0f2fe', stroke: '#0ea5e9' },
      { r: 2, c: 0, text: '0', fill: '#dcfce7', stroke: '#16a34a' },
      { r: 2, c: 1, text: '2', fill: '#dcfce7', stroke: '#16a34a' },
      { r: 2, c: 2, text: '4', fill: '#dcfce7', stroke: '#16a34a' },
      { r: 2, c: 3, text: '6', fill: '#dcfce7', stroke: '#16a34a' },
      { r: 2, c: 4, text: '7', fill: '#dcfce7', stroke: '#16a34a' },
    ],
    caption: 'DP 用状态定义加转移方程避免重复计算；要明确边界、遍历顺序和空间压缩。',
  },
  backtracking: {
    image: 'diagram_backtracking.webp',
    alt: '回溯决策树与剪枝',
    title: '回溯：决策树与剪枝',
    type: 'tree',
    root: {
      text: '开始',
      children: [
        { text: '选 A', children: [{ text: '选 B' }, { text: '不选 B，剪枝' }] },
        { text: '不选 A', children: [{ text: '选 B' }, { text: '不选 B' }] },
      ],
    },
    notes: ['路径表示当前选择，选择列表表示可选分支', '到达边界记录结果，撤销选择恢复状态'],
    caption: '回溯在决策树上深度优先搜索；剪枝条件和撤销选择是正确性的关键。',
  },
  union_find: {
    image: 'diagram_union_find.webp',
    alt: '并查集合并与路径压缩',
    title: '并查集：合并集合与路径压缩',
    type: 'tree',
    root: {
      text: '代表元 1',
      children: [
        { text: '2', children: [{ text: '4' }, { text: '5' }] },
        { text: '3', children: [{ text: '6' }, { text: '7' }] },
      ],
    },
    notes: ['find 沿父指针找到代表元', 'union 按秩合并，避免树退化成链', '路径压缩让后续查询接近 O(1)'],
    caption: '并查集用父指针表示集合，按秩合并加路径压缩后接近 O(1)。',
  },
  trie: {
    image: 'diagram_trie.webp',
    alt: 'Trie 前缀树结构',
    title: 'Trie：按字符前缀共享路径',
    type: 'tree',
    root: {
      text: '根节点',
      children: [
        { text: 'c', children: [{ text: 'a', children: [{ text: 't' }, { text: 'r' }] }, { text: 'o', children: [{ text: 'w' }] }] },
      ],
    },
    notes: ['节点标记是否为单词结尾', '查询复杂度 O(词长)，与词表大小无关'],
    caption: 'Trie 用公共前缀共享节点，查询复杂度只与字符串长度有关；适合前缀搜索和自动补全。',
  },
  segment_tree: {
    image: 'diagram_segment_tree.webp',
    alt: '线段树区间分解结构',
    title: '线段树：区间查询与更新的分治结构',
    type: 'tree',
    root: {
      text: '[1,8]',
      children: [
        { text: '[1,4]', children: [{ text: '[1,2]' }, { text: '[3,4]' }] },
        { text: '[5,8]', children: [{ text: '[5,6]' }, { text: '[7,8]' }] },
      ],
    },
    notes: ['每个节点保存一个区间的聚合值', '区间查询拆成 O(log n) 个节点', '区间更新用懒标记避免重复下推'],
    caption: '线段树把区间二分存储，查询和更新都是 O(log n)；树状数组适合前缀和场景。',
  },
  monotonic_stack: {
    image: 'diagram_monotonic_stack.webp',
    alt: '单调栈与下一个更大元素',
    title: '单调栈：用有序栈找下一个更大元素',
    type: 'compare',
    columns: [
      { title: '单调递增栈', items: ['栈底到栈顶递增', '找下一个更小元素', '遇到更小值弹出栈顶', '每个元素最多入出栈一次'] },
      { title: '单调递减栈', items: ['栈底到栈顶递减', '找下一个更大元素', '遇到更大值弹出栈顶', '适合柱状图最大矩形'] },
    ],
    notes: ['从左到右扫描得到右侧第一个更大元素', '从右到左扫描得到左侧第一个更大元素'],
    caption: '单调栈在 O(n) 内找到左右第一个更大或更小元素；单调队列用于滑动窗口最值。',
  },
  string_matching: {
    image: 'diagram_kmp.webp',
    alt: 'KMP next 数组与匹配过程',
    title: 'KMP：next 数组让主串指针不回溯',
    type: 'grid',
    rows: 2,
    cols: 6,
    colLabels: ['位置 0', '位置 1', '位置 2', '位置 3', '位置 4', '位置 5'],
    rowLabels: ['模式串', 'next 数组'],
    cells: [
      { r: 0, c: 0, text: 'a', fill: '#e7eeff', stroke: '#6c8ff8' },
      { r: 0, c: 1, text: 'b', fill: '#e7eeff', stroke: '#6c8ff8' },
      { r: 0, c: 2, text: 'a', fill: '#e7eeff', stroke: '#6c8ff8' },
      { r: 0, c: 3, text: 'b', fill: '#e7eeff', stroke: '#6c8ff8' },
      { r: 0, c: 4, text: 'a', fill: '#e7eeff', stroke: '#6c8ff8' },
      { r: 0, c: 5, text: 'c', fill: '#e7eeff', stroke: '#6c8ff8' },
      { r: 1, c: 0, text: '-1', fill: '#e0f2fe', stroke: '#0ea5e9' },
      { r: 1, c: 1, text: '0', fill: '#e0f2fe', stroke: '#0ea5e9' },
      { r: 1, c: 2, text: '0', fill: '#e0f2fe', stroke: '#0ea5e9' },
      { r: 1, c: 3, text: '1', fill: '#e0f2fe', stroke: '#0ea5e9' },
      { r: 1, c: 4, text: '2', fill: '#e0f2fe', stroke: '#0ea5e9' },
      { r: 1, c: 5, text: '3', fill: '#e0f2fe', stroke: '#0ea5e9' },
    ],
    caption: 'KMP 利用已匹配前缀信息跳过无效比较，时间复杂度 O(n+m)；BM 算法适合长模式串。',
  },
  network_flow: {
    image: 'diagram_network_flow.webp',
    alt: '网络流残量网络与增广路径',
    title: '网络流：残量网络与增广路径',
    type: 'flow',
    steps: [
      { title: '建立残量网络', desc: '正向容量与反向流量' },
      { title: '寻找增广路径', desc: 'BFS 或 DFS 找到剩余容量' },
      { title: '更新残量', desc: '正向减容量，反向加流量' },
      { title: '重复到无路径', desc: '得到最大流' },
    ],
    notes: ['最大流等于最小割', 'Dinic 用分层图提高效率', '二分图匹配可以转化为最大流'],
    caption: '残量网络让算法可以撤销之前的流量选择；最大流最小割定理是网络流的核心结论。',
  },
  algo_shortest_paths: {
    image: 'diagram_shortest_paths.webp',
    alt: 'Dijkstra 松弛过程',
    title: 'Dijkstra：每次选择最近的未访问节点',
    type: 'flow',
    steps: [
      { title: '初始化距离', desc: '起点 0，其余无穷大' },
      { title: '选最小节点', desc: '从未访问集合取出' },
      { title: '松弛邻居', desc: '更新更短的路径' },
      { title: '重复', desc: '直到所有节点确定' },
    ],
    notes: ['优先队列实现 O((V+E) log V)', '边权不能为负', 'Bellman-Ford 支持负权并检测负环'],
    caption: 'Dijkstra 要求边权非负；Bellman-Ford 支持负权并检测负环，Floyd 求全源最短路。',
  },
  algo_mst: {
    image: 'diagram_mst.webp',
    alt: 'Kruskal 最小生成树选边过程',
    title: '最小生成树：按权值从小到大选边',
    type: 'flow',
    steps: [
      { title: '边排序', desc: '按权值升序排列' },
      { title: '并查集判环', desc: '两端不在同一集合' },
      { title: '加入安全边', desc: '合并两个集合' },
      { title: '得到 n-1 条边', desc: '生成树完成' },
    ],
    notes: ['Kruskal 按边选，适合稀疏图', 'Prim 按点扩展，适合稠密图', 'MST 总权值最小但不唯一'],
    caption: 'Kruskal 适合稀疏图，Prim 适合稠密图；MST 保证总权值最小但不保证唯一。',
  },
  algo_topological: {
    image: 'diagram_topological.webp',
    alt: '拓扑排序与入度队列',
    title: '拓扑排序：每次取出入度为 0 的节点',
    type: 'flow',
    steps: [
      { title: '统计入度', desc: '计算每个节点的前置依赖' },
      { title: '入队零入度', desc: '所有无依赖节点入队' },
      { title: '弹出并输出', desc: '删除节点及其出边' },
      { title: '更新邻居入度', desc: '新的零入度节点入队' },
    ],
    notes: ['输出顺序可能不唯一', '存在环时无法完成拓扑排序', '可用于构建依赖解析和任务调度'],
    caption: '拓扑排序只适用于 DAG；存在环时无法排序，可用于依赖解析和任务调度。',
  },
};
