// P1 编程语言运行时与内存模型配图数据。
module.exports = {
  python_variables: {
    image: 'diagram_python_variables.webp',
    alt: 'Python 变量绑定与可变对象',
    title: 'Python 变量：名字绑定与对象',
    type: 'compare',
    columns: [
      { title: '可变对象', items: ['list、dict、set', '多个名字可指向同一对象', '原地修改对所有引用可见', '函数默认参数慎用可变对象'] },
      { title: '不可变对象', items: ['int、str、tuple', '修改会创建新对象', '可以安全共享', '可哈希并作为字典键'] },
    ],
    caption: '变量是名字到对象的引用；可变对象共享修改，不可变对象重新绑定名字。',
  },
  python_concurrency: {
    image: 'diagram_python_concurrency.webp',
    alt: 'Python 线程、进程与 asyncio 对比',
    title: 'Python 并发模型：线程、进程与异步',
    type: 'compare',
    columns: [
      { title: '多线程', items: ['共享内存', '受 GIL 限制', '适合 I/O 密集', '锁使用不当会死锁'] },
      { title: '多进程', items: ['独立解释器与内存', '绕过 GIL', '进程间通信有成本', '适合 CPU 密集'] },
      { title: 'asyncio', items: ['单线程事件循环', 'await 主动让出', '适合高并发 I/O', '阻塞调用会卡住循环'] },
    ],
    caption: 'CPU 密集用多进程，I/O 密集用线程或 asyncio；GIL 让同一时刻只有一个线程执行字节码。',
  },
  python_decorators_generators: {
    image: 'diagram_python_decorators.webp',
    alt: '装饰器与生成器执行过程',
    title: '装饰器与生成器：函数包装与惰性序列',
    type: 'flow',
    steps: [
      { title: '定义装饰器', desc: '接收函数作为参数' },
      { title: '包装函数', desc: '返回新的 wrapper' },
      { title: '调用前处理', desc: '日志、鉴权、计时' },
      { title: '调用后处理', desc: '缓存、异常、清理' },
    ],
    notes: ['生成器用 yield 暂停和恢复执行', '生成器表达式是惰性求值', '装饰器链从下往上应用'],
    caption: '装饰器接收函数并返回新函数；生成器用 yield 暂停和恢复执行，适合流式处理大数据。',
  },
  python_context_iterators: {
    image: 'diagram_python_context_iterators.webp',
    alt: '上下文管理器与迭代器协议',
    title: '上下文管理器与迭代器协议',
    type: 'compare',
    columns: [
      { title: '上下文管理器', items: ['with 进入时调用 __enter__', '退出时调用 __exit__', '异常时也能释放资源', 'contextlib 可简化实现'] },
      { title: '迭代器协议', items: ['__iter__ 返回迭代器', '__next__ 产出下一个值', '耗尽时抛 StopIteration', 'for 循环自动处理异常'] },
    ],
    caption: 'with 保证异常时也能释放资源；迭代器用 __next__ 逐个产出并在耗尽时抛 StopIteration。',
  },
  java_basics: {
    image: 'diagram_java_runtime.webp',
    alt: 'JDK JRE JVM 与字节码',
    title: 'Java 运行体系：JDK、JRE、JVM 与字节码',
    type: 'layers',
    layers: [
      { title: 'JDK 开发工具包', desc: 'javac、jar、调试与性能工具' },
      { title: 'JRE 运行环境', desc: '核心类库与 Java 虚拟机' },
      { title: 'JVM 虚拟机', desc: '类加载、解释执行与 JIT 编译' },
      { title: '字节码与本地机器码', desc: '跨平台中间表示，运行时编译成机器码' },
    ],
    caption: '源码编译成字节码，JVM 负责加载、解释和 JIT 编译；跨平台来自字节码和虚拟机。',
  },
  java_oop: {
    image: 'diagram_java_oop.webp',
    alt: 'Java 类加载与对象创建',
    title: 'Java 对象创建与类加载',
    type: 'flow',
    steps: [
      { title: '加载', desc: '读取 class 字节码' },
      { title: '链接', desc: '验证、准备、解析符号' },
      { title: '初始化', desc: '执行静态初始化块' },
      { title: '创建对象', desc: '堆分配并调用构造方法' },
    ],
    notes: ['方法区保存类元数据，堆保存对象，栈保存引用与局部变量', '多态调用通过虚方法表定位实现'],
    caption: '类加载分加载、链接、初始化；对象在堆分配，方法调用通过虚方法表实现多态。',
  },
  java_collections: {
    image: 'diagram_java_collections.webp',
    alt: 'HashMap 数组、链表与红黑树',
    title: 'HashMap：数组、链表与红黑树',
    type: 'tree',
    root: {
      text: '哈希桶数组',
      children: [
        { text: '桶 0', children: [{ text: 'key A' }, { text: 'key C' }] },
        { text: '桶 1', children: [{ text: 'key B' }] },
        { text: '桶 2', children: [{ text: '红黑树节点' }] },
        { text: '桶 3', children: [{ text: '空' }] },
      ],
    },
    notes: ['默认容量 16，负载因子 0.75', '链表长度超过阈值转为红黑树', '扩容时重新计算索引并迁移节点'],
    caption: 'HashMap 默认负载因子 0.75，冲突多时链表转红黑树；扩容会重新分配桶。',
  },
  java_concurrency: {
    image: 'diagram_java_concurrency.webp',
    alt: 'synchronized、AQS 与线程池',
    title: 'Java 并发：锁、AQS 与线程池',
    type: 'compare',
    columns: [
      { title: 'synchronized', items: ['JVM 内置锁', '自动释放', '偏向锁、轻量级锁优化', '不可中断、不区分读写'] },
      { title: 'AQS / Lock', items: ['状态加等待队列', '可中断、可超时', '支持读写锁与条件变量', '需要手动释放'] },
      { title: '线程池', items: ['复用线程降低开销', '核心数、队列、拒绝策略', '队列过大掩盖过载', '需要监控活跃与排队数'] },
    ],
    caption: 'synchronized 由 JVM 实现，AQS 用状态和等待队列实现锁；线程池参数决定吞吐与排队。',
  },
  java_gc_tuning: {
    image: 'diagram_java_gc.webp',
    alt: 'JVM 分代堆与垃圾回收',
    title: 'JVM 分代堆：Eden、Survivor 与 Old',
    type: 'layers',
    layers: [
      { title: 'Eden 区', desc: '新对象优先在这里分配' },
      { title: 'Survivor 区', desc: 'Minor GC 后存活对象复制到这里' },
      { title: 'Old 区', desc: '长期存活或大对象进入老年代' },
      { title: 'Metaspace', desc: '类元数据，使用本地内存' },
    ],
    caption: '对象优先在 Eden 分配，多次存活进入老年代；G1 按 Region 回收，关注停顿时间和吞吐。',
  },
  java_virtual_threads: {
    image: 'diagram_java_virtual_threads.webp',
    alt: '平台线程与虚拟线程对比',
    title: '平台线程与虚拟线程',
    type: 'compare',
    columns: [
      { title: '平台线程', items: ['一对一映射操作系统线程', '创建成本高', '数量受内存限制', '适合 CPU 密集任务'] },
      { title: '虚拟线程', items: ['由 JVM 调度', '阻塞时卸载载体线程', '可以创建数十万个', '适合高并发 I/O'] },
    ],
    notes: ['虚拟线程不适合长时间 CPU 计算', '避免在虚拟线程中持有大量锁', '结构化并发让父子任务生命周期一致'],
    caption: '虚拟线程由 JVM 调度，阻塞时卸载载体线程；适合高并发 I/O，不适合 CPU 密集任务。',
  },
  js_execution_context: {
    image: 'diagram_js_execution_context.webp',
    alt: 'JavaScript 执行上下文与作用域链',
    title: 'JavaScript 执行上下文与作用域链',
    type: 'layers',
    layers: [
      { title: '全局执行上下文', desc: '全局对象、全局变量和函数声明' },
      { title: '函数执行上下文', desc: '每次调用创建新的变量环境' },
      { title: '词法环境', desc: 'let、const 的块级作用域' },
      { title: '作用域链', desc: '查找变量时逐层向外，闭包保留外部引用' },
    ],
    caption: '函数调用创建执行上下文；闭包让内部函数保留对外部词法环境的引用。',
  },
  js_objects: {
    image: 'diagram_js_objects.webp',
    alt: 'JavaScript 原型链',
    title: 'JavaScript 原型链',
    type: 'tree',
    root: {
      text: '实例对象',
      children: [
        { text: '构造函数 prototype', children: [{ text: 'Object.prototype', children: [{ text: 'null' }] }] },
      ],
    },
    notes: ['属性查找沿原型链向上', 'class 是原型继承的语法糖', 'this 由调用方式决定，箭头函数继承外层 this'],
    caption: '属性查找沿原型链向上；class 是原型继承的语法糖，this 由调用方式决定。',
  },
  js_async: {
    image: 'diagram_js_async.webp',
    alt: '事件循环、微任务与宏任务',
    title: '事件循环：调用栈、微任务与宏任务',
    type: 'flow',
    steps: [
      { title: '同步代码', desc: '调用栈顺序执行' },
      { title: '微任务队列', desc: 'Promise、queueMicrotask' },
      { title: '宏任务队列', desc: 'setTimeout、I/O、事件' },
      { title: '事件循环', desc: '清空微任务后再取宏任务' },
    ],
    notes: ['微任务优先级高于宏任务', '微任务中继续产生微任务会一直清空', '长时间同步代码会阻塞渲染'],
    caption: 'Promise 回调进入微任务，setTimeout 进入宏任务；微任务在当前宏任务结束后清空。',
  },
  js_memory_gc: {
    image: 'diagram_js_memory_gc.webp',
    alt: 'JavaScript 标记清除与分代回收',
    title: 'JavaScript 垃圾回收：标记与分代',
    type: 'cycle',
    nodes: [
      { title: '标记', desc: '从根对象遍历可达对象' },
      { title: '清除', desc: '回收不可达对象' },
      { title: '整理', desc: '压缩内存减少碎片' },
      { title: '分代', desc: '新对象回收更频繁' },
    ],
    center: 'V8 垃圾回收',
    backLabel: '减少全局变量和闭包持有，避免内存泄漏',
    caption: '从根对象标记可达对象，不可达对象被回收；分代假设让新对象回收更频繁。',
  },
  c_pointers: {
    image: 'diagram_c_pointers.webp',
    alt: 'C 指针与内存分区',
    title: 'C 指针与内存分区',
    type: 'layers',
    layers: [
      { title: '栈 Stack', desc: '局部变量、函数参数、返回地址，自动回收' },
      { title: '堆 Heap', desc: 'malloc 分配，必须 free，容易泄漏或悬空' },
      { title: '静态区', desc: '全局变量和 static 变量，程序生命周期存在' },
      { title: '常量区', desc: '字符串字面量和只读常量' },
    ],
    caption: '指针保存地址，解引用访问目标；栈自动回收，堆需要 free，悬空指针和越界是常见错误。',
  },
  c_structs: {
    image: 'diagram_c_structs.webp',
    alt: 'C 结构体内存对齐',
    title: '结构体内存对齐',
    type: 'grid',
    rows: 1,
    cols: 4,
    colLabels: ['char 1 字节', 'padding 3 字节', 'int 4 字节', 'padding 4 字节'],
    cells: [
      { r: 0, c: 0, text: 'c', fill: '#e7eeff', stroke: '#6c8ff8', bold: true },
      { r: 0, c: 1, text: '对齐填充', fill: '#f9fafb', stroke: '#9ca3af' },
      { r: 0, c: 2, text: 'i', fill: '#e0f2fe', stroke: '#0ea5e9', bold: true },
      { r: 0, c: 3, text: '尾部填充', fill: '#f9fafb', stroke: '#9ca3af' },
    ],
    caption: '编译器按成员最大对齐要求填充；调整成员顺序可以减少 padding，联合体大小取决于最大成员。',
  },
  c_preprocessor: {
    image: 'diagram_c_preprocessor.webp',
    alt: 'C 预处理宏与头文件展开',
    title: 'C 预处理：宏、条件编译与头文件',
    type: 'flow',
    steps: [
      { title: '#include', desc: '把头文件内容插入源文件' },
      { title: '#define', desc: '文本替换，参数要加括号' },
      { title: '条件编译', desc: '#ifdef 控制平台与调试代码' },
      { title: '头文件卫士', desc: '#pragma once 防止重复包含' },
    ],
    caption: '#include 是文本替换，#define 是宏展开；头文件卫士防止重复包含，宏参数需要加括号。',
  },
  cpp_memory: {
    image: 'diagram_cpp_memory.webp',
    alt: 'C++ 智能指针所有权模型',
    title: 'C++ 智能指针：所有权模型',
    type: 'compare',
    columns: [
      { title: 'unique_ptr', items: ['独占所有权', '不能复制只能移动', '零额外开销', '默认首选'] },
      { title: 'shared_ptr', items: ['引用计数共享', '计数归零时释放', '有控制块开销', '注意循环引用'] },
      { title: 'weak_ptr', items: ['不增加引用计数', '打破循环引用', '使用前 lock 提升', '观察 shared_ptr 生命周期'] },
    ],
    caption: 'unique_ptr 独占所有权，shared_ptr 引用计数共享，weak_ptr 打破循环引用；RAII 保证异常安全。',
  },
  cpp_move_semantics: {
    image: 'diagram_cpp_move.webp',
    alt: 'C++ 移动语义与右值引用',
    title: 'C++ 移动语义与右值引用',
    type: 'flow',
    steps: [
      { title: '左值与右值', desc: '左值有名字，右值是临时值' },
      { title: '右值引用', desc: 'T&& 绑定临时对象' },
      { title: '移动构造', desc: '窃取资源而不是深拷贝' },
      { title: '完美转发', desc: 'std::forward 保留值类别' },
    ],
    notes: ['std::move 只是把表达式转成右值引用', '移动后对象处于有效但未指定状态', 'Rule of Five 管理资源类型'],
    caption: '移动构造转移资源而不是复制；std::move 只是类型转换，转发引用配合 std::forward 保留值类别。',
  },
  cpp_concurrency_atomics: {
    image: 'diagram_cpp_atomics.webp',
    alt: 'C++ 原子操作与内存序',
    title: 'C++ 原子操作与内存序',
    type: 'grid',
    rows: 1,
    cols: 4,
    colLabels: ['relaxed', 'acquire', 'release', 'seq_cst'],
    cells: [
      { r: 0, c: 0, text: '只保证原子性\n不建立同步', fill: '#e7eeff', stroke: '#6c8ff8', bold: true },
      { r: 0, c: 1, text: '读操作\n之后的读写不能上移', fill: '#e0f2fe', stroke: '#0ea5e9', bold: true },
      { r: 0, c: 2, text: '写操作\n之前的读写不能下移', fill: '#dcfce7', stroke: '#16a34a', bold: true },
      { r: 0, c: 3, text: '全局顺序一致\n最严格也最慢', fill: '#fef3c7', stroke: '#f59e0b', bold: true },
    ],
    caption: 'relaxed 只保证原子性，acquire/release 建立同步关系，seq_cst 提供全局顺序；错误内存序导致难以复现的 bug。',
  },
  rust_smart_pointers: {
    image: 'diagram_rust_smart_pointers.webp',
    alt: 'Rust 智能指针与内部可变性',
    title: 'Rust 智能指针：所有权与内部可变性',
    type: 'compare',
    columns: [
      { title: 'Box<T>', items: ['独占堆分配', '编译期所有权检查', '零运行时开销', '适合递归类型'] },
      { title: 'Rc<T>', items: ['引用计数共享', '只能单线程', '不可变借用为主', '计数归零释放'] },
      { title: 'RefCell<T>', items: ['运行期借用检查', '内部可变性', '违反规则会 panic', '常与 Rc 组合'] },
      { title: 'Arc<T>', items: ['原子引用计数', '可跨线程共享', '开销高于 Rc', '配合 Mutex 修改'] },
    ],
    caption: 'Box 独占堆分配，Rc 共享只读，RefCell 运行期借用检查，Arc 跨线程共享。',
  },
  rust_async_tokio: {
    image: 'diagram_rust_async.webp',
    alt: 'Rust Future 状态机与 tokio 调度',
    title: 'Rust 异步：Future、调度器与唤醒',
    type: 'flow',
    steps: [
      { title: 'async 函数', desc: '编译成状态机' },
      { title: 'Future', desc: 'poll 推进状态' },
      { title: 'Tokio 调度器', desc: '在任务队列中调度' },
      { title: '唤醒', desc: 'I/O 就绪后重新 poll' },
    ],
    notes: ['Future 是惰性的，必须被 poll 或 await', '.await 挂起当前任务而不阻塞线程', '阻塞操作要用 spawn_blocking'],
    caption: 'async 函数编译成状态机，Future 被 poll 驱动；tokio 运行时负责调度和唤醒。',
  },
  go_concurrency: {
    image: 'diagram_go_concurrency.webp',
    alt: 'Go goroutine channel context',
    title: 'Go 并发：goroutine、channel 与 context',
    type: 'compare',
    columns: [
      { title: 'goroutine', items: ['由 Go 运行时调度', '初始栈很小', '可以创建数十万个', '用 go 关键字启动'] },
      { title: 'channel', items: ['goroutine 之间通信', '无缓冲会同步阻塞', '有缓冲提供队列', 'close 后不能再发送'] },
      { title: 'context', items: ['传递取消信号', '支持超时和截止时间', '贯穿调用链', '配合 select 监听'] },
    ],
    caption: 'goroutine 由运行时调度，channel 用于通信和同步，context 传递取消和超时。',
  },
  go_concurrency_patterns: {
    image: 'diagram_go_patterns.webp',
    alt: 'Go Worker Pool 与 Pipeline 模式',
    title: 'Go 并发模式：Worker Pool 与 Pipeline',
    type: 'flow',
    steps: [
      { title: '任务队列', desc: 'channel 分发任务' },
      { title: 'Worker Pool', desc: '固定数量 worker 消费' },
      { title: 'Pipeline', desc: '多个阶段用 channel 连接' },
      { title: 'fan-out / fan-in', desc: '并行处理后汇总结果' },
    ],
    notes: ['errgroup 收集错误并取消其余任务', '限制并发度防止打爆下游', '用 context 处理超时与退出'],
    caption: '固定 worker 数量控制并发度，channel 连接流水线阶段，errgroup 收集错误并取消。',
  },
  go_performance: {
    image: 'diagram_go_gc.webp',
    alt: 'Go 三色标记与 GC 调步',
    title: 'Go 性能与 GC：三色标记与调步',
    type: 'cycle',
    nodes: [
      { title: '标记准备', desc: '开启写屏障' },
      { title: '三色标记', desc: '白灰黑标记可达对象' },
      { title: '标记终止', desc: '短暂 STW 收尾' },
      { title: '并发清扫', desc: '回收白色对象' },
    ],
    center: 'GOGC 调步',
    backLabel: '逃逸分析决定栈分配还是堆分配',
    caption: '逃逸分析决定栈还是堆分配；三色标记加写屏障并发回收，GOGC 控制堆增长目标。',
  },
  csharp_gc_performance: {
    image: 'diagram_csharp_gc.webp',
    alt: 'C# 分代垃圾回收与 LOH',
    title: 'C# 垃圾回收：分代与 LOH',
    type: 'layers',
    layers: [
      { title: 'Gen0', desc: '新对象分配，回收最频繁' },
      { title: 'Gen1', desc: 'Gen0 存活对象的缓冲层' },
      { title: 'Gen2', desc: '长期存活对象，回收成本最高' },
      { title: 'LOH 大对象堆', desc: '大于阈值的大对象，通常不压缩' },
    ],
    caption: '新对象在 Gen0 分配，存活越久代越高；大对象进入 LOH，减少分配和复用对象是关键。',
  },
  csharp_async_streams: {
    image: 'diagram_csharp_async.webp',
    alt: 'C# async await 与异步流',
    title: 'C# async/await 与异步流',
    type: 'flow',
    steps: [
      { title: '调用异步方法', desc: '返回 Task 或 Task<T>' },
      { title: 'await 挂起', desc: '释放线程而不是阻塞' },
      { title: '状态机恢复', desc: 'I/O 完成后继续执行' },
      { title: '异步流', desc: 'IAsyncEnumerable 逐个产出' },
    ],
    notes: ['async 方法编译成状态机', '不要阻塞等待 Task.Result', 'IAsyncEnumerable 用 await foreach 消费'],
    caption: 'async 方法编译成状态机，await 挂起而不阻塞线程；IAsyncEnumerable 支持流式异步产出。',
  },
  kotlin_coroutines: {
    image: 'diagram_kotlin_coroutines.webp',
    alt: 'Kotlin 协程挂起与恢复',
    title: 'Kotlin 协程：挂起与恢复',
    type: 'flow',
    steps: [
      { title: '启动协程', desc: 'launch 或 async' },
      { title: '挂起函数', desc: 'suspend 保存执行状态' },
      { title: '调度器执行', desc: 'Dispatchers 切换线程' },
      { title: '恢复继续', desc: 'I/O 完成后从挂起点继续' },
    ],
    notes: ['结构化并发保证父子作用域一起取消', 'runBlocking 只用于桥接阻塞代码', '协程不是线程，挂起不阻塞线程'],
    caption: '协程用挂起代替阻塞线程；结构化并发保证父作用域取消时子协程一起取消。',
  },
  swift_oop: {
    image: 'diagram_swift_arc.webp',
    alt: 'Swift 值类型、引用类型与 ARC',
    title: 'Swift 值类型、引用类型与 ARC',
    type: 'compare',
    columns: [
      { title: '值类型 struct', items: ['赋值时复制', '线程安全更容易', '适合数据模型', '写时复制优化'] },
      { title: '引用类型 class', items: ['共享同一实例', '继承与多态', 'ARC 管理生命周期', '注意循环引用'] },
    ],
    notes: ['weak 引用不增加计数，自动置 nil', 'unowned 假定对象始终存在', '闭包捕获 self 容易形成循环引用'],
    caption: '结构体是值语义，类是引用语义；ARC 自动管理引用计数，循环引用用 weak/unowned 打破。',
  },
  ts_type_level: {
    image: 'diagram_ts_types.webp',
    alt: 'TypeScript 类型编程层次',
    title: 'TypeScript 类型编程：从泛型到条件类型',
    type: 'layers',
    layers: [
      { title: '基础类型与联合', desc: 'string、number、联合与交叉类型' },
      { title: '泛型与约束', desc: 'T extends U 限制类型范围' },
      { title: '条件类型', desc: 'T extends U ? X : Y 类型分支' },
      { title: '映射与模板字面量', desc: '批量改写属性与字符串类型' },
    ],
    caption: '类型在编译期擦除；泛型约束、条件类型和映射类型让类型系统表达复杂约束。',
  },
  flutter_basics: {
    image: 'diagram_flutter_trees.webp',
    alt: 'Flutter Widget、Element 与 RenderObject 三棵树',
    title: 'Flutter 三棵树：Widget、Element 与 RenderObject',
    type: 'layers',
    layers: [
      { title: 'Widget 树', desc: '不可变配置，描述界面长什么样' },
      { title: 'Element 树', desc: '保存状态与生命周期，连接 Widget 与渲染对象' },
      { title: 'RenderObject 树', desc: '负责布局、绘制与命中测试' },
      { title: 'GPU 合成', desc: '图层提交给 Skia/Impeller 渲染' },
    ],
    caption: 'Widget 是不可变配置，Element 保存状态和生命周期，RenderObject 负责布局与绘制。',
  },
};
