// P2 跨语言对照配图数据。
module.exports = {
  cross_first_program: {
    image: 'diagram_cross_first.webp',
    alt: '三种运行方式的对照',
    title: '第一个程序：三种运行方式',
    type: 'compare',
    columns: [
      { title: '编译执行', items: ['C、C++、Go、Rust', '先编译成机器码再运行', '启动快、无运行时依赖', '需为每个平台分别构建', '错误多在编译期发现'] },
      { title: '虚拟机执行', items: ['Java、C#、Kotlin', '编译成字节码由 VM 运行', '跨平台靠运行时', 'JIT 可做运行时优化', '需要安装或打包运行时'] },
      { title: '解释执行', items: ['Python、JavaScript、Shell', '由解释器逐行执行', '改完即可运行', '启动与性能依赖解释器', '类型错误常在运行期暴露'] },
    ],
    caption: '三者的差别在于「什么时候翻译成机器指令」；这也决定了启动速度、部署方式与错误暴露时机。',
  },
  cross_types_variables: {
    image: 'diagram_cross_types.webp',
    alt: '静态类型与动态类型的对照',
    title: '类型系统：静态与动态的取舍',
    type: 'compare',
    columns: [
      { title: '静态类型', items: ['编译期检查类型', 'IDE 补全与重构更强', '重构大项目更安全', '需要写类型标注', '代表：Java、Go、Rust、TS'] },
      { title: '动态类型', items: ['运行期决定类型', '写法简短、原型快', '灵活但易出运行期错误', '依赖测试与类型检查工具', '代表：Python、Ruby、JS'] },
    ],
    notes: ['类型推断让静态语言不必处处标注', '可选类型与运行时校验可以渐进增强'],
    caption: '静态与动态不是优劣而是取舍：项目越大、协作越多，编译期检查的收益越明显。',
  },
  cross_collections: {
    image: 'diagram_cross_collections.webp',
    alt: '三种核心集合在语言中的对应',
    title: '三种核心集合的跨语言对照',
    type: 'grid',
    rows: 3,
    cols: 3,
    rowLabels: ['Java', 'Python', 'Go'],
    colLabels: ['有序列表', '键值映射', '去重集合'],
    cells: [
      { r: 0, c: 0, text: 'ArrayList', fill: '#e7eeff', stroke: '#6c8ff8', bold: true },
      { r: 0, c: 1, text: 'HashMap', fill: '#e0f2fe', stroke: '#0ea5e9', bold: true },
      { r: 0, c: 2, text: 'HashSet', fill: '#dcfce7', stroke: '#16a34a', bold: true },
      { r: 1, c: 0, text: 'list', fill: '#e7eeff', stroke: '#6c8ff8', bold: true },
      { r: 1, c: 1, text: 'dict', fill: '#e0f2fe', stroke: '#0ea5e9', bold: true },
      { r: 1, c: 2, text: 'set', fill: '#dcfce7', stroke: '#16a34a', bold: true },
      { r: 2, c: 0, text: 'slice', fill: '#e7eeff', stroke: '#6c8ff8', bold: true },
      { r: 2, c: 1, text: 'map', fill: '#e0f2fe', stroke: '#0ea5e9', bold: true },
      { r: 2, c: 2, text: 'map[T]struct{}', fill: '#dcfce7', stroke: '#16a34a', bold: true },
    ],
    notes: ['哈希表平均 O(1)，有序结构查找 O(log n)'],
    caption: '集合的语义比名字更重要：是否有序、是否允许重复、查找复杂度决定选型。',
  },
  cross_concurrency: {
    image: 'diagram_cross_concurrency.webp',
    alt: '线程、协程、事件循环三大并发模型',
    title: '并发三大家族：线程、协程、事件循环',
    type: 'compare',
    columns: [
      { title: '线程', items: ['Java、C++、C#', '由操作系统调度', '共享内存需加锁', '阻塞会占用线程', '适合 CPU 密集与成熟生态'] },
      { title: '协程', items: ['Kotlin、Go、Swift、Python asyncio', '用户态调度，开销更小', '可挂起而不阻塞线程', '结构化并发便于取消', '注意别阻塞调度线程'] },
      { title: '事件循环', items: ['JavaScript、Node.js', '单线程加回调队列', 'I/O 高效、无锁竞争', 'CPU 密集会卡住全流程', '用工作线程或子进程卸载'] },
    ],
    caption: '模型不同但目标一致：让 I/O 等待时间被别的任务利用；选型要看任务是 I/O 密集还是 CPU 密集。',
  },
  cross_errors_testing: {
    image: 'diagram_cross_errors.webp',
    alt: '异常、错误值、结果类型三种错误处理流派',
    title: '错误处理三大流派',
    type: 'compare',
    columns: [
      { title: '异常', items: ['Java、Python、C#、Kotlin', '异常沿调用栈向上抛', '正常路径不必写检查', '可能被忽略或漏捕获', '要区分可恢复与致命'] },
      { title: '返回错误值', items: ['Go、C', '错误作为返回值显式检查', '控制流一眼可见', '容易写重复的 if err', '要用 %w 包装保留上下文'] },
      { title: '结果类型', items: ['Rust Result、C# 与 Kotlin 的 Result', '类型系统强制处理', '编译期保证不遗漏', '可链式组合与转换', '错误即值，便于测试'] },
    ],
    caption: '三种流派都要回答同一个问题：错误在哪一层被处理、上下文怎么保留、调用方会不会遗漏。',
  },
  cross_package_manage: {
    image: 'diagram_cross_package.webp',
    alt: '九种生态的包管理器与锁文件',
    title: '包管理与依赖：清单、锁文件、仓库',
    type: 'grid',
    rows: 4,
    cols: 2,
    rowLabels: ['Python', 'JavaScript', 'Java/Kotlin', 'Rust'],
    colLabels: ['包管理器', '锁文件'],
    cells: [
      { r: 0, c: 0, text: 'pip / uv / poetry' },
      { r: 0, c: 1, text: 'requirements.txt / poetry.lock' },
      { r: 1, c: 0, text: 'npm / pnpm / yarn' },
      { r: 1, c: 1, text: 'package-lock.json / pnpm-lock.yaml' },
      { r: 2, c: 0, text: 'Maven / Gradle' },
      { r: 2, c: 1, text: 'pom.xml / gradle.lockfile' },
      { r: 3, c: 0, text: 'cargo' },
      { r: 3, c: 1, text: 'Cargo.lock' },
    ],
    notes: ['清单声明范围，锁文件固定精确版本', '两者都要进版本库才能复现构建'],
    caption: '依赖可复现的关键是锁文件入库；只提交清单会在不同机器装出不同版本。',
  },
  cross_build_release: {
    image: 'diagram_cross_build.webp',
    alt: '从源码到制品的构建流水线',
    title: '构建流水线：源码、依赖、编译、制品、发布',
    type: 'flow',
    steps: [
      { title: '源码', desc: '版本受控的输入' },
      { title: '依赖解析', desc: '按锁文件还原环境' },
      { title: '编译打包', desc: '各语言工具链' },
      { title: '制品', desc: '二进制、jar、wheel、镜像' },
      { title: '发布', desc: '带版本号与校验值' },
    ],
    notes: ['开发用热重载，生产用最小化构建', '制品要唯一可追溯'],
    caption: '制品是构建的产物而不是源码本身；同一制品在测试与生产间传递才能保证一致。',
  },
  cross_logging_observability: {
    image: 'diagram_cross_logging.webp',
    alt: '结构化日志、指标、链路与告警',
    title: '日志与可观测性：从记录到告警',
    type: 'layers',
    widths: [1, 0.86, 0.7, 0.5],
    layers: [
      { title: '结构化日志', desc: '键值对输出，含时间、级别、请求 ID' },
      { title: '指标', desc: '计数器、仪表、直方图，聚合看趋势' },
      { title: '链路追踪', desc: '用 trace ID 串起跨服务调用' },
      { title: '告警', desc: '基于 SLO 的阈值与错误的预算' },
    ],
    caption: '日志要能被机器解析，指标要能反映用户体验，链路要能跨服务串联。',
  },
  cross_cli_args: {
    image: 'diagram_cross_cli.webp',
    alt: '命令行参数解析的四个共同概念',
    title: '命令行参数：四个共同概念',
    type: 'grid',
    rows: 4,
    cols: 2,
    colLabels: ['概念', '说明'],
    cells: [
      { r: 0, c: 0, text: '位置参数', fill: '#e7eeff', stroke: '#6c8ff8', bold: true },
      { r: 0, c: 1, text: '按顺序传入，如 cp a b' },
      { r: 1, c: 0, text: '选项与标志', fill: '#e0f2fe', stroke: '#0ea5e9', bold: true },
      { r: 1, c: 1, text: '-v 短选项，--verbose 长选项' },
      { r: 2, c: 0, text: '子命令', fill: '#dcfce7', stroke: '#16a34a', bold: true },
      { r: 2, c: 1, text: 'git commit、docker run 的组织方式' },
      { r: 3, c: 0, text: '退出码', fill: '#fef3c7', stroke: '#f59e0b', bold: true },
      { r: 3, c: 1, text: '0 成功，非 0 表示失败原因' },
    ],
    notes: ['参数缺失要给出用法提示', '标准库与第三方库按复杂度选择'],
    caption: '各语言库名不同，但位置参数、选项、子命令、退出码这四件事是共通的。',
  },
  cross_string_regex: {
    image: 'diagram_cross_strings.webp',
    alt: '可变与不可变字符串的对照',
    title: '字符串：可变与不可变的两类设计',
    type: 'compare',
    columns: [
      { title: '不可变字符串', items: ['Java、C#、Python、Go、Rust', '每次修改都产生新对象', '可安全共享与做键', '频繁拼接要用 builder', '正则库通常独立'] },
      { title: '可变字符串', items: ['C++ std::string、Ruby、PHP', '原地修改，注意容量', '拼接高效但共享有风险', '迭代器可能失效', '需显式处理编码'] },
    ],
    notes: ['正则元字符与转义在各语言略有差异', '原始字符串能减少反斜杠地狱'],
    caption: '字符串可变性决定了拼接、并发共享与哈希键的用法；跨语言迁移时这是最容易踩坑的地方。',
  },
  cross_time_timezone: {
    image: 'diagram_cross_time.webp',
    alt: '时间戳、时区与本地化显示的转换',
    title: '时间处理：UTC 存储、时区转换、本地显示',
    type: 'layers',
    widths: [1, 0.8, 0.6],
    layers: [
      { title: '存储时间戳', desc: '统一用 UTC 或带偏移量的时间点' },
      { title: '时区转换', desc: '按用户或业务时区计算边界' },
      { title: '本地化显示', desc: '格式化与语言习惯交给展示层' },
    ],
    notes: ['区分时间点与本地时间', '夏令时会产生重复与缺失的时刻'],
    caption: '三条铁律：存储用 UTC，计算用明确时区，展示交给本地化；混用必然出错。',
  },
  cross_serialization: {
    image: 'diagram_cross_serialization.webp',
    alt: 'JSON、YAML、Protobuf 的对比',
    title: '序列化格式：JSON、YAML、Protobuf',
    type: 'compare',
    columns: [
      { title: 'JSON', items: ['最通用的交换格式', '浏览器原生支持', '可读性尚可、体积偏大', '无类型与注释', '适合对外 API'] },
      { title: 'YAML', items: ['配置文件首选', '支持注释与多文档', '缩进敏感易出错', '适合人工维护', '解析慢于 JSON'] },
      { title: 'Protobuf', items: ['强类型与 schema', '二进制体积小、速度快', '适合服务间通信', '需要代码生成', '可读性差'] },
    ],
    notes: ['对外接口用 JSON，内部高频通信用 Protobuf', '配置不要用文本工具乱改'],
    caption: '选格式看场景：对外可读优先 JSON，配置用 YAML，内部性能敏感用 Protobuf。',
  },
  cross_performance_profiling: {
    image: 'diagram_cross_profiling.webp',
    alt: '性能剖析的五步流程',
    title: '性能剖析：基准、采样、火焰图、定位、验证',
    type: 'flow',
    steps: [
      { title: '基准测试', desc: '可重复的负载与指标' },
      { title: '采样剖析', desc: '按时间采样调用栈' },
      { title: '火焰图', desc: '看宽度找热点路径' },
      { title: '定位瓶颈', desc: '区分 CPU、I/O 与锁' },
      { title: '优化验证', desc: '前后对比再决定保留' },
    ],
    notes: ['先测量再优化', '基准要预热，避免 JIT 与缓存干扰'],
    caption: '性能工作的一半是测量：没有可重复的基准，优化就只是猜测。',
  },
  cross_ci_config: {
    image: 'diagram_cross_ci.webp',
    alt: '跨生态的通用 CI 五阶段',
    title: 'CI 流水线：跨生态通用的五个阶段',
    type: 'flow',
    direction: 'vertical',
    steps: [
      { title: '检出与缓存', desc: '拉源码，缓存依赖目录' },
      { title: '安装依赖', desc: '按锁文件还原精确版本' },
      { title: '构建', desc: '编译或打包' },
      { title: '测试与检查', desc: '单测、lint、类型检查' },
      { title: '制品与部署', desc: '上传制品并按环境发布' },
    ],
    caption: '各生态的命令不同，但五阶段结构一致；把依赖缓存做好，流水线速度会有量级差别。',
  },
  cross_security_ecosystem: {
    image: 'diagram_cross_security.webp',
    alt: '依赖安全与密钥管理流程',
    title: '供应链安全：清单、扫描、密钥、轮换',
    type: 'flow',
    steps: [
      { title: '依赖清单', desc: '锁定版本并生成 SBOM' },
      { title: '漏洞扫描', desc: '对比漏洞库并分级' },
      { title: '许可证检查', desc: '避免不合规依赖' },
      { title: '密钥管理', desc: '密钥不入库，走密钥服务' },
      { title: '轮换与吊销', desc: '定期轮换并支持应急' },
    ],
    notes: ['泄露后先吊销再排查，顺序不能反'],
    caption: '供应链风险来自依赖、构建与密钥三条路径；先能列出清单，才谈得上治理。',
  },
  cross_db_access: {
    image: 'diagram_cross_db.webp',
    alt: '原生驱动、ORM、查询构建器的对照',
    title: '数据库访问三种方式',
    type: 'compare',
    columns: [
      { title: '原生驱动', items: ['直接写 SQL 与参数绑定', '性能与语义最可控', '样板代码多', '适合复杂查询与批处理', '必须防 SQL 注入'] },
      { title: 'ORM', items: ['对象与表映射', '开发效率高', '易触发 N+1 查询', '复杂查询难表达', '要会看生成的 SQL'] },
      { title: '查询构建器', items: ['用代码拼 SQL', '比 ORM 更贴近 SQL', '类型安全取决于实现', '适合动态条件', '仍需处理事务'] },
    ],
    notes: ['N+1：一次查询取出列表，再逐条查关联'],
    caption: '三种方式常混用：常规增删改查用 ORM，复杂报表回到原生 SQL 并保留可读性。',
  },
  cross_api_contract: {
    image: 'diagram_contract.webp',
    alt: '契约定义、代码生成与契约测试',
    title: '接口契约：定义、生成、测试、校验',
    type: 'flow',
    steps: [
      { title: '契约定义', desc: 'OpenAPI 或 IDL 描述接口' },
      { title: '代码生成', desc: '生成客户端与服务端骨架' },
      { title: '实现对齐', desc: '按契约实现与校验参数' },
      { title: '契约测试', desc: '生产者与消费者双向验证' },
      { title: '版本管理', desc: '破坏性变更要升版本' },
    ],
    notes: ['契约变更要与代码同批评审', '消费者驱动契约能提前发现不兼容'],
    caption: '契约是服务间的接口合同；把它纳入版本库与流水线，才能避免上线才发现不兼容。',
  },
  cross_i18n: {
    image: 'diagram_i18n_flow.webp',
    alt: '国际化的抽取、翻译、格式化与测试',
    title: '国际化流程：抽取、翻译、格式化、测试',
    type: 'flow',
    steps: [
      { title: '文案抽取', desc: '代码中不硬编码文案' },
      { title: '资源文件', desc: '按语言维护键值对' },
      { title: '格式化规则', desc: '复数、性别、日期与货币' },
      { title: '本地化测试', desc: '假语言与伪本地化验证' },
      { title: '回退策略', desc: '缺失键要有默认与告警' },
    ],
    notes: ['不要用字符串拼接句子', '文本长度差异会影响布局'],
    caption: '国际化的关键是永远不要拼接自然语言；复数与语序规则必须交给格式化库。',
  },
};
