// P2 项目实战配图数据。
module.exports = {
  project_requirements_design: {
    image: 'diagram_project_requirements.webp',
    alt: '从想法到排期的五个步骤',
    title: '需求到设计：想法、目标、范围、任务、排期',
    type: 'flow',
    steps: [
      { title: '模糊想法', desc: '想解决谁的什么问题' },
      { title: '可验收目标', desc: '写成可判断完成的标准' },
      { title: '划定范围', desc: '明确不做什么' },
      { title: '拆解任务', desc: '每项不超过一天' },
      { title: '排期依赖', desc: '识别关键路径与风险' },
    ],
    notes: ['范围蔓延是项目延期的主因', '任务要有明确完成定义'],
    caption: '第一步不是写代码，而是把「做一个工具」变成「谁能用它完成什么、怎样算完成」。',
  },
  project_coding_workflow: {
    image: 'diagram_coding_workflow.webp',
    alt: '编码工作流的五个环节',
    title: '编码工作流：分支、提交、自测、评审、合并',
    type: 'flow',
    steps: [
      { title: '拉分支', desc: '每个任务一条短分支' },
      { title: '小步提交', desc: '一次提交只做一件事' },
      { title: '本地自测', desc: '测试与静态检查先过' },
      { title: '发起评审', desc: '写清背景与验证方式' },
      { title: '合并主干', desc: '删除分支保持整洁' },
    ],
    notes: ['提交信息写「为什么」而不只是「做了什么」', '分支存活时间越短合并冲突越少'],
    caption: '小步提交加及时评审，能让问题在几小时内暴露，而不是在发布前夜集中爆发。',
  },
  project_testing_quality: {
    image: 'diagram_quality_gates.webp',
    alt: '四层质量门禁',
    title: '质量门禁：四层防线把问题挡在上线前',
    type: 'layers',
    widths: [0.55, 0.75, 0.9, 1],
    layers: [
      { title: '提交门禁', desc: '格式化、lint、单元测试，本地或 pre-commit 拦截' },
      { title: 'CI 门禁', desc: '全量测试、类型检查、依赖与安全扫描' },
      { title: '预发验证', desc: '真实依赖下的集成与契约测试' },
      { title: '生产观测', desc: '灰度指标、告警与快速回滚' },
    ],
    caption: '每层门禁回答不同问题；把所有检查都堆到最后一层，代价就是发布变成高风险动作。',
  },
  project_deploy_ops: {
    image: 'diagram_deploy_flow.webp',
    alt: '从构建到回滚的发布流程',
    title: '发布流程：构建、预发、灰度、全量、回滚',
    type: 'flow',
    steps: [
      { title: '构建制品', desc: '版本号唯一且可追溯' },
      { title: '预发验证', desc: '与环境同构的最后一关' },
      { title: '灰度放量', desc: '先小流量观察指标' },
      { title: '全量发布', desc: '分批推进并持续观察' },
      { title: '回滚预案', desc: '一分钟内可退回' },
    ],
    notes: ['配置与代码分离', '数据库变更要兼容前后两个版本'],
    caption: '稳定发布的关键不是不出错，而是出错时能快速、确定地回退。',
  },
  project_retro_improve: {
    image: 'diagram_retro_loop.webp',
    alt: '度量、复盘、改进、验证的闭环',
    title: '改进闭环：度量、复盘、改进、验证',
    type: 'cycle',
    center: '持续改进',
    nodes: [
      { title: '度量', desc: '用数据看现状' },
      { title: '复盘', desc: '还原决策与偏差' },
      { title: '改进', desc: '形成可执行行动项' },
      { title: '验证', desc: '下个周期看是否变好' },
    ],
    backLabel: '没有验证的改进会退回去',
    caption: '复盘的价值在下个周期体现：行动项要落到人、时间和验证方式上。',
  },
  project_python_cli_todo: {
    image: 'diagram_python_todo.webp',
    alt: 'Python CLI 待办工具的结构',
    title: 'CLI 待办工具：解析、模型、存储、输出',
    type: 'flow',
    direction: 'vertical',
    steps: [
      { title: '参数解析', desc: 'argparse 定义子命令与选项' },
      { title: '任务模型', desc: '标题、状态、优先级、截止时间' },
      { title: '持久化', desc: 'JSON 或 SQLite 保存任务' },
      { title: '命令执行', desc: '增删改查与筛选' },
      { title: '输出格式', desc: '表格展示与退出码' },
    ],
    caption: '小工具也要分层：解析、模型、存储、输出分开，才能加测试和换存储方式。',
  },
  project_rest_api_sqlite: {
    image: 'diagram_rest_sqlite.webp',
    alt: 'REST API 与 SQLite 事务的调用时序',
    title: 'REST API 与 SQLite：一次写入的时序',
    type: 'sequence',
    actors: ['客户端', 'API 服务', '事务', 'SQLite'],
    messages: [
      { from: 0, to: 1, label: 'POST /orders' },
      { from: 1, to: 2, label: '开启事务 BEGIN' },
      { from: 2, to: 3, label: '写入订单与明细' },
      { from: 3, to: 2, label: '约束校验通过' },
      { from: 2, to: 1, label: 'COMMIT 提交' },
      { from: 1, to: 0, label: '201 返回资源 ID' },
    ],
    notes: ['失败要 ROLLBACK', '写操作串行化避免 database is locked'],
    caption: 'API 层负责校验与状态码，事务层保证多条写入要么全成功要么全回滚。',
  },
  project_rag_agent_service: {
    image: 'diagram_rag_service.webp',
    alt: '本地 RAG 客服 Agent 的处理流程',
    title: 'RAG 客服 Agent：入库、检索、组装、生成',
    type: 'flow',
    steps: [
      { title: '文档入库', desc: '切分、向量化、写索引' },
      { title: '检索召回', desc: '向量加关键词混合召回' },
      { title: '提示组装', desc: '问题、上下文与工具' },
      { title: '模型生成', desc: '带引用回答并调用工具' },
      { title: '返回与记录', desc: '附来源，记录反馈' },
    ],
    notes: ['没有召回到就别让模型硬答', '回答要带出处便于核查'],
    caption: 'RAG 的质量上限由检索决定；把引用返回给用户，才能让答案可验证。',
  },
  project_debug_performance_triage: {
    image: 'diagram_perf_triage.webp',
    alt: '慢接口定位的排查顺序',
    title: '慢接口定位：从现象到根因的五步',
    type: 'flow',
    steps: [
      { title: '确认现象', desc: '区分偶发与稳定复现' },
      { title: '看指标', desc: 'QPS、P99、错误率' },
      { title: '看链路', desc: '找出最慢的那一段' },
      { title: '看代码', desc: '剖析热点与慢查询' },
      { title: '验证修复', desc: '压测对比并补监控' },
    ],
    notes: ['先量化再优化，避免凭感觉猜', '改完要有对比数据'],
    caption: '性能排查的顺序是先确认范围、再逐层收窄；每一次优化都要有前后对比数据。',
  },
  project_interview_coding_system_design: {
    image: 'diagram_interview_prep.webp',
    alt: '算法编码与系统设计两条准备主线',
    title: '面试准备：算法编码与系统设计两条主线',
    type: 'compare',
    columns: [
      { title: '算法编码', items: ['按题型刷：数组、树、图、DP', '先说思路再写代码', '写前确认边界与复杂度', '写完自测样例', '把错题整理成模板'] },
      { title: '系统设计', items: ['先问清需求与规模', '估算 QPS、存储与带宽', '画清组件与数据流', '讨论瓶颈与取舍', '给出可演进的方案'] },
    ],
    notes: ['面试考的是沟通与推理过程，不只是最终答案'],
    caption: '两条主线都要练「说出来」：把思路讲清楚，比默写答案更能体现工程能力。',
  },
};
