// P2 Shell 配图数据。
module.exports = {
  shell_bash: {
    image: 'diagram_shell_basics.webp',
    alt: 'Bash 脚本的基本构成',
    title: 'Bash 脚本：shebang、变量、命令与退出码',
    type: 'flow',
    steps: [
      { title: 'shebang', desc: '#!/usr/bin/env bash' },
      { title: '变量', desc: '赋值不加空格，引用要加引号' },
      { title: '命令', desc: '外部命令与内建命令' },
      { title: '退出码', desc: '0 成功，非 0 表示失败' },
    ],
    notes: ['set -euo pipefail 是脚本的第一道保险', '用 shellcheck 静态检查'],
    caption: '脚本的健壮性来自显式的失败处理：命令失败要能中断，变量未定义要能报错。',
  },
  shell_flow: {
    image: 'diagram_shell_flow.webp',
    alt: 'Shell 条件、循环、函数与退出码',
    title: 'Shell 流程控制：判断、循环、函数、返回码',
    type: 'flow',
    steps: [
      { title: '条件', desc: 'if / case 分支' },
      { title: '循环', desc: 'for / while / until' },
      { title: '函数', desc: '封装可复用逻辑' },
      { title: '参数', desc: '位置参数与 getopts' },
      { title: '退出码', desc: 'return 与 exit 的区别' },
    ],
    notes: ['[ ] 与 [[ ]] 的行为差异', '命令替换要用双引号包裹'],
    caption: 'Shell 的分支与循环都以退出码为判断依据；函数返回值同样是退出码，不是数据。',
  },
  shell_pipeline: {
    image: 'diagram_shell_pipeline.webp',
    alt: '文本处理流水线的六个核心工具',
    title: '文本流水线：grep、cut、sort、uniq、awk、sed',
    type: 'flow',
    steps: [
      { title: 'grep', desc: '按模式筛行' },
      { title: 'cut', desc: '按列切字段' },
      { title: 'sort', desc: '排序便于聚合' },
      { title: 'uniq -c', desc: '去重并计数' },
      { title: 'awk', desc: '计算与格式化' },
    ],
    notes: ['sort 必须排在 uniq 之前', '大文件优先用流式工具而不是全量读入内存'],
    caption: '每个工具只做一件事，用管道串联就能完成日志统计、去重与报表生成。',
  },
  shell_robust: {
    image: 'diagram_shell_robust.webp',
    alt: '健壮脚本的四个要点',
    title: '健壮脚本：严格模式、清理、引号、检查',
    type: 'flow',
    steps: [
      { title: '严格模式', desc: 'set -euo pipefail' },
      { title: '清理钩子', desc: 'trap 处理退出与信号' },
      { title: '引号包裹', desc: '"$var" 防止分词与通配' },
      { title: '静态检查', desc: 'shellcheck 提前发现问题' },
    ],
    notes: ['mktemp 创建临时文件并确保清理', '不要解析 ls 的输出'],
    caption: '可移植与健壮并不冲突：严格模式、显式引号、可靠清理是脚本能进生产的前提。',
  },
  shell_process_cron: {
    image: 'diagram_shell_cron.webp',
    alt: '进程控制与定时任务',
    title: '进程控制与定时任务：从作业到调度',
    type: 'flow',
    steps: [
      { title: '作业控制', desc: 'jobs、fg、bg 管理前后台' },
      { title: '信号', desc: 'kill -TERM 优雅退出' },
      { title: 'cron', desc: '五段时间表达式定时' },
      { title: 'systemd timer', desc: '依赖与日志更完善' },
      { title: '日志轮转', desc: 'logrotate 控制体积' },
    ],
    notes: ['cron 环境变量与登录 shell 不同', '任务要幂等，重跑不能产生副作用'],
    caption: '定时任务的难点不是调度，而是幂等、并发互斥和日志可追溯。',
  },
  shell_script_engineering: {
    image: 'diagram_shell_engineering.webp',
    alt: 'Shell 脚本工程化的四个实践',
    title: 'Shell 工程化：目录、测试、检查、发布',
    type: 'flow',
    steps: [
      { title: '目录结构', desc: 'bin、lib、test 分离' },
      { title: '单元测试', desc: 'bats 断言函数行为' },
      { title: '静态检查', desc: 'shellcheck 与 shfmt' },
      { title: '版本发布', desc: '打标签并附带变更说明' },
    ],
    notes: ['超过几百行的脚本考虑改用 Python 或 Go', '公共函数抽到 lib 并加注释'],
    caption: '脚本一旦被团队依赖，就需要和代码一样有测试、检查与版本管理。',
  },
  shell_container: {
    image: 'diagram_shell_container.webp',
    alt: 'Shell 脚本在容器与集群中的位置',
    title: 'Shell 与容器：构建、入口、运维三段',
    type: 'flow',
    steps: [
      { title: 'Dockerfile', desc: 'RUN 里执行构建脚本' },
      { title: 'entrypoint', desc: '容器启动时初始化环境' },
      { title: '健康检查', desc: '探针脚本判断就绪' },
      { title: 'kubectl', desc: '脚本化发布与回滚' },
    ],
    notes: ['入口脚本要正确处理 SIGTERM', 'exec 让主进程接管 PID 1'],
    caption: '容器脚本的核心职责是初始化与信号转发；用 exec 保证主进程能收到停止信号。',
  },
  shell_text_advanced: {
    image: 'diagram_shell_text_tools.webp',
    alt: 'grep、sed、awk 三者分工',
    title: 'grep、sed、awk：三者的分工',
    type: 'compare',
    columns: [
      { title: 'grep', items: ['按行匹配模式', '过滤与计数', '-E 扩展正则', '-r 递归目录', '不修改内容'] },
      { title: 'sed', items: ['流式替换与删除', 's/旧/新/g', '-n 配合 p 打印', '按行号或地址操作', '适合就地编辑'] },
      { title: 'awk', items: ['按字段处理', '$1、$NF 取列', '条件与循环', '聚合统计求和', '自定义输出格式'] },
    ],
    notes: ['正则元字符在不同工具里略有差异', '就地编辑前先备份或用 -i.bak'],
    caption: '选工具看问题：筛行用 grep，改行用 sed，按列计算用 awk。',
  },
  shell_ops_scripts: {
    image: 'diagram_shell_ops.webp',
    alt: '运维脚本的三类常见场景',
    title: '运维脚本三类场景：备份、巡检、批量操作',
    type: 'compare',
    columns: [
      { title: '备份', items: ['确定备份窗口', '全量与增量结合', '校验可恢复性', '保留策略与清理', '失败要告警'] },
      { title: '巡检', items: ['磁盘、内存、负载', '服务存活与端口', '证书与日志过期', '输出结构化报告', '异常即告警'] },
      { title: '批量操作', items: ['清单驱动而非手写', '并发度可控', '逐台记录结果', '失败可重试', '危险操作先演练'] },
    ],
    caption: '运维脚本的第一要求是安全可重试：批量操作要先 dry-run，再小范围验证，最后全量。',
  },
  shell_ci_templates: {
    image: 'diagram_shell_ci.webp',
    alt: 'CI 流水线中的 Shell 脚本阶段',
    title: 'CI 脚本模板：检出、构建、测试、部署、回滚',
    type: 'flow',
    direction: 'vertical',
    steps: [
      { title: '检出与准备', desc: '拉代码、装依赖、缓存' },
      { title: '构建', desc: '编译并产出制品' },
      { title: '测试', desc: '单测与静态检查' },
      { title: '部署', desc: '发布到目标环境' },
      { title: '验证与回滚', desc: '健康检查失败即回退' },
    ],
    caption: 'CI 脚本要可重复执行、失败快速退出、日志足够定位，且把回滚路径提前准备好。',
  },
  shell_security: {
    image: 'diagram_shell_security.webp',
    alt: 'Shell 脚本安全加固的四道防线',
    title: 'Shell 安全：输入、权限、环境、审计',
    type: 'flow',
    steps: [
      { title: '校验输入', desc: '白名单与长度检查' },
      { title: '最小权限', desc: '避免直接使用 root' },
      { title: '隔离环境', desc: '限制 PATH 与工作目录' },
      { title: '记录审计', desc: '关键操作写日志' },
    ],
    notes: ['禁止 eval 拼接外部输入', '临时文件用 mktemp 并限制权限'],
    caption: '脚本注入的根源是把外部输入当代码执行；校验、引用与最小权限能挡住绝大多数风险。',
  },
  shell_json_yaml: {
    image: 'diagram_jq_yq.webp',
    alt: 'jq 与 yq 处理结构化数据',
    title: '结构化数据处理：jq 处理 JSON，yq 处理 YAML',
    type: 'compare',
    columns: [
      { title: 'jq（JSON）', items: ['按路径取值 .a.b', '管道连续变换', 'map/select 过滤数组', '支持默认值与类型转换', '输出可再喂给下一个工具'] },
      { title: 'yq（YAML）', items: ['读写 YAML 与多文档', '语法与 jq 高度相似', '可原地修改配置文件', '保留注释需注意版本', '适合 K8s 清单批处理'] },
    ],
    notes: ['不要用 sed 改 JSON：缩进、转义、顺序都不可靠', '解析失败先验证输入是否合法'],
    caption: '结构化数据要用结构化工具：jq/yq 能正确处理转义与嵌套，文本工具会在边界情况上出错。',
  },
  shell_project_deploy: {
    image: 'diagram_zero_downtime.webp',
    alt: '零停机部署的五个步骤',
    title: '零停机部署：新实例就绪后再切流量',
    type: 'flow',
    direction: 'vertical',
    steps: [
      { title: '构建新版本', desc: '产出不可变制品' },
      { title: '启动新实例', desc: '不接流量先启动' },
      { title: '健康检查', desc: '探针通过才算就绪' },
      { title: '切换流量', desc: '负载均衡摘挂实例' },
      { title: '停旧实例', desc: '优雅退出并保留回滚包' },
    ],
    caption: '零停机的关键是「先就绪再接入」；任何时刻都要保留上一版本以便一分钟内回滚。',
  },
  shell_project_log_analysis: {
    image: 'diagram_log_alert.webp',
    alt: '日志采集到告警的流水线',
    title: '日志分析告警流水线：采集、解析、聚合、告警',
    type: 'flow',
    steps: [
      { title: '采集', desc: 'tail -F 或日志代理' },
      { title: '解析', desc: '提取时间、级别、字段' },
      { title: '聚合', desc: '按分钟与错误码计数' },
      { title: '判定', desc: '阈值与同比对比' },
      { title: '告警', desc: '通知并附上下文' },
    ],
    notes: ['告警要能指向具体原因', '避免重复告警与告警风暴'],
    caption: '日志告警的价值在于快速定位；只报「错误变多」而不带样本，等于把排查成本转给值班人。',
  },
  shell_portability: {
    image: 'diagram_shell_posix.webp',
    alt: 'Bash 扩展与 POSIX 兼容写法对照',
    title: '可移植性：Bash 扩展与 POSIX 写法对照',
    type: 'compare',
    columns: [
      { title: 'Bash 扩展', items: ['[[ ]] 条件表达式', '数组与关联数组', 'local 声明局部变量', '进程替换 <()', '字符串替换 ${v//a/b}'] },
      { title: 'POSIX 兼容', items: ['[ ] 加引号判断', '无数组，用位置参数', '函数内变量全局', '避免 <<< 与 <<(', '用 sed 或 cut 处理字符串'] },
    ],
    notes: ['#!/bin/sh 要按 POSIX 写', '在 Alpine 等精简镜像里尤其重要'],
    caption: '确定运行环境再选语法：需要跨发行版与容器运行时，就坚持 POSIX 子集。',
  },
  shell_security_hardening: {
    image: 'diagram_shell_hardening.webp',
    alt: 'Shell 脚本的分层加固',
    title: '分层加固：输入层、权限层、环境层、审计层',
    type: 'layers',
    widths: [1, 0.86, 0.7, 0.54],
    layers: [
      { title: '输入层', desc: '白名单校验、拒绝特殊字符、限制长度' },
      { title: '权限层', desc: '非 root 运行、最小文件权限、按需提权' },
      { title: '环境层', desc: '固定 PATH、限定工作目录、禁网络与危险命令' },
      { title: '审计层', desc: '记录执行者、参数与结果，便于追溯' },
    ],
    caption: '加固不是单点措施而是一层层收窄：每层都假设上一层可能被绕过。',
  },
  shell_automation_advanced: {
    image: 'diagram_shell_automation.webp',
    alt: '自动化脚本的四个进阶能力',
    title: '自动化进阶：触发、并发、重试、上报',
    type: 'flow',
    steps: [
      { title: '触发', desc: '定时、事件或 Webhook' },
      { title: '并发控制', desc: '锁文件避免重复执行' },
      { title: '重试幂等', desc: '指数退避且可安全重跑' },
      { title: '指标上报', desc: '耗时、成功率、产出量' },
    ],
    notes: ['用 flock 做互斥', '失败要保留现场日志'],
    caption: '自动化脚本进入生产后就是服务：需要互斥、幂等、可观测和明确的失败处理。',
  },
  shell_first_script: {
    image: 'diagram_shell_first.webp',
    alt: '第一个 Shell 脚本的结构',
    title: '第一个脚本：四行代码的结构',
    type: 'flow',
    steps: [
      { title: 'shebang', desc: '指定解释器路径' },
      { title: '变量', desc: 'name="World" 不加空格' },
      { title: '输出', desc: 'echo "Hello, $name"' },
      { title: '执行', desc: 'chmod +x 后直接运行' },
    ],
    notes: ['bash script.sh 与 ./script.sh 的区别在权限', '退出码 0 表示成功'],
    caption: '脚本的本质是一串按顺序执行的命令；先跑通最小示例，再逐步加入判断与循环。',
  },
  shell_variables_args: {
    image: 'diagram_shell_args.webp',
    alt: 'Shell 位置参数与特殊变量的含义',
    title: '变量与参数：五个必须记住的符号',
    type: 'grid',
    rows: 5,
    cols: 2,
    colLabels: ['写法', '含义'],
    cells: [
      { r: 0, c: 0, text: '$0', fill: '#e7eeff', stroke: '#6c8ff8', bold: true },
      { r: 0, c: 1, text: '脚本自身的名称' },
      { r: 1, c: 0, text: '$1 $2', fill: '#e7eeff', stroke: '#6c8ff8', bold: true },
      { r: 1, c: 1, text: '第 1、2 个位置参数' },
      { r: 2, c: 0, text: '$@', fill: '#e0f2fe', stroke: '#0ea5e9', bold: true },
      { r: 2, c: 1, text: '全部参数，加引号保留分组' },
      { r: 3, c: 0, text: '$#', fill: '#dcfce7', stroke: '#16a34a', bold: true },
      { r: 3, c: 1, text: '参数的个数' },
      { r: 4, c: 0, text: '$?', fill: '#fef3c7', stroke: '#f59e0b', bold: true },
      { r: 4, c: 1, text: '上一条命令的退出码' },
    ],
    caption: '"$@" 与 $@ 的差别在引号：前者保留参数边界，后者会被再次分词。',
  },
  shell_conditions: {
    image: 'diagram_shell_conditions.webp',
    alt: 'Shell 条件判断的四种结构',
    title: '条件判断：测试、分支、多路、退出码',
    type: 'flow',
    steps: [
      { title: 'test / [ ]', desc: '比较数值、字符串与文件' },
      { title: 'if/elif/else', desc: '二选一与多分支' },
      { title: 'case', desc: '按模式匹配分支' },
      { title: '退出码', desc: '判断命令是否成功' },
    ],
    notes: ['[ -f file ] 判断文件存在', '字符串比较用 = 而不是 ==（POSIX）'],
    caption: 'Shell 的 if 判断的本质是命令的退出码；理解这一点就不会被 [ ] 的怪异行为困住。',
  },
  shell_loops: {
    image: 'diagram_shell_loops.webp',
    alt: 'Shell 三种循环与控制语句',
    title: '循环：for、while、until 与流程控制',
    type: 'flow',
    steps: [
      { title: 'for', desc: '遍历列表或文件' },
      { title: 'while', desc: '条件为真时重复' },
      { title: 'until', desc: '条件为假时重复' },
      { title: 'break/continue', desc: '跳出或跳过本次' },
      { title: '读取输入', desc: 'while read line 逐行处理' },
    ],
    notes: ['循环体里的变量作用域要用 local', 'IFS 影响 for 的分词方式'],
    caption: '循环处理文件时要考虑空格与特殊字符：用 IFS= read -r 逐行读取最稳妥。',
  },
  shell_pipeline_intro: {
    image: 'diagram_shell_pipe_intro.webp',
    alt: '标准输入输出与管道的连接方式',
    title: '管道入门：标准输入、输出与重定向',
    type: 'flow',
    steps: [
      { title: '标准输入', desc: 'fd 0，默认来自键盘' },
      { title: '管道 |', desc: '前一命令输出接入下一命令' },
      { title: '标准输出', desc: 'fd 1，默认打印到终端' },
      { title: '重定向', desc: '> 覆盖，>> 追加，2> 错误' },
    ],
    notes: ['2>&1 把错误合并到标准输出', '管道中每个命令是独立进程'],
    caption: '管道连接的是数据流，不是文件；理解 fd 就能理解 >、>>、2>&1 的写法。',
  },
};
