// P2 软件工程配图数据。
module.exports = {
  design_patterns: {
    image: 'diagram_patterns.webp',
    alt: '设计模式的三类划分',
    title: '设计模式三类：创建、结构、行为',
    type: 'compare',
    columns: [
      { title: '创建型', items: ['工厂方法：把创建延迟到子类', '抽象工厂：一族相关对象', '建造者：分步构造复杂对象', '单例：全局唯一实例', '关注对象怎么被创建'] },
      { title: '结构型', items: ['适配器：转换接口', '装饰器：动态叠加职责', '代理：控制访问', '组合：树形统一处理', '关注对象怎么被组装'] },
      { title: '行为型', items: ['策略：替换算法', '观察者：事件通知', '模板方法：固定骨架', '责任链：逐级处理', '关注对象怎么协作'] },
    ],
    notes: ['SOLID：单一职责、开闭、里氏替换、接口隔离、依赖倒置', '模式是沟通词汇，不是炫技清单'],
    caption: '模式解决的是可复用的设计问题；先有变化点，再引入模式，否则只是增加抽象层。',
  },
  testing_strategy: {
    image: 'diagram_test_pyramid.webp',
    alt: '测试金字塔的层次与配比',
    title: '测试金字塔：单元多、集成中、端到端少',
    type: 'layers',
    widths: [0.45, 0.72, 1],
    layers: [
      { title: '端到端 E2E', desc: '少量关键路径，验证真实链路，最慢最脆' },
      { title: '集成测试', desc: '验证模块协作与外部依赖边界' },
      { title: '单元测试', desc: '数量最多、执行最快，定位到函数级' },
    ],
    notes: ['测试替身：stub 提供数据、mock 验证交互、fake 轻量实现'],
    caption: '金字塔倒过来就是反模式：大量脆弱的端到端测试会让团队不敢改代码。',
  },
  requirements_modeling: {
    image: 'diagram_requirements.webp',
    alt: '从需求到领域模型的过程',
    title: '需求到模型：收集、故事、验收、建模',
    type: 'flow',
    steps: [
      { title: '收集需求', desc: '区分功能与非功能' },
      { title: '用户故事', desc: '角色、目标、价值' },
      { title: '验收标准', desc: '可验证的完成定义' },
      { title: '建模', desc: '用例图、类图、时序图' },
      { title: '领域模型', desc: '统一语言与边界' },
    ],
    notes: ['需求要可验收，否则无法判断是否完成', 'DDD 的核心是统一语言与限界上下文'],
    caption: '把模糊想法变成可验收目标，再用模型对齐术语，是减少返工最有效的一步。',
  },
  se_test_design: {
    image: 'diagram_test_design.webp',
    alt: '六种经典测试用例设计方法',
    title: '六种测试用例设计方法',
    type: 'grid',
    rows: 2,
    cols: 3,
    cells: [
      { r: 0, c: 0, text: '等价类划分\n分组抽样，减少冗余', fill: '#e7eeff', stroke: '#6c8ff8', bold: true },
      { r: 0, c: 1, text: '边界值分析\n最小、最大与越界', fill: '#e0f2fe', stroke: '#0ea5e9', bold: true },
      { r: 0, c: 2, text: '判定表\n条件组合与动作', fill: '#dcfce7', stroke: '#16a34a', bold: true },
      { r: 1, c: 0, text: '因果图\n输入输出的因果约束', fill: '#fef3c7', stroke: '#f59e0b', bold: true },
      { r: 1, c: 1, text: '状态迁移\n覆盖状态与迁移路径', fill: '#ede9fe', stroke: '#7c3aed', bold: true },
      { r: 1, c: 2, text: '场景法\n串起主流程与异常流', fill: '#fee2e2', stroke: '#dc2626', bold: true },
    ],
    notes: ['用例结构：前置条件、步骤、预期结果'],
    caption: '先用等价类与边界值控制数量，再用判定表与状态迁移覆盖组合与路径。',
  },
  se_tdd_refactor: {
    image: 'diagram_tdd_cycle.webp',
    alt: 'TDD 红绿重构循环',
    title: 'TDD 循环：红、绿、重构',
    type: 'cycle',
    center: '小步前进',
    nodes: [
      { title: '红', desc: '先写一个会失败的测试' },
      { title: '绿', desc: '用最简单的方式通过' },
      { title: '重构', desc: '保持测试通过改善结构' },
      { title: '提交', desc: '每一步都可回退' },
    ],
    backLabel: '每轮循环控制在几分钟以内',
    caption: 'TDD 把设计压力提前：测试先行的目的不是覆盖率，而是让接口从调用方视角长出来。',
  },
  se_quality_metrics: {
    image: 'diagram_quality_metrics.webp',
    alt: '该度量与不该度量的指标对照',
    title: '质量度量：该看什么，不该看什么',
    type: 'compare',
    columns: [
      { title: '值得度量', items: ['变更前置时间', '部署频率', '变更失败率', '故障恢复时间', '逃逸缺陷数'] },
      { title: '容易误导', items: ['个人代码行数', '提交次数排名', '单纯的覆盖率数字', '缺陷数按人统计', '工时填报精度'] },
    ],
    notes: ['度量用于改进流程，不用于考核个人', '覆盖率是手段，不是目标'],
    caption: '好的度量推动系统改进，坏的度量会让人优化数字而不是优化结果。',
  },
  sdl_security: {
    image: 'diagram_sdl.webp',
    alt: '安全左移的开发流程',
    title: 'SDL：把安全左移到每个阶段',
    type: 'flow',
    steps: [
      { title: '需求', desc: '明确安全与合规要求' },
      { title: '设计', desc: '威胁建模与信任边界' },
      { title: '编码', desc: '安全规范与依赖扫描' },
      { title: '测试', desc: 'SAST、DAST、渗透' },
      { title: '运维', desc: '监控、响应与修复' },
    ],
    notes: ['STRIDE：仿冒、篡改、否认、信息泄露、拒绝服务、权限提升'],
    caption: '越早发现安全问题修复成本越低；威胁建模是设计阶段性价比最高的活动。',
  },
  se_code_review: {
    image: 'diagram_code_review.webp',
    alt: '代码评审的完整流程',
    title: '代码评审：自审、小批量、评审、合并',
    type: 'flow',
    steps: [
      { title: '作者自审', desc: '先自己过一遍 diff' },
      { title: '小批量提交', desc: '单次改动控制在可读范围' },
      { title: '评审反馈', desc: '针对代码而非个人' },
      { title: '修改回应', desc: '逐条回复或说明理由' },
      { title: '合并', desc: '通过门禁后进入主干' },
    ],
    notes: ['评论要说明原因与建议', '评审要看逻辑与边界，而不只是格式'],
    caption: '评审的目标是共享上下文与发现缺陷；改动越小，评审质量越高、速度越快。',
  },
  se_tech_writing: {
    image: 'diagram_docs_types.webp',
    alt: '三类工程文档的定位',
    title: '工程文档三类：README、设计文档、运维手册',
    type: 'compare',
    columns: [
      { title: 'README', items: ['这是什么、解决什么问题', '快速开始与最小示例', '依赖与运行环境', '常见问题', '写给第一次接触的人'] },
      { title: '设计文档', items: ['背景与目标', '方案与权衡', '数据模型与接口', '风险与回滚', '写给未来的维护者'] },
      { title: '运维手册', items: ['部署步骤与配置项', '监控指标与告警', '常见故障处置', '扩容与回滚流程', '写给半夜被叫醒的人'] },
    ],
    caption: '好文档的标准是让目标读者在最少上下文下完成任务；先写清楚读者是谁，再决定写什么。',
  },
  se_postmortem: {
    image: 'diagram_incident.webp',
    alt: '事故处理与复盘流程',
    title: '事故处理：止损、定位、修复、复盘',
    type: 'flow',
    steps: [
      { title: '止损', desc: '先恢复服务再查原因' },
      { title: '定位', desc: '按时间线收集证据' },
      { title: '修复', desc: '消除根因并验证' },
      { title: '复盘', desc: '无责还原决策过程' },
      { title: '改进', desc: '转成可跟踪的行动项' },
    ],
    notes: ['无责复盘不等于无责任，而是聚焦系统与流程', '改进项要有负责人与截止时间'],
    caption: '复盘的产出是改进项，不是责任认定；没有行动项的复盘等于没做。',
  },
  se_oncall: {
    image: 'diagram_oncall.webp',
    alt: 'On-Call 值班的告警闭环',
    title: 'On-Call：告警、分级、响应、复盘',
    type: 'cycle',
    center: '告警治理',
    nodes: [
      { title: '触发告警', desc: '基于 SLO 而不是直觉' },
      { title: '分级响应', desc: '按影响面决定处理方式' },
      { title: '恢复服务', desc: '止损优先于根因' },
      { title: '复盘改进', desc: '消除噪音与盲区' },
    ],
    backLabel: '可行动、有上下文、不重复',
    caption: '每条告警都应该可行动；不能行动的告警就是噪音，会训练值班人忽略信号。',
  },
  se_tech_debt: {
    image: 'diagram_tech_debt.webp',
    alt: '技术债务的四象限与处理策略',
    title: '技术债务：按影响与成本排优先级',
    type: 'grid',
    rows: 2,
    cols: 2,
    rowLabels: ['影响大', '影响小'],
    colLabels: ['成本低', '成本高'],
    cells: [
      { r: 0, c: 0, text: '立即偿还\n小改动解决大问题', fill: '#dcfce7', stroke: '#16a34a', bold: true },
      { r: 0, c: 1, text: '排期专项\n拆分后逐步偿还', fill: '#fef3c7', stroke: '#f59e0b', bold: true },
      { r: 1, c: 0, text: '顺手清理\n改到这里就顺手做掉', fill: '#e0f2fe', stroke: '#0ea5e9', bold: true },
      { r: 1, c: 1, text: '记录暂缓\n写清原因与触发条件', fill: '#f3f4f6', stroke: '#9ca3af', bold: true },
    ],
    caption: '债务本身不可怕，可怕的是无人知晓；把它显式记录并纳入优先级才是管理。',
  },
};
