// P2 工具链配图数据。
module.exports = {
  git_basics: {
    image: 'diagram_git_three_areas.webp',
    alt: 'Git 工作区、暂存区与版本库流转',
    title: 'Git 三个工作区域与提交流转',
    type: 'flow',
    steps: [
      { title: '工作区', desc: '编辑文件，尚未登记' },
      { title: '暂存区', desc: 'git add 挑选本次改动' },
      { title: '本地仓库', desc: 'git commit 形成版本' },
      { title: '远程仓库', desc: 'git push 共享给团队' },
    ],
    notes: ['git status 看状态', 'git diff 看未暂存改动', 'git log 看历史'],
    caption: '改动逐级向右流转；每次提交应是一个可独立描述、可回滚的改动单元。',
  },
  cli: {
    image: 'diagram_cli_basics.webp',
    alt: '命令行常用操作的四步流程',
    title: '命令行四个高频动作：定位、查看、过滤、组合',
    type: 'flow',
    steps: [
      { title: '定位', desc: 'pwd、ls、cd 确定位置' },
      { title: '查看', desc: 'cat、less、head 读内容' },
      { title: '过滤', desc: 'grep、find 缩小范围' },
      { title: '组合', desc: '管道与重定向串联工具' },
    ],
    notes: ['权限：chmod 与 chown 决定能不能读写执行', '不确定的命令先 --help 或 man'],
    caption: '命令行的威力来自小而专的工具组合；管道让上一个命令的输出成为下一个的输入。',
  },
  debugging: {
    image: 'diagram_debug_loop.webp',
    alt: '调试的复现、假设、验证、修复循环',
    title: '调试循环：复现、假设、验证、修复',
    type: 'cycle',
    center: '调试循环',
    nodes: [
      { title: '复现', desc: '固定输入与步骤' },
      { title: '假设', desc: '提出可验证的猜想' },
      { title: '验证', desc: '断点、日志、二分' },
      { title: '修复', desc: '改动并补回归测试' },
    ],
    backLabel: '卡住时回到「复现」，先缩小范围再动手改',
    caption: '调试是科学方法：先稳定复现，再用最小实验验证假设，最后用测试锁住修复。',
  },
  docker: {
    image: 'diagram_container_vm.webp',
    alt: '容器与虚拟机的结构对比',
    title: '容器与虚拟机：隔离层次的差别',
    type: 'compare',
    columns: [
      { title: '容器', items: ['共享宿主机内核', '只打包应用与依赖', '启动秒级、体积小', '隔离靠 namespace 与 cgroup', '同一内核，需注意兼容性'] },
      { title: '虚拟机', items: ['每台自带完整内核', '虚拟化 CPU 与内存', '启动分钟级、体积大', '隔离靠 Hypervisor', '内核独立，兼容性更好'] },
    ],
    notes: ['镜像 = 只读层叠加', '容器 = 镜像 + 可写层 + 进程'],
    caption: '镜像负责可复现的打包，容器负责运行隔离；两者共同解决「在我机器上是好的」。',
  },
  ci_cd: {
    image: 'diagram_ci_pipeline.webp',
    alt: '持续集成流水线的五个阶段',
    title: 'CI/CD 流水线：从提交到部署的五段',
    type: 'flow',
    steps: [
      { title: '触发', desc: 'push 或 PR 触发' },
      { title: '构建', desc: '装依赖并编译' },
      { title: '测试', desc: '单测、静态检查' },
      { title: '制品', desc: '产出可部署包' },
      { title: '部署', desc: '发布并验证' },
    ],
    notes: ['同一份制品贯穿各环境', '失败要快速反馈', '密钥放 Secrets 不入库'],
    caption: '流水线把质量检查自动化；越靠前的阶段发现问题，修复成本越低。',
  },
  kubernetes: {
    image: 'diagram_k8s_objects.webp',
    alt: 'Kubernetes 从集群到容器的对象层次',
    title: 'Kubernetes 对象层次：集群、节点、Pod、容器',
    type: 'layers',
    widths: [1, 0.82, 0.62, 0.42],
    layers: [
      { title: '集群 Cluster', desc: '控制平面与工作节点的整体' },
      { title: '节点 Node', desc: '运行 Pod 的机器，含 kubelet 与 kube-proxy' },
      { title: 'Pod', desc: '最小调度单元，共享网络与存储' },
      { title: '容器', desc: '真正运行的进程，由镜像创建' },
    ],
    caption: '声明式对象描述期望状态，控制器持续把实际状态调谐到期望状态。',
  },
  observability: {
    image: 'diagram_observability_pillars.webp',
    alt: '日志、指标、链路追踪三大支柱',
    title: '可观测性三大支柱：日志、指标、链路',
    type: 'compare',
    columns: [
      { title: '日志 Logs', items: ['记录离散事件详情', '结构化字段便于检索', '适合定位具体错误', '成本随量增长'] },
      { title: '指标 Metrics', items: ['聚合的数值时间序列', '适合看趋势与告警', '存储成本低', '缺少单次请求细节'] },
      { title: '链路 Traces', items: ['串起一次请求的调用路径', '看各段耗时与依赖', '需要上下文传播', '采样控制成本'] },
    ],
    notes: ['先用指标发现异常，再用链路定位环节，最后用日志看细节'],
    caption: '三者互补：指标负责发现，链路负责定位，日志负责解释。',
  },
  terraform: {
    image: 'diagram_terraform_flow.webp',
    alt: 'Terraform 从编写到应用的流程',
    title: 'Terraform 工作流：编写、计划、应用、状态',
    type: 'flow',
    steps: [
      { title: '编写 HCL', desc: '声明期望的基础设施' },
      { title: 'init', desc: '下载 provider 与模块' },
      { title: 'plan', desc: '预览将要发生的变更' },
      { title: 'apply', desc: '执行变更并更新状态' },
      { title: 'state', desc: '记录实际资源映射' },
    ],
    notes: ['状态文件要远程存储并加锁', 'plan 必须人工确认后再 apply'],
    caption: '基础设施即代码把环境变成可评审、可回滚的声明；状态文件是它与真实资源的映射。',
  },
  linux_performance: {
    image: 'diagram_linux_perf.webp',
    alt: 'CPU、内存、磁盘、网络四类资源排查',
    title: 'Linux 性能排查：四类资源与常用指标',
    type: 'compare',
    columns: [
      { title: 'CPU', items: ['负载与运行队列', 'us/sy/wa 占比', 'top、pidstat', '多核是否均衡'] },
      { title: '内存', items: ['可用内存与缓存', '换页与 OOM', 'free、vmstat', '是否有泄漏'] },
      { title: '磁盘 I/O', items: ['吞吐与 IOPS', '等待时间 await', 'iostat、iotop', '顺序还是随机'] },
      { title: '网络', items: ['带宽与重传', '连接数与队列', 'ss、sar、tcpdump', '延迟还是丢包'] },
    ],
    caption: '先看全局指标判断哪类资源饱和，再进入进程级工具定位到具体进程与线程。',
  },
  gateway: {
    image: 'diagram_api_gateway.webp',
    alt: 'API 网关的接入、路由、策略与转发',
    title: 'API 网关：接入、路由、策略、转发',
    type: 'flow',
    steps: [
      { title: '接入', desc: 'TLS 终止与连接管理' },
      { title: '路由', desc: '按路径与域名匹配服务' },
      { title: '策略', desc: '鉴权、限流、灰度' },
      { title: '转发', desc: '负载均衡到后端实例' },
    ],
    notes: ['四层看 IP 与端口，七层看 HTTP 内容', '轮询、最少连接、一致性哈希各有适用场景'],
    caption: '网关把鉴权、限流、灰度等横切关注点从业务服务里收拢到入口统一处理。',
  },
  toolchain_project: {
    image: 'diagram_pipeline_project.webp',
    alt: '完整 CI/CD 流水线的六个阶段',
    title: '完整流水线：提交到验证的六个阶段',
    type: 'flow',
    direction: 'vertical',
    steps: [
      { title: '提交代码', desc: '小步提交，附带变更说明' },
      { title: '静态检查', desc: '格式、lint 与类型检查' },
      { title: '构建镜像', desc: '可复现地产出制品' },
      { title: '自动化测试', desc: '单元、集成与契约测试' },
      { title: '部署预发', desc: '同构环境验证' },
      { title: '灰度与回滚', desc: '分批放量，随时可退' },
    ],
    caption: '流水线的价值是让「发布」变成例行操作；任何一步失败都应停在原地而不是带病上线。',
  },
  gitops_argocd: {
    image: 'diagram_gitops.webp',
    alt: 'GitOps 以 Git 为期望状态的同步闭环',
    title: 'GitOps：以 Git 为唯一事实来源',
    type: 'cycle',
    center: '声明即状态',
    nodes: [
      { title: '提交清单', desc: 'YAML 进入 Git 仓库' },
      { title: 'ArgoCD 监听', desc: '检测期望状态变化' },
      { title: '集群同步', desc: '自动 apply 到集群' },
      { title: '漂移自愈', desc: '偏离即回滚到 Git' },
    ],
    backLabel: '回滚 = 回退一次 Git 提交',
    caption: 'GitOps 把部署变成代码评审；集群状态永远可以向 Git 收敛，回滚只需回退提交。',
  },
  git_intro: {
    image: 'diagram_git_intro.webp',
    alt: '第一次提交的三步操作',
    title: '第一次提交：init、add、commit',
    type: 'flow',
    steps: [
      { title: 'git init', desc: '在项目目录建立版本库' },
      { title: 'git add', desc: '把文件放入暂存区' },
      { title: 'git commit', desc: '写说明并生成版本' },
      { title: 'git push', desc: '推送到远程仓库备份' },
    ],
    notes: ['git config 先设置用户名与邮箱', '.gitignore 排除构建产物与密钥'],
    caption: '提交是本地操作，推送才是共享；先本地形成清晰的提交历史，再同步到远程。',
  },
  cli_intro: {
    image: 'diagram_cli_intro.webp',
    alt: '命令行入门的五个基本动作',
    title: '命令行入门：五个动作走完一轮',
    type: 'flow',
    steps: [
      { title: 'pwd', desc: '我在哪个目录' },
      { title: 'ls', desc: '这里有什么文件' },
      { title: 'cd', desc: '切换到目标目录' },
      { title: 'cat', desc: '查看文件内容' },
      { title: '管道', desc: '把输出交给下一个命令' },
    ],
    notes: ['Tab 补全减少拼写错误', '上箭头翻历史命令'],
    caption: '命令行的学习路径是记住少量高频命令，再用管道把它们组合成自己的工具。',
  },
};
