// P3 Java 课程配图数据。
module.exports = {
  java_types: {
    image: 'diagram_java_types.webp',
    alt: '基本类型、包装类与字符串',
    title: '变量与类型：基本类型、包装类、字符串',
    type: 'compare',
    columns: [
      { title: '基本类型', items: ['byte/short/int/long', 'float/double', 'char、boolean', '存值，默认 0 或 false', '比较用 =='] },
      { title: '包装类', items: ['Integer、Long、Double', '可为 null，能进集合', '自动装箱与拆箱', '比较要用 equals', '注意空指针风险'] },
    ],
    notes: ['String 不可变，拼接用 StringBuilder', 'var 只是局部变量类型推断'],
    caption: '基本类型高效、包装类灵活；两者混用时要注意 null 与 equal 语义。',
  },
  java_control_methods: {
    image: 'diagram_java_control.webp',
    alt: 'Java 分支、循环与方法',
    title: '控制流与方法：分支、循环、定义、重载',
    type: 'flow',
    steps: [
      { title: '分支', desc: 'if / else 与 switch' },
      { title: '循环', desc: 'for、while、增强 for' },
      { title: '方法定义', desc: '返回类型、名称、参数列表' },
      { title: '重载', desc: '同名不同参数列表' },
      { title: '值传递', desc: '参数传入的是值的副本' },
    ],
    notes: ['Java 只有值传递，对象传的是引用副本'],
    caption: '方法签名由名称与参数列表决定；返回类型不同不构成重载。',
  },
  java_inheritance: {
    image: 'diagram_java_inheritance.webp',
    alt: '类、抽象类、接口与多态',
    title: '继承体系：类、抽象类、接口、多态',
    type: 'flow',
    steps: [
      { title: '类与继承', desc: 'extends 复用父类实现' },
      { title: '抽象类', desc: '部分实现，可含抽象方法' },
      { title: '接口', desc: '定义能力契约，可多实现' },
      { title: '多态', desc: '父类型引用指向子类对象' },
      { title: 'Object 方法', desc: 'equals、hashCode、toString' },
    ],
    notes: ['重写 equals 必须同时重写 hashCode', '优先组合而不是深层继承'],
    caption: '接口描述能做什么，抽象类描述是什么；多态让调用方依赖抽象而非实现。',
  },
  java_exceptions: {
    image: 'diagram_java_exceptions.webp',
    alt: 'Java 异常体系与资源管理',
    title: '异常与文件 IO：捕获、抛出、资源管理',
    type: 'flow',
    steps: [
      { title: '异常体系', desc: '受检异常与运行时异常' },
      { title: '捕获', desc: 'catch 按具体类型处理' },
      { title: '抛出', desc: 'throw 与 throws 声明' },
      { title: '资源管理', desc: 'try-with-resources 自动关闭' },
      { title: '文件 IO', desc: 'NIO.2 的 Path 与 Files' },
    ],
    notes: ['不要吞异常，至少记录日志', '自定义异常要保留原始 cause'],
    caption: '受检异常强制调用方处理；资源管理交给try-with-resources，避免句柄泄漏。',
  },
  java_lambda_stream: {
    image: 'diagram_java_stream.webp',
    alt: 'Lambda 与 Stream 的流水线',
    title: 'Lambda 与 Stream：从集合到结果的流水线',
    type: 'flow',
    steps: [
      { title: '函数式接口', desc: 'Function、Predicate、Consumer' },
      { title: 'Lambda', desc: '把行为作为参数传入' },
      { title: 'Stream', desc: 'filter、map、sorted 中间操作' },
      { title: '终止操作', desc: 'collect、reduce、forEach' },
      { title: 'Optional', desc: '显式表达可能为空' },
    ],
    notes: ['流是惰性的，遇到终止操作才执行', '并行流不适合阻塞与有状态操作'],
    caption: 'Stream 把循环拆成声明式流水线；中间操作惰性执行，终止操作才真正触发计算。',
  },
  java_tooling: {
    image: 'diagram_java_tooling.webp',
    alt: 'Java 构建、测试、日志与数据库工具',
    title: 'Java 生态：构建、测试、日志、数据访问',
    type: 'flow',
    steps: [
      { title: '构建', desc: 'Maven 声明式或 Gradle 灵活' },
      { title: '测试', desc: 'JUnit 5 加断言库' },
      { title: '日志', desc: 'SLF4J 门面加实现' },
      { title: '数据访问', desc: 'JDBC、JPA 与连接池' },
    ],
    notes: ['依赖冲突用 mvn dependency:tree 排查', '日志用占位符而不是字符串拼接'],
    caption: '生态工具解决不同问题：构建管依赖，测试管行为，日志管可观测，数据访问管持久化。',
  },
  java_project: {
    image: 'diagram_spring_layers.webp',
    alt: 'Spring Boot 应用的分层结构',
    title: 'Spring Boot 分层：Controller、Service、Repository、Entity',
    type: 'layers',
    widths: [1, 0.85, 0.7, 0.55],
    layers: [
      { title: 'Controller', desc: '接收请求、校验参数、返回响应' },
      { title: 'Service', desc: '业务规则与事务边界' },
      { title: 'Repository', desc: '数据访问与查询封装' },
      { title: 'Entity / DB', desc: '表映射与持久化存储' },
    ],
    caption: '分层让每层职责单一：接口层不写业务，业务层不拼 SQL，仓储层不做编排。',
  },
  java_project_inventory: {
    image: 'diagram_java_inventory.webp',
    alt: '库存服务的一次请求时序',
    title: '库存服务：一次入库请求的时序',
    type: 'sequence',
    actors: ['客户端', 'Controller', 'Service', 'Repository'],
    messages: [
      { from: 0, to: 1, label: 'POST /inventory' },
      { from: 1, to: 2, label: '参数校验后调用' },
      { from: 2, to: 3, label: '按 SKU 查询库存' },
      { from: 3, to: 2, label: '返回当前数量' },
      { from: 2, to: 3, label: '更新库存并提交事务' },
      { from: 1, to: 0, label: '200 返回最新库存' },
    ],
    notes: ['并发更新要用乐观锁或行锁'],
    caption: '一次写请求穿过四层：校验在接口层，规则与服务边界在 Service，持久化在 Repository。',
  },
  java_project_order_concurrency: {
    image: 'diagram_java_order.webp',
    alt: '并发订单处理的流水线',
    title: '并发订单处理：队列、线程池、幂等',
    type: 'flow',
    steps: [
      { title: '接单', desc: '接口只做校验与入队' },
      { title: '队列缓冲', desc: '削峰并解耦处理速度' },
      { title: '线程池消费', desc: '控制并发度与拒绝策略' },
      { title: '幂等校验', desc: '按订单号去重' },
      { title: '更新库存', desc: '事务内扣减并记录流水' },
    ],
    notes: ['队列要有界并配置拒绝策略', '幂等键决定重复消息是否安全'],
    caption: '并发处理的关键是限流、幂等与可观测：队列缓冲峰值，幂等保证重复消费不出错。',
  },
  java_modern_features: {
    image: 'diagram_java_modern.webp',
    alt: 'Record、Sealed 与模式匹配',
    title: '现代 Java：Record、Sealed、模式匹配',
    type: 'flow',
    steps: [
      { title: 'Record', desc: '不可变数据载体，自带访问器' },
      { title: 'Sealed', desc: '限制哪些类可以继承' },
      { title: '模式匹配', desc: 'instanceof 直接绑定变量' },
      { title: 'switch 表达式', desc: '分支即表达式并可穷尽检查' },
    ],
    notes: ['密封加模式匹配让分支可被编译器穷尽检查'],
    caption: '把类型约束写进语言：Record 表达数据，Sealed 表达封闭集合，模式匹配安全解构。',
  },
  java_first_class: {
    image: 'diagram_java_first.webp',
    alt: '第一个 Java 类的编写与运行',
    title: '第一个类：编写、编译、运行',
    type: 'flow',
    steps: [
      { title: '类声明', desc: 'public class Hello' },
      { title: 'main 方法', desc: '程序入口签名固定' },
      { title: '编译', desc: 'javac 生成 .class 字节码' },
      { title: '运行', desc: 'java 类名启动 JVM' },
    ],
    notes: ['文件名要与 public 类名一致', 'main 的参数是字符串数组'],
    caption: 'Java 先编译成字节码再由 JVM 执行；理解这一步就理解了跨平台的基础。',
  },
  java_variables_output: {
    image: 'diagram_java_vars.webp',
    alt: '变量声明与输出',
    title: '变量与输出：声明、赋值、拼接、打印',
    type: 'flow',
    steps: [
      { title: '声明类型', desc: 'int age; 或 var age = 18' },
      { title: '赋值', desc: '变量必须先初始化再使用' },
      { title: '字符串拼接', desc: '加号或格式化输出' },
      { title: '输出', desc: 'System.out.println 打印并换行' },
    ],
    notes: ['整数相除会丢失小数部分', 'printf 可控制格式'],
    caption: 'Java 是静态类型语言：类型确定后不能随意改变，这能在编译期发现大量错误。',
  },
  java_conditions: {
    image: 'diagram_java_if.webp',
    alt: 'Java 条件分支',
    title: '条件判断：if、else if、switch、三元',
    type: 'flow',
    steps: [
      { title: 'if', desc: '布尔表达式必须为 boolean' },
      { title: 'else if', desc: '按顺序判断多个条件' },
      { title: 'switch', desc: '多等值分支更清晰' },
      { title: '三元表达式', desc: '简单二选一的简洁写法' },
    ],
    notes: ['switch 的每个分支要记得 break 或使用箭头语法'],
    caption: '条件必须显式为布尔值；多等值判断用 switch 比长串 if 更易读。',
  },
  java_loops: {
    image: 'diagram_java_loops.webp',
    alt: 'Java 三种循环与流程控制',
    title: '循环：for、while、do-while、跳出',
    type: 'flow',
    steps: [
      { title: 'for', desc: '已知次数或有索引时使用' },
      { title: '增强 for', desc: '遍历数组与集合更简洁' },
      { title: 'while', desc: '条件为真时重复' },
      { title: 'do-while', desc: '至少执行一次' },
      { title: 'break/continue', desc: '结束循环或跳过本次' },
    ],
    notes: ['遍历中删除元素要用迭代器'],
    caption: '选循环看退出条件：次数确定用 for，依赖状态用 while，至少执行一次用 do-while。',
  },
  java_methods_intro: {
    image: 'diagram_java_methods.webp',
    alt: '方法定义、参数与返回值',
    title: '方法入门：定义、参数、返回、调用',
    type: 'flow',
    steps: [
      { title: '定义', desc: '修饰符 返回类型 名称(参数)' },
      { title: '参数', desc: '按类型与顺序传递' },
      { title: '返回值', desc: 'return 结果或 void' },
      { title: '调用', desc: '对象或类名调用并接收结果' },
    ],
    notes: ['static 方法属于类而不是对象', '方法名用小驼峰命名'],
    caption: '方法是可复用的最小单元：职责单一、参数明确，调用方就不需要了解内部实现。',
  },
};
