// P3 JavaScript 课程配图数据。
module.exports = {
  js_basics: {
    image: 'diagram_js_env.webp',
    alt: '浏览器与 Node.js 两种运行环境',
    title: '两种运行环境：浏览器与 Node.js',
    type: 'compare',
    columns: [
      { title: '浏览器', items: ['有 window 与 DOM', '能操作页面与事件', '受同源策略限制', '脚本由页面引入', '适合界面与交互'] },
      { title: 'Node.js', items: ['有 process 与文件系统', '没有 DOM', '可读写文件与网络', '自带 npm 生态', '适合服务端与工具链'] },
    ],
    notes: ['语言核心相同，差别在宿主提供的 API', '严格模式让部分错误提前暴露'],
    caption: 'JavaScript 是语言，浏览器与 Node 是两个宿主环境；学会区分语言与平台 API。',
  },
  js_types: {
    image: 'diagram_js_declare.webp',
    alt: 'var、let、const 三种声明方式',
    title: '三种声明方式：var、let、const',
    type: 'compare',
    columns: [
      { title: 'var', items: ['函数作用域', '存在变量提升', '可重复声明', '易造成意外覆盖', '新代码不建议使用'] },
      { title: 'let', items: ['块级作用域', '可重新赋值', '不能重复声明', '暂时性死区', '需要变化时使用'] },
      { title: 'const', items: ['块级作用域', '不能重新赋值', '对象内容仍可修改', '优先使用', '表达意图更清晰'] },
    ],
    notes: ['默认用 const，需要重新赋值时才用 let'],
    caption: '声明方式决定作用域与可变性；默认 const 能让读者立刻知道这个绑定不会变。',
  },
  js_operators_control: {
    image: 'diagram_js_control.webp',
    alt: '运算符与条件循环',
    title: '运算符与控制流：相等、分支、循环',
    type: 'flow',
    steps: [
      { title: '相等判断', desc: '=== 严格相等，避免隐式转换' },
      { title: '逻辑短路', desc: '&& 与 || 返回操作数而不是布尔' },
      { title: '分支', desc: 'if / else 与 switch' },
      { title: '循环', desc: 'for、for…of、while' },
    ],
    notes: ['真假值：0、""、null、undefined、NaN 为假', '?? 只在 null/undefined 时取默认值'],
    caption: '优先用 === 与 ??：显式比较能避开隐式类型转换带来的意外结果。',
  },
  js_functions: {
    image: 'diagram_js_functions_scope.webp',
    alt: '函数定义方式、闭包与 this',
    title: '函数、作用域与 this：三种定义与闭包',
    type: 'flow',
    steps: [
      { title: '函数声明', desc: '有提升，可先调用后定义' },
      { title: '函数表达式', desc: '赋值给变量，按顺序执行' },
      { title: '箭头函数', desc: '没有自己的 this 与 arguments' },
      { title: '闭包', desc: '函数记住定义时的作用域' },
      { title: 'this 绑定', desc: '取决于调用方式，箭头函数继承外层' },
    ],
    notes: ['回调里用箭头函数避免 this 丢失'],
    caption: 'this 由调用方式决定；闭包让函数记住定义时的环境，是模块与私有状态的实现基础。',
  },
  js_arrays: {
    image: 'diagram_js_array_methods.webp',
    alt: '数组的增删改查与函数式方法',
    title: '数组：增删改查与函数式方法',
    type: 'flow',
    steps: [
      { title: '增删改', desc: 'push/pop、shift/unshift、splice' },
      { title: '查找', desc: 'indexOf、find、includes' },
      { title: '变换', desc: 'map 映射、filter 过滤' },
      { title: '聚合', desc: 'reduce 汇总成单个结果' },
      { title: '不可变写法', desc: '展开运算符生成新数组' },
    ],
    notes: ['sort 会原地修改并默认按字符串排序'],
    caption: 'map/filter/reduce 把循环意图写在方法名里；不可变操作让状态变化更容易追踪。',
  },
  js_dom_events: {
    image: 'diagram_js_dom.webp',
    alt: 'DOM 选择、事件监听与委托',
    title: 'DOM 与事件：选择、监听、冒泡、委托',
    type: 'flow',
    steps: [
      { title: '选择元素', desc: 'querySelector 返回第一个匹配' },
      { title: '修改内容', desc: 'textContent 比 innerHTML 安全' },
      { title: '监听事件', desc: 'addEventListener 绑定回调' },
      { title: '冒泡与委托', desc: '在父元素统一处理子元素事件' },
      { title: '表单与存储', desc: '取值、校验、localStorage' },
    ],
    notes: ['事件委托减少监听器数量', '避免用 innerHTML 拼接用户输入'],
    caption: '事件从目标向上冒泡；利用委托可以在父节点统一处理，动态元素也不必重新绑定。',
  },
  js_errors_debugging: {
    image: 'diagram_js_errors.webp',
    alt: '错误处理与调试手段',
    title: '错误与调试：捕获、清理、定位、性能',
    type: 'flow',
    steps: [
      { title: '错误对象', desc: 'name、message 与 stack' },
      { title: 'try/catch', desc: '捕获同步异常' },
      { title: 'finally', desc: '无论如何都执行的清理' },
      { title: '异步错误', desc: 'Promise 用 catch 或 await 加 try' },
      { title: '调试手段', desc: '断点、console 与性能面板' },
    ],
    notes: ['不要吞掉异常，至少上报或记录', '未处理的 Promise 拒绝会静默失败'],
    caption: '异步错误最容易被忽略；统一在边界处捕获并上报，才能发现线上的真实问题。',
  },
  js_modules_tooling: {
    image: 'diagram_js_modules.webp',
    alt: 'ES Module 与 CommonJS 对照',
    title: '模块化：ES Module 与 CommonJS',
    type: 'compare',
    columns: [
      { title: 'ES Module', items: ['import / export 语法', '静态分析，可摇树优化', '浏览器原生支持', '顶层为严格模式', '现代项目首选'] },
      { title: 'CommonJS', items: ['require / module.exports', '运行时加载', 'Node 早期标准', '可条件加载', '与 ESM 混用需注意'] },
    ],
    notes: ['package.json 的 type 字段决定默认模块体系'],
    caption: 'ESM 是标准且可静态分析；迁移时要留意默认导出与循环依赖的差异。',
  },
  js_project: {
    image: 'diagram_vite_react.webp',
    alt: 'Vite 与 React 应用的结构',
    title: 'Vite + React：组件、状态、请求、构建',
    type: 'layers',
    widths: [1, 0.85, 0.7, 0.55],
    layers: [
      { title: '组件层', desc: 'UI 与交互，函数组件加 hooks' },
      { title: '状态层', desc: 'useState 与 useReducer 管理数据' },
      { title: '数据层', desc: 'fetch 请求后端并处理加载与错误' },
      { title: '构建层', desc: 'Vite 开发热更新、生产打包' },
    ],
    caption: '前端的复杂度多在状态同步：把组件、状态与数据请求分层，调试时才能快速定位。',
  },
  js_project_node_api: {
    image: 'diagram_express_api.webp',
    alt: 'Express 请求处理链路',
    title: 'Express API：路由、中间件、控制器、数据',
    type: 'flow',
    steps: [
      { title: '路由', desc: '按方法与路径分发' },
      { title: '中间件', desc: '日志、鉴权、参数校验' },
      { title: '控制器', desc: '调用服务并组装响应' },
      { title: '数据层', desc: '查询数据库或缓存' },
      { title: '错误处理', desc: '统一中间件返回错误结构' },
    ],
    notes: ['异步控制器要捕获异常', '中间件顺序决定执行结果'],
    caption: 'Express 的核心是中间件管道：请求依次穿过各层，最后统一由错误中间件兜底。',
  },
  js_project_realtime_chat: {
    image: 'diagram_chat_ws.webp',
    alt: '实时聊天室的消息时序',
    title: '实时聊天：WebSocket 消息时序',
    type: 'sequence',
    actors: ['客户端 A', '服务端', '客户端 B'],
    messages: [
      { from: 0, to: 1, label: '建立 WebSocket 连接' },
      { from: 0, to: 1, label: '发送消息' },
      { from: 1, to: 1, label: '校验并写入历史' },
      { from: 1, to: 2, label: '推送给房间成员' },
      { from: 1, to: 0, label: '回执与消息 ID' },
    ],
    notes: ['断线要重连并补拉历史消息'],
    caption: '长连接要处理断线重连、消息顺序与重复投递；回执与 ID 让客户端能对齐状态。',
  },
  js_node_backend: {
    image: 'diagram_node_backend.webp',
    alt: 'Node.js 后端的分层与事件循环',
    title: 'Node 后端：事件循环、中间件、服务、数据',
    type: 'layers',
    widths: [1, 0.85, 0.7, 0.55],
    layers: [
      { title: '事件循环', desc: '非阻塞 I/O，回调与微任务按序执行' },
      { title: '接口层', desc: '路由、参数校验与鉴权' },
      { title: '服务层', desc: '业务规则与事务编排' },
      { title: '数据层', desc: '数据库、缓存与连接池' },
    ],
    caption: 'Node 适合 I/O 密集场景；CPU 密集任务要交给工作线程或独立服务。',
  },
  js_console_start: {
    image: 'diagram_js_console.webp',
    alt: '控制台入门四步',
    title: '控制台入门：打开、输出、变量、运行',
    type: 'flow',
    steps: [
      { title: '打开控制台', desc: '浏览器按 F12 进入 Console' },
      { title: '输出', desc: 'console.log 打印结果' },
      { title: '变量', desc: 'let 声明并可重新赋值' },
      { title: '立即执行', desc: '回车即运行，适合试错' },
    ],
    notes: ['控制台是学习语法最方便的试验场'],
    caption: '控制台提供即时反馈：改一行、按回车、看结果，是建立语感最快的方式。',
  },
  js_variables_types_intro: {
    image: 'diagram_js_var_intro.webp',
    alt: '变量、类型与模板字符串',
    title: '变量与类型入门：声明、类型、拼接',
    type: 'flow',
    steps: [
      { title: '声明变量', desc: 'let 可变，const 不可重新赋值' },
      { title: '基本类型', desc: '字符串、数字、布尔、null、undefined' },
      { title: '查看类型', desc: 'typeof 判断基本类型' },
      { title: '模板字符串', desc: '反引号中 ${} 嵌入变量' },
    ],
    notes: ['NaN 表示不是一个有效数字', 'typeof null 返回 object 是历史遗留'],
    caption: 'JavaScript 是动态类型：变量本身没有类型，值才有；typeof 是最快的检查手段。',
  },
  js_conditions_loops: {
    image: 'diagram_js_cond_loops.webp',
    alt: '条件与循环入门',
    title: '条件与循环：比较、分支、遍历',
    type: 'flow',
    steps: [
      { title: '比较', desc: '用 === 比较值与类型' },
      { title: '分支', desc: 'if / else 处理两种情况' },
      { title: 'for', desc: '按索引或次数重复' },
      { title: 'while', desc: '条件为真时重复执行' },
    ],
    notes: ['循环要有终止条件', 'break 可提前结束循环'],
    caption: '条件和循环是所有程序的骨架；先写清终止条件，再考虑优化。',
  },
  js_functions_intro: {
    image: 'diagram_js_func_intro.webp',
    alt: '函数入门四步',
    title: '函数入门：定义、参数、返回、调用',
    type: 'flow',
    steps: [
      { title: '定义', desc: 'function 名称(参数) { }' },
      { title: '参数', desc: '调用时传入的输入值' },
      { title: '返回', desc: 'return 把结果交给调用方' },
      { title: '调用', desc: '函数名加括号执行' },
    ],
    notes: ['没有 return 时返回 undefined', '参数个数不匹配不会报错'],
    caption: '函数是输入到输出的映射：起一个能说明动作的名字，比写注释更有效。',
  },
  js_dom_intro: {
    image: 'diagram_js_dom_intro.webp',
    alt: 'DOM 操作入门四步',
    title: 'DOM 入门：选择、修改、监听、更新',
    type: 'flow',
    steps: [
      { title: '选择元素', desc: 'document.querySelector' },
      { title: '修改内容', desc: 'textContent 更新文本' },
      { title: '监听事件', desc: '点击时执行回调' },
      { title: '页面更新', desc: '浏览器重绘界面' },
    ],
    notes: ['脚本要放在页面元素之后或等 DOMContentLoaded'],
    caption: 'DOM 是页面在内存中的树；JavaScript 通过修改这棵树来更新用户看到的界面。',
  },
};
