// P3 Python 课程配图数据。
module.exports = {
  python_basics: {
    image: 'diagram_py_basics.webp',
    alt: 'Python 基础语法的四个要点',
    title: 'Python 基础：缩进、变量、输入输出、运行',
    type: 'flow',
    steps: [
      { title: '缩进即语法', desc: '同一代码块缩进必须一致' },
      { title: '变量与类型', desc: '动态类型，赋值即声明' },
      { title: '输入输出', desc: 'input() 返回字符串' },
      { title: '运行脚本', desc: 'python 文件名.py' },
    ],
    notes: ['f-string 是最常用的格式化方式', 'type() 查看类型，方便排查'],
    caption: 'Python 用缩进表达层级；先熟悉变量、输入输出与运行方式，再进入分支与循环。',
  },
  python_functions: {
    image: 'diagram_py_functions.webp',
    alt: 'Python 函数的定义、参数与返回值',
    title: '函数：定义、参数、返回值、解包',
    type: 'flow',
    steps: [
      { title: '定义与调用', desc: 'def 名称(参数): 缩进函数体' },
      { title: '参数', desc: '位置、关键字、默认值' },
      { title: '返回值', desc: 'return 结果，无返回即 None' },
      { title: '多返回值', desc: '实际返回元组，可解包接收' },
    ],
    notes: ['可变默认参数是经典陷阱，用 None 代替', '文档字符串写明参数与返回值'],
    caption: '函数把一段逻辑命名并隔离作用域；参数设计决定调用方是否好用。',
  },
  python_control_flow: {
    image: 'diagram_py_control.webp',
    alt: 'Python 分支、循环与推导式',
    title: '控制流：分支、循环、推导式',
    type: 'flow',
    steps: [
      { title: '条件', desc: 'if / elif / else 按顺序判断' },
      { title: 'for', desc: '遍历序列、range 与字典' },
      { title: 'while', desc: '条件为真时重复执行' },
      { title: '推导式', desc: '一行生成列表、字典与集合' },
    ],
    notes: ['break 跳出循环，continue 跳过本次', '推导式过复杂时应改回普通循环'],
    caption: '推导式是 Python 的表达式化循环；可读性优先，嵌套过深就换回显式循环。',
  },
  python_data_structures: {
    image: 'diagram_py_containers.webp',
    alt: '列表、元组、字典、集合的特性对照',
    title: '四种内置容器：特性与用途',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['列表', '元组', '字典', '集合'],
    colLabels: ['可变性', '有序性', '典型用途'],
    cells: [
      { r: 0, c: 0, text: '可变', fill: '#e7eeff', stroke: '#6c8ff8', bold: true },
      { r: 0, c: 1, text: '有序' },
      { r: 0, c: 2, text: '有序集合，下标访问' },
      { r: 1, c: 0, text: '不可变', fill: '#e0f2fe', stroke: '#0ea5e9', bold: true },
      { r: 1, c: 1, text: '有序' },
      { r: 1, c: 2, text: '固定记录，可作字典键' },
      { r: 2, c: 0, text: '可变', fill: '#dcfce7', stroke: '#16a34a', bold: true },
      { r: 2, c: 1, text: '保持插入顺序' },
      { r: 2, c: 2, text: '键值映射，最常用结构' },
      { r: 3, c: 0, text: '可变', fill: '#fef3c7', stroke: '#f59e0b', bold: true },
      { r: 3, c: 1, text: '无序' },
      { r: 3, c: 2, text: '去重与集合运算' },
    ],
    notes: ['查找：list 是 O(n)，dict/set 平均 O(1)'],
    caption: '选容器看三件事：要不要改、要不要顺序、按什么方式查找。',
  },
  python_oop: {
    image: 'diagram_py_oop.webp',
    alt: 'Python 类、继承与多态',
    title: '面向对象：类、封装、继承、多态',
    type: 'flow',
    steps: [
      { title: '定义类', desc: 'class 与 __init__ 初始化实例' },
      { title: '封装', desc: '约定 _ 与 __ 前缀表示内部' },
      { title: '继承', desc: '复用父类并用 super() 扩展' },
      { title: '多态', desc: '同一接口的不同实现' },
      { title: '魔术方法', desc: '__str__、__eq__ 定义对象行为' },
    ],
    notes: ['dataclass 适合只存数据的类', '组合通常比深层继承更灵活'],
    caption: 'Python 的封装靠约定而非强制；明确接口、少用深层继承是更重要的实践。',
  },
  python_errors_files: {
    image: 'diagram_py_errors.webp',
    alt: '异常处理与文件操作',
    title: '异常与文件：捕获、清理、读写、序列化',
    type: 'flow',
    steps: [
      { title: '捕获', desc: 'try/except 按具体异常类型处理' },
      { title: '清理', desc: 'finally 与 with 保证资源释放' },
      { title: '读写文件', desc: 'open 指定模式与编码 utf-8' },
      { title: 'JSON', desc: 'json.load / dump 与对象互转' },
    ],
    notes: ['不要裸 except 吞掉所有异常', '文件操作优先用 with'],
    caption: '异常处理的底线是保留上下文：要么处理，要么带着信息继续抛出。',
  },
  python_modules_stdlib: {
    image: 'diagram_py_modules.webp',
    alt: '模块、包、虚拟环境与依赖',
    title: '工程结构：模块、包、虚拟环境、依赖',
    type: 'layers',
    widths: [1, 0.85, 0.68, 0.5],
    layers: [
      { title: '模块 module', desc: '一个 .py 文件，用 import 引入' },
      { title: '包 package', desc: '带 __init__.py 的目录，形成命名空间' },
      { title: '虚拟环境 venv', desc: '为每个项目隔离依赖版本' },
      { title: '依赖清单', desc: 'requirements.txt 或 pyproject.toml 锁定版本' },
    ],
    caption: '虚拟环境解决版本冲突；依赖清单保证别人能装出同一套环境。',
  },
  python_typing_testing: {
    image: 'diagram_py_typing.webp',
    alt: '类型注解与 pytest 测试流程',
    title: '类型注解与测试：标注、检查、用例、覆盖',
    type: 'flow',
    steps: [
      { title: '类型注解', desc: '参数与返回值写清类型' },
      { title: '静态检查', desc: 'mypy 或 pyright 提前发现错误' },
      { title: 'pytest 用例', desc: '断言行为而不是实现' },
      { title: '覆盖率', desc: '看未覆盖分支而不是追数字' },
    ],
    notes: ['注解不影响运行，但能显著提升可维护性', '测试要能独立、可重复地运行'],
    caption: '类型注解把一部分运行时错误提前到编辑期；测试则锁住行为不被后续改动破坏。',
  },
  python_project: {
    image: 'diagram_py_scraper.webp',
    alt: '爬虫与数据分析流程',
    title: '爬虫与数据分析：请求、解析、清洗、统计',
    type: 'flow',
    direction: 'vertical',
    steps: [
      { title: '发起请求', desc: 'requests 设置超时与重试' },
      { title: '解析页面', desc: 'BeautifulSoup 提取字段' },
      { title: '清洗数据', desc: '去重、补空、规范类型' },
      { title: '保存结果', desc: '写入 CSV 或 SQLite' },
      { title: '统计分析', desc: 'pandas 汇总并可视化' },
    ],
    caption: '爬虫要遵守 robots 与访问频率；先小样本验证解析规则，再全量抓取。',
  },
  python_project_api: {
    image: 'diagram_fastapi.webp',
    alt: 'FastAPI 订单服务的请求处理链路',
    title: 'FastAPI 订单服务：路由、校验、服务、存储',
    type: 'flow',
    steps: [
      { title: '路由', desc: '按方法与路径分发请求' },
      { title: '参数校验', desc: 'Pydantic 模型校验并转换' },
      { title: '业务逻辑', desc: '服务层处理库存与金额' },
      { title: '数据访问', desc: 'ORM 写入订单与明细' },
      { title: '响应', desc: '序列化并返回状态码' },
    ],
    notes: ['依赖注入管理数据库会话', '错误要返回统一结构'],
    caption: '分层的目的是让校验、业务与存储各自可测；接口层只做编排，不写业务规则。',
  },
  python_project_etl: {
    image: 'diagram_py_etl.webp',
    alt: 'CSV 到 SQLite 的 ETL 流程',
    title: 'ETL 流水线：抽取、清洗、转换、加载、校验',
    type: 'flow',
    steps: [
      { title: '抽取 Extract', desc: '分块读取大 CSV' },
      { title: '清洗 Clean', desc: '去重、补默认值、统一格式' },
      { title: '转换 Transform', desc: '字段计算与类型转换' },
      { title: '加载 Load', desc: '批量写入 SQLite 事务' },
      { title: '校验 Verify', desc: '对比行数与关键指标' },
    ],
    notes: ['批量插入要放在单个事务里', '每一步都要能重跑'],
    caption: 'ETL 的可靠性来自可重跑与可校验：任何一步失败都应能安全重来。',
  },
  python_packaging_performance: {
    image: 'diagram_py_packaging.webp',
    alt: 'Python 打包、发布与性能优化',
    title: '打包发布与性能：构建、发布、剖析、优化',
    type: 'flow',
    steps: [
      { title: '项目元数据', desc: 'pyproject.toml 描述包' },
      { title: '构建制品', desc: 'build 生成 wheel 与 sdist' },
      { title: '发布', desc: '上传到私有或公开索引' },
      { title: '性能剖析', desc: 'cProfile、py-spy 找热点' },
      { title: '优化验证', desc: '基准对比再决定保留' },
    ],
    caption: '先剖析再优化；Python 的性能瓶颈常在循环、I/O 与重复计算，而不在语言本身。',
  },
  python_first_script: {
    image: 'diagram_py_first.webp',
    alt: '第一个 Python 脚本的四个步骤',
    title: '第一个脚本：写、存、跑、看',
    type: 'flow',
    steps: [
      { title: '写代码', desc: 'print("Hello")' },
      { title: '存文件', desc: '保存为 hello.py' },
      { title: '运行', desc: 'python hello.py' },
      { title: '看输出', desc: '终端显示结果' },
    ],
    notes: ['.py 后缀是 Python 源文件的约定', '报错先看最后一行'],
    caption: '从一行 print 开始建立反馈循环；能跑起来、能看到输出，才谈得上继续学习。',
  },
  python_input_output: {
    image: 'diagram_py_io.webp',
    alt: '输入、转换与格式化输出',
    title: '输入输出：读入、转换、格式化',
    type: 'flow',
    steps: [
      { title: 'input()', desc: '读取一行，结果永远是字符串' },
      { title: '类型转换', desc: 'int() / float() 显式转换' },
      { title: 'f-string', desc: 'f"{name} 你好" 嵌入变量' },
      { title: '格式化', desc: '控制小数位与对齐' },
    ],
    notes: ['转换失败会抛 ValueError，要先校验', 'print 默认换行，可用 end 修改'],
    caption: '输入得到的永远是字符串；先转换再计算，是新手最常见的第一个坑。',
  },
  python_if_else: {
    image: 'diagram_py_if.webp',
    alt: '条件判断的分支结构',
    title: '条件判断：真假、分支、多路',
    type: 'flow',
    steps: [
      { title: '真假值', desc: '比较与 in 表达式' },
      { title: 'if', desc: '条件成立时执行' },
      { title: 'elif', desc: '按顺序检查多个条件' },
      { title: 'else', desc: '兜底分支' },
    ],
    notes: ['缩进决定分支归属', '条件按从上到下顺序短路判断'],
    caption: '分支按书写顺序匹配，第一个成立的分支执行后就不再继续判断。',
  },
  python_loops: {
    image: 'diagram_py_loops.webp',
    alt: 'for 与 while 循环',
    title: '循环：遍历、计数、跳出',
    type: 'flow',
    steps: [
      { title: 'for', desc: '遍历列表、字符串与 range' },
      { title: 'while', desc: '条件为真时持续执行' },
      { title: 'break', desc: '立即结束整个循环' },
      { title: 'continue', desc: '跳过本次进入下一轮' },
    ],
    notes: ['range(5) 从 0 到 4', 'while 要有退出条件，避免死循环'],
    caption: '遍历已知序列用 for，等待某个条件用 while；两者都能用 break 提前结束。',
  },
  python_list_dict_basics: {
    image: 'diagram_py_list_dict.webp',
    alt: '列表与字典的对照',
    title: '列表与字典：两种最常用的容器',
    type: 'compare',
    columns: [
      { title: '列表 list', items: ['按位置存放一串值', '下标从 0 开始', 'append 追加、pop 删除', '切片取出子列表', '适合有序数据'] },
      { title: '字典 dict', items: ['按键存取值', '键必须可哈希', 'get 提供默认值', '遍历 items() 取键值', '适合带标签的数据'] },
    ],
    notes: ['列表查找是 O(n)，字典查找平均 O(1)'],
    caption: '按位置找用列表，按键找用字典；数据结构选对，代码会短很多。',
  },
};
