// P4 算法与数据结构配图数据。
module.exports = {
  binary_search: {
    image: 'diagram_algo_binary_search.webp',
    alt: '二分查找的缩小过程',
    title: '二分查找：每次排除一半',
    type: 'flow',
    steps: [
      { title: '确定区间', desc: '有序数组，left 与 right' },
      { title: '取中间', desc: 'mid = left + (right-left)/2' },
      { title: '比较', desc: '目标小于中值则收缩右界' },
      { title: '重复', desc: '区间为空则未找到' },
    ],
    notes: ['复杂度 O(log n)', '边界用左闭右开可减少出错'],
    caption: '二分的前提是单调性；只要答案具有单调性，就可以把查找变成判定。',
  },
  bubble_sort: {
    image: 'diagram_algo_bubble.webp',
    alt: '冒泡排序的相邻比较与交换',
    title: '冒泡排序：相邻比较，大值上浮',
    type: 'flow',
    steps: [
      { title: '相邻比较', desc: '比较相邻两个元素' },
      { title: '逆序交换', desc: '前者大则交换位置' },
      { title: '一轮归位', desc: '最大的元素移到末尾' },
      { title: '重复收缩', desc: '未排序区间每次减一' },
    ],
    notes: ['平均与最坏 O(n²)，最好 O(n)（已有序加标记）'],
    caption: '冒泡是理解排序的入门模型；实践中几乎总是用内置排序，因为它更快也更稳。',
  },
  stack_queue: {
    image: 'diagram_algo_stack_queue.webp',
    alt: '栈与队列的进出顺序对比',
    title: '栈与队列：两种访问顺序',
    type: 'compare',
    columns: [
      { title: '栈 Stack', items: ['后进先出 LIFO', '入栈 push，出栈 pop', '只看栈顶元素', '函数调用与撤销操作', '可用数组或链表实现'] },
      { title: '队列 Queue', items: ['先进先出 FIFO', '入队 enqueue，出队 dequeue', '看队首元素', '任务调度与广度优先', '环形缓冲避免搬移'] },
    ],
    notes: ['双端队列与优先队列是常见变体'],
    caption: '两者的差别只在「从哪一端取」；这个差别决定了它们适用的算法场景。',
  },
  sorting: {
    image: 'diagram_algo_sorting_family.webp',
    alt: '常见排序算法的复杂度与稳定性',
    title: '排序算法家族：复杂度与稳定性',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['插入排序', '归并排序', '快速排序', '堆排序'],
    colLabels: ['平均复杂度', '稳定性', '适用场景'],
    cells: [
      { r: 0, c: 0, text: 'O(n²)' },
      { r: 0, c: 1, text: '稳定' },
      { r: 0, c: 2, text: '小数组或近似有序' },
      { r: 1, c: 0, text: 'O(n log n)' },
      { r: 1, c: 1, text: '稳定' },
      { r: 1, c: 2, text: '要求稳定，外部排序' },
      { r: 2, c: 0, text: 'O(n log n)' },
      { r: 2, c: 1, text: '不稳定' },
      { r: 2, c: 2, text: '通用内存排序，常数小' },
      { r: 3, c: 0, text: 'O(n log n)' },
      { r: 3, c: 1, text: '不稳定' },
      { r: 3, c: 2, text: '只需前 K 大，内存紧张' },
    ],
    notes: ['比较排序的下界是 O(n log n)'],
    caption: '没有最好的排序：看数据规模、是否要求稳定、内存与已有顺序。',
  },
  two_pointers: {
    image: 'diagram_algo_two_pointers.webp',
    alt: '相向双指针与滑动窗口',
    title: '双指针的两种主流形态',
    type: 'compare',
    columns: [
      { title: '相向双指针', items: ['左右指针从两端靠拢', '要求数组有序', '两数之和、三数之和', '每步排除一侧', '复杂度降到 O(n)'] },
      { title: '滑动窗口', items: ['左右指针同向移动', '维护区间内统计量', '最长无重复子串', '和小于目标的最长子数组', '窗口扩张与收缩交替'] },
    ],
    notes: ['同向双指针也用于快慢指针判环'],
    caption: '双指针的本质是利用单调性避免重复枚举；写之前先想清楚窗口内维护什么量。',
  },
  greedy: {
    image: 'diagram_algo_greedy.webp',
    alt: '贪心算法的选择与验证',
    title: '贪心：每步选局部最优',
    type: 'flow',
    steps: [
      { title: '定义选择', desc: '明确每一步比较什么' },
      { title: '局部最优', desc: '取当前看起来最好的选项' },
      { title: '不可撤销', desc: '选完不回退，因此要证明' },
      { title: '正确性论证', desc: '交换论证或归纳' },
    ],
    notes: ['区间调度按右端点排序', '零钱兑换只在面值规范时可用贪心'],
    caption: '贪心的关键是证明局部最优能导出全局最优；证不出来就换动态规划。',
  },
  bit_manipulation: {
    image: 'diagram_algo_bits.webp',
    alt: '位运算的常用技巧',
    title: '位运算：运算、技巧、状态压缩',
    type: 'flow',
    steps: [
      { title: '基础运算', desc: '与、或、异或、取反、移位' },
      { title: '常用技巧', desc: 'n&(n-1) 消去最低位 1' },
      { title: '异或性质', desc: '相同为 0，可找只出现一次的数' },
      { title: '状态压缩', desc: '用整数的二进制位表示集合' },
    ],
    notes: ['左移相当于乘 2，注意溢出与符号'],
    caption: '位运算把集合与开关状态压进一个整数，是状态压缩 DP 与底层优化的基础工具。',
  },
  prefix_sum: {
    image: 'diagram_algo_prefix.webp',
    alt: '前缀和与差分',
    title: '前缀和与差分：把区间操作降到 O(1)',
    type: 'flow',
    steps: [
      { title: '原数组', desc: '需要反复查询区间' },
      { title: '前缀和', desc: 'pre[i] 表示前 i 项之和' },
      { title: '区间求和', desc: 'sum(l,r)=pre[r+1]-pre[l]' },
      { title: '差分', desc: '区间加值转为两端点修改' },
    ],
    notes: ['二维前缀和用容斥计算子矩阵'],
    caption: '前缀和把重复的区间计算变成一次预处理；差分是它的逆运算，用于区间修改。',
  },
  binary_answer: {
    image: 'diagram_algo_binary_answer.webp',
    alt: '二分答案的判定与收缩',
    title: '二分答案：对答案空间二分',
    type: 'flow',
    steps: [
      { title: '确定范围', desc: '答案的最小与最大可能值' },
      { title: '设计判定', desc: '给定 x 能否满足条件' },
      { title: '验证单调性', desc: 'x 变大时判定结果单调变化' },
      { title: '二分收缩', desc: '找最小可行解或最大可行解' },
    ],
    notes: ['判定函数通常用贪心或计数实现'],
    caption: '二分答案把最优化问题转成判定问题：只要能快速判断可行性，就能二分出最优值。',
  },
  probabilistic_structures: {
    image: 'diagram_algo_probabilistic.webp',
    alt: '布隆过滤器、HyperLogLog 与跳表',
    title: '概率数据结构：用精度换空间',
    type: 'compare',
    columns: [
      { title: '布隆过滤器', items: ['判断元素是否可能存在', '有假阳性、无假阴性', '多个哈希映射到位数组', '适合缓存穿透防护', '不支持删除（计数变体除外）'] },
      { title: 'HyperLogLog', items: ['估算基数（去重计数）', '误差约 0.81%', '内存固定且极小', '适合 UV 统计', '不能取出具体元素'] },
      { title: '跳表', items: ['多层索引的有序链表', '期望 O(log n) 查找', '实现比平衡树简单', '支持范围查询', 'Redis 有序集合使用'] },
    ],
    caption: '概率结构用可控误差换取数量级的内存与速度收益，前提是业务能接受近似结果。',
  },
  balanced_tree: {
    image: 'diagram_algo_balanced_tree.webp',
    alt: 'AVL、红黑树与 B+ 树的对比',
    title: '平衡树家族：AVL、红黑树、B+ 树',
    type: 'compare',
    columns: [
      { title: 'AVL 树', items: ['严格平衡，高度差不超过 1', '查找最快', '插入删除旋转多', '适合读多写少', '内存索引场景'] },
      { title: '红黑树', items: ['近似平衡，最长路径不超两倍', '插入删除旋转少', '综合性能稳定', 'C++ map、Java TreeMap', '内存有序容器首选'] },
      { title: 'B+ 树', items: ['多路平衡，节点大', '所有数据在叶子并成链表', '层高低，磁盘 I/O 少', '支持范围扫描', '数据库索引的标准结构'] },
    ],
    caption: '选择平衡树看存储介质：内存用红黑树，磁盘用 B+ 树，因为磁盘 I/O 次数才是瓶颈。',
  },
  sorting_advanced: {
    image: 'diagram_algo_radix.webp',
    alt: '非比较排序与外部排序',
    title: '线性排序与外部排序',
    type: 'flow',
    steps: [
      { title: '计数排序', desc: '按值域统计出现次数' },
      { title: '基数排序', desc: '按位从低到高多轮分配' },
      { title: '桶排序', desc: '按区间分桶后各桶排序' },
      { title: '外部排序', desc: '分块排序加多路归并' },
    ],
    notes: ['突破 O(n log n) 的前提是数据有额外结构'],
    caption: '非比较排序利用值域或位数信息；数据量超过内存时，外部排序用多轮归并完成。',
  },
  cache_eviction: {
    image: 'diagram_algo_cache_eviction.webp',
    alt: 'LRU、LFU 与 FIFO 淘汰策略',
    title: '缓存淘汰：LRU、LFU、FIFO',
    type: 'compare',
    columns: [
      { title: 'LRU', items: ['淘汰最久未使用', '哈希表加双向链表', '命中率通常较高', '突发扫描会污染缓存', 'Redis 常用策略之一'] },
      { title: 'LFU', items: ['淘汰访问次数最少', '对热点更稳定', '需要维护频次计数', '新数据容易被饿死', '适合热点长期稳定'] },
      { title: 'FIFO', items: ['按进入顺序淘汰', '实现最简单', '不考虑访问频率', '命中率通常较低', '适合数据顺序访问'] },
    ],
    notes: ['缓存淘汰要与过期时间、预热策略配合'],
    caption: '淘汰策略决定缓存保留什么；命中率之外，还要考虑实现成本与访问分布。',
  },
  algorithms_project: {
    image: 'diagram_algo_project.webp',
    alt: '三个数据结构实战小项目',
    title: '实战三题：LRU 缓存、词频 TopK、任务调度',
    type: 'flow',
    steps: [
      { title: 'LRU 缓存', desc: '哈希表加双向链表，O(1) 读写' },
      { title: '词频 TopK', desc: '哈希计数加小顶堆，O(n log k)' },
      { title: '任务调度', desc: '优先队列按时间与优先级出队' },
    ],
    notes: ['先把接口定清楚再选数据结构'],
    caption: '数据结构题的价值在于把接口与复杂度对齐：先说清操作，再选实现。',
  },
  algo_np_approximation: {
    image: 'diagram_algo_np.webp',
    alt: 'P、NP、NP 完全与近似算法',
    title: '计算复杂性：P、NP、NP 完全、近似',
    type: 'layers',
    widths: [0.55, 0.75, 0.9, 1],
    layers: [
      { title: 'P 类', desc: '多项式时间可解的问题' },
      { title: 'NP 类', desc: '解可在多项式时间验证的问题' },
      { title: 'NP 完全', desc: '最难的一类，互相可归约' },
      { title: '近似与启发式', desc: '放弃最优解，换取可接受的解与时间' },
    ],
    caption: '碰到 NP 完全问题不要硬求最优：近似算法、启发式与问题规模裁剪才是工程解法。',
  },
  algo_computational_geometry: {
    image: 'diagram_algo_geometry.webp',
    alt: '计算几何的核心工具',
    title: '计算几何：叉积、凸包、相交、最近点对',
    type: 'flow',
    steps: [
      { title: '向量与叉积', desc: '判断方向与左右关系' },
      { title: '凸包', desc: 'Andrew 单调链 O(n log n)' },
      { title: '线段相交', desc: '跨立实验加端点判断' },
      { title: '最近点对', desc: '分治加按 y 剪枝' },
    ],
    notes: ['浮点误差要用 eps 比较', '优先用整数坐标避免精度问题'],
    caption: '计算几何的难点在边界与精度：方向判断、共线与重合情况要逐一处理。',
  },
  algo_persistent_parallel: {
    image: 'diagram_algo_persistent.webp',
    alt: '持久化数据结构与并行算法',
    title: '持久化与并行：两条进阶路线',
    type: 'compare',
    columns: [
      { title: '持久化数据结构', items: ['修改后保留历史版本', '路径复制共享节点', '可持久化线段树', '版本回滚与查询', '空间换时间的典型'] },
      { title: '并行算法', items: ['把任务分解到多核', '分治与归并常见', '注意负载均衡', '减少共享写冲突', '加速比受 Amdahl 限制'] },
    ],
    caption: '持久化解决「回到过去」，并行解决「同时做更多」；两者都要求对数据共享方式想清楚。',
  },
  algorithm_intro: {
    image: 'diagram_algo_intro.webp',
    alt: '算法的输入、步骤、输出与复杂度',
    title: '算法入门：输入、步骤、输出、复杂度',
    type: 'flow',
    steps: [
      { title: '输入', desc: '明确数据规模与取值范围' },
      { title: '步骤', desc: '有限、确定、可执行' },
      { title: '输出', desc: '满足正确性要求的结果' },
      { title: '复杂度', desc: '衡量时间与空间增长' },
    ],
    notes: ['先保证正确性，再优化复杂度'],
    caption: '算法是解决问题的有限步骤；复杂度描述的是当规模变大时，代价如何增长。',
  },
  linear_search_intro: {
    image: 'diagram_algo_linear_search.webp',
    alt: '线性查找的逐项比较',
    title: '线性查找：从头逐个比较',
    type: 'flow',
    steps: [
      { title: '从头开始', desc: '下标指向第一个元素' },
      { title: '逐个比较', desc: '与目标值比较' },
      { title: '命中返回', desc: '相等则返回下标' },
      { title: '遍历结束', desc: '没有命中返回未找到' },
    ],
    notes: ['复杂度 O(n)，无需数据有序'],
    caption: '线性查找是最朴素的算法：数据无序时它仍然有效，只是代价随规模线性增长。',
  },
};
