// P4 AI 与智能体配图数据。
module.exports = {
  ai_concept_intro: {
    image: 'diagram_ai_concept.webp',
    alt: 'AI、机器学习与生成式 AI 的包含关系',
    title: 'AI 概念入门：三层包含关系',
    type: 'tree',
    root: {
      text: '人工智能 AI',
      children: [
        {
          text: '机器学习 ML',
          children: [
            {
              text: '深度学习 DL',
              children: [
                { text: '大语言模型' },
                { text: '生成式 AI' },
              ],
            },
            { text: '传统机器学习' },
          ],
        },
        { text: '规则与搜索' },
      ],
    },
    notes: ['AI 是目标，ML 是方法，生成式 AI 是当前最活跃的分支'],
    caption: '不要混用三个词：AI 范围最大，机器学习是实现方式，生成式 AI 侧重创造新内容。',
  },
  ai_basics: {
    image: 'diagram_ai_basics.webp',
    alt: '三类机器学习范式对比',
    title: '三类学习范式：数据决定方法',
    type: 'grid',
    rows: 3,
    cols: 3,
    rowLabels: ['监督学习', '无监督学习', '强化学习'],
    colLabels: ['数据形式', '学习目标', '典型应用'],
    cells: [
      { r: 0, c: 0, text: '带标签样本' },
      { r: 0, c: 1, text: '学习输入到输出的映射' },
      { r: 0, c: 2, text: '分类、回归、预测' },
      { r: 1, c: 0, text: '无标签数据' },
      { r: 1, c: 1, text: '发现结构、分组与降维' },
      { r: 1, c: 2, text: '聚类、异常检测' },
      { r: 2, c: 0, text: '与环境交互的奖励' },
      { r: 2, c: 1, text: '学习最大化长期回报的策略' },
      { r: 2, c: 2, text: '游戏、机器人、对齐' },
    ],
    notes: ['学习路径：先理解数据与任务，再选择模型与评测方式'],
    caption: '先判断有没有标签、目标是什么，再谈模型；数据和评测往往比模型选择更关键。',
  },
  prompt_intro: {
    image: 'diagram_ai_prompt_intro.webp',
    alt: '提示词的四个基本要素',
    title: '提示词入门：把需求说清楚',
    type: 'grid',
    rows: 4,
    cols: 2,
    rowLabels: ['目标', '上下文', '约束', '输出格式'],
    colLabels: ['写什么', '示例'],
    cells: [
      { r: 0, c: 0, text: '要模型完成什么任务' },
      { r: 0, c: 1, text: '把这段会议记录总结成要点' },
      { r: 1, c: 0, text: '背景、读者、已知信息' },
      { r: 1, c: 1, text: '面向没参会的同事' },
      { r: 2, c: 0, text: '长度、语气、不能做什么' },
      { r: 2, c: 1, text: '不超过 5 条，不编造' },
      { r: 3, c: 0, text: '结构、字段与示例' },
      { r: 3, c: 1, text: '每条一句话，用 Markdown 列表' },
    ],
    notes: ['提示词是可迭代的输入，不是一次写好的咒语'],
    caption: '目标、上下文、约束、格式四件事说清楚，输出质量通常就会显著提升。',
  },
  ai_prompt_engineering: {
    image: 'diagram_ai_prompt_engineering.webp',
    alt: '提示工程从设计到评测的闭环',
    title: '提示工程：从写法到迭代评测',
    type: 'flow',
    steps: [
      { title: '结构化提示', desc: '角色、任务、上下文与输出规格' },
      { title: '少样本示例', desc: '用输入输出对锚定格式与风格' },
      { title: '分解与推理', desc: '复杂任务拆步骤，让过程可检查' },
      { title: '批量评测', desc: '用固定测试集对比不同提示' },
      { title: '版本迭代', desc: '记录版本、指标与回归结果' },
    ],
    notes: ['思维链适合推理任务，但不必对所有任务强制展示过程'],
    caption: '提示工程不是调措辞，而是用评测数据驱动提示的版本迭代。',
  },
  ai_embeddings_rag: {
    image: 'diagram_ai_embeddings_rag.webp',
    alt: 'RAG 从文档入库到生成答案的流程',
    title: 'RAG：先检索，再生成',
    type: 'sequence',
    actors: ['文档', '切分与向量化', '向量库', '大模型'],
    messages: [
      { from: 0, to: 1, label: '解析并切成语义块' },
      { from: 1, to: 2, label: '写入向量与元数据' },
      { from: 3, to: 2, label: '问题向量化后检索 Top-K' },
      { from: 2, to: 3, label: '返回相关片段与来源' },
      { from: 3, to: 3, label: '拼接上下文生成答案' },
      { from: 3, to: 0, label: '附带引用，可回溯原文' },
    ],
    caption: 'RAG 的效果由分块、检索与提示共同决定；引用与评测是避免幻觉的关键。',
  },
  vector_db: {
    image: 'diagram_ai_vector_db.webp',
    alt: '向量数据库选型与索引调优维度',
    title: '向量数据库：选型看五件事',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['专用向量库', '关系库扩展', '搜索引擎', '内存方案'],
    colLabels: ['代表方案', '优势', '适用场景'],
    cells: [
      { r: 0, c: 0, text: 'Milvus / Qdrant' },
      { r: 0, c: 1, text: '规模与索引能力完整' },
      { r: 0, c: 2, text: '大规模独立检索服务' },
      { r: 1, c: 0, text: 'pgvector' },
      { r: 1, c: 1, text: '与业务数据同库事务' },
      { r: 1, c: 2, text: '中小规模、少组件' },
      { r: 2, c: 0, text: 'Elasticsearch / OpenSearch' },
      { r: 2, c: 1, text: '关键词与向量混合检索' },
      { r: 2, c: 2, text: '已有搜索基础设施' },
      { r: 3, c: 0, text: 'FAISS / 内存索引' },
      { r: 3, c: 1, text: '延迟低、部署简单' },
      { r: 3, c: 2, text: '离线评测与原型' },
    ],
    notes: ['调优重点：召回率、延迟、过滤能力与成本'],
    caption: '先明确数据规模、过滤条件与一致性要求，再在召回率和成本之间调索引参数。',
  },
  ai_context_engineering: {
    image: 'diagram_ai_context_engineering.webp',
    alt: '上下文工程的选择、压缩与更新',
    title: '上下文工程：模型看到什么',
    type: 'layers',
    layers: [
      { title: '选择', desc: '只放入与当前任务相关的事实与工具说明', fill: '#eef4ff', stroke: '#6c8ff8' },
      { title: '压缩', desc: '摘要、去重与结构化，减少无关 token', fill: '#e8f2ff', stroke: '#6c8ff8' },
      { title: '排序', desc: '重要信息靠近首尾，降低中间遗忘', fill: '#e6f7f1', stroke: '#3fae8a' },
      { title: '更新', desc: '多轮中维护状态，及时淘汰过期信息', fill: '#fff4e6', stroke: '#e6a23c' },
      { title: '预算', desc: '为系统、历史、检索与输出分配额度', fill: '#fdeeee', stroke: '#d97070' },
    ],
    widths: [0.72, 0.84, 0.92, 1, 0.88],
    caption: '上下文窗口不是越大越好：相关性、顺序与新鲜度共同决定模型的实际表现。',
  },
  ai_engineering: {
    image: 'diagram_ai_engineering.webp',
    alt: 'AI 应用工程化的四个支柱',
    title: 'AI 应用工程化：让效果可复现',
    type: 'compare',
    columns: [
      { title: '评测与可观测', items: ['建立固定评测集与金标准', '记录输入、输出与工具轨迹', '离线评测加线上监控', '回归防止提示改动退化', '失败样本进入下一轮迭代'] },
      { title: '成本与安全', items: ['按任务选择模型与参数', '缓存、批处理与上下文瘦身', '输入过滤与输出审核', '权限最小化与审计日志', '降级策略与人工兜底'] },
    ],
    notes: ['没有评测与观测的 AI 应用，无法稳定迭代'],
    caption: '工程化把「偶尔效果不错」变成「持续可度量、可回滚、可运营」。',
  },
  model_evaluation: {
    image: 'diagram_ai_model_eval.webp',
    alt: '模型评测的公开基准与私有评测集',
    title: '模型评测与选型：基准只是起点',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['公开基准', '私有评测集', '人工评审', '在线指标'],
    colLabels: ['看什么', '局限', '建议'],
    cells: [
      { r: 0, c: 0, text: '知识、推理与代码分数' },
      { r: 0, c: 1, text: '可能被训练数据污染' },
      { r: 0, c: 2, text: '快速筛选候选模型' },
      { r: 1, c: 0, text: '贴近真实业务的测试集' },
      { r: 1, c: 1, text: '构建与维护成本高' },
      { r: 1, c: 2, text: '作为主要决策依据' },
      { r: 2, c: 0, text: '盲评与偏好对比' },
      { r: 2, c: 1, text: '主观且难以规模化' },
      { r: 2, c: 2, text: '校准自动评分' },
      { r: 3, c: 0, text: '成功率、延迟与成本' },
      { r: 3, c: 1, text: '受流量与场景影响' },
      { r: 3, c: 2, text: '用 A/B 验证真实收益' },
    ],
    notes: ['选型维度：质量、延迟、价格、上下文、工具能力与合规'],
    caption: '公开榜单用来缩小范围，私有评测与线上 A/B 才决定最终选型。',
  },
  ai_data_engineering: {
    image: 'diagram_ai_data_engineering.webp',
    alt: '从数据清洗到数据血缘的流程',
    title: '数据工程：模型效果的地基',
    type: 'flow',
    steps: [
      { title: '清洗与去重', desc: '统一格式、处理缺失与敏感信息' },
      { title: '标注规范', desc: '写清边界案例，先小批试标' },
      { title: '一致性校验', desc: '多人交叉标注，计算一致率' },
      { title: '合成与增强', desc: '用模型扩充长尾，人工抽检' },
      { title: '血缘与版本', desc: '记录数据来源、处理与用量' },
    ],
    notes: ['标注质量决定监督效果，数据血缘决定问题能否追溯'],
    caption: '高质量数据不是一次性清洗，而是有规范、有抽检、有版本、有血缘的持续生产。',
  },
  ai_rag_agent_project: {
    image: 'diagram_ai_rag_project.webp',
    alt: '文档问答助手的端到端架构',
    title: '实战：文档问答助手（RAG + Agent）',
    type: 'sequence',
    actors: ['用户', 'Agent', '检索与工具', '大模型'],
    messages: [
      { from: 0, to: 1, label: '提出业务问题' },
      { from: 1, to: 2, label: '混合检索：向量 + 关键词' },
      { from: 2, to: 1, label: '返回候选片段与来源' },
      { from: 1, to: 4, label: '不足时调用工具补数据' },
      { from: 1, to: 3, label: '组织上下文并生成答案' },
      { from: 3, to: 0, label: '输出答案与可点击引用' },
    ],
    notes: ['评测集覆盖：可答、不可答、需多跳、需工具四类问题'],
    caption: '把检索、工具与生成拆开评测，才能定位是召回问题、推理问题还是提示问题。',
  },
  ai_multi_agent: {
    image: 'diagram_ai_multi_agent.webp',
    alt: '多智能体的三种协作模式',
    title: '多智能体：协作模式与边界',
    type: 'compare',
    columns: [
      { title: '常见编排模式', items: ['主管分发：一个 Agent 拆解与汇总', '流水线：按阶段串行交接', '辩论评审：多角色交叉检查', '并行探索：多个方案同时试', '共享工作区交换中间产物'] },
      { title: '失败模式与治理', items: ['上下文在传递中丢失', '责任边界不清导致循环', '成本随角色数成倍增长', '错误被下游放大', '需要超时、预算与终止条件'] },
    ],
    notes: ['能用单 Agent 加工具解决，就不要引入多 Agent'],
    caption: '多智能体的价值来自分工与校验，代价是通信、成本与不可控性；先证明单 Agent 不够用。',
  },
  ai_coding_assistant: {
    image: 'diagram_ai_coding_assistant.webp',
    alt: 'AI 编程助手的使用流程与评审要点',
    title: 'AI 编程助手：把生成纳入工程流程',
    type: 'flow',
    steps: [
      { title: '提供上下文', desc: '相关代码、接口与约束说明' },
      { title: '小步生成', desc: '一次只改一个明确目标' },
      { title: '本地验证', desc: '编译、测试与静态检查' },
      { title: '人工评审', desc: '看边界、安全与可维护性' },
      { title: '沉淀规范', desc: '把有效提示与检查写入团队约定' },
    ],
    notes: ['Agent 型助手要限制文件、命令与网络权限'],
    caption: 'AI 负责加速草稿与重复劳动，正确性与责任仍然属于提交代码的人。',
  },
  ai_agent_evaluation: {
    image: 'diagram_ai_agent_eval.webp',
    alt: 'Agent 评测的维度与方法',
    title: 'Agent 评测：不只看最终答案',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['结果评测', '轨迹评测', 'LLM 评审', '回归闭环'],
    colLabels: ['评什么', '方法', '注意点'],
    cells: [
      { r: 0, c: 0, text: '任务是否完成' },
      { r: 0, c: 1, text: '金标准断言与规则匹配' },
      { r: 0, c: 2, text: '允许等价答案' },
      { r: 1, c: 0, text: '工具调用是否合理' },
      { r: 1, c: 1, text: '检查步骤、参数与顺序' },
      { r: 1, c: 2, text: '轨迹比结果更可诊断' },
      { r: 2, c: 0, text: '主观质量与帮助性' },
      { r: 2, c: 1, text: 'LLM-as-Judge 加人工校准' },
      { r: 2, c: 2, text: '防止位置与长度偏差' },
      { r: 3, c: 0, text: '改动是否造成退化' },
      { r: 3, c: 1, text: '固定测试集持续跑分' },
      { r: 3, c: 2, text: '失败样本进入回归集' },
    ],
    notes: ['评测维度：完成率、正确性、效率、成本与安全性'],
    caption: 'Agent 的能力体现在过程：只看最终答案，无法发现绕路、乱调工具或高成本成功。',
  },
  multimodal_rag: {
    image: 'diagram_ai_multimodal_rag.webp',
    alt: '多模态 RAG 的解析与检索流程',
    title: '多模态 RAG：让图文表格都能被检索',
    type: 'flow',
    steps: [
      { title: '版面解析', desc: '识别标题、段落、表格与图片区域' },
      { title: '多模态表示', desc: '文本、图像分别编码到向量空间' },
      { title: '跨模态检索', desc: '按问题召回文字与图像片段' },
      { title: '融合生成', desc: '把图表信息转成模型可读上下文' },
      { title: '可溯源引用', desc: '答案回链到页码与原始区域' },
    ],
    notes: ['表格与图表要保留结构，不能只当纯文本切分'],
    caption: '多模态 RAG 的难点在解析与对齐：检索到正确页面后，还要让模型读懂其中的结构。',
  },
  agent_cost_performance: {
    image: 'diagram_ai_cost_performance.webp',
    alt: 'Agent 成本与性能优化的主要手段',
    title: 'Agent 成本与性能：把钱花在关键步骤',
    type: 'compare',
    columns: [
      { title: '降本手段', items: ['上下文瘦身与历史摘要', '按难度路由大小模型', '缓存检索结果与稳定前缀', '合并调用、减少无效轮次', '为每个任务设置 token 预算'] },
      { title: '提效手段', items: ['并行化独立工具调用', '流式输出降低首字延迟', '预取与预热高频数据', '限制工具超时与重试次数', '压测 P50/P95 与成功率'] },
    ],
    notes: ['成本、延迟、质量三者要一起看，单独优化任一项都可能伤害体验'],
    caption: '先测量每个环节的 token 与耗时，再优化大头；模型路由与缓存通常收益最快。',
  },
  ai_computer_use: {
    image: 'diagram_ai_computer_use.webp',
    alt: 'Computer Use 的观察与操作循环',
    title: 'Computer Use：观察、决策、操作',
    type: 'cycle',
    nodes: [
      { title: '截图', desc: '获取当前界面状态' },
      { title: '理解', desc: '识别控件与目标' },
      { title: '规划', desc: '决定下一步动作' },
      { title: '操作', desc: '点击、输入与滚动' },
      { title: '校验', desc: '确认结果是否符合预期' },
    ],
    center: '感知-行动循环',
    notes: ['高风险操作需人工确认，敏感界面要限制权限'],
    caption: '桌面自动化把模型接入真实系统，因此权限、确认与可回滚设计比单步准确率更重要。',
  },
  ai_browser_agent: {
    image: 'diagram_ai_browser_agent.webp',
    alt: '浏览器 Agent 的工作流程与约束',
    title: '浏览器 Agent：把网页当作工具',
    type: 'flow',
    steps: [
      { title: '理解任务', desc: '明确目标网站、字段与成功条件' },
      { title: '导航与定位', desc: '结合 DOM、文本与截图找到元素' },
      { title: '交互操作', desc: '点击、填表、上传与翻页' },
      { title: '结果抽取', desc: '结构化保存并校验关键字段' },
      { title: '异常处理', desc: '验证码、登录与反自动化约束' },
    ],
    notes: ['优先使用官方 API，网页自动化是最后手段'],
    caption: '浏览器环境脆弱且多变，Agent 需要重试、兜底与人工接管，而不是假定页面永远不变。',
  },
  ai_coding_agent: {
    image: 'diagram_ai_coding_agent.webp',
    alt: '代码 Agent 从读代码到提交改动的流程',
    title: '代码 Agent：可评审的自动化改动',
    type: 'flow',
    steps: [
      { title: '读代码与文档', desc: '建立仓库结构与依赖认知' },
      { title: '定位与计划', desc: '找到改动点，声明范围与风险' },
      { title: '编辑与运行', desc: '改代码、跑测试与静态检查' },
      { title: '自查与解释', desc: '检查 diff，说明取舍与遗留' },
      { title: '提交评审', desc: '小步提交，保留可回滚历史' },
    ],
    notes: ['权限边界：可写目录、可执行命令与网络访问都要显式限定'],
    caption: '代码 Agent 的产出要像同事的 PR 一样被评审：看范围、看测试、看回归风险。',
  },
  ai_guardrails: {
    image: 'diagram_ai_guardrails.webp',
    alt: '输入、工具调用与输出三层安全护栏',
    title: '安全护栏：三道检查点',
    type: 'layers',
    layers: [
      { title: '输入护栏', desc: '越狱与注入检测、敏感信息识别', fill: '#eef4ff', stroke: '#6c8ff8' },
      { title: '上下文隔离', desc: '区分系统指令与不可信外部内容', fill: '#e8f2ff', stroke: '#6c8ff8' },
      { title: '工具调用护栏', desc: '白名单、参数校验与人工确认', fill: '#e6f7f1', stroke: '#3fae8a' },
      { title: '输出审核', desc: '事实校验、敏感内容与格式检查', fill: '#fff4e6', stroke: '#e6a23c' },
      { title: '监控与审计', desc: '记录拦截原因，持续更新规则', fill: '#fdeeee', stroke: '#d97070' },
    ],
    widths: [0.74, 0.84, 1, 0.9, 0.8],
    caption: '护栏要可解释、可度量、可迭代；只在最后一层过滤输出，无法阻止危险的工具调用。',
  },
  ai_realtime_api: {
    image: 'diagram_ai_realtime_api.webp',
    alt: '实时语音交互的流式链路',
    title: 'Realtime API：低延迟语音交互',
    type: 'sequence',
    actors: ['用户', '音频采集', '实时模型', '应用'],
    messages: [
      { from: 0, to: 1, label: '持续上传语音流' },
      { from: 1, to: 2, label: '流式识别与语义理解' },
      { from: 2, to: 3, label: '边生成边返回音频与文本' },
      { from: 3, to: 2, label: '播放并支持随时打断' },
      { from: 2, to: 3, label: '调用工具补充实时信息' },
      { from: 3, to: 0, label: '多轮对话保持上下文' },
    ],
    caption: '实时交互的关键指标是首字延迟、打断响应与端到端稳定性，而不是单次识别准确率。',
  },
  ai_governance: {
    image: 'diagram_ai_governance.webp',
    alt: 'AI 治理的闭环流程',
    title: 'AI 治理：从风险到监督的闭环',
    type: 'cycle',
    nodes: [
      { title: '数据来源', desc: '授权、隐私与版权' },
      { title: '模型卡片', desc: '能力、限制与适用边界' },
      { title: '评测审计', desc: '质量、偏见与安全测试' },
      { title: '上线监控', desc: '漂移、滥用与事故响应' },
      { title: '人类监督', desc: '复核、申诉与纠偏' },
    ],
    center: '可信 AI',
    notes: ['合规要求因地区与行业而异，需保留决策与数据记录'],
    caption: '治理不是上线前的一次审批，而是覆盖数据、模型、应用与运营的持续责任机制。',
  },
};
