// P4 数据库与数据工程配图数据。
module.exports = {
  db_design: {
    image: 'diagram_db_design.webp',
    alt: '从需求到三大范式的数据库设计流程',
    title: '数据库设计：从实体到范式',
    type: 'layers',
    layers: [
      { title: '需求与实体', desc: '找出名词、属性与业务规则', fill: '#eef4ff', stroke: '#6c8ff8' },
      { title: 'ER 建模', desc: '实体、关系与一对多/多对多基数', fill: '#e8f2ff', stroke: '#6c8ff8' },
      { title: '键与约束', desc: '主键唯一标识，外键维护引用完整性', fill: '#e6f7f1', stroke: '#3fae8a' },
      { title: '规范化', desc: '1NF 原子、2NF 消除部分依赖、3NF 消除传递依赖', fill: '#fff4e6', stroke: '#e6a23c' },
      { title: '反范式权衡', desc: '读多写少时允许冗余，用一致性成本换查询性能', fill: '#fdeeee', stroke: '#d97070' },
    ],
    widths: [0.72, 0.82, 0.9, 1, 0.94],
    caption: '范式解决的是数据冗余与更新异常；反范式是有意识的性能取舍，不是设计失误。',
  },
  nosql: {
    image: 'diagram_db_nosql_family.webp',
    alt: '四类 NoSQL 数据模型对比',
    title: 'NoSQL 四类模型与选型',
    type: 'compare',
    columns: [
      { title: '键值与文档', items: ['Redis：内存键值，缓存与计数', '按 key 直接寻址，延迟极低', 'MongoDB：JSON 文档，字段灵活', '文档内嵌减少跨表查询', '适合会话、目录与内容管理'] },
      { title: '列族与图', items: ['HBase/Cassandra：宽表列族', '按分区键水平扩展，写吞吐高', 'Neo4j：节点与关系属性图', '多跳关系查询天然高效', '适合风控、推荐与知识图谱'] },
    ],
    notes: ['CAP 只能同时满足一致性、可用性与分区容错中的两项', '选型先看访问模式，再看一致性与扩展需求'],
    caption: 'NoSQL 不是「不用 SQL」，而是为特定访问模式放弃部分关系能力与强一致。',
  },
  db_ops: {
    image: 'diagram_db_ops_flow.webp',
    alt: '数据库运维的备份、迁移与扩展流程',
    title: '数据库运维：先保命，再扩展',
    type: 'flow',
    steps: [
      { title: '容量与基线', desc: '摸清数据量、QPS 与增长趋势' },
      { title: '备份与恢复', desc: '定义 RPO/RTO，定期做恢复演练' },
      { title: '在线变更', desc: '低锁 DDL，灰度执行并保留回滚' },
      { title: '水平扩展', desc: '读写分离、分库分表与路由治理' },
    ],
    notes: ['没有经过恢复验证的备份，等于没有备份'],
    caption: '运维的核心不是「永远不出故障」，而是把恢复时间与数据损失控制在可接受范围内。',
  },
  sql_advanced: {
    image: 'diagram_db_sql_advanced.webp',
    alt: '窗口函数与 CTE 的能力对比',
    title: '窗口函数与 CTE：让 SQL 表达更复杂逻辑',
    type: 'compare',
    columns: [
      { title: '窗口函数', items: ['在结果集上开窗计算，不合并行', 'ROW_NUMBER 排名与去重', 'SUM/AVG OVER 累计与移动平均', 'PARTITION BY 分组、ORDER BY 排序', '适合排名、同比与占比分析'] },
      { title: '公用表表达式 CTE', items: ['WITH 定义临时结果集', '把复杂查询拆成可读步骤', '递归 CTE 处理树与层级', '避免重复子查询，便于调试', '注意物化行为与执行计划'] },
    ],
    notes: ['窗口函数在 WHERE 之后计算，筛选结果需再包一层子查询'],
    caption: '窗口函数解决「保留明细的同时做聚合」，CTE 解决「把长 SQL 写成可读的流水线」。',
  },
  storage_engine: {
    image: 'diagram_db_storage_engine.webp',
    alt: 'InnoDB 从 SQL 到磁盘的分层结构',
    title: 'InnoDB：一条 SQL 如何落到磁盘',
    type: 'layers',
    layers: [
      { title: '连接与 SQL 层', desc: '解析、优化并生成执行计划', fill: '#eef4ff', stroke: '#6c8ff8' },
      { title: 'Buffer Pool', desc: '内存缓存数据页，减少随机磁盘 IO', fill: '#e8f2ff', stroke: '#6c8ff8' },
      { title: '聚簇索引 B+ 树', desc: '主键即数据，二级索引需回表', fill: '#e6f7f1', stroke: '#3fae8a' },
      { title: 'redo log 与 WAL', desc: '先写日志再刷盘，保证崩溃恢复', fill: '#fff4e6', stroke: '#e6a23c' },
      { title: 'undo 与 binlog', desc: 'undo 支撑回滚与 MVCC，binlog 用于复制', fill: '#fdeeee', stroke: '#d97070' },
    ],
    widths: [0.7, 0.82, 0.92, 1, 0.96],
    caption: '理解存储引擎，才能解释「为什么加了索引还是慢」以及「为什么事务能回滚」。',
  },
  database_project: {
    image: 'diagram_db_project_flow.webp',
    alt: '订单库实战的五个步骤',
    title: '实战：设计并优化一个订单库',
    type: 'flow',
    steps: [
      { title: '业务建模', desc: '用户、商品、订单、支付与状态机' },
      { title: '造测试数据', desc: '构造千万级订单模拟真实增长' },
      { title: '索引与改写', desc: '组合索引、覆盖索引与慢 SQL 治理' },
      { title: '事务与并发', desc: '隔离级别、锁顺序与库存扣减' },
      { title: '分页与归档', desc: '游标分页、冷热分离与历史归档' },
    ],
    notes: ['每一步都用执行计划与压测数据验证，而不是凭感觉调优'],
    caption: '订单库是数据库知识的综合练习：建模决定上限，索引与事务决定稳定性。',
  },
  bigdata_batch_stream: {
    image: 'diagram_db_batch_stream.webp',
    alt: '批处理与流处理的差异',
    title: '批处理与流处理：两套数据管道',
    type: 'compare',
    columns: [
      { title: '批处理', items: ['按小时或按天处理有界数据', 'HDFS 存储，Spark 计算', '吞吐高、延迟分钟到小时', '重跑简单，结果可复现', '适合离线报表与全量重算'] },
      { title: '流处理', items: ['持续处理无界数据流', 'Kafka 传输，Flink 计算', '延迟秒级甚至毫秒级', '要处理乱序、水位线与状态', '适合实时监控与风控'] },
    ],
    notes: ['数仓分层 ODS → DWD → DWS → ADS 批流共用', '数据质量与成本治理要覆盖两条链路'],
    caption: '批流不是二选一：常见架构是流式入湖、批式校正，同一份口径服务两类场景。',
  },
  data_lakehouse: {
    image: 'diagram_db_lakehouse_layers.webp',
    alt: '湖仓一体的分层架构',
    title: '湖仓一体：在对象存储上做数据仓库',
    type: 'layers',
    layers: [
      { title: '数据源', desc: '业务库、日志、埋点与第三方数据', fill: '#eef4ff', stroke: '#6c8ff8' },
      { title: '对象存储', desc: 'S3/OSS/HDFS 存原始与明细数据', fill: '#e8f2ff', stroke: '#6c8ff8' },
      { title: '开放表格式', desc: 'Iceberg/Hudi/Delta 提供 ACID 与快照', fill: '#e6f7f1', stroke: '#3fae8a' },
      { title: '计算引擎', desc: 'Spark/Flink/Trino 读写同一份数据', fill: '#fff4e6', stroke: '#e6a23c' },
      { title: '查询与服务', desc: 'BI、特征平台与在线服务统一口径', fill: '#fdeeee', stroke: '#d97070' },
    ],
    widths: [0.7, 0.82, 0.92, 1, 0.9],
    notes: ['小文件合并、快照过期与元数据治理是长期运维重点'],
    caption: '湖仓的价值在于一份存储支撑多种计算，同时保留事务、时间旅行与 Schema 演进。',
  },
  airflow_quality: {
    image: 'diagram_db_airflow_quality.webp',
    alt: 'Airflow 调度与数据质量检查闭环',
    title: 'Airflow：把调度与质量检查串成闭环',
    type: 'flow',
    steps: [
      { title: '定义 DAG', desc: '任务依赖、重试与 SLA 声明' },
      { title: '幂等执行', desc: '同一分区重复跑结果一致' },
      { title: '质量检查', desc: '完整性、唯一性、及时性与准确性' },
      { title: '告警与回填', desc: '失败告警、定位与 backfill 补数' },
    ],
    notes: ['六项检查：完整性、唯一性、及时性、有效性、一致性、准确性'],
    caption: '调度的难点不在「按时跑」，而在失败可重试、数据可回填、问题可定位。',
  },
  realtime_warehouse: {
    image: 'diagram_db_realtime_warehouse.webp',
    alt: '从 Kafka 到 Flink 再到实时数仓的链路',
    title: '实时数仓：数据如何流动',
    type: 'sequence',
    actors: ['业务库', 'Kafka', 'Flink', '实时数仓'],
    messages: [
      { from: 0, to: 1, label: 'CDC 捕获变更日志' },
      { from: 1, to: 2, label: '按分区消费，保证顺序' },
      { from: 2, to: 2, label: '水位线处理乱序' },
      { from: 2, to: 3, label: '精确一次写入明细层' },
      { from: 3, to: 2, label: '维表关联与聚合回查' },
      { from: 2, to: 3, label: '产出指标并对外服务' },
    ],
    caption: '实时链路的难点是乱序、状态与一致性；先把分层和口径定清楚，再谈毫秒级延迟。',
  },
  db_postgresql_deep: {
    image: 'diagram_db_postgresql.webp',
    alt: 'PostgreSQL 的核心机制与实践要点',
    title: 'PostgreSQL 深入实践',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['MVCC', 'VACUUM', '执行计划', '逻辑复制'],
    colLabels: ['核心机制', '关键要点', '实践建议'],
    cells: [
      { r: 0, c: 0, text: '多版本并发控制' },
      { r: 0, c: 1, text: '读不阻塞写，写不阻塞读' },
      { r: 0, c: 2, text: '关注长事务与膨胀' },
      { r: 1, c: 0, text: '回收死元组空间' },
      { r: 1, c: 1, text: 'autovacuum 与冻结阈值' },
      { r: 1, c: 2, text: '监控表膨胀与年龄' },
      { r: 2, c: 0, text: 'EXPLAIN ANALYZE' },
      { r: 2, c: 1, text: '扫描方式、行数估算与代价' },
      { r: 2, c: 2, text: '统计信息与索引验证' },
      { r: 3, c: 0, text: '发布订阅同步' },
      { r: 3, c: 1, text: '逻辑解码与冲突处理' },
      { r: 3, c: 2, text: '用于升级与读写分离' },
    ],
    notes: ['扩展生态是 PostgreSQL 的重要优势，但要在可控范围内引入'],
    caption: 'PostgreSQL 的深度来自机制透明：理解 MVCC、VACUUM 与执行计划，才能稳定调优。',
  },
  db_graph: {
    image: 'diagram_db_graph.webp',
    alt: '图数据库的模型、查询与算法',
    title: '图数据库：关系本身就是一等公民',
    type: 'tree',
    root: {
      text: '属性图模型',
      children: [
        {
          text: '节点与关系',
          children: [
            { text: '节点带标签' },
            { text: '关系有方向和类型' },
          ],
        },
        {
          text: 'Cypher 查询',
          children: [
            { text: 'MATCH 模式匹配' },
            { text: '多跳关系遍历' },
          ],
        },
        {
          text: '图算法',
          children: [
            { text: '最短路与中心度' },
            { text: '社区发现' },
          ],
        },
      ],
    },
    notes: ['关系深、模式灵活时优势明显；全量扫描与聚合并非强项'],
    caption: '图数据库把连接成本前移到写入与建模阶段，换来多跳关系查询的低延迟。',
  },
  db_time_series: {
    image: 'diagram_db_time_series.webp',
    alt: '时序数据的写入特征与治理策略',
    title: '时序数据库：高写入与降采样',
    type: 'compare',
    columns: [
      { title: '写入特征', items: ['数据点带时间戳与标签', '按时间追加，几乎不更新', '写入吞吐远高于查询', '允许一定程度的乱序', '按时间分区自动切分'] },
      { title: '查询与治理', items: ['按时间范围与标签过滤', '降采样与预聚合', '保留策略自动过期', '连续查询生成汇总', '监控告警与容量规划'] },
    ],
    notes: ['标签基数过高会放大索引与内存开销'],
    caption: '时序场景的核心矛盾是写入量与保留成本，降采样与保留策略比单点查询优化更重要。',
  },
  db_migration_governance: {
    image: 'diagram_db_migration.webp',
    alt: '在线 Schema 变更的六个阶段',
    title: 'Schema 治理：可回滚的在线变更',
    type: 'timeline',
    total: 10,
    tasks: [
      { label: '影响评估', start: 0, duration: 1.5, desc: '锁与兼容性' },
      { label: '影子表', start: 1, duration: 2, desc: '建新结构' },
      { label: '双写与回填', start: 2.5, duration: 2.5, desc: '数据追平' },
      { label: '一致性校验', start: 4.5, duration: 1.5, desc: '抽样比对' },
      { label: '灰度切换', start: 5.5, duration: 2, desc: '按流量放量' },
      { label: '清理与归档', start: 7.5, duration: 2, desc: '下线旧结构' },
    ],
    notes: ['每一步都要有回滚点；大表 DDL 优先选择在线工具'],
    caption: 'Schema 变更不是一次执行，而是一段可观测、可回退的迁移过程。',
  },
  db_permissions_security: {
    image: 'diagram_db_permissions.webp',
    alt: '数据库安全的五层防线',
    title: '数据库安全：从网络到审计',
    type: 'layers',
    layers: [
      { title: '网络隔离', desc: '只允许受信网段与应用访问', fill: '#eef4ff', stroke: '#6c8ff8' },
      { title: '账号与最小权限', desc: '应用账号不拥有 DDL 与超级权限', fill: '#e8f2ff', stroke: '#6c8ff8' },
      { title: '行级与列级安全', desc: '按租户与角色限制可见数据', fill: '#e6f7f1', stroke: '#3fae8a' },
      { title: '加密与脱敏', desc: '传输 TLS，静态加密与敏感字段掩码', fill: '#fff4e6', stroke: '#e6a23c' },
      { title: '审计与告警', desc: '记录高危操作，异常行为实时告警', fill: '#fdeeee', stroke: '#d97070' },
    ],
    widths: [0.7, 0.86, 0.92, 1, 0.9],
    caption: '安全的关键是默认拒绝与权限收敛；审计日志要独立存放，避免被攻击者一并清除。',
  },
  db_backup_recovery: {
    image: 'diagram_db_backup_recovery.webp',
    alt: '从备份策略到时间点恢复的流程',
    title: '备份与恢复：目标决定策略',
    type: 'flow',
    steps: [
      { title: '定义目标', desc: 'RPO 允许丢多少数据，RTO 允许停多久' },
      { title: '全量与增量', desc: '周期全备加日常增量，控制窗口' },
      { title: '日志归档', desc: 'WAL/binlog 连续归档到独立存储' },
      { title: '时间点恢复', desc: '恢复到故障前任意时间点' },
      { title: '定期演练', desc: '在隔离环境验证恢复耗时与完整性' },
    ],
    notes: ['备份要异地、加密、监控，并防止误删'],
    caption: 'RPO/RTO 是业务指标，不是数据库参数；恢复演练是唯一可靠的验收方式。',
  },
  sql_table_intro: {
    image: 'diagram_db_table_intro.webp',
    alt: '表结构与主键约束示意',
    title: '表入门：行与列组成结构化数据',
    type: 'grid',
    rows: 3,
    cols: 3,
    rowLabels: ['id', 'name', 'email'],
    colLabels: ['含义', '类型', '约束'],
    cells: [
      { r: 0, c: 0, text: '用户编号' },
      { r: 0, c: 1, text: '整数' },
      { r: 0, c: 2, text: '主键，唯一且非空' },
      { r: 1, c: 0, text: '用户名' },
      { r: 1, c: 1, text: '变长字符串' },
      { r: 1, c: 2, text: '非空' },
      { r: 2, c: 0, text: '邮箱' },
      { r: 2, c: 1, text: '变长字符串' },
      { r: 2, c: 2, text: '唯一，可空' },
    ],
    notes: ['先设计表结构，再用 INSERT 写入数据'],
    caption: '表是关系的载体：列定义类型与约束，行表示一条条真实记录。',
  },
  sql_query_intro: {
    image: 'diagram_db_query_intro.webp',
    alt: 'SELECT 查询的执行顺序',
    title: '查询入门：SELECT 的执行顺序',
    type: 'flow',
    steps: [
      { title: 'FROM', desc: '确定从哪张表取数据' },
      { title: 'WHERE', desc: '先过滤掉不需要的行' },
      { title: 'SELECT', desc: '选择要输出的列与表达式' },
      { title: 'ORDER BY', desc: '对结果排序' },
      { title: 'LIMIT', desc: '只取前 N 行' },
    ],
    notes: ['书写顺序与执行顺序不同，先过滤再排序能显著减少开销'],
    caption: '把查询拆成「取表、过滤、投影、排序、截断」，复杂 SQL 也能逐步读懂。',
  },
};
