// P4 计算机基础配图数据。
module.exports = {
  binary: {
    image: 'diagram_fund_binary.webp',
    alt: '位、字节与进制转换',
    title: '二进制：位、字节与进制互转',
    type: 'flow',
    steps: [
      { title: '位 bit', desc: '只有 0 与 1 两种状态' },
      { title: '字节 byte', desc: '8 位，可表示 0-255' },
      { title: '十进制互转', desc: '除 2 取余，按权展开' },
      { title: '十六进制', desc: '4 位一组，缩写二进制' },
    ],
    notes: ['n 位二进制可表示 2^n 种状态', '有符号数用补码表示负数'],
    caption: '计算机用高低电平表示 0 和 1；进制的选择只是同一数值的不同书写方式。',
  },
  assembly: {
    image: 'diagram_fund_assembly.webp',
    alt: '从源码到机器指令与寄存器',
    title: '指令集与汇编：源码、指令、寄存器、约定',
    type: 'flow',
    steps: [
      { title: '源码', desc: '高级语言表达逻辑' },
      { title: '汇编', desc: '助记符对应一条机器指令' },
      { title: '机器指令', desc: '操作码加操作数编码' },
      { title: '寄存器与约定', desc: '传参、返回值与栈帧规则' },
    ],
    notes: ['ISA 是软硬件之间的接口契约', '调用约定决定参数放在哪些寄存器'],
    caption: '汇编是指令集的可读形式；理解寄存器与调用约定，才能看懂函数调用与栈帧。',
  },
  discrete_math: {
    image: 'diagram_fund_discrete.webp',
    alt: '离散数学的四个核心模块',
    title: '离散数学四个核心模块',
    type: 'grid',
    rows: 2,
    cols: 2,
    cells: [
      { r: 0, c: 0, text: '命题逻辑\n与、或、非、蕴含与量词', fill: '#e7eeff', stroke: '#6c8ff8', bold: true },
      { r: 0, c: 1, text: '集合与关系\n笛卡尔积、等价关系、偏序', fill: '#e0f2fe', stroke: '#0ea5e9', bold: true },
      { r: 1, c: 0, text: '图论\n路径、连通、树与网络流', fill: '#dcfce7', stroke: '#16a34a', bold: true },
      { r: 1, c: 1, text: '组合计数\n排列组合、鸽巢、递推', fill: '#fef3c7', stroke: '#f59e0b', bold: true },
    ],
    caption: '离散数学是算法与类型系统的语言基础：逻辑用于推理，图论用于建模，组合用于估算复杂度。',
  },
  probability: {
    image: 'diagram_fund_probability.webp',
    alt: '从样本空间到贝叶斯与分布',
    title: '概率统计：样本空间、条件概率、贝叶斯、分布',
    type: 'flow',
    steps: [
      { title: '样本空间', desc: '所有可能结果的集合' },
      { title: '条件概率', desc: '已知信息下重新计算可能' },
      { title: '贝叶斯公式', desc: '先验结合证据得到后验' },
      { title: '常见分布', desc: '二项、泊松、正态' },
    ],
    notes: ['期望描述平均水平，方差描述波动', '小样本结论要谨慎'],
    caption: '概率思维的价值在于量化不确定性：先验加证据得到后验，是很多算法与模型的基础。',
  },
  computation_theory: {
    image: 'diagram_fund_theory.webp',
    alt: '自动机、文法与可计算性层次',
    title: '计算理论：自动机、文法、可计算性',
    type: 'layers',
    widths: [1, 0.82, 0.64],
    layers: [
      { title: '有限自动机与正则表达式', desc: '只能描述正则语言，没有记忆能力' },
      { title: '上下文无关文法与下推自动机', desc: '带栈的记忆，可描述嵌套结构' },
      { title: '图灵机与可计算性', desc: '停机问题不可判定，存在计算边界' },
    ],
    caption: '计算模型的能力逐层增强；正则表达式的理论边界决定了它无法表达嵌套语法。',
  },
  compiler_frontend: {
    image: 'diagram_fund_frontend.webp',
    alt: '词法分析与语法分析流程',
    title: '编译前端：源码、Token、语法树、语义',
    type: 'flow',
    steps: [
      { title: '源码', desc: '字符流输入' },
      { title: '词法分析', desc: '切分为 Token 序列' },
      { title: '语法分析', desc: '构建抽象语法树 AST' },
      { title: '语义分析', desc: '类型检查与符号表' },
      { title: '中间表示', desc: '交给后端优化与生成' },
    ],
    notes: ['词法用有限自动机，语法用文法规则', '错误恢复让编译器一次报出多个问题'],
    caption: '前端负责理解程序结构：词法切词、语法建树、语义检查，最后生成统一的中间表示。',
  },
  semantics_analysis: {
    image: 'diagram_fund_semantics.webp',
    alt: '符号表、类型检查与控制流分析',
    title: '语义分析：符号表、类型、控制流',
    type: 'flow',
    steps: [
      { title: '符号表', desc: '记录变量、函数与作用域' },
      { title: '类型检查', desc: '验证运算与赋值是否合法' },
      { title: '作用域解析', desc: '确定每个名字指向哪个声明' },
      { title: '控制流分析', desc: '检测不可达代码与未初始化' },
    ],
    notes: ['符号表通常按作用域分层组织'],
    caption: '语法正确不代表程序有意义；语义分析负责回答「这个程序讲得通吗」。',
  },
  ir_optimization: {
    image: 'diagram_fund_ir.webp',
    alt: '中间表示与经典优化',
    title: '中间表示与优化：CFG、数据流、优化',
    type: 'flow',
    steps: [
      { title: '中间表示', desc: '三地址码或 SSA 形式' },
      { title: '基础块与 CFG', desc: '把代码切成分支图' },
      { title: '数据流分析', desc: '到达定义、活跃变量' },
      { title: '经典优化', desc: '常量传播、死代码消除、内联' },
    ],
    notes: ['优化必须保持程序语义不变'],
    caption: 'IR 让前端与后端解耦；优化在 IR 上进行，因此可以复用给多种目标平台。',
  },
  codegen_registers: {
    image: 'diagram_fund_codegen.webp',
    alt: '后端代码生成与寄存器分配',
    title: '代码生成：指令选择、寄存器分配、栈帧',
    type: 'flow',
    steps: [
      { title: '指令选择', desc: '用目标指令覆盖 IR 树' },
      { title: '寄存器分配', desc: '图着色或线性扫描' },
      { title: '指令调度', desc: '填充流水线延迟槽' },
      { title: '栈帧布局', desc: '保存现场与局部变量' },
    ],
    notes: ['寄存器溢出会带来额外访存开销'],
    caption: '后端把 IR 落到具体硬件：寄存器数量有限，分配质量直接决定生成代码的性能。',
  },
  performance_metrics: {
    image: 'diagram_fund_perf.webp',
    alt: '性能度量与 Amdahl 定律',
    title: '性能度量：时间、吞吐、加速比',
    type: 'flow',
    steps: [
      { title: '两个基本指标', desc: '响应时间与吞吐量' },
      { title: 'CPU 时间公式', desc: '指令数 × CPI × 时钟周期' },
      { title: 'Amdahl 定律', desc: '加速比受不可并行部分限制' },
      { title: '基准测试', desc: '可重复、有代表性、看分布' },
    ],
    notes: ['平均延迟会掩盖长尾，要看 P95 与 P99'],
    caption: '性能优化的前提是测量：先确认瓶颈在哪一层，再决定优化哪一部分。',
  },
  cryptography: {
    image: 'diagram_fund_crypto.webp',
    alt: '对称加密、非对称加密与哈希',
    title: '密码学三类原语',
    type: 'compare',
    columns: [
      { title: '对称加密', items: ['同一密钥加解密', '速度快，适合大数据量', 'AES 加 GCM 提供认证', '密钥分发是难点', '严禁重复使用随机数'] },
      { title: '非对称加密', items: ['公钥加密、私钥解密', 'RSA、椭圆曲线 ECC', '速度慢，用于交换密钥', '可做数字签名', '密钥长度要求更高'] },
      { title: '哈希与 MAC', items: ['单向压缩，定长输出', 'SHA-256 用于完整性', '口令要用 bcrypt/Argon2', 'HMAC 提供消息认证', '注意长度扩展攻击'] },
    ],
    notes: ['不要自己设计加密算法与协议', '随机数必须使用密码学安全来源'],
    caption: '真实系统三者配合：非对称交换密钥，对称加密数据，哈希与签名保证完整性与身份。',
  },
  graphics_media: {
    image: 'diagram_fund_graphics.webp',
    alt: '图形渲染管线',
    title: '渲染管线：顶点、光栅化、着色、合成',
    type: 'flow',
    steps: [
      { title: '顶点处理', desc: '模型变换与投影' },
      { title: '图元装配', desc: '组成三角形并裁剪' },
      { title: '光栅化', desc: '三角形转为片元' },
      { title: '片元着色', desc: '纹理采样与光照计算' },
      { title: '输出合成', desc: '深度测试与混合' },
    ],
    notes: ['音频关注采样率与位深', '视频关注分辨率、帧率与码率'],
    caption: 'GPU 的强大来自并行：成千上万个顶点与片元被同时处理，管线各阶段可流水执行。',
  },
  fundamentals_project: {
    image: 'diagram_fund_lifecycle.webp',
    alt: '程序从源码到运行的全生命周期',
    title: '程序全生命周期：编译、加载、运行、观察',
    type: 'flow',
    direction: 'vertical',
    steps: [
      { title: '编写源码', desc: '高级语言表达意图' },
      { title: '编译与链接', desc: '生成可执行文件' },
      { title: '加载', desc: '映射代码段与数据段到内存' },
      { title: '运行', desc: 'CPU 取指执行，栈堆增长' },
      { title: '观察', desc: '用工具看内存、进程与缓存' },
    ],
    caption: '把「写代码」到「CPU 执行」串成一条链，是理解计算机系统最有效的方式。',
  },
  fundamentals_pipeline: {
    image: 'diagram_fund_pipeline.webp',
    alt: 'CPU 流水线的五个阶段',
    title: 'CPU 流水线：五个阶段重叠执行',
    type: 'flow',
    steps: [
      { title: '取指 IF', desc: '按 PC 读取指令' },
      { title: '译码 ID', desc: '解析操作码与操作数' },
      { title: '执行 EX', desc: 'ALU 运算或地址计算' },
      { title: '访存 MEM', desc: '读写数据内存' },
      { title: '写回 WB', desc: '结果写回寄存器' },
    ],
    notes: ['数据冒险用转发与停顿解决', '分支预测失败要清空流水线'],
    caption: '流水线让多条指令重叠执行；冒险与分支是限制指令级并行的主要因素。',
  },
  fundamentals_simd: {
    image: 'diagram_fund_simd.webp',
    alt: '标量与 SIMD 向量化对比',
    title: 'SIMD：一条指令处理多个数据',
    type: 'compare',
    columns: [
      { title: '标量执行', items: ['一次处理一个元素', '循环开销占比高', '依赖分支预测', '代码直观易读', '优化空间有限'] },
      { title: 'SIMD 向量化', items: ['一条指令处理 4-16 个元素', '需数据连续对齐', '要处理尾部剩余元素', '注意别名与依赖', '编译器可自动向量化'] },
    ],
    notes: ['先保证正确性，再用基准验证加速比'],
    caption: '向量化把数据并行交给硬件；数据布局是否连续，往往决定编译器能否自动向量化。',
  },
  fundamentals_embedded_iot: {
    image: 'diagram_fund_iot.webp',
    alt: '嵌入式与 IoT 的层次结构',
    title: '嵌入式与 IoT：传感、控制、通信、云',
    type: 'layers',
    widths: [0.55, 0.75, 0.9, 1],
    layers: [
      { title: '传感器与执行器', desc: '采集物理量或驱动设备' },
      { title: 'MCU 与实时系统', desc: '中断、定时器、低功耗与实时约束' },
      { title: '通信协议', desc: 'MQTT、CoAP、BLE 与 LoRa' },
      { title: '云平台与数据', desc: '设备管理、时序存储、规则与告警' },
    ],
    caption: '嵌入式关注资源与实时性，IoT 关注连接与运维；两者共同决定端到端可靠性。',
  },
  fundamentals_architecture_case: {
    image: 'diagram_fund_arch_case.webp',
    alt: '体系结构设计的权衡过程',
    title: '体系结构综合案例：需求、选型、权衡、验证',
    type: 'flow',
    steps: [
      { title: '明确需求', desc: '负载特征与约束条件' },
      { title: '方案选型', desc: '多核、缓存、指令集扩展' },
      { title: '权衡取舍', desc: '面积、功耗、性能与成本' },
      { title: '验证评估', desc: '基准测试与瓶颈分析' },
    ],
    caption: '体系结构没有银弹：每一项性能收益都要用面积、功耗或复杂度来交换。',
  },
  computer_organization_intro: {
    image: 'diagram_fund_org_intro.webp',
    alt: '计算机组成的基本结构',
    title: '计算机组成：输入、CPU、内存、输出',
    type: 'flow',
    steps: [
      { title: '输入设备', desc: '键盘、传感器把信号送入' },
      { title: 'CPU', desc: '控制器调度，运算器计算' },
      { title: '内存与存储', desc: '存放指令与数据' },
      { title: '输出设备', desc: '屏幕、网络返回结果' },
    ],
    notes: ['冯·诺依曼结构：程序与数据同样存储'],
    caption: '计算机由五大部件构成；理解数据在部件之间的流动，是学习体系结构的起点。',
  },
  binary_intro: {
    image: 'diagram_fund_binary_intro.webp',
    alt: '二进制入门四步',
    title: '二进制入门：状态、位、字节、转换',
    type: 'flow',
    steps: [
      { title: '两种状态', desc: '通断电对应 1 与 0' },
      { title: '位', desc: '最小信息单位' },
      { title: '字节', desc: '8 位组合表示更多值' },
      { title: '转换', desc: '按权展开或除 2 取余' },
    ],
    notes: ['1 字节可以表示 256 种状态'],
    caption: '二进制不是计算机的偏好，而是物理实现的必然；一切数据最终都是 0 和 1 的组合。',
  },
};
