// P5 C# 课程配图数据。
module.exports = {
  csharp_basics: {
    image: 'diagram_cs_platform.webp',
    alt: 'C# 从源码到 CLR 运行的分层',
    title: 'C# 与 .NET：源码如何运行',
    type: 'layers',
    layers: [
      { title: 'C# 源码', desc: '类、命名空间与项目文件组织代码', fill: '#eef4ff', stroke: '#6c8ff8' },
      { title: '编译为 IL', desc: '中间语言与元数据，平台无关', fill: '#e8f2ff', stroke: '#6c8ff8' },
      { title: 'CLR 运行时', desc: 'JIT 编译、GC 与类型安全', fill: '#e6f7f1', stroke: '#3fae8a' },
      { title: '基础类库', desc: '集合、IO、网络与 LINQ 统一 API', fill: '#fff4e6', stroke: '#e6a23c' },
      { title: 'dotnet CLI', desc: 'new、build、run、test、publish', fill: '#fdeeee', stroke: '#d97070' },
    ],
    widths: [0.7, 0.82, 0.9, 1, 0.88],
    caption: '.NET 用 IL 与 CLR 实现跨平台：一次编译，由运行时负责本地化与内存管理。',
  },
  csharp_dotnet_first: {
    image: 'diagram_cs_first.webp',
    alt: '创建并运行第一个 C# 项目',
    title: '第一个程序：dotnet CLI 三步走',
    type: 'flow',
    steps: [
      { title: '创建项目', desc: 'dotnet new console -o HelloApp' },
      { title: '编写代码', desc: '在 Program.cs 中输出内容' },
      { title: '运行项目', desc: 'dotnet run 编译并启动' },
      { title: '发布产物', desc: 'dotnet publish 生成部署文件' },
    ],
    notes: ['项目文件 .csproj 声明目标框架与依赖'],
    caption: 'dotnet CLI 把创建、构建、测试与发布统一到一条工具链上。',
  },
  csharp_variables_input: {
    image: 'diagram_cs_variables.webp',
    alt: 'C# 变量、类型与输入转换',
    title: '变量与输入：类型与可空性',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['var 推断', '值类型', '可空类型', '输入转换'],
    colLabels: ['写法', '含义', '注意点'],
    cells: [
      { r: 0, c: 0, text: 'var name = "Ada";' },
      { r: 0, c: 1, text: '编译期推断具体类型' },
      { r: 0, c: 2, text: '仍是静态类型，不是动态' },
      { r: 1, c: 0, text: 'int、double、bool、char' },
      { r: 1, c: 1, text: '直接保存值，复制即独立' },
      { r: 1, c: 2, text: '注意默认值与数值范围' },
      { r: 2, c: 0, text: 'int? age = null;' },
      { r: 2, c: 1, text: '值类型也可以缺失' },
      { r: 2, c: 2, text: '使用前要判空或取值' },
      { r: 3, c: 0, text: 'int.TryParse(text, out var n)' },
      { r: 3, c: 1, text: '安全解析失败返回 false' },
      { r: 3, c: 2, text: '不要用 Convert 硬转换' },
    ],
    notes: ['开启可空引用类型后，编译器会提示潜在空引用'],
    caption: 'C# 强调静态类型与显式可空：把「可能没有值」写进类型里。',
  },
  csharp_types: {
    image: 'diagram_cs_types.webp',
    alt: '值类型与引用类型的差异',
    title: '值类型与引用类型：复制行为不同',
    type: 'compare',
    columns: [
      { title: '值类型', items: ['struct、int、double、bool、enum', '赋值复制整个值', '通常分配在栈或内联存储', '默认不可为 null，除非用 Nullable', '相等比较默认按值'] },
      { title: '引用类型', items: ['class、string、数组、委托、接口', '赋值复制引用，指向同一对象', '对象分配在托管堆', '默认可以为 null', '相等比较默认按引用'] },
    ],
    notes: ['string 是引用类型但具有值语义；不可变且支持驻留'],
    caption: '选择值类型还是引用类型，本质是选择复制语义与身份语义。',
  },
  csharp_conditions: {
    image: 'diagram_cs_conditions.webp',
    alt: 'C# 条件分支与模式匹配',
    title: '条件判断：if、switch 与模式',
    type: 'grid',
    rows: 3,
    cols: 3,
    rowLabels: ['if / else', 'switch 表达式', '模式匹配'],
    colLabels: ['写法', '优势', '注意点'],
    cells: [
      { r: 0, c: 0, text: 'if (score >= 60)' },
      { r: 0, c: 1, text: '普通范围与布尔判断' },
      { r: 0, c: 2, text: '避免深层嵌套' },
      { r: 1, c: 0, text: 'var level = score switch { ... };' },
      { r: 1, c: 1, text: '表达式返回结果，更紧凑' },
      { r: 1, c: 2, text: '要覆盖默认分支' },
      { r: 2, c: 0, text: 'obj is User { Age: > 18 } u' },
      { r: 2, c: 1, text: '同时判断类型与属性' },
      { r: 2, c: 2, text: '顺序会影响匹配结果' },
    ],
    notes: ['switch 表达式要求所有分支返回兼容类型'],
    caption: '模式匹配把类型检查、解构与条件合并，让分支更接近业务语义。',
  },
  csharp_loops: {
    image: 'diagram_cs_loops.webp',
    alt: 'C# 三种循环结构',
    title: '循环：for、foreach 与 while',
    type: 'grid',
    rows: 3,
    cols: 3,
    rowLabels: ['for', 'foreach', 'while'],
    colLabels: ['适用场景', '写法', '注意点'],
    cells: [
      { r: 0, c: 0, text: '已知次数或需要索引' },
      { r: 0, c: 1, text: 'for (int i = 0; i < n; i++)' },
      { r: 0, c: 2, text: '边界与索引越界' },
      { r: 1, c: 0, text: '遍历集合与数组' },
      { r: 1, c: 1, text: 'foreach (var item in items)' },
      { r: 1, c: 2, text: '不要边遍历边修改集合' },
      { r: 2, c: 0, text: '条件驱动，次数未知' },
      { r: 2, c: 1, text: 'while (condition) { }' },
      { r: 2, c: 2, text: '确保循环变量会变化' },
    ],
    notes: ['LINQ 可以替代许多显式循环，让意图更清晰'],
    caption: '循环要写清终止条件与迭代变量；能用集合操作表达时优先用它。',
  },
  csharp_methods_intro: {
    image: 'diagram_cs_methods.webp',
    alt: 'C# 方法的参数与返回值',
    title: '方法入门：参数、返回值与可选参数',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['返回值', '可选参数', '命名参数', '表达式方法'],
    colLabels: ['写法', '作用', '注意点'],
    cells: [
      { r: 0, c: 0, text: 'int Add(int a, int b)' },
      { r: 0, c: 1, text: '返回值类型写在方法名前' },
      { r: 0, c: 2, text: 'void 表示无返回值' },
      { r: 1, c: 0, text: 'string Greet(string name = "World")' },
      { r: 1, c: 1, text: '调用时可省略参数' },
      { r: 1, c: 2, text: '默认值必须是编译期常量' },
      { r: 2, c: 0, text: 'Greet(name: "Ada")' },
      { r: 2, c: 1, text: '按名字传参，提升可读性' },
      { r: 2, c: 2, text: '位置参数要写在前面' },
      { r: 3, c: 0, text: 'int Square(int x) => x * x;' },
      { r: 3, c: 1, text: '单表达式方法更简洁' },
      { r: 3, c: 2, text: '复杂逻辑仍用方法体' },
    ],
    notes: ['方法名用动词短语，参数名表达含义，返回值表达结果'],
    caption: '方法签名是调用契约：参数默认值、重载与命名参数都在扩大接口的表达力。',
  },
  csharp_control_methods: {
    image: 'diagram_cs_control_methods.webp',
    alt: '控制流与参数修饰符、迭代器',
    title: '控制流与方法：修饰符与迭代器',
    type: 'compare',
    columns: [
      { title: '参数修饰符', items: ['ref 传入并可能修改原变量', 'out 用于返回多个结果', 'in 只读引用减少拷贝', 'params 接收可变数量参数', '修饰符要体现在调用处'] },
      { title: '迭代器与模式', items: ['yield return 惰性产出序列', 'yield break 提前结束', '方法可返回 IEnumerable<T>', 'switch 表达式做分支选择', '局部函数拆分复杂方法'] },
    ],
    notes: ['out 参数在方法返回前必须赋值'],
    caption: 'C# 的方法既能表达数据流（迭代器），也能表达引用语义（ref/out/in）。',
  },
  csharp_oop: {
    image: 'diagram_cs_oop.webp',
    alt: 'C# 类型系统的对象建模方式',
    title: '类与对象：属性、记录与静态成员',
    type: 'layers',
    layers: [
      { title: '类与封装', desc: '私有字段、公有方法与访问控制', fill: '#eef4ff', stroke: '#6c8ff8' },
      { title: '属性', desc: 'get/set、init 与只读计算属性', fill: '#e8f2ff', stroke: '#6c8ff8' },
      { title: '对象初始化器', desc: 'new User { Name = "Ada" }', fill: '#e6f7f1', stroke: '#3fae8a' },
      { title: 'record', desc: '值相等、with 复制与不可变数据', fill: '#fff4e6', stroke: '#e6a23c' },
      { title: '静态成员', desc: '属于类型而非实例的工具与常量', fill: '#fdeeee', stroke: '#d97070' },
    ],
    widths: [0.72, 0.82, 0.9, 1, 0.88],
    caption: 'class 表达有身份的对象，record 表达以值相等的数据；按语义选择类型。',
  },
  csharp_inheritance: {
    image: 'diagram_cs_inheritance.webp',
    alt: '继承、接口与多态关系',
    title: '继承与多态：复用行为，解耦契约',
    type: 'tree',
    root: {
      text: '基类 / 接口',
      children: [
        {
          text: '抽象类',
          children: [
            { text: '共享实现' },
            { text: '可定义抽象成员' },
          ],
        },
        {
          text: '接口',
          children: [
            { text: '定义能力契约' },
            { text: '一个类可实现多个' },
          ],
        },
        {
          text: '多态调用',
          children: [
            { text: 'virtual / override' },
            { text: '运行时选择实现' },
          ],
        },
      ],
    },
    notes: ['优先组合与接口，深度继承会让修改成本快速上升'],
    caption: '继承解决「是什么」，接口解决「能做什么」；多态让调用方依赖抽象而非实现。',
  },
  csharp_records_patterns: {
    image: 'diagram_cs_records_patterns.webp',
    alt: 'record 与模式匹配的配合',
    title: 'Record 与模式：表达不可变数据',
    type: 'compare',
    columns: [
      { title: 'record', items: ['值相等按属性比较', 'with 表达式生成修改副本', '可声明为不可变数据', '适合 DTO、事件与领域值', '注意与类的相等语义差异'] },
      { title: '模式匹配', items: ['属性模式直接解构对象', '位置模式按构造参数匹配', '列表模式匹配序列形状', 'switch 表达式穷尽分支', '让非法状态尽早暴露'] },
    ],
    notes: ['不可变数据配合模式匹配，能显著减少状态修改带来的缺陷'],
    caption: 'record 描述「是什么值」，模式匹配描述「如何分支处理」，两者天然互补。',
  },
  csharp_collections_linq: {
    image: 'diagram_cs_collections_linq.webp',
    alt: '集合类型与 LINQ 的选型',
    title: '集合与 LINQ：选择合适的数据结构',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['List', 'Dictionary', 'HashSet', 'LINQ'],
    colLabels: ['结构', '复杂度', '适用场景'],
    cells: [
      { r: 0, c: 0, text: '动态数组' },
      { r: 0, c: 1, text: '索引 O(1)，查找 O(n)' },
      { r: 0, c: 2, text: '有序列表与批量遍历' },
      { r: 1, c: 0, text: '哈希键值映射' },
      { r: 1, c: 1, text: '查找插入平均 O(1)' },
      { r: 1, c: 2, text: '按 key 快速访问' },
      { r: 2, c: 0, text: '哈希集合' },
      { r: 2, c: 1, text: '去重与包含判断 O(1)' },
      { r: 2, c: 2, text: '集合运算与唯一性' },
      { r: 3, c: 0, text: '查询表达式与方法链' },
      { r: 3, c: 1, text: '延迟执行，注意枚举次数' },
      { r: 3, c: 2, text: '过滤、投影与聚合' },
    ],
    notes: ['LINQ 查询是延迟的，枚举多次会重复执行；必要时先 ToList'],
    caption: '先选集合保证复杂度，再用 LINQ 表达转换意图，两者不要互相替代。',
  },
  csharp_async: {
    image: 'diagram_cs_async.webp',
    alt: 'async/await 的调用链与取消',
    title: '异步编程：Task、await 与取消',
    type: 'sequence',
    actors: ['调用方', 'async 方法', 'Task 调度', 'IO 资源'],
    messages: [
      { from: 0, to: 1, label: '调用并传入取消令牌' },
      { from: 1, to: 2, label: '启动异步操作' },
      { from: 2, to: 3, label: '发起网络或磁盘 IO' },
      { from: 3, to: 2, label: 'IO 完成回调' },
      { from: 2, to: 1, label: '恢复执行并返回结果' },
      { from: 1, to: 0, label: '传播异常或取消' },
    ],
    notes: ['async 方法内部不要用 Task.Wait 或 .Result 阻塞线程'],
    caption: '异步的价值是释放线程等待 IO；取消令牌让长任务可以被及时终止。',
  },
  csharp_ecosystem: {
    image: 'diagram_cs_ecosystem.webp',
    alt: '.NET 生态的关键组成',
    title: '.NET 生态：包、测试与 Web',
    type: 'layers',
    layers: [
      { title: 'NuGet', desc: '包管理与版本锁定', fill: '#eef4ff', stroke: '#6c8ff8' },
      { title: 'xUnit', desc: '单元测试与断言', fill: '#e8f2ff', stroke: '#6c8ff8' },
      { title: 'ASP.NET Core', desc: '最小 API、中间件与依赖注入', fill: '#e6f7f1', stroke: '#3fae8a' },
      { title: 'EF Core', desc: '对象关系映射与迁移', fill: '#fff4e6', stroke: '#e6a23c' },
      { title: '发布部署', desc: '容器、配置与健康检查', fill: '#fdeeee', stroke: '#d97070' },
    ],
    widths: [0.7, 0.78, 0.92, 1, 0.86],
    caption: '现代 .NET 开发围绕依赖注入、配置与测试展开；框架负责管线，业务保持清晰。',
  },
  csharp_project: {
    image: 'diagram_cs_webapi_project.webp',
    alt: 'Web API 与 EF Core 的请求链路',
    title: '实战 Web API：请求到数据库',
    type: 'sequence',
    actors: ['客户端', '最小 API', 'DbContext', '数据库'],
    messages: [
      { from: 0, to: 1, label: '发送 JSON 请求' },
      { from: 1, to: 1, label: '模型绑定与校验' },
      { from: 1, to: 2, label: '查询或更新实体' },
      { from: 2, to: 3, label: '生成 SQL 并执行' },
      { from: 3, to: 2, label: '返回结果集' },
      { from: 2, to: 0, label: '映射 DTO 并响应' },
    ],
    notes: ['测试用内存数据库或容器化数据库，避免依赖开发环境'],
    caption: 'API 层负责协议与校验，DbContext 负责持久化；边界清晰才好测试与演进。',
  },
  csharp_project_inventory_cli: {
    image: 'diagram_cs_inventory_cli.webp',
    alt: '库存管理 CLI 的实现流程',
    title: '实战库存 CLI：命令到持久化',
    type: 'flow',
    steps: [
      { title: '定义命令', desc: 'System.CommandLine 声明子命令与参数' },
      { title: '参数校验', desc: '检查数量、ID 与必填项' },
      { title: 'SQLite 操作', desc: '参数化语句完成增删改查' },
      { title: 'xUnit 测试', desc: '覆盖库存不足、重复与并发更新' },
    ],
    notes: ['库存扣减要放在事务中并校验影响行数'],
    caption: 'CLI 的可靠性来自参数校验、事务边界与可重复的测试。',
  },
  csharp_project_blazor_admin: {
    image: 'diagram_cs_blazor_admin.webp',
    alt: 'Blazor 管理后台的数据流',
    title: '实战 Blazor 后台：组件与实时刷新',
    type: 'sequence',
    actors: ['浏览器', 'Blazor 组件', 'EF Core', 'SignalR'],
    messages: [
      { from: 0, to: 1, label: '提交表单与分页请求' },
      { from: 1, to: 2, label: '查询订单数据' },
      { from: 2, to: 1, label: '返回分页结果' },
      { from: 3, to: 1, label: '推送订单状态变更' },
      { from: 1, to: 0, label: '局部刷新列表' },
      { from: 0, to: 1, label: '表单校验失败提示' },
    ],
    notes: ['服务端渲染与交互模式要按页面需求选择'],
    caption: 'Blazor 把组件、数据访问与实时推送组合在同一技术栈内，适合内部管理后台。',
  },
};
