// P5 C++ 课程配图数据。
module.exports = {
  cpp_basics: {
    image: 'diagram_cpp_build.webp',
    alt: 'C++ 从源码到可执行文件的四个阶段',
    title: '编译流程：预处理到链接',
    type: 'flow',
    steps: [
      { title: '预处理', desc: '展开宏与头文件，生成翻译单元' },
      { title: '编译', desc: '语法分析、优化并生成汇编' },
      { title: '汇编', desc: '把汇编翻译成目标文件' },
      { title: '链接', desc: '合并目标文件与库，解析符号' },
    ],
    notes: ['头文件放声明，源文件放定义，用 include guard 防止重复包含'],
    caption: '理解四个阶段，才能读懂「找不到符号」「重复定义」这类链接错误。',
  },
  cpp_first_program: {
    image: 'diagram_cpp_first_program.webp',
    alt: 'C++ 最小程序的编译与运行',
    title: '第一个程序：从源文件到运行',
    type: 'flow',
    steps: [
      { title: '#include', desc: '引入 iostream 等标准库头文件' },
      { title: 'main 函数', desc: '程序入口，返回 int 状态码' },
      { title: '编译', desc: 'g++ main.cpp -o app -std=c++20' },
      { title: '运行', desc: '执行可执行文件并查看输出' },
    ],
    notes: ['开启 -Wall -Wextra 能在入门阶段发现大量隐患'],
    caption: 'C++ 没有虚拟机：源码必须显式编译链接为当前平台的可执行文件。',
  },
  cpp_variables_io: {
    image: 'diagram_cpp_variables.webp',
    alt: 'C++ 变量、类型与输入输出',
    title: '变量与输入输出：类型先行',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['基本类型', 'auto 推断', 'const 常量', '输入输出'],
    colLabels: ['写法', '特点', '注意点'],
    cells: [
      { r: 0, c: 0, text: 'int、double、bool、char' },
      { r: 0, c: 1, text: '平台相关的宽度与范围' },
      { r: 0, c: 2, text: '优先用 fixed width 类型' },
      { r: 1, c: 0, text: 'auto count = 0;' },
      { r: 1, c: 1, text: '由初始化表达式推断' },
      { r: 1, c: 2, text: '不要滥用 auto 隐藏类型' },
      { r: 2, c: 0, text: 'constexpr int kMax = 100;' },
      { r: 2, c: 1, text: '编译期常量，可优化' },
      { r: 2, c: 2, text: '能 const 就不要可写' },
      { r: 3, c: 0, text: 'std::cin / std::cout' },
      { r: 3, c: 1, text: '类型安全的流式 IO' },
      { r: 3, c: 2, text: '检查输入失败状态' },
    ],
    notes: ['整数溢出与未初始化变量是 C++ 中最常见的两类未定义行为'],
    caption: 'C++ 把控制权交给程序员，也把初始化、范围和生命周期责任一并交出。',
  },
  cpp_types: {
    image: 'diagram_cpp_types.webp',
    alt: '值类型、转换与常量正确性',
    title: '类型与转换：把未定义行为挡在门外',
    type: 'compare',
    columns: [
      { title: '类型与值', items: ['基本类型宽度与平台相关', '用固定宽度类型表达协议', 'auto 推断但保留引用与 const', 'constexpr 表达编译期常量', '注意有符号与无符号混用'] },
      { title: '类型转换', items: ['隐式转换可能丢失精度', '用 static_cast 表达明确意图', 'dynamic_cast 用于多态安全向下转换', 'const_cast 只用于兼容旧接口', 'reinterpret_cast 极少使用'] },
    ],
    notes: ['未定义行为包括越界、悬垂引用、有符号溢出与数据竞争'],
    caption: 'C++ 的类型安全依赖纪律：转换要写明意图，范围要提前检查。',
  },
  cpp_conditions: {
    image: 'diagram_cpp_conditions.webp',
    alt: 'C++ 条件分支的常见写法',
    title: '条件判断：if、switch 与三元表达式',
    type: 'grid',
    rows: 3,
    cols: 3,
    rowLabels: ['if / else', 'switch', '三元表达式'],
    colLabels: ['适用场景', '写法要点', '常见陷阱'],
    cells: [
      { r: 0, c: 0, text: '范围与布尔条件' },
      { r: 0, c: 1, text: '条件表达式直接返回 bool' },
      { r: 0, c: 2, text: '赋值写成 == 的判断' },
      { r: 1, c: 0, text: '离散枚举值的多分支' },
      { r: 1, c: 1, text: '每个 case 后写 break' },
      { r: 1, c: 2, text: '忘记 default 漏掉新枚举' },
      { r: 2, c: 0, text: '简单二选一取值' },
      { r: 2, c: 1, text: '两个分支类型要兼容' },
      { r: 2, c: 2, text: '嵌套过深影响可读性' },
    ],
    notes: ['switch 的 case 标签必须是编译期常量'],
    caption: '分支写法本身不难，难的是穷尽所有状态并让非法状态无法表示。',
  },
  cpp_loops: {
    image: 'diagram_cpp_loops.webp',
    alt: 'C++ 循环的四种形态',
    title: '循环：for、while 与范围遍历',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['for', 'while', 'do-while', '范围 for'],
    colLabels: ['写法', '适用场景', '注意点'],
    cells: [
      { r: 0, c: 0, text: 'for (int i = 0; i < n; ++i)' },
      { r: 0, c: 1, text: '已知次数或索引遍历' },
      { r: 0, c: 2, text: '注意边界是 < 还是 <=' },
      { r: 1, c: 0, text: 'while (cond) { }' },
      { r: 1, c: 1, text: '条件驱动，次数未知' },
      { r: 1, c: 2, text: '确保条件最终会变假' },
      { r: 2, c: 0, text: 'do { } while (cond);' },
      { r: 2, c: 1, text: '至少执行一次' },
      { r: 2, c: 2, text: '不要漏掉结尾分号' },
      { r: 3, c: 0, text: 'for (auto& x : items)' },
      { r: 3, c: 1, text: '遍历容器元素' },
      { r: 3, c: 2, text: '修改元素要用引用' },
    ],
    notes: ['循环内修改容器大小可能导致迭代器失效'],
    caption: '循环的正确性取决于边界与不变量：写之前先说清「每次迭代后什么为真」。',
  },
  cpp_functions_intro: {
    image: 'diagram_cpp_functions_intro.webp',
    alt: '值传递与引用传递的差异',
    title: '函数：值传递、引用传递与返回值',
    type: 'compare',
    columns: [
      { title: '参数传递', items: ['值传递复制一份，修改不影响原值', '引用传递可修改实参', 'const 引用避免大对象拷贝', '指针传递可表达可空', '默认参数只能写在声明处'] },
      { title: '返回值与拆分', items: ['返回 void 表示只产生副作用', '返回引用要保证生命周期', '结构化绑定接收多个返回值', '函数保持单一职责便于测试', '用 lambda 表达局部行为'] },
    ],
    notes: ['返回局部变量的引用或指针是悬垂引用，属于未定义行为'],
    caption: '函数接口要表达意图：是否修改参数、是否可空、返回值是否可能失效。',
  },
  cpp_control_functions: {
    image: 'diagram_cpp_control_functions.webp',
    alt: '控制流与函数特性的组合',
    title: '控制流与函数：重载、默认参数与 lambda',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['函数重载', '默认参数', 'lambda', '返回值'],
    colLabels: ['作用', '写法', '注意点'],
    cells: [
      { r: 0, c: 0, text: '同名函数按参数区分' },
      { r: 0, c: 1, text: 'void print(int); void print(string);' },
      { r: 0, c: 2, text: '避免仅靠返回值重载' },
      { r: 1, c: 0, text: '为常用参数提供默认值' },
      { r: 1, c: 1, text: 'void log(string msg = "ok")' },
      { r: 1, c: 2, text: '默认参数写在末尾' },
      { r: 2, c: 0, text: '就地定义短小函数对象' },
      { r: 2, c: 1, text: '[&](int x) { return x * 2; }' },
      { r: 2, c: 2, text: '按需捕获，避免悬垂' },
      { r: 3, c: 0, text: '返回结果或错误码' },
      { r: 3, c: 1, text: 'std::optional<T>' },
      { r: 3, c: 2, text: '用调用方检查代替魔法值' },
    ],
    notes: ['重载解析规则复杂，参数类型差异过大会降低可读性'],
    caption: 'C++ 提供丰富的函数表达方式，团队需要约定边界，避免接口难以理解。',
  },
  cpp_pointers: {
    image: 'diagram_cpp_pointers.webp',
    alt: '指针与引用的语义对比',
    title: '指针与引用：两种间接方式',
    type: 'compare',
    columns: [
      { title: '指针', items: ['保存地址，可为 nullptr', '可以重新指向其他对象', '支持指针运算与数组遍历', '需要显式解引用 *p', '所有权归属必须写清楚'] },
      { title: '引用', items: ['对象的别名，必须初始化', '不能重新绑定到其他对象', '使用语法与对象一致', 'const 引用可延长临时对象生命', '返回值引用要检查生命周期'] },
    ],
    notes: ['优先用引用表达「必然存在」，用指针表达「可能为空」'],
    caption: '现代 C++ 先用引用与智能指针表达意图，裸指针主要用于观察而非拥有。',
  },
  cpp_oop: {
    image: 'diagram_cpp_oop.webp',
    alt: 'C++ 面向对象的五个层次',
    title: '类与对象：从封装到多态',
    type: 'layers',
    layers: [
      { title: '封装', desc: '私有数据、公有接口，维护类不变量', fill: '#eef4ff', stroke: '#6c8ff8' },
      { title: '构造与析构', desc: 'RAII 管理资源，析构自动释放', fill: '#e8f2ff', stroke: '#6c8ff8' },
      { title: '继承', desc: '复用与分类，优先组合而非深度继承', fill: '#e6f7f1', stroke: '#3fae8a' },
      { title: '虚函数多态', desc: '基类指针调用派生实现，析构函数要虚', fill: '#fff4e6', stroke: '#e6a23c' },
      { title: '运算符与拷贝控制', desc: '三/五法则，明确拷贝与移动语义', fill: '#fdeeee', stroke: '#d97070' },
    ],
    widths: [0.7, 0.84, 0.9, 1, 0.96],
    caption: 'C++ 面向对象的核心不是继承，而是用类型封装不变量并自动管理资源。',
  },
  cpp_templates: {
    image: 'diagram_cpp_templates.webp',
    alt: 'C++ 模板编程的五个层次',
    title: '模板：从函数模板到可变参数',
    type: 'layers',
    layers: [
      { title: '函数模板', desc: '一套逻辑适配多种参数类型', fill: '#eef4ff', stroke: '#6c8ff8' },
      { title: '类模板', desc: '容器与泛型数据结构的基础', fill: '#e8f2ff', stroke: '#6c8ff8' },
      { title: '特化与偏特化', desc: '为特定类型提供定制实现', fill: '#e6f7f1', stroke: '#3fae8a' },
      { title: 'type traits', desc: '在编译期查询与转换类型', fill: '#fff4e6', stroke: '#e6a23c' },
      { title: '可变参数模板', desc: '递归展开参数包，实现通用转发', fill: '#fdeeee', stroke: '#d97070' },
    ],
    widths: [0.72, 0.82, 0.9, 1, 0.94],
    notes: ['模板错误信息很长：用 Concepts 提前约束能显著改善可读性'],
    caption: '模板把类型变成参数，换来零成本抽象，代价是编译时间与错误信息复杂度。',
  },
  cpp_concepts_ranges: {
    image: 'diagram_cpp_concepts_ranges.webp',
    alt: 'Concepts 与 Ranges 的职责对比',
    title: 'Concepts 与 Ranges：约束与管道',
    type: 'compare',
    columns: [
      { title: 'Concepts', items: ['给模板参数起约束名字', 'requires 表达式描述能力', '错误信息更贴近调用点', '可组合多个 concept', '替代 SFINAE 的复杂技巧'] },
      { title: 'Ranges', items: ['range 适配器组合数据管道', 'view 是惰性、不拥有数据', 'filter、transform、take', '可读性接近函数式风格', '注意迭代器与生命周期'] },
    ],
    notes: ['惰性 view 不产生中间容器，但悬垂引用风险也更隐蔽'],
    caption: 'Concepts 约束模板输入，Ranges 组合数据转换，二者共同提升泛型代码的可读性。',
  },
  cpp_stl: {
    image: 'diagram_cpp_stl.webp',
    alt: 'STL 容器、迭代器与算法的选择',
    title: 'STL：容器与算法的正确组合',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['vector', 'map / set', 'unordered', '算法库'],
    colLabels: ['结构', '复杂度', '适用场景'],
    cells: [
      { r: 0, c: 0, text: '连续动态数组' },
      { r: 0, c: 1, text: '随机访问 O(1)，尾部插入均摊 O(1)' },
      { r: 0, c: 2, text: '默认首选容器' },
      { r: 1, c: 0, text: '有序树结构' },
      { r: 1, c: 1, text: '查找插入 O(log n)' },
      { r: 1, c: 2, text: '需要有序遍历与范围查询' },
      { r: 2, c: 0, text: '哈希表' },
      { r: 2, c: 1, text: '平均 O(1)，最坏 O(n)' },
      { r: 2, c: 2, text: '只需精确查找与去重' },
      { r: 3, c: 0, text: 'std::sort、find_if' },
      { r: 3, c: 1, text: '与迭代器解耦的通用算法' },
      { r: 3, c: 2, text: 'erase-remove 惯用法' },
    ],
    notes: ['vector 的迭代器在扩容后可能失效，erase 后也要重新获取'],
    caption: '先选容器再选算法：复杂度、迭代器稳定性与内存布局共同决定性能。',
  },
  cpp_modern: {
    image: 'diagram_cpp_modern.webp',
    alt: '现代 C++ 的关键特性',
    title: '现代 C++：让资源与表达更安全',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['移动语义', '结构化绑定', '可选与变体', 'Ranges 与并发'],
    colLabels: ['解决的问题', '关键写法', '实践建议'],
    cells: [
      { r: 0, c: 0, text: '避免不必要的深拷贝' },
      { r: 0, c: 1, text: 'std::move、右值引用' },
      { r: 0, c: 2, text: 'move 后对象状态要明确' },
      { r: 1, c: 0, text: '一次解包多个返回值' },
      { r: 1, c: 1, text: 'auto [id, name] = pair' },
      { r: 1, c: 2, text: '引用绑定注意生命周期' },
      { r: 2, c: 0, text: '表达可能为空或多种类型' },
      { r: 2, c: 1, text: 'std::optional、std::variant' },
      { r: 2, c: 2, text: '用 std::visit 穷尽分支' },
      { r: 3, c: 0, text: '惰性管道与并行算法' },
      { r: 3, c: 1, text: 'views、execution policy' },
      { r: 3, c: 2, text: '并发下注意数据竞争' },
    ],
    notes: ['现代 C++ 的核心方向：用类型和 RAII 把资源错误变成编译错误'],
    caption: '新特性不是目的：用移动语义减少拷贝，用 optional/variant 表达状态，用 RAII 管资源。',
  },
  cpp_tooling: {
    image: 'diagram_cpp_tooling.webp',
    alt: 'C++ 工程工具链的五个环节',
    title: '工程工具链：构建、依赖与调试',
    type: 'layers',
    layers: [
      { title: 'CMake', desc: '声明目标、依赖与编译选项', fill: '#eef4ff', stroke: '#6c8ff8' },
      { title: '包管理', desc: 'vcpkg 或 conan 管理第三方依赖', fill: '#e8f2ff', stroke: '#6c8ff8' },
      { title: '调试器', desc: 'gdb/lldb 断点、调用栈与变量查看', fill: '#e6f7f1', stroke: '#3fae8a' },
      { title: 'Sanitizer', desc: 'ASan、UBSan、TSan 检测内存与并发错误', fill: '#fff4e6', stroke: '#e6a23c' },
      { title: '单元测试', desc: 'Catch2 或 GoogleTest 覆盖模块行为', fill: '#fdeeee', stroke: '#d97070' },
    ],
    widths: [0.72, 0.84, 0.9, 1, 0.9],
    caption: 'C++ 工程化的关键是把构建、依赖、调试与检查标准化，减少环境差异。',
  },
  cpp_project: {
    image: 'diagram_cpp_project.webp',
    alt: 'CMake 多文件项目的组织方式',
    title: '实战：CMake 多文件项目',
    type: 'flow',
    steps: [
      { title: '目录分层', desc: 'include 放声明，src 放实现' },
      { title: '构建静态库', desc: 'add_library 抽取可复用模块' },
      { title: '接入测试', desc: 'CTest 注册并运行单元测试' },
      { title: '开启 Sanitizer', desc: 'CI 与本地用不同构建类型检查' },
    ],
    notes: ['编译选项用 target_* 传播，避免全局变量污染'],
    caption: 'CMake 的目标式写法把依赖、包含路径与编译选项绑定到具体库，项目越大收益越明显。',
  },
  cpp_project_http: {
    image: 'diagram_cpp_http_project.webp',
    alt: 'C++ HTTP JSON 服务的请求链路',
    title: '实战 HTTP 服务：请求到响应',
    type: 'sequence',
    actors: ['客户端', 'HTTP 路由', 'JSON 校验', '业务处理'],
    messages: [
      { from: 0, to: 1, label: '发送 HTTP 请求' },
      { from: 1, to: 2, label: '解析路径与请求体' },
      { from: 2, to: 1, label: '校验字段与类型' },
      { from: 1, to: 3, label: '调用业务函数' },
      { from: 3, to: 1, label: '返回结果或错误码' },
      { from: 1, to: 0, label: '序列化 JSON 响应' },
    ],
    notes: ['错误响应也要结构化：code、message 与必要上下文'],
    caption: 'C++ 服务同样需要边界校验、统一错误与测试，语言不改变工程原则。',
  },
  cpp_project_taskdb: {
    image: 'diagram_cpp_taskdb_project.webp',
    alt: '任务数据库 CLI 的实现流程',
    title: '实战任务库 CLI：从参数到持久化',
    type: 'flow',
    steps: [
      { title: '解析参数', desc: '识别 add、list、done、remove 子命令' },
      { title: '打开数据库', desc: 'SQLite 连接与建表迁移' },
      { title: '执行 CRUD', desc: '参数化语句避免注入' },
      { title: '测试与错误', desc: '覆盖空输入、重复 ID 与事务失败' },
    ],
    notes: ['CLI 的退出码与错误信息要和参数一样稳定'],
    caption: 'C++20 与 SQLite 的组合覆盖了真实工具的核心：解析、持久化、错误与测试。',
  },
};
