// P5 Go 课程配图数据。
module.exports = {
  go_basics: {
    image: 'diagram_go_basics.webp',
    alt: 'Go 语言的核心特征',
    title: 'Go 基础：简洁、并发与显式错误',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['包与工具链', '变量与函数', '并发模型', '错误处理'],
    colLabels: ['核心概念', '写法', '设计取舍'],
    cells: [
      { r: 0, c: 0, text: 'go mod 管理依赖' },
      { r: 0, c: 1, text: 'go run / go build / go test' },
      { r: 0, c: 2, text: '标准工具链开箱即用' },
      { r: 1, c: 0, text: '静态类型，显式声明' },
      { r: 1, c: 1, text: 'func、短变量声明 :=' },
      { r: 1, c: 2, text: '少语法糖，可读优先' },
      { r: 2, c: 0, text: 'goroutine 与 channel' },
      { r: 2, c: 1, text: 'go f()、chan T、select' },
      { r: 2, c: 2, text: '通过通信共享内存' },
      { r: 3, c: 0, text: '错误是普通返回值' },
      { r: 3, c: 1, text: 'if err != nil 显式处理' },
      { r: 3, c: 2, text: '不用异常控制流程' },
    ],
    notes: ['并发不是并行：goroutine 由运行时调度到线程'],
    caption: 'Go 的设计哲学是少而明确：错误显式处理，接口隐式实现，并发用通道通信。',
  },
  go_first_program: {
    image: 'diagram_go_first_program.webp',
    alt: 'Go 最小程序的结构',
    title: '第一个程序：包、导入与入口',
    type: 'flow',
    steps: [
      { title: 'package main', desc: '声明可执行程序所属的包' },
      { title: 'import', desc: '按需引入标准库或第三方包' },
      { title: 'func main', desc: '程序入口，无参数无返回值' },
      { title: 'go run', desc: '编译并运行，快速验证' },
      { title: 'go build', desc: '生成单个可执行文件' },
    ],
    notes: ['未使用的导入与变量会直接编译失败'],
    caption: 'Go 用强制格式化与严格编译，把团队从风格争论中解放出来。',
  },
  go_variables_input: {
    image: 'diagram_go_variables.webp',
    alt: 'Go 变量声明与输入处理',
    title: '变量与输入：声明、推断与错误',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['var 声明', '短变量声明', '零值', '输入解析'],
    colLabels: ['写法', '特点', '注意点'],
    cells: [
      { r: 0, c: 0, text: 'var name string' },
      { r: 0, c: 1, text: '显式类型，可在包级使用' },
      { r: 0, c: 2, text: '可同时声明多个变量' },
      { r: 1, c: 0, text: 'age := 18' },
      { r: 1, c: 1, text: '函数内使用，自动推断' },
      { r: 1, c: 2, text: '至少有一个新变量' },
      { r: 2, c: 0, text: '未赋值即零值' },
      { r: 2, c: 1, text: '0、空串、nil、false' },
      { r: 2, c: 2, text: '不要依赖隐式默认值' },
      { r: 3, c: 0, text: 'fmt.Scan 或 bufio' },
      { r: 3, c: 1, text: '读取并解析用户输入' },
      { r: 3, c: 2, text: '必须检查错误' },
    ],
    notes: ['读取输入后要验证范围与格式，错误不能忽略'],
    caption: 'Go 的零值让变量总有确定初值，但业务上的「有效值」仍需显式校验。',
  },
  go_conditions: {
    image: 'diagram_go_conditions.webp',
    alt: 'Go 条件分支的常见写法',
    title: '条件判断：if、switch 与类型分支',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['if', 'if 初始化语句', 'switch', '类型 switch'],
    colLabels: ['写法', '用途', '注意点'],
    cells: [
      { r: 0, c: 0, text: 'if score >= 60' },
      { r: 0, c: 1, text: '普通条件判断' },
      { r: 0, c: 2, text: '条件不需要括号' },
      { r: 1, c: 0, text: 'if v, err := f(); err != nil' },
      { r: 1, c: 1, text: '限定变量作用域' },
      { r: 1, c: 2, text: '变量只在分支内可见' },
      { r: 2, c: 0, text: 'switch value {' },
      { r: 2, c: 1, text: '多分支匹配，默认不穿透' },
      { r: 2, c: 2, text: '用 fallthrough 显式穿透' },
      { r: 3, c: 0, text: 'switch v := x.(type)' },
      { r: 3, c: 1, text: '按动态类型分支' },
      { r: 3, c: 2, text: '配合接口断言使用' },
    ],
    notes: ['switch 比长链 if-else 更清晰，也更容易穷尽分支'],
    caption: 'Go 的条件语句强调局部作用域与显式分支，减少临时变量泄漏。',
  },
  go_loops: {
    image: 'diagram_go_loops.webp',
    alt: 'Go for 循环的四种形态',
    title: '循环：只有 for，但足够表达一切',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['三段式 for', '条件 for', '无限 for', 'range'],
    colLabels: ['写法', '等价形态', '典型用途'],
    cells: [
      { r: 0, c: 0, text: 'for i := 0; i < n; i++' },
      { r: 0, c: 1, text: '标准计数循环' },
      { r: 0, c: 2, text: '按索引遍历' },
      { r: 1, c: 0, text: 'for cond {' },
      { r: 1, c: 1, text: '相当于 while' },
      { r: 1, c: 2, text: '条件驱动循环' },
      { r: 2, c: 0, text: 'for {' },
      { r: 2, c: 1, text: '配合 break 退出' },
      { r: 2, c: 2, text: '事件循环、守护任务' },
      { r: 3, c: 0, text: 'for i, v := range xs' },
      { r: 3, c: 1, text: '遍历数组、切片、map、channel' },
      { r: 3, c: 2, text: '注意不要复制大对象' },
    ],
    notes: ['break 与 continue 可配合标签跳出多层循环'],
    caption: 'Go 把 while 和 do-while 统一到 for，用更少的语法覆盖同样的控制流。',
  },
  go_functions_intro: {
    image: 'diagram_go_functions.webp',
    alt: 'Go 函数的多返回值与错误处理',
    title: '函数：多返回值与显式错误',
    type: 'compare',
    columns: [
      { title: '函数签名', items: ['参数类型写在变量之后', '返回值可以多个', '命名返回值便于文档化', '函数是一等值，可作参数', 'defer 延迟执行清理'] },
      { title: '错误处理', items: ['错误作为最后一个返回值', '调用方立即检查 err', '用 %w 包装保留错误链', 'errors.Is 判断哨兵错误', '自定义错误类型承载上下文'] },
    ],
    notes: ['panic 只用于不可恢复的程序错误，业务错误用 error'],
    caption: '多返回值让「结果 + 错误」成为显式契约，调用方无法装作没看见。',
  },
  go_interfaces_errors: {
    image: 'diagram_go_interfaces_errors.webp',
    alt: '隐式接口与错误链',
    title: '接口与错误：两个隐式契约',
    type: 'compare',
    columns: [
      { title: '隐式接口', items: ['实现类型无需声明 implements', '接口定义在使用方而非实现方', '小接口更容易组合', '类型断言取出具体值', '空接口不再推荐滥用'] },
      { title: '错误链', items: ['%w 包装底层错误', 'errors.Is 判断是否同一类错误', 'errors.As 提取具体错误类型', '错误信息要包含上下文', '不要把错误字符串当 API'] },
    ],
    notes: ['接口越小越稳定：一个方法的接口最容易被满足'],
    caption: 'Go 的接口与错误都靠约定而非继承：描述需要什么，而不是声明自己是什么。',
  },
  go_generics_stdlib: {
    image: 'diagram_go_generics_stdlib.webp',
    alt: 'Go 泛型与标准库要点',
    title: '泛型与标准库：写更通用的代码',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['类型参数', '约束', 'net/http', 'encoding/json'],
    colLabels: ['写法', '作用', '工程要点'],
    cells: [
      { r: 0, c: 0, text: 'func Map[T, U any]' },
      { r: 0, c: 1, text: '让算法与容器通用' },
      { r: 0, c: 2, text: '不要为泛型而泛型' },
      { r: 1, c: 0, text: 'T interface{ ~int }' },
      { r: 1, c: 1, text: '约束可用类型集合' },
      { r: 1, c: 2, text: '优先使用标准约束' },
      { r: 2, c: 0, text: 'Client{Timeout: ...}' },
      { r: 2, c: 1, text: '显式设置超时与连接复用' },
      { r: 2, c: 2, text: '避免默认客户端裸用' },
      { r: 3, c: 0, text: 'json:"name,omitempty"' },
      { r: 3, c: 1, text: '控制序列化字段名与空值' },
      { r: 3, c: 2, text: '注意零值与指针差异' },
    ],
    notes: ['标准库优先：net/http、encoding/json、slices 与 maps 已覆盖大量场景'],
    caption: '泛型解决类型复用，标准库解决工程复用；先查标准库，再考虑抽象。',
  },
  go_project: {
    image: 'diagram_go_project.webp',
    alt: 'Go 工程实践的四个环节',
    title: 'Go 工程实践：模块、测试与部署',
    type: 'flow',
    steps: [
      { title: '模块布局', desc: 'cmd、internal、pkg 按职责分层' },
      { title: '表驱动测试', desc: '用用例表覆盖正常与边界输入' },
      { title: '性能剖析', desc: 'pprof 定位 CPU、内存与阻塞' },
      { title: '静态部署', desc: '交叉编译为单文件，容器无依赖运行' },
    ],
    notes: ['internal 目录阻止外部模块导入，是边界而非装饰'],
    caption: 'Go 工程化强调标准工具链与简单结构：测试、剖析、部署都不需要额外框架。',
  },
  go_testing: {
    image: 'diagram_go_testing.webp',
    alt: 'Go 测试的三种主要形态',
    title: '测试进阶：基准、模糊与集成',
    type: 'compare',
    columns: [
      { title: '基准与模糊', items: ['Benchmark 测函数吞吐', 'b.ResetTimer 排除准备开销', '模糊测试自动生成输入', '发现 panic 与越界', '失败样本进入种子语料'] },
      { title: '集成与竞态', items: ['用真实依赖验证契约', '测试隔离：临时库与随机端口', 'go test -race 检测数据竞争', '并行测试注意共享状态', 'CI 分层执行快慢测试'] },
    ],
    notes: ['测试失败信息要包含输入、期望与实际'],
    caption: '基准回答「多快」，模糊回答「什么输入会崩」，竞态检测回答「并发是否安全」。',
  },
  go_data_access: {
    image: 'diagram_go_data_access.webp',
    alt: 'database/sql 的事务与连接池',
    title: '数据访问：连接池与事务模板',
    type: 'flow',
    steps: [
      { title: '配置连接池', desc: '设置最大连接、空闲与生命周期' },
      { title: '开启事务', desc: 'defer 回滚，成功后提交' },
      { title: '批量写入', desc: '准备语句与分批提交降低往返' },
      { title: '上下文取消', desc: '请求取消时中止慢查询' },
    ],
    notes: ['连接数不是越大越好，要匹配数据库承载能力'],
    caption: '数据访问层要同时管理连接、事务与取消，任何一项失控都会拖垮服务。',
  },
  go_microservice: {
    image: 'diagram_go_microservice.webp',
    alt: 'Go 微服务的可观测与生命周期',
    title: '微服务：可观测性与优雅关闭',
    type: 'layers',
    layers: [
      { title: '配置校验', desc: '启动时验证必填配置，快速失败', fill: '#eef4ff', stroke: '#6c8ff8' },
      { title: '结构化日志', desc: '字段化输出，携带请求与追踪 ID', fill: '#e8f2ff', stroke: '#6c8ff8' },
      { title: '指标与链路', desc: 'RED 指标、延迟分布与调用链', fill: '#e6f7f1', stroke: '#3fae8a' },
      { title: '优雅关闭', desc: '停止接收新请求，等待在途完成', fill: '#fff4e6', stroke: '#e6a23c' },
      { title: '健康检查', desc: '区分存活与就绪，配合编排系统', fill: '#fdeeee', stroke: '#d97070' },
    ],
    widths: [0.72, 0.84, 0.92, 1, 0.86],
    caption: '微服务的可运维性来自配置、日志、指标与关闭流程的统一设计。',
  },
  go_grpc: {
    image: 'diagram_go_grpc.webp',
    alt: 'gRPC 的四种调用方式',
    title: 'gRPC：四种调用方式与契约演进',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['一元调用', '服务端流', '客户端流', '双向流'],
    colLabels: ['模式', '典型场景', '注意点'],
    cells: [
      { r: 0, c: 0, text: '请求一条，响应一条' },
      { r: 0, c: 1, text: '普通 RPC 接口' },
      { r: 0, c: 2, text: '设置超时与重试策略' },
      { r: 1, c: 0, text: '请求一条，响应多条' },
      { r: 1, c: 1, text: '订阅、进度推送' },
      { r: 1, c: 2, text: '客户端要能取消' },
      { r: 2, c: 0, text: '请求多条，响应一条' },
      { r: 2, c: 1, text: '批量上传、聚合' },
      { r: 2, c: 2, text: '控制消息大小与背压' },
      { r: 3, c: 0, text: '双向持续收发' },
      { r: 3, c: 1, text: '实时对话、协同' },
      { r: 3, c: 2, text: '管理连接生命周期' },
    ],
    notes: ['字段编号一旦发布不可复用；只增不改是契约演进原则'],
    caption: 'Protobuf 定义契约，gRPC 负责传输；向后兼容依赖字段编号纪律。',
  },
  go_pprof: {
    image: 'diagram_go_pprof.webp',
    alt: 'pprof 六种剖析类型',
    title: 'pprof：六种剖析定位不同瓶颈',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['CPU', '堆内存', '阻塞', '互斥锁'],
    colLabels: ['回答的问题', '采集方式', '常见发现'],
    cells: [
      { r: 0, c: 0, text: '时间花在哪些函数' },
      { r: 0, c: 1, text: '运行时采样 CPU' },
      { r: 0, c: 2, text: '热点循环与序列化' },
      { r: 1, c: 0, text: '内存分配在哪里' },
      { r: 1, c: 1, text: 'heap profile 采样' },
      { r: 1, c: 2, text: '频繁分配与对象泄漏' },
      { r: 2, c: 0, text: 'goroutine 卡在哪里' },
      { r: 2, c: 1, text: 'block profile 采样' },
      { r: 2, c: 2, text: '无缓冲通道与锁竞争' },
      { r: 3, c: 0, text: '哪个锁竞争最激烈' },
      { r: 3, c: 1, text: 'mutex profile 采样' },
      { r: 3, c: 2, text: '共享计数器与缓存锁' },
    ],
    notes: ['另有 goroutine 与 trace 两类：分别看快照与时间线'],
    caption: '优化前先采集：pprof 用采样数据指出热点，避免凭直觉改代码。',
  },
  go_profiling_deep: {
    image: 'diagram_go_profiling_deep.webp',
    alt: 'Go 性能剖析的完整流程',
    title: '性能调优：从基准到验证',
    type: 'flow',
    steps: [
      { title: '写基准', desc: '固定输入与预热，保证结果可比较' },
      { title: '采 pprof', desc: 'CPU、内存、阻塞与锁分别定位' },
      { title: '看 trace', desc: '分析调度延迟与 GC 停顿' },
      { title: '逃逸分析', desc: '减少堆分配与不必要的拷贝' },
      { title: '回归验证', desc: '用同一基准确认收益与副作用' },
    ],
    notes: ['优化要有基线、有对照、有回归，避免只凭单次结果'],
    caption: '性能问题是系统问题：CPU、内存、锁与调度要一起看，改完必须复测。',
  },
  go_generics_deep: {
    image: 'diagram_go_generics_deep.webp',
    alt: 'Go 泛型约束与性能',
    title: '泛型深入：约束、类型集合与性能',
    type: 'layers',
    layers: [
      { title: '类型参数', desc: '让函数与类型适配多种具体类型', fill: '#eef4ff', stroke: '#6c8ff8' },
      { title: '约束接口', desc: '用接口描述可接受的类型集合', fill: '#e8f2ff', stroke: '#6c8ff8' },
      { title: '类型集合', desc: '用联合与 ~ 表示底层类型', fill: '#e6f7f1', stroke: '#3fae8a' },
      { title: '单态化', desc: '编译期为具体类型生成代码', fill: '#fff4e6', stroke: '#e6a23c' },
      { title: '性能权衡', desc: '泛型通常接近手写，但要关注代码体积', fill: '#fdeeee', stroke: '#d97070' },
    ],
    widths: [0.72, 0.84, 0.9, 1, 0.92],
    caption: '泛型先保证表达力与类型安全，再评估生成代码体积；不要用 any 绕过约束。',
  },
  go_cloud_native_security: {
    image: 'diagram_go_cloud_security.webp',
    alt: '云原生服务的安全与可靠性层次',
    title: '云原生服务：安全与可靠性',
    type: 'layers',
    layers: [
      { title: '传输安全', desc: 'mTLS 双向认证，证书自动轮换', fill: '#eef4ff', stroke: '#6c8ff8' },
      { title: '身份与令牌', desc: '短期令牌、作用域最小化', fill: '#e8f2ff', stroke: '#6c8ff8' },
      { title: '超时与重试', desc: '全链路超时，重试带退避与抖动', fill: '#e6f7f1', stroke: '#3fae8a' },
      { title: '限流与熔断', desc: '保护自身与下游，区分优先级', fill: '#fff4e6', stroke: '#e6a23c' },
      { title: '安全配置', desc: '密钥不落盘，启动校验与最小权限', fill: '#fdeeee', stroke: '#d97070' },
    ],
    widths: [0.72, 0.84, 0.9, 1, 0.9],
    caption: '云原生安全不是单点加固，而是身份、传输、流量与配置的整体约束。',
  },
  go_project_rest_api: {
    image: 'diagram_go_rest_api.webp',
    alt: 'Go REST API 的请求链路',
    title: '实战 REST API：请求如何流转',
    type: 'sequence',
    actors: ['客户端', '路由与中间件', '服务逻辑', 'SQLite'],
    messages: [
      { from: 0, to: 1, label: 'HTTP 请求携带参数' },
      { from: 1, to: 1, label: '日志、恢复与超时中间件' },
      { from: 1, to: 2, label: '校验并调用业务函数' },
      { from: 2, to: 3, label: '参数化查询与事务' },
      { from: 3, to: 2, label: '返回领域对象' },
      { from: 2, to: 0, label: '序列化 JSON 与状态码' },
    ],
    notes: ['优雅关闭：等待在途请求完成再退出进程'],
    caption: 'REST 服务的骨架是中间件、校验、业务与数据访问，测试要覆盖错误路径。',
  },
  go_project_worker_pool: {
    image: 'diagram_go_worker_pool.webp',
    alt: 'Go Worker Pool 的任务流转',
    title: '实战 Worker Pool：限流、重试与取消',
    type: 'flow',
    steps: [
      { title: '任务队列', desc: '生产者把 URL 写入通道并关闭' },
      { title: '固定 Worker', desc: 'N 个 goroutine 并发消费任务' },
      { title: '限流与重试', desc: '令牌桶限速，失败指数退避' },
      { title: '上下文取消', desc: '首个错误或超时后停止新任务' },
      { title: '汇总结果', desc: 'errgroup 收拢错误与统计' },
    ],
    notes: ['必须保证 goroutine 可退出，避免泄漏与死锁'],
    caption: '并发任务的三件事：限流保护下游、取消及时止损、汇总给出确定结果。',
  },
};
