// P5 TypeScript 课程配图数据。
module.exports = {
  typescript: {
    image: 'diagram_ts_type_system.webp',
    alt: 'TypeScript 类型系统的五个层次',
    title: 'TypeScript 类型系统：从标注到工程化',
    type: 'layers',
    layers: [
      { title: '类型标注', desc: '给变量、参数与返回值声明类型', fill: '#eef4ff', stroke: '#6c8ff8' },
      { title: '类型推断', desc: '多数场景无需手写，让编译器推导', fill: '#e8f2ff', stroke: '#6c8ff8' },
      { title: '类型收窄', desc: '用控制流把联合类型缩小到具体分支', fill: '#e6f7f1', stroke: '#3fae8a' },
      { title: '泛型与工具类型', desc: '用类型参数表达可复用约束', fill: '#fff4e6', stroke: '#e6a23c' },
      { title: '工程配置', desc: 'strict、构建、声明文件与团队规范', fill: '#fdeeee', stroke: '#d97070' },
    ],
    widths: [0.7, 0.82, 0.9, 1, 0.92],
    caption: '类型系统既是文档也是检查器：把约束前移到编译期，运行时错误就会更少。',
  },
  ts_first_types: {
    image: 'diagram_ts_first_types.webp',
    alt: '从 JavaScript 到 TypeScript 的第一步',
    title: '第一个类型：给 JavaScript 加一层检查',
    type: 'flow',
    steps: [
      { title: '写 JavaScript', desc: '先有可运行的逻辑' },
      { title: '改为 .ts', desc: '安装 TypeScript 并配置 tsconfig' },
      { title: '添加标注', desc: '给关键参数与返回值写类型' },
      { title: '运行检查', desc: 'tsc 报出类型不匹配的位置' },
      { title: '修复并运行', desc: '类型通过后再执行代码' },
    ],
    notes: ['类型错误在编译期暴露，不等于运行时一定安全'],
    caption: 'TypeScript 不改变运行逻辑，它在代码执行前增加一层静态检查。',
  },
  ts_basic_types: {
    image: 'diagram_ts_basic_types.webp',
    alt: 'TypeScript 基础类型一览',
    title: '基础类型：string、number、boolean 与联合',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['string', 'number', 'boolean', '联合类型'],
    colLabels: ['写法', '含义', '常见错误'],
    cells: [
      { r: 0, c: 0, text: "name: string" },
      { r: 0, c: 1, text: '文本，支持模板字符串' },
      { r: 0, c: 2, text: '把数字赋给字符串' },
      { r: 1, c: 0, text: 'age: number' },
      { r: 1, c: 1, text: '整数与浮点数统一为 number' },
      { r: 1, c: 2, text: '忘记处理 NaN' },
      { r: 2, c: 0, text: 'ok: boolean' },
      { r: 2, c: 1, text: '只有 true 与 false' },
      { r: 2, c: 2, text: '用 0/1 代替布尔值' },
      { r: 3, c: 0, text: "status: 'on' | 'off'" },
      { r: 3, c: 1, text: '值只能是列出的字面量' },
      { r: 3, c: 2, text: '忘记穷尽所有分支' },
    ],
    notes: ['优先让编译器推断，只有在推断不够精确时才手写标注'],
    caption: '联合类型配合收窄，是 TypeScript 表达业务状态最常用的组合。',
  },
  ts_interface_intro: {
    image: 'diagram_ts_interface.webp',
    alt: 'interface 描述对象契约的常见成员',
    title: 'interface：描述对象的形状',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['必填属性', '可选属性', '只读属性', '方法'],
    colLabels: ['写法', '作用', '注意点'],
    cells: [
      { r: 0, c: 0, text: 'id: number' },
      { r: 0, c: 1, text: '对象必须提供该字段' },
      { r: 0, c: 2, text: '缺少字段会报错' },
      { r: 1, c: 0, text: 'name?: string' },
      { r: 1, c: 1, text: '字段可以不存在' },
      { r: 1, c: 2, text: '使用前要判空' },
      { r: 2, c: 0, text: 'readonly id: number' },
      { r: 2, c: 1, text: '初始化后不可重新赋值' },
      { r: 2, c: 2, text: '只约束编译期' },
      { r: 3, c: 0, text: 'save(): Promise<void>' },
      { r: 3, c: 1, text: '声明对象可调用的方法' },
      { r: 3, c: 2, text: '实现要匹配签名' },
    ],
    notes: ['interface 可扩展、可合并；type 更适合联合与组合'],
    caption: '接口是团队之间的契约：先定义对象形状，再写实现与测试。',
  },
  ts_function_types: {
    image: 'diagram_ts_function_types.webp',
    alt: '函数类型的参数、返回值与回调',
    title: '函数类型：参数与返回值都要说清楚',
    type: 'compare',
    columns: [
      { title: '函数声明', items: ['参数逐个标注类型', '返回值标注或交给推断', '可选参数写在必填参数之后', '默认值参数自动变为可选', '剩余参数用数组类型'] },
      { title: '回调与泛型', items: ['回调参数由上下文推断', '函数类型可赋给变量', '泛型保留输入输出关系', '重载表达多种调用签名', 'this 类型可显式约束'] },
    ],
    notes: ['开启 strictFunctionTypes 能发现更多回调类型问题'],
    caption: '函数是最小可测试单元；把参数和返回值写清楚，调用方就能获得即时提示。',
  },
  ts_arrays_objects: {
    image: 'diagram_ts_arrays_objects.webp',
    alt: '数组、元组与对象类型的建模方式',
    title: '数组与对象：把数据结构建模清楚',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['数组', '元组', '对象', '可选字段'],
    colLabels: ['写法', '含义', '使用场景'],
    cells: [
      { r: 0, c: 0, text: 'number[]' },
      { r: 0, c: 1, text: '同类型元素列表' },
      { r: 0, c: 2, text: '列表、批量数据' },
      { r: 1, c: 0, text: '[number, string]' },
      { r: 1, c: 1, text: '固定长度与顺序' },
      { r: 1, c: 2, text: '坐标、返回值对' },
      { r: 2, c: 0, text: '{ id: number }' },
      { r: 2, c: 1, text: '具名属性结构' },
      { r: 2, c: 2, text: '接口、配置对象' },
      { r: 3, c: 0, text: 'email?: string' },
      { r: 3, c: 1, text: '字段可能不存在' },
      { r: 3, c: 2, text: '表单、部分更新' },
    ],
    notes: ['对象字面量赋值会触发多余属性检查'],
    caption: '先描述数据形状，再写处理逻辑；类型会把隐含假设显式化。',
  },
  ts_narrowing_generics: {
    image: 'diagram_ts_narrowing.webp',
    alt: '五种类型收窄手段',
    title: '类型收窄：让联合类型逐步变小',
    type: 'grid',
    rows: 5,
    cols: 3,
    rowLabels: ['typeof', 'in', 'instanceof', '字面量判别', '自定义守卫'],
    colLabels: ['适用对象', '写法要点', '结果'],
    cells: [
      { r: 0, c: 0, text: '基础类型' },
      { r: 0, c: 1, text: "typeof value === 'string'" },
      { r: 0, c: 2, text: '缩到 string' },
      { r: 1, c: 0, text: '对象属性' },
      { r: 1, c: 1, text: "'name' in value" },
      { r: 1, c: 2, text: '区分对象分支' },
      { r: 2, c: 0, text: '类实例' },
      { r: 2, c: 1, text: 'value instanceof Date' },
      { r: 2, c: 2, text: '缩到具体类' },
      { r: 3, c: 0, text: '可辨识联合' },
      { r: 3, c: 1, text: "kind === 'success'" },
      { r: 3, c: 2, text: '锁定成员类型' },
      { r: 4, c: 0, text: '复杂结构' },
      { r: 4, c: 1, text: 'value is User' },
      { r: 4, c: 2, text: '自定义判定函数' },
    ],
    notes: ['泛型约束用 extends 表达：T extends { id: number }'],
    caption: '收窄的本质是把运行时检查翻译成编译期信息，让每个分支只看到确定类型。',
  },
  ts_utility_types: {
    image: 'diagram_ts_utility_types.webp',
    alt: '常用工具类型与声明文件',
    title: '工具类型：从已有类型派生新类型',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['Partial', 'Pick', 'Omit', 'Record'],
    colLabels: ['作用', '示例', '场景'],
    cells: [
      { r: 0, c: 0, text: '把所有属性变为可选' },
      { r: 0, c: 1, text: 'Partial<User>' },
      { r: 0, c: 2, text: '表单草稿、更新参数' },
      { r: 1, c: 0, text: '挑选部分属性' },
      { r: 1, c: 1, text: "Pick<User, 'id' | 'name'>" },
      { r: 1, c: 2, text: '列表投影、DTO' },
      { r: 2, c: 0, text: '排除部分属性' },
      { r: 2, c: 1, text: "Omit<User, 'password'>" },
      { r: 2, c: 2, text: '安全输出、脱敏' },
      { r: 3, c: 0, text: '构造键值映射' },
      { r: 3, c: 1, text: 'Record<Role, string[]>' },
      { r: 3, c: 2, text: '字典、权限表' },
    ],
    notes: ['映射类型与 keyof 可以自定义派生规则；.d.ts 描述外来模块'],
    caption: '不要重复定义相似接口：用工具类型从单一来源派生，改一处就能全局生效。',
  },
  ts_project: {
    image: 'diagram_ts_project.webp',
    alt: 'TypeScript 工程配置的四个环节',
    title: '工程配置：让类型检查稳定可复现',
    type: 'flow',
    steps: [
      { title: '开启 strict', desc: '严格模式暴露空值与隐式 any' },
      { title: 'tsc --noEmit', desc: '类型检查与产物构建分开执行' },
      { title: '运行时校验', desc: '外部数据用 zod 等 schema 解析' },
      { title: '团队规范', desc: '统一路径别名、lint 与 CI 门禁' },
    ],
    notes: ['编译期类型无法验证网络响应与配置文件，边界必须校验'],
    caption: '类型安全的关键在边界：内部保持强类型，外部数据先校验再使用。',
  },
  ts_decorators_pro: {
    image: 'diagram_ts_decorators.webp',
    alt: '装饰器与进阶类型的适用场景',
    title: '装饰器与进阶类型：各司其职',
    type: 'compare',
    columns: [
      { title: '装饰器', items: ['为类与方法附加元行为', '依赖 reflect-metadata 运行时', '常见于 NestJS 与 ORM', '注意标准与实验性语法差异', '业务逻辑不要藏在装饰器里'] },
      { title: '进阶类型', items: ['条件类型表达类型层分支', 'infer 提取结构中的类型', '映射类型批量改造属性', '模板字面量类型约束字符串', '目标是无重复的类型推导'] },
    ],
    notes: ['类型体操以可读性为边界，复杂推导要配注释与测试'],
    caption: '装饰器解决运行时横切关注点，进阶类型解决编译期结构推导，两者不要混为一谈。',
  },
  ts_build_test: {
    image: 'diagram_ts_build_test.webp',
    alt: '构建工具与测试工具的分工',
    title: '构建与测试：工具链如何分工',
    type: 'compare',
    columns: [
      { title: '构建工具', items: ['tsc 生成类型声明与产物', 'tsup 适合库与双格式输出', 'Vite 面向应用开发与打包', '区分 ESM 与 CJS 入口', '产物要验证可被真实导入'] },
      { title: '测试工具', items: ['Vitest 与 TS 配置天然集成', '单元测试覆盖纯逻辑', '组件测试验证交互', 'MSW 拦截网络请求', 'CI 同时跑类型检查与测试'] },
    ],
    notes: ['构建与类型检查是两件事，CI 中应分别执行'],
    caption: '库关注产物与声明文件，应用关注开发体验与打包体积；测试跟随业务风险分配。',
  },
  ts_fullstack_project: {
    image: 'diagram_ts_fullstack.webp',
    alt: '全栈类型安全的数据流',
    title: '全栈类型安全：一份 schema 贯穿前后端',
    type: 'sequence',
    actors: ['共享 schema', '前端', 'API 服务', '数据库'],
    messages: [
      { from: 0, to: 1, label: '导出请求与响应类型' },
      { from: 1, to: 2, label: '发起类型化请求' },
      { from: 2, to: 0, label: '用同一 schema 校验入参' },
      { from: 2, to: 3, label: '持久化并映射结果' },
      { from: 3, to: 2, label: '返回领域对象' },
      { from: 2, to: 1, label: '响应类型与前端一致' },
    ],
    notes: ['共享的是契约与校验规则，不是把服务端代码打包进前端'],
    caption: '端到端类型让接口改动在编译期暴露；运行时校验则守住真实网络边界。',
  },
  ts_type_challenges: {
    image: 'diagram_ts_type_challenges.webp',
    alt: '类型体操的四类核心工具',
    title: '类型体操：条件、infer、映射与模板字面量',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['条件类型', 'infer', '映射类型', '模板字面量'],
    colLabels: ['作用', '示例', '常见用途'],
    cells: [
      { r: 0, c: 0, text: '类型层面的 if-else' },
      { r: 0, c: 1, text: 'T extends U ? X : Y' },
      { r: 0, c: 2, text: '分支生成不同类型' },
      { r: 1, c: 0, text: '从结构中提取类型' },
      { r: 1, c: 1, text: 'T extends (infer R)[]' },
      { r: 1, c: 2, text: '提取返回值与元素' },
      { r: 2, c: 0, text: '遍历属性批量改造' },
      { r: 2, c: 1, text: '[K in keyof T]' },
      { r: 2, c: 2, text: '只读、可选化' },
      { r: 3, c: 0, text: '字符串模式约束' },
      { r: 3, c: 1, text: '`get${K}`' },
      { r: 3, c: 2, text: '事件名、路由参数' },
    ],
    notes: ['递归类型要设置终止条件，避免编译器深度报错'],
    caption: '类型体操的目标是消除重复与错误，不是炫技；能推断出来就不要手写。',
  },
  ts_node_backend: {
    image: 'diagram_ts_node_backend.webp',
    alt: 'TypeScript Node 后端的分层结构',
    title: 'Node 后端：分层与生产必做项',
    type: 'layers',
    layers: [
      { title: '路由层', desc: '解析请求、校验参数与返回状态码', fill: '#eef4ff', stroke: '#6c8ff8' },
      { title: '服务层', desc: '编排业务规则，保持与框架无关', fill: '#e8f2ff', stroke: '#6c8ff8' },
      { title: '数据访问层', desc: '封装查询、事务与领域映射', fill: '#e6f7f1', stroke: '#3fae8a' },
      { title: 'Schema 校验', desc: '入参与出参都在边界处验证', fill: '#fff4e6', stroke: '#e6a23c' },
      { title: '生产必做', desc: '日志、指标、超时、限流与优雅关闭', fill: '#fdeeee', stroke: '#d97070' },
    ],
    widths: [0.72, 0.84, 0.9, 1, 0.94],
    caption: '框架可以替换，分层与边界校验不能省；类型只覆盖编译期，运行时要再验一次。',
  },
  ts_monorepo: {
    image: 'diagram_ts_monorepo.webp',
    alt: 'Monorepo 的包结构与依赖方向',
    title: 'Monorepo：依赖方向决定可维护性',
    type: 'tree',
    root: {
      text: 'workspace 根',
      children: [
        {
          text: 'apps',
          children: [
            { text: 'Web 前端' },
            { text: 'Node 服务' },
          ],
        },
        {
          text: 'packages',
          children: [
            { text: '共享 schema' },
            { text: '工具与配置' },
          ],
        },
      ],
    },
    notes: ['apps 依赖 packages，packages 不反向依赖 apps', '任务缓存与版本发布要纳入 CI'],
    caption: 'Monorepo 的收益来自共享与原子改动，代价是构建复杂度；依赖方向必须单向。',
  },
  ts_testing: {
    image: 'diagram_ts_testing.webp',
    alt: 'Vitest、Testing Library 与 MSW 的组合',
    title: '测试策略：三层工具各管一段',
    type: 'compare',
    columns: [
      { title: 'Vitest 与组件测试', items: ['Vitest 跑单元与集成测试', '覆盖纯函数、状态与边界', 'Testing Library 按用户视角查询', '断言可访问角色与文本', '避免依赖组件内部实现'] },
      { title: 'MSW 与端到端', items: ['MSW 在网络上拦截请求', '同一份 handler 复用到浏览器', '模拟成功、失败与超时', '端到端测试验证关键流程', '测试数据用工厂函数生成'] },
    ],
    notes: ['测试金字塔：单元多、集成适中、端到端只覆盖关键路径'],
    caption: '测试要跟着风险走：纯逻辑用单元测试，接口契约用集成测试，核心流程才上端到端。',
  },
  ts_build_performance: {
    image: 'diagram_ts_build_perf.webp',
    alt: '类型检查与构建性能优化步骤',
    title: '构建性能：先定位，再优化',
    type: 'flow',
    steps: [
      { title: '测量热点', desc: '用 --diagnostics 与 --extendedDiagnostics' },
      { title: '隔离检查', desc: 'tsc --noEmit 独立于打包流程' },
      { title: '增量与引用', desc: 'incremental 与 project references' },
      { title: '拆分任务', desc: 'lint、类型检查、测试并行到 CI' },
    ],
    notes: ['避免过深的类型推导与巨型联合类型，它们会拖慢编辑器'],
    caption: '构建慢通常是类型推导或项目结构问题；先拿数据，再决定是否换工具。',
  },
  ts_project_cli: {
    image: 'diagram_ts_cli_project.webp',
    alt: '类型安全 CLI 的实现流程',
    title: '实战 CLI：从参数到发布',
    type: 'flow',
    steps: [
      { title: '定义命令', desc: '声明子命令、参数与帮助信息' },
      { title: 'Zod 校验', desc: '把字符串参数解析为配置对象' },
      { title: '执行逻辑', desc: '业务函数保持纯函数便于测试' },
      { title: 'Vitest 覆盖', desc: '测试参数组合与错误信息' },
      { title: '构建发布', desc: '生成可执行入口与类型声明' },
    ],
    notes: ['退出码与错误信息也是 CLI 的公开契约'],
    caption: 'CLI 的质量取决于边界校验与可脚本化：参数、输出、退出码都要稳定。',
  },
  ts_project_websocket_dashboard: {
    image: 'diagram_ts_ws_dashboard.webp',
    alt: '实时监控面板的消息链路',
    title: '实战面板：WebSocket 消息如何流动',
    type: 'sequence',
    actors: ['采集端', 'WS 服务', '前端状态', '图表'],
    messages: [
      { from: 0, to: 1, label: '推送指标消息' },
      { from: 1, to: 2, label: '校验消息协议并分发' },
      { from: 2, to: 3, label: '批量更新图表数据' },
      { from: 2, to: 1, label: '断线后指数退避重连' },
      { from: 1, to: 2, label: '补发快照对齐状态' },
      { from: 2, to: 3, label: '渲染最新窗口' },
    ],
    notes: ['协议要版本化，消息要校验，重连要能补齐缺口'],
    caption: '实时面板的难点不在画图，而在连接生命周期与消息一致性。',
  },
  ts_runtime_validation: {
    image: 'diagram_ts_runtime_validation.webp',
    alt: '运行时校验把未知数据收敛为类型',
    title: '运行时校验：守住类型系统的边界',
    type: 'flow',
    steps: [
      { title: '接收 unknown', desc: '外部数据先视为不可信' },
      { title: 'Schema 解析', desc: '用 zod 校验结构与取值' },
      { title: '得到具体类型', desc: '解析成功才进入业务逻辑' },
      { title: '错误分支', desc: '校验失败返回可读错误' },
    ],
    notes: ['API、配置、localStorage 与消息队列都是外部边界'],
    caption: '编译期类型是承诺，运行时校验是证据；没有校验，类型断言只是自我安慰。',
  },
  ts_performance: {
    image: 'diagram_ts_performance.webp',
    alt: '编译性能与运行性能的优化要点',
    title: '性能优化：编译期与运行期分开看',
    type: 'compare',
    columns: [
      { title: '编译与检查', items: ['增量编译与项目引用', '避免不必要的类型体操', '拆分大型声明文件', 'CI 并行执行类型与测试', '监控编辑器响应速度'] },
      { title: '运行与打包', items: ['按路由拆包与懒加载', 'tree shaking 去掉死代码', '避免重复打包依赖', '分析产物体积与首屏', '用真实设备测运行时性能'] },
    ],
    notes: ['编译性能影响开发效率，运行性能影响用户体验，指标要分别采集'],
    caption: 'TypeScript 本身不拖慢运行时，但类型设计会影响构建，打包配置会影响体积。',
  },
};
