// P6 HTML 与 CSS 课程配图数据。
module.exports = {
  html_tags_intro: {
    image: 'diagram_web_html_tags.webp',
    alt: '常用 HTML 标签与页面结构',
    title: 'HTML 标签入门：搭出页面骨架',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['标题', '段落', '列表', '链接'],
    colLabels: ['标签', '作用', '注意点'],
    cells: [
      { r: 0, c: 0, text: 'h1 ~ h6' },
      { r: 0, c: 1, text: '表达标题层级' },
      { r: 0, c: 2, text: '一页通常只有一个 h1' },
      { r: 1, c: 0, text: 'p' },
      { r: 1, c: 1, text: '组织段落文本' },
      { r: 1, c: 2, text: '不要用换行模拟段落' },
      { r: 2, c: 0, text: 'ul / ol / li' },
      { r: 2, c: 1, text: '无序与有序列表' },
      { r: 2, c: 2, text: '列表结构帮助辅助技术' },
      { r: 3, c: 0, text: 'a' },
      { r: 3, c: 1, text: '跳转到其他资源' },
      { r: 3, c: 2, text: '链接文字要说明目的地' },
    ],
    notes: ['标签表达语义，样式交给 CSS，行为交给 JavaScript'],
    caption: 'HTML 是内容与语义的载体；结构清晰是无障碍与搜索引擎优化的基础。',
  },
  html_basics: {
    image: 'diagram_web_html_semantic.webp',
    alt: '语义化页面结构',
    title: '语义化：用标签表达结构含义',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['header / nav', 'main', 'section / article', 'footer'],
    colLabels: ['语义', '典型内容', '注意点'],
    cells: [
      { r: 0, c: 0, text: '页头与导航区域' },
      { r: 0, c: 1, text: 'Logo、菜单与搜索' },
      { r: 0, c: 2, text: '导航用 nav 包裹' },
      { r: 1, c: 0, text: '页面唯一主内容' },
      { r: 1, c: 1, text: '每页只应有一个 main' },
      { r: 1, c: 2, text: '不要把侧栏放进去' },
      { r: 2, c: 0, text: '独立区块与可复用内容' },
      { r: 2, c: 1, text: '带标题的主题内容' },
      { r: 2, c: 2, text: 'section 应有标题' },
      { r: 3, c: 0, text: '页脚信息' },
      { r: 3, c: 1, text: '版权、联系方式与链接' },
      { r: 3, c: 2, text: '不要滥用 div' },
    ],
    notes: ['表单控件要关联 label，图片要有有意义的 alt'],
    caption: '语义标签让屏幕阅读器、搜索引擎和同事都能更快理解页面结构。',
  },
  css_selectors_intro: {
    image: 'diagram_web_css_selectors.webp',
    alt: 'CSS 选择器类型与特异性',
    title: '选择器入门：找到要样式化的元素',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['元素选择器', '类选择器', 'ID 选择器', '组合选择器'],
    colLabels: ['写法', '特异性', '建议'],
    cells: [
      { r: 0, c: 0, text: 'p { }' },
      { r: 0, c: 1, text: '最低' },
      { r: 0, c: 2, text: '适合基础排版' },
      { r: 1, c: 0, text: '.card { }' },
      { r: 1, c: 1, text: '中' },
      { r: 1, c: 2, text: '组件样式优先用类' },
      { r: 2, c: 0, text: '#app { }' },
      { r: 2, c: 1, text: '高' },
      { r: 2, c: 2, text: '尽量少用，避免难覆盖' },
      { r: 3, c: 0, text: '.card > .title' },
      { r: 3, c: 1, text: '累加' },
      { r: 3, c: 2, text: '保持选择器简短' },
    ],
    notes: ['层叠与继承决定最终生效值；优先级不是唯一手段'],
    caption: '优先使用低特异性、语义清晰的类选择器，让样式更容易覆盖与维护。',
  },
  css_basics: {
    image: 'diagram_web_css_basics.webp',
    alt: 'CSS 盒模型、单位与层叠',
    title: 'CSS 基础：盒模型与层叠',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['盒模型', '单位', '层叠', '继承'],
    colLabels: ['概念', '示例', '实践建议'],
    cells: [
      { r: 0, c: 0, text: 'content + padding + border + margin' },
      { r: 0, c: 1, text: 'box-sizing: border-box' },
      { r: 0, c: 2, text: '全局统一盒模型' },
      { r: 1, c: 0, text: '绝对与相对单位' },
      { r: 1, c: 1, text: 'rem、em、px、%' },
      { r: 1, c: 2, text: '字号用 rem，布局用相对单位' },
      { r: 2, c: 0, text: '优先级与来源顺序' },
      { r: 2, c: 1, text: '内联、ID、类、元素' },
      { r: 2, c: 2, text: '减少 !important' },
      { r: 3, c: 0, text: '可继承与不可继承属性' },
      { r: 3, c: 1, text: 'color 继承，border 不继承' },
      { r: 3, c: 2, text: '用继承减少重复声明' },
    ],
    notes: ['外边距折叠发生在块级元素之间，会影响垂直间距'],
    caption: '盒模型决定元素占多大空间，层叠与继承决定哪条规则最终生效。',
  },
  css_layout: {
    image: 'diagram_web_css_layout.webp',
    alt: 'Flex 与 Grid 的布局对比',
    title: '布局：Flex 一维，Grid 二维',
    type: 'compare',
    columns: [
      { title: 'Flexbox', items: ['沿主轴排列，适合一维布局', 'justify-content 控制主轴', 'align-items 控制交叉轴', 'flex-grow/shrink 分配空间', '导航、工具栏与卡片行'] },
      { title: 'Grid', items: ['同时定义行与列，二维布局', 'grid-template 定义轨道', 'gap 统一间距', '可用命名区域表达版式', '页面骨架与复杂面板'] },
    ],
    notes: ['定位与浮动仍有适用场景，但页面布局优先 Flex/Grid'],
    caption: '一维排列用 Flex，二维结构用 Grid；两者可以嵌套组合。',
  },
  css_render_animation: {
    image: 'diagram_web_css_render.webp',
    alt: '浏览器关键渲染路径',
    title: '渲染与动画：关键路径五步',
    type: 'flow',
    steps: [
      { title: '解析 HTML', desc: '构建 DOM 树' },
      { title: '解析 CSS', desc: '构建 CSSOM 并合并样式' },
      { title: '布局', desc: '计算元素位置与大小' },
      { title: '绘制', desc: '生成绘制指令与图层' },
      { title: '合成', desc: 'GPU 合成并显示到屏幕' },
    ],
    notes: ['transform 与 opacity 通常只触发合成，动画更流畅'],
    caption: '改布局属性会回流，改绘制属性会重绘；动画优先使用合成层属性。',
  },
  css_advanced: {
    image: 'diagram_web_css_advanced.webp',
    alt: 'CSS 变量、伪类与现代特性',
    title: 'CSS 进阶：变量、状态与现代特性',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['CSS 变量', '伪类', '现代选择器', '容器查询'],
    colLabels: ['作用', '示例', '实践建议'],
    cells: [
      { r: 0, c: 0, text: '集中管理主题与尺寸' },
      { r: 0, c: 1, text: '--color-primary: #2563eb' },
      { r: 0, c: 2, text: '语义化命名，避免直接存颜色' },
      { r: 1, c: 0, text: '表达交互与结构状态' },
      { r: 1, c: 1, text: ':hover、:focus-visible、:nth-child' },
      { r: 1, c: 2, text: '键盘焦点要可见' },
      { r: 2, c: 0, text: '减少类名与嵌套' },
      { r: 2, c: 1, text: ':is、:where、:has' },
      { r: 2, c: 2, text: '注意浏览器兼容' },
      { r: 3, c: 0, text: '按容器宽度响应' },
      { r: 3, c: 1, text: '@container' },
      { r: 3, c: 2, text: '组件级响应式更灵活' },
    ],
    notes: ['命名与分层比语法技巧更能决定样式长期可维护性'],
    caption: '现代 CSS 让主题、状态与响应式更内聚；但组织方式仍要服务于团队理解。',
  },
  html_css_project: {
    image: 'diagram_web_landing_project.webp',
    alt: '响应式落地页的实现流程',
    title: '实战落地页：从结构到响应式',
    type: 'flow',
    steps: [
      { title: '语义结构', desc: 'header、main、section、footer 分层' },
      { title: '移动优先', desc: '先写小屏布局，再用媒体查询增强' },
      { title: 'Flex 与 Grid', desc: '导航用 Flex，内容区用 Grid' },
      { title: '深色模式', desc: '变量切换主题并校验对比度' },
      { title: '质量检查', desc: '无障碍、性能与多尺寸回归' },
    ],
    notes: ['先保证内容与结构可用，再叠加视觉与动效'],
    caption: '落地页的质量取决于结构与响应式策略，而不是特效数量。',
  },
  web_performance: {
    image: 'diagram_web_performance.webp',
    alt: '核心 Web 指标与优化方向',
    title: '前端性能：三个核心指标',
    type: 'grid',
    rows: 3,
    cols: 3,
    rowLabels: ['LCP', 'INP', 'CLS'],
    colLabels: ['衡量什么', '优化方向', '验证方式'],
    cells: [
      { r: 0, c: 0, text: '最大内容绘制时间' },
      { r: 0, c: 1, text: '压缩图片、预加载关键资源' },
      { r: 0, c: 2, text: 'Lighthouse 与真实用户监控' },
      { r: 1, c: 0, text: '交互响应延迟' },
      { r: 1, c: 1, text: '拆分长任务、减少主线程阻塞' },
      { r: 1, c: 2, text: 'Performance 面板与 INP 归因' },
      { r: 2, c: 0, text: '布局偏移累积' },
      { r: 2, c: 1, text: '预留图片与广告尺寸' },
      { r: 2, c: 2, text: '布局偏移观察器' },
    ],
    notes: ['优化顺序：先测量真实用户数据，再定位瓶颈，最后验证收益'],
    caption: '性能不是一次性优化：建立指标基线，持续监控并防止回归。',
  },
  css_design_tokens: {
    image: 'diagram_web_design_tokens.webp',
    alt: '设计令牌的三层结构',
    title: '设计令牌：三层结构与主题',
    type: 'layers',
    layers: [
      { title: '基础令牌', desc: '原始色板、字号与间距刻度', fill: '#eef4ff', stroke: '#6c8ff8' },
      { title: '语义令牌', desc: 'text-primary、surface-hover 等语义名', fill: '#e8f2ff', stroke: '#6c8ff8' },
      { title: '组件令牌', desc: '按钮、卡片等组件的局部覆盖', fill: '#e6f7f1', stroke: '#3fae8a' },
      { title: '主题映射', desc: '浅色与深色模式切换同一语义令牌', fill: '#fff4e6', stroke: '#e6a23c' },
      { title: '校验与发布', desc: '对比度检查、版本化与跨端同步', fill: '#fdeeee', stroke: '#d97070' },
    ],
    widths: [0.72, 0.84, 0.9, 1, 0.9],
    caption: '组件只引用语义令牌，主题只重映射语义令牌；基础值变化不会散落到各处。',
  },
  a11y_aria: {
    image: 'diagram_web_a11y.webp',
    alt: '可访问性的原生优先与焦点管理',
    title: '可访问性：原生优先，ARIA 补充',
    type: 'layers',
    layers: [
      { title: '语义 HTML', desc: 'button、label、nav 自带可访问语义', fill: '#eef4ff', stroke: '#6c8ff8' },
      { title: '键盘可达', desc: '所有交互可用 Tab 与 Enter 操作', fill: '#e8f2ff', stroke: '#6c8ff8' },
      { title: '焦点管理', desc: '弹窗打开后聚焦，关闭后归还焦点', fill: '#e6f7f1', stroke: '#3fae8a' },
      { title: 'ARIA 补充', desc: '仅当原生元素无法表达时使用', fill: '#fff4e6', stroke: '#e6a23c' },
      { title: '验证方式', desc: '屏幕阅读器、自动扫描与人工走查', fill: '#fdeeee', stroke: '#d97070' },
    ],
    widths: [0.72, 0.84, 0.9, 1, 0.88],
    caption: '能用原生元素就不要用 ARIA；错误的 ARIA 比没有更糟，焦点顺序必须可预测。',
  },
  browser_rendering: {
    image: 'diagram_web_event_loop.webp',
    alt: '事件循环与任务队列',
    title: '事件循环：宏任务与微任务',
    type: 'sequence',
    actors: ['调用栈', '微任务队列', '宏任务队列', '渲染'],
    messages: [
      { from: 0, to: 1, label: '同步代码执行完毕后清空微任务' },
      { from: 1, to: 0, label: 'Promise 回调依次执行' },
      { from: 0, to: 2, label: '取下一个宏任务' },
      { from: 2, to: 0, label: '定时器与事件回调入栈' },
      { from: 0, to: 3, label: '浏览器伺机执行渲染' },
      { from: 3, to: 0, label: '长任务会阻塞渲染与交互' },
    ],
    notes: ['强制同步布局会打断优化，应批量读取再批量写入'],
    caption: '理解事件循环，才能解释为什么微任务先执行、长任务会卡住页面。',
  },
  web_pwa_offline: {
    image: 'diagram_web_pwa.webp',
    alt: 'Service Worker 缓存策略',
    title: 'PWA 离线：五种缓存策略',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['Cache First', 'Network First', 'Stale While Revalidate', '离线队列'],
    colLabels: ['策略', '适用资源', '注意点'],
    cells: [
      { r: 0, c: 0, text: '缓存优先，回退网络' },
      { r: 0, c: 1, text: '静态资源与字体' },
      { r: 0, c: 2, text: '更新要用版本化文件名' },
      { r: 1, c: 0, text: '网络优先，失败用缓存' },
      { r: 1, c: 1, text: '接口数据与页面' },
      { r: 1, c: 2, text: '注意超时与错误提示' },
      { r: 2, c: 0, text: '先用缓存同时后台更新' },
      { r: 2, c: 1, text: '频繁变化的列表' },
      { r: 2, c: 2, text: '要处理更新抖动' },
      { r: 3, c: 0, text: '离线暂存，恢复后重放' },
      { r: 3, c: 1, text: '表单与写操作' },
      { r: 3, c: 2, text: '注意幂等与冲突合并' },
    ],
    notes: ['Service Worker 要设计版本升级与旧缓存清理'],
    caption: '离线能力不是「全缓存」，而是按资源特征选择合适的缓存与同步策略。',
  },
  web_components: {
    image: 'diagram_web_components.webp',
    alt: 'Web Components 的核心能力',
    title: 'Web Components：自定义元素与隔离',
    type: 'layers',
    layers: [
      { title: '自定义元素', desc: 'customElements.define 注册标签', fill: '#eef4ff', stroke: '#6c8ff8' },
      { title: '生命周期', desc: 'connected、disconnected、attributeChanged', fill: '#e8f2ff', stroke: '#6c8ff8' },
      { title: 'Shadow DOM', desc: '样式与结构隔离，避免互相污染', fill: '#e6f7f1', stroke: '#3fae8a' },
      { title: '模板与插槽', desc: 'template 与 slot 组合内容', fill: '#fff4e6', stroke: '#e6a23c' },
      { title: '事件通信', desc: '自定义事件向上传递状态', fill: '#fdeeee', stroke: '#d97070' },
    ],
    widths: [0.72, 0.84, 0.9, 1, 0.86],
    caption: 'Shadow DOM 隔离样式，但事件、主题与无障碍仍需显式设计。',
  },
};
