// P6 网络课程配图数据。
module.exports = {
  network_layers_intro: {
    image: 'diagram_net_layers.webp',
    alt: '网络四层模型与协议对应',
    title: '网络分层：每层解决一件事',
    type: 'layers',
    layers: [
      { title: '应用层', desc: 'HTTP、DNS、SMTP 等业务协议', fill: '#eef4ff', stroke: '#6c8ff8' },
      { title: '传输层', desc: 'TCP 可靠传输，UDP 低开销报文', fill: '#e8f2ff', stroke: '#6c8ff8' },
      { title: '网络层', desc: 'IP 寻址与路由转发', fill: '#e6f7f1', stroke: '#3fae8a' },
      { title: '链路层', desc: '以太网、Wi-Fi 与物理介质', fill: '#fff4e6', stroke: '#e6a23c' },
    ],
    caption: '分层让每层只依赖下层提供的服务：排障时也从下往上确认链路是否通。',
  },
  ip_port_intro: {
    image: 'diagram_net_ip_port.webp',
    alt: 'IP 地址、端口与连接的关系',
    title: 'IP 与端口：定位主机与进程',
    type: 'grid',
    rows: 3,
    cols: 3,
    rowLabels: ['IP 地址', '端口', '连接'],
    colLabels: ['作用', '示例', '注意点'],
    cells: [
      { r: 0, c: 0, text: '定位网络中的主机' },
      { r: 0, c: 1, text: '192.168.1.10 或 2001:db8::1' },
      { r: 0, c: 2, text: '区分公网、内网与回环' },
      { r: 1, c: 0, text: '定位主机上的进程' },
      { r: 1, c: 1, text: 'HTTP 80、HTTPS 443' },
      { r: 1, c: 2, text: '0-1024 多为系统端口' },
      { r: 2, c: 0, text: '四元组标识一条连接' },
      { r: 2, c: 1, text: '源 IP、源端口、目的 IP、目的端口' },
      { r: 2, c: 2, text: 'NAT 会改写地址与端口' },
    ],
    notes: ['一台主机可以同时建立大量连接，靠端口区分不同进程'],
    caption: 'IP 找到机器，端口找到进程，四元组确定一条具体连接。',
  },
  tcp_ip: {
    image: 'diagram_net_tcp_ip.webp',
    alt: 'TCP 三次握手与四次挥手',
    title: 'TCP：三次握手建立可靠连接',
    type: 'sequence',
    actors: ['客户端', '服务端', '网络', '应用层'],
    messages: [
      { from: 0, to: 1, label: 'SYN，携带初始序列号' },
      { from: 1, to: 0, label: 'SYN + ACK，确认并回传序号' },
      { from: 0, to: 1, label: 'ACK，连接建立' },
      { from: 3, to: 3, label: '应用数据分片与编号' },
      { from: 2, to: 2, label: '超时重传与拥塞控制' },
      { from: 0, to: 1, label: 'FIN / ACK 四次挥手关闭' },
    ],
    notes: ['TCP 保证有序与可靠，UDP 保留报文边界但不保证到达'],
    caption: '三次握手确认双向可达与初始序号；可靠性由确认、重传与拥塞控制共同实现。',
  },
  dns: {
    image: 'diagram_net_dns.webp',
    alt: 'DNS 递归解析流程',
    title: 'DNS：域名如何变成 IP',
    type: 'flow',
    steps: [
      { title: '本地缓存', desc: '先查浏览器、系统与 hosts' },
      { title: '递归解析器', desc: '向运营商或公共 DNS 发起查询' },
      { title: '根与顶级域', desc: '逐级定位 .com 与权威服务器' },
      { title: '权威应答', desc: '返回 A/AAAA/CNAME 等记录' },
      { title: '缓存 TTL', desc: '按 TTL 缓存，减少后续查询' },
    ],
    notes: ['A 记录返回 IPv4，AAAA 返回 IPv6，CNAME 指向另一个域名'],
    caption: 'DNS 是分布式缓存系统：解析延迟主要取决于缓存命中与权威服务器响应。',
  },
  cdn_proxy: {
    image: 'diagram_net_cdn.webp',
    alt: 'CDN 边缘缓存与回源流程',
    title: 'CDN 与代理：把内容推到离用户更近',
    type: 'layers',
    layers: [
      { title: '用户请求', desc: '就近接入边缘节点', fill: '#eef4ff', stroke: '#6c8ff8' },
      { title: '边缘缓存', desc: '命中则直接返回，降低延迟', fill: '#e8f2ff', stroke: '#6c8ff8' },
      { title: '缓存策略', desc: 'Cache-Control、ETag 与过期时间', fill: '#e6f7f1', stroke: '#3fae8a' },
      { title: '回源', desc: '未命中时向源站取内容并缓存', fill: '#fff4e6', stroke: '#e6a23c' },
      { title: '动态加速', desc: '对不可缓存请求优化链路与连接', fill: '#fdeeee', stroke: '#d97070' },
    ],
    widths: [0.7, 0.84, 0.92, 1, 0.88],
    caption: '缓存命中率决定 CDN 收益；Cache-Control 与版本化 URL 是控制失效的主要手段。',
  },
  websocket: {
    image: 'diagram_net_websocket.webp',
    alt: 'WebSocket 握手与双向通信',
    title: 'WebSocket：一次升级，持续双向',
    type: 'sequence',
    actors: ['浏览器', '服务端', '网关', '业务系统'],
    messages: [
      { from: 0, to: 1, label: 'HTTP Upgrade 请求' },
      { from: 1, to: 0, label: '101 Switching Protocols' },
      { from: 0, to: 1, label: '客户端发送消息帧' },
      { from: 1, to: 0, label: '服务端主动推送' },
      { from: 0, to: 0, label: '心跳检测连接存活' },
      { from: 1, to: 3, label: '水平扩展需共享订阅状态' },
    ],
    notes: ['断线重连要带退避与状态补偿，不能只重连不补数据'],
    caption: 'WebSocket 解决服务端主动推送，但连接管理、心跳与多实例路由仍需自行设计。',
  },
  http2_http3: {
    image: 'diagram_net_http2_http3.webp',
    alt: 'HTTP/2 与 HTTP/3 的机制对比',
    title: 'HTTP/2 与 HTTP/3：多路复用的两条路',
    type: 'compare',
    columns: [
      { title: 'HTTP/2', items: ['基于 TCP，一条连接多路复用', 'HPACK 压缩请求头', '二进制分帧减少解析歧义', '队头阻塞仍可能发生在 TCP 层', '服务端推送使用需谨慎'] },
      { title: 'HTTP/3', items: ['基于 QUIC，默认加密', '流之间独立，避免 TCP 队头阻塞', '0-RTT 或 1-RTT 建连', '连接迁移适应网络切换', 'UDP 在某些网络可能受限'] },
    ],
    notes: ['协议升级要考虑中间设备兼容与回退策略'],
    caption: 'HTTP/2 在 TCP 上做多路复用，HTTP/3 用 QUIC 把流独立出来，弱网表现更好。',
  },
  wireless_mobile: {
    image: 'diagram_net_wireless.webp',
    alt: 'Wi-Fi 与蜂窝网络的特征对比',
    title: '无线与移动网络：共享介质与弱网',
    type: 'compare',
    columns: [
      { title: 'Wi-Fi', items: ['共享信道，CSMA/CA 避免冲突', '信号强度影响速率与丢包', '切换 AP 可能短暂中断', '局域网内延迟通常较低', '适合大流量与固定场景'] },
      { title: '蜂窝网络', items: ['基站调度与移动性管理', '弱网下延迟与抖动明显', '频繁切换基站需连接恢复', '流量与电量成本更高', '优化要容忍超时与重试'] },
    ],
    notes: ['移动端弱网优化：超时、重试、压缩、增量同步与离线缓存'],
    caption: '无线网络的不确定性来自共享介质与移动性，客户端必须假设网络随时会变差。',
  },
  network_attacks: {
    image: 'diagram_net_attacks.webp',
    alt: '网络攻击与纵深防御层次',
    title: '网络攻击与纵深防御',
    type: 'layers',
    layers: [
      { title: '网络边界', desc: '防火墙、WAF 与 DDoS 清洗', fill: '#eef4ff', stroke: '#6c8ff8' },
      { title: '传输安全', desc: 'TLS、证书校验与 HSTS', fill: '#e8f2ff', stroke: '#6c8ff8' },
      { title: '身份与访问', desc: '认证、授权与最小权限', fill: '#e6f7f1', stroke: '#3fae8a' },
      { title: '应用防护', desc: '输入校验、输出编码与限流', fill: '#fff4e6', stroke: '#e6a23c' },
      { title: '监测响应', desc: '日志、告警、封禁与复盘', fill: '#fdeeee', stroke: '#d97070' },
    ],
    widths: [0.7, 0.84, 0.9, 1, 0.86],
    caption: '单一防线必然会被绕过；纵深防御的目标是提高攻击成本并缩短发现时间。',
  },
  web_security: {
    image: 'diagram_net_web_security.webp',
    alt: '常见 Web 漏洞与防护手段',
    title: 'Web 安全：四类高频漏洞',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['XSS', 'CSRF', 'SQL 注入', 'SSRF'],
    colLabels: ['成因', '防护', '验证方式'],
    cells: [
      { r: 0, c: 0, text: '不可信内容被当作脚本执行' },
      { r: 0, c: 1, text: '输出编码与 CSP' },
      { r: 0, c: 2, text: '注入测试与浏览器验证' },
      { r: 1, c: 0, text: '浏览器自动携带凭证发起请求' },
      { r: 1, c: 1, text: 'CSRF Token 与 SameSite' },
      { r: 1, c: 2, text: '跨站请求复现' },
      { r: 2, c: 0, text: 'SQL 拼接了用户输入' },
      { r: 2, c: 1, text: '参数化查询与最小权限' },
      { r: 2, c: 2, text: '注入载荷与日志检查' },
      { r: 3, c: 0, text: '服务端请求了用户指定地址' },
      { r: 3, c: 1, text: 'URL 白名单与网络隔离' },
      { r: 3, c: 2, text: '内网地址探测' },
    ],
    notes: ['会话安全还包括 HttpOnly、Secure 与合理过期时间'],
    caption: 'Web 漏洞的共同点是信任了不可信输入；防护要把校验、编码与权限放在正确边界。',
  },
  network_project: {
    image: 'diagram_net_packet_project.webp',
    alt: '一次请求的抓包分析流程',
    title: '实战抓包：从 DNS 到 HTTP 全链路',
    type: 'flow',
    steps: [
      { title: '确定目标', desc: '记录 URL、时间与客户端环境' },
      { title: '开始抓包', desc: '过滤 host 与端口，控制范围' },
      { title: '看 DNS', desc: '确认解析结果与耗时' },
      { title: '看 TCP/TLS', desc: '握手、证书与重传情况' },
      { title: '看 HTTP', desc: '请求头、状态码与响应时间' },
    ],
    notes: ['排查顺序：先确认链路可达，再看协议细节，最后定位应用问题'],
    caption: '抓包的价值是把「感觉慢」拆成 DNS、连接、TLS 与应用各段的具体耗时。',
  },
  auth_oauth: {
    image: 'diagram_net_oauth.webp',
    alt: 'OAuth2 授权码流程',
    title: 'OAuth2：授权码流程怎么走',
    type: 'sequence',
    actors: ['用户', '客户端应用', '授权服务器', '资源服务器'],
    messages: [
      { from: 0, to: 2, label: '登录并同意授权' },
      { from: 2, to: 1, label: '重定向携带授权码' },
      { from: 1, to: 2, label: '用授权码换取令牌' },
      { from: 2, to: 1, label: '返回访问令牌与刷新令牌' },
      { from: 1, to: 3, label: '携带令牌访问资源' },
      { from: 3, to: 1, label: '校验声明并返回数据' },
    ],
    notes: ['PKCE 防止授权码被截获；令牌校验要检查签名、过期与受众'],
    caption: 'OAuth2 解决授权委托，不是登录协议；身份认证应使用 OpenID Connect。',
  },
  pentest_basics: {
    image: 'diagram_net_pentest.webp',
    alt: '渗透测试的授权与执行流程',
    title: '渗透测试：先授权，再验证',
    type: 'flow',
    steps: [
      { title: '授权与范围', desc: '书面授权、目标清单与时间窗口' },
      { title: '信息收集', desc: '资产、端口、指纹与公开信息' },
      { title: '漏洞验证', desc: '最小化验证，避免破坏数据' },
      { title: '影响评估', desc: '确认可利用性与业务影响' },
      { title: '报告与复测', desc: '复现步骤、修复建议与验证' },
    ],
    notes: ['未授权扫描与测试可能违法，范围与证据链必须清晰'],
    caption: '渗透测试的目标是验证风险与推动修复，不是炫技或造成破坏。',
  },
  network_ipv6: {
    image: 'diagram_net_ipv6.webp',
    alt: 'IPv6 的特性与迁移策略',
    title: 'IPv6：地址、自动配置与迁移',
    type: 'compare',
    columns: [
      { title: '协议特性', items: ['128 位地址空间', '地址分为网络前缀与接口标识', '邻居发现替代 ARP', 'SLAAC 支持无状态自动配置', '默认启用 IPsec 能力'] },
      { title: '迁移策略', items: ['双栈同时运行两套协议', 'NAT64/DNS64 过渡', '优先使用 IPv6，回退 IPv4', '监控两条链路质量', '应用避免硬编码地址族'] },
    ],
    notes: ['IPv6 没有广播，用组播与邻居发现完成链路交互'],
    caption: 'IPv6 迁移是长期共存过程：双栈、回退与监控缺一不可。',
  },
  network_p2p: {
    image: 'diagram_net_p2p.webp',
    alt: 'P2P 打洞与中继流程',
    title: 'P2P 与 NAT 穿透：直连优先，中继兜底',
    type: 'flow',
    steps: [
      { title: '注册与发现', desc: '通过 DHT 或信令服务找到对端' },
      { title: '交换候选地址', desc: '收集公网与内网地址候选' },
      { title: 'NAT 打洞', desc: '双方同时发包建立映射' },
      { title: '失败中继', desc: '无法直连时使用 TURN 转发' },
      { title: '信任与加密', desc: '校验节点身份，端到端加密' },
    ],
    notes: ['对称 NAT 常导致打洞失败，中继是可用性的保障'],
    caption: 'P2P 的目标是降低服务器带宽成本，但连接成功率依赖 NAT 类型与中继兜底。',
  },
  network_smtp: {
    image: 'diagram_net_smtp.webp',
    alt: '邮件投递链路与认证机制',
    title: '邮件协议：从发送到收件箱',
    type: 'sequence',
    actors: ['发件客户端', '发送服务器', '接收服务器', '收件客户端'],
    messages: [
      { from: 0, to: 1, label: 'SMTP 提交邮件' },
      { from: 1, to: 2, label: 'DNS 查询 MX 记录' },
      { from: 1, to: 2, label: 'SMTP 投递并协商 TLS' },
      { from: 2, to: 2, label: 'SPF / DKIM / DMARC 校验' },
      { from: 2, to: 3, label: 'IMAP 拉取或推送' },
      { from: 3, to: 0, label: '展示邮件与垃圾标记' },
    ],
    notes: ['SPF 验证发件 IP，DKIM 验证签名，DMARC 定义失败处理策略'],
    caption: '邮件是多方协作系统：投递成功不等于进入收件箱，信誉与认证同样关键。',
  },
};
