// P6 Rust 课程配图数据。
module.exports = {
  rust_basics: {
    image: 'diagram_rust_basics.webp',
    alt: 'Rust 的四个核心支柱',
    title: 'Rust 基础：所有权、借用、Result 与并发',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['所有权', '借用检查', 'Result', '并发安全'],
    colLabels: ['核心规则', '编译器保证', '代价与收益'],
    cells: [
      { r: 0, c: 0, text: '每个值只有一个所有者' },
      { r: 0, c: 1, text: '离开作用域自动释放' },
      { r: 0, c: 2, text: '无需 GC 也无需手动 free' },
      { r: 1, c: 0, text: '同一时刻一个可变借用' },
      { r: 1, c: 1, text: '或任意多个只读借用' },
      { r: 1, c: 2, text: '数据竞争在编译期被拒绝' },
      { r: 2, c: 0, text: '错误是返回值而非异常' },
      { r: 2, c: 1, text: '必须显式处理 Ok 与 Err' },
      { r: 2, c: 2, text: '错误路径清晰但代码略多' },
      { r: 3, c: 0, text: 'Send 与 Sync 标记线程安全' },
      { r: 3, c: 1, text: 'Arc 共享所有权，Mutex 保护可变' },
      { r: 3, c: 2, text: '并发错误前移到编译期' },
    ],
    notes: ['学习 Rust 的难点在所有权模型，而不是语法'],
    caption: 'Rust 用所有权与类型系统把内存和并发错误挡在编译期，代价是必须理解借用规则。',
  },
  rust_cargo_first: {
    image: 'diagram_rust_cargo.webp',
    alt: 'Cargo 项目的创建与构建流程',
    title: '第一个项目：Cargo 四步',
    type: 'flow',
    steps: [
      { title: 'cargo new', desc: '创建项目与 Cargo.toml' },
      { title: 'cargo run', desc: '编译并运行当前项目' },
      { title: 'cargo check', desc: '快速类型检查，不生成产物' },
      { title: 'cargo build', desc: '生成 debug 或 release 产物' },
    ],
    notes: ['Cargo.toml 管理依赖，Cargo.lock 锁定版本'],
    caption: 'Cargo 同时是包管理器、构建工具与测试入口，是 Rust 工程的统一基础。',
  },
  rust_variables_mutability: {
    image: 'diagram_rust_mutability.webp',
    alt: '不可变默认与可变声明',
    title: '变量与可变性：默认不可变',
    type: 'compare',
    columns: [
      { title: 'let 与 mut', items: ['let 声明默认不可变', 'let mut 显式允许修改', '编译器阻止意外写入', '不可变变量可安全共享', '可变作用域应尽量缩小'] },
      { title: '遮蔽与作用域', items: ['let 可重复声明同名变量', '遮蔽生成新变量而非修改', '可顺带改变类型', '块作用域结束即释放', '用遮蔽替代临时变量名'] },
    ],
    notes: ['mutability 是接口设计的一部分：默认收窄，需要时再开放'],
    caption: '不可变默认让「谁会修改」变得明确，遮蔽则让类型转换步骤保持线性。',
  },
  rust_conditions: {
    image: 'diagram_rust_conditions.webp',
    alt: 'Rust 条件分支与模式匹配',
    title: '条件判断：if 与 match',
    type: 'grid',
    rows: 3,
    cols: 3,
    rowLabels: ['if / else', 'match', 'if let'],
    colLabels: ['写法', '特点', '注意点'],
    cells: [
      { r: 0, c: 0, text: 'if score >= 60 { } else { }' },
      { r: 0, c: 1, text: '条件是 bool，分支可返回值' },
      { r: 0, c: 2, text: '两个分支类型必须一致' },
      { r: 1, c: 0, text: 'match value { ... }' },
      { r: 1, c: 1, text: '必须穷尽所有可能' },
      { r: 1, c: 2, text: '用 _ 兜底要谨慎' },
      { r: 2, c: 0, text: 'if let Some(v) = opt' },
      { r: 2, c: 1, text: '只关心一个匹配分支' },
      { r: 2, c: 2, text: '多分支仍用 match' },
    ],
    notes: ['match 的穷尽性检查会在新增枚举变体时提醒你处理'],
    caption: 'Rust 用模式匹配替代大量 if-else，编译器强制处理所有状态。',
  },
  rust_loops: {
    image: 'diagram_rust_loops.webp',
    alt: 'Rust 三种循环结构',
    title: '循环：loop、while 与 for',
    type: 'grid',
    rows: 3,
    cols: 3,
    rowLabels: ['loop', 'while', 'for'],
    colLabels: ['写法', '适用场景', '注意点'],
    cells: [
      { r: 0, c: 0, text: 'loop { break value; }' },
      { r: 0, c: 1, text: '无限循环并可返回值' },
      { r: 0, c: 2, text: '用 break 携带结果' },
      { r: 1, c: 0, text: 'while condition { }' },
      { r: 1, c: 1, text: '条件驱动，次数未知' },
      { r: 1, c: 2, text: '确保状态会推进' },
      { r: 2, c: 0, text: 'for item in collection' },
      { r: 2, c: 1, text: '遍历迭代器，最常用' },
      { r: 2, c: 2, text: '注意移动与借用' },
    ],
    notes: ['迭代器链通常比手写循环更清晰，也更易优化'],
    caption: 'Rust 的 for 直接消费迭代器，配合 map/filter 能把循环意图表达得更清楚。',
  },
  rust_functions_intro: {
    image: 'diagram_rust_functions.webp',
    alt: 'Rust 函数的参数、返回值与表达式',
    title: '函数入门：表达式与返回类型',
    type: 'flow',
    steps: [
      { title: '声明参数', desc: '每个参数都要写类型' },
      { title: '函数体', desc: '最后一行表达式即返回值' },
      { title: '返回 Result', desc: '可能失败时返回 Ok 或 Err' },
      { title: '调用与测试', desc: '用单元测试覆盖边界输入' },
    ],
    notes: ['最后一行不加分号才是表达式返回值，加了分号就变成语句'],
    caption: 'Rust 函数以表达式为中心：返回值类型写在箭头后，错误通过 Result 显式传递。',
  },
  rust_ownership: {
    image: 'diagram_rust_ownership.webp',
    alt: '所有权、借用与生命周期的关系',
    title: '所有权：Move、Copy、借用与生命周期',
    type: 'layers',
    layers: [
      { title: '所有权', desc: '每个值有唯一所有者，离开作用域即释放', fill: '#eef4ff', stroke: '#6c8ff8' },
      { title: 'Move 与 Copy', desc: '赋值默认移动；实现 Copy 的类型按位复制', fill: '#e8f2ff', stroke: '#6c8ff8' },
      { title: '借用', desc: '&T 共享只读，&mut T 独占可写', fill: '#e6f7f1', stroke: '#3fae8a' },
      { title: '生命周期', desc: '标注引用之间的有效期依赖', fill: '#fff4e6', stroke: '#e6a23c' },
      { title: '智能指针', desc: 'Box、Rc、RefCell、Arc 表达共享与内部可变', fill: '#fdeeee', stroke: '#d97070' },
    ],
    widths: [0.7, 0.82, 0.9, 1, 0.94],
    caption: '借用规则可以概括为：共享不可变，可变不共享；生命周期是编译器验证借用有效的依据。',
  },
  rust_types_traits: {
    image: 'diagram_rust_types_traits.webp',
    alt: 'Option、Result、trait 与模式匹配',
    title: '类型系统：用类型表达状态',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['Option', 'Result', 'trait', '模式匹配'],
    colLabels: ['表达什么', '典型写法', '工程价值'],
    cells: [
      { r: 0, c: 0, text: '值可能存在或不存在' },
      { r: 0, c: 1, text: 'Option<T>' },
      { r: 0, c: 2, text: '替代 null，强制处理缺失' },
      { r: 1, c: 0, text: '操作成功或失败' },
      { r: 1, c: 1, text: 'Result<T, E>' },
      { r: 1, c: 2, text: '错误必须显式处理' },
      { r: 2, c: 0, text: '共享行为契约' },
      { r: 2, c: 1, text: 'trait Trait { fn f(&self); }' },
      { r: 2, c: 2, text: '静态或动态分发' },
      { r: 3, c: 0, text: '按结构分支处理' },
      { r: 3, c: 1, text: 'match / if let / while let' },
      { r: 3, c: 2, text: '穷尽性由编译器保证' },
    ],
    notes: ['用类型表达非法状态不可表示，是 Rust 建模的核心思路'],
    caption: 'Option 与 Result 把空值和错误写进类型，trait 把共享行为抽象成契约。',
  },
  rust_traits_generics: {
    image: 'diagram_rust_traits_generics.webp',
    alt: '静态分发与动态分发对比',
    title: 'trait 与泛型：两种分发方式',
    type: 'compare',
    columns: [
      { title: '静态分发', items: ['泛型参数在编译期单态化', '无虚表查找开销', '可能增加二进制体积', '适合性能敏感的热路径', 'trait 约束写在泛型上'] },
      { title: '动态分发', items: ['dyn Trait 通过虚表调用', '运行时决定具体实现', '便于异构集合', '有间接调用开销', '对象安全是前提'] },
    ],
    notes: ['关联类型让 trait 表达「一个实现对应一种类型」的关系'],
    caption: '默认用泛型获得性能，需要运行时多态或异构集合时再用 dyn Trait。',
  },
  rust_errors_iterators: {
    image: 'diagram_rust_errors_iterators.webp',
    alt: '错误处理、迭代器与异步的配合',
    title: '错误、迭代器与异步',
    type: 'compare',
    columns: [
      { title: '错误处理', items: ['thiserror 定义领域错误', 'anyhow 用于应用层聚合', '? 运算符传播错误', '错误要保留上下文', '库不要 panic 处理可恢复错误'] },
      { title: '迭代器与异步', items: ['迭代器是零开销抽象', 'map/filter/collect 组合', '惰性执行，消费时才运行', 'tokio 提供异步运行时', 'async 函数返回 Future'] },
    ],
    notes: ['异步代码中的阻塞调用会卡住整个执行器线程'],
    caption: '错误用类型表达，迭代器用组合表达，异步用 Future 表达；三者都可以零成本抽象。',
  },
  rust_concurrency_cargo: {
    image: 'diagram_rust_concurrency.webp',
    alt: 'Rust 并发与工程工具',
    title: '并发与工程：从线程到异步',
    type: 'layers',
    layers: [
      { title: 'Send 与 Sync', desc: '编译期标记类型能否跨线程转移与共享', fill: '#eef4ff', stroke: '#6c8ff8' },
      { title: '标准线程', desc: 'thread::spawn 与 join 处理并行计算', fill: '#e8f2ff', stroke: '#6c8ff8' },
      { title: '共享状态', desc: 'Arc<Mutex<T>> 或通道传递消息', fill: '#e6f7f1', stroke: '#3fae8a' },
      { title: '异步运行时', desc: 'tokio 调度大量 IO 任务', fill: '#fff4e6', stroke: '#e6a23c' },
      { title: 'Cargo 工作流', desc: 'workspace、feature、测试与发布', fill: '#fdeeee', stroke: '#d97070' },
    ],
    widths: [0.72, 0.84, 0.9, 1, 0.92],
    caption: 'Rust 并发先用类型和所有权排除数据竞争，再按 IO 密集或 CPU 密集选择模型。',
  },
  rust_macros_wasm: {
    image: 'diagram_rust_macros_wasm.webp',
    alt: '宏、WASM 与跨平台的边界',
    title: '宏与 WASM：元编程与跨平台',
    type: 'compare',
    columns: [
      { title: '宏', items: ['macro_rules! 声明宏做模式替换', '过程宏在编译期生成代码', 'derive 宏自动实现 trait', '宏能减少样板但难调试', '优先用泛型与函数'] },
      { title: 'WASM 与跨平台', items: ['wasm-bindgen 连接 JS 与 Rust', 'WASM 适合计算密集型模块', '边界传输有序列化成本', '注意文件与线程能力差异', '交叉编译要验证目标平台'] },
    ],
    notes: ['宏展开可用 cargo expand 查看，便于理解生成代码'],
    caption: '宏扩展表达能力，WASM 扩展运行边界；两者都要先确认简单方案确实不够用。',
  },
  rust_unsafe_ffi: {
    image: 'diagram_rust_unsafe_ffi.webp',
    alt: 'unsafe 的能力与 FFI 互操作',
    title: 'unsafe 与 FFI：把风险局部化',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['unsafe 能力', 'C 互操作', '错误边界', '生态选择'],
    colLabels: ['内容', '写法', '实践要求'],
    cells: [
      { r: 0, c: 0, text: '解引用裸指针' },
      { r: 0, c: 1, text: 'unsafe { *ptr }' },
      { r: 0, c: 2, text: '必须说明安全前提' },
      { r: 1, c: 0, text: '调用 unsafe 函数或外部函数' },
      { r: 1, c: 1, text: 'extern "C" 声明接口' },
      { r: 1, c: 2, text: '用安全封装隔离边界' },
      { r: 2, c: 0, text: '访问可变静态或联合体字段' },
      { r: 2, c: 1, text: '谨慎处理生命周期' },
      { r: 2, c: 2, text: '不能靠 unsafe 绕过借用检查' },
      { r: 3, c: 0, text: '选择成熟 crate 而非重造' },
      { r: 3, c: 1, text: 'bindgen、cbindgen 生成绑定' },
      { r: 3, c: 2, text: '测试覆盖跨语言边界' },
    ],
    notes: ['unsafe 不是关闭检查，而是把必须人工保证的契约写进代码'],
    caption: 'FFI 的每一处边界都要有明确的安全不变量与测试，否则内存错误会跨语言传播。',
  },
  rust_cli_project: {
    image: 'diagram_rust_cli_project.webp',
    alt: 'Rust 命令行工具的实现流程',
    title: '实战 CLI：解析、错误与发布',
    type: 'flow',
    steps: [
      { title: 'clap 解析', desc: '声明子命令、参数与帮助信息' },
      { title: '领域逻辑', desc: '把 IO 与业务计算分离' },
      { title: '错误处理', desc: 'anyhow 汇总并输出可读信息' },
      { title: 'assert_cmd 测试', desc: '端到端验证命令输出与退出码' },
      { title: '发布二进制', desc: '交叉编译并附带校验和' },
    ],
    notes: ['CLI 的退出码、标准输出与错误输出都是公开接口'],
    caption: 'Rust CLI 的优势是单文件发布与可靠错误处理，测试要覆盖真实命令行调用。',
  },
  rust_project_axum_api: {
    image: 'diagram_rust_axum_api.webp',
    alt: 'Axum REST API 的请求链路',
    title: '实战 Axum API：异步请求链路',
    type: 'sequence',
    actors: ['客户端', 'Axum 路由', '业务服务', 'SQLx / 数据库'],
    messages: [
      { from: 0, to: 1, label: '发送 HTTP 请求' },
      { from: 1, to: 1, label: '中间件：追踪与超时' },
      { from: 1, to: 2, label: '反序列化并校验入参' },
      { from: 2, to: 3, label: '异步查询或写入' },
      { from: 3, to: 2, label: '返回领域结果' },
      { from: 2, to: 0, label: '序列化 JSON 与状态码' },
    ],
    notes: ['集成测试启动真实路由与临时数据库，覆盖错误路径'],
    caption: 'Axum 负责路由与提取器，业务层保持纯异步函数，数据库访问集中在仓储层。',
  },
  rust_project_downloader: {
    image: 'diagram_rust_downloader.webp',
    alt: '并发下载器的任务流程',
    title: '实战下载器：限流、重试与进度',
    type: 'flow',
    steps: [
      { title: '读取任务', desc: '解析 URL 列表与目标路径' },
      { title: 'Semaphore 限流', desc: '限制同时下载的连接数' },
      { title: '分块与重试', desc: '断点续传，失败指数退避' },
      { title: '统计进度', desc: '原子计数并定期上报' },
      { title: '汇总错误', desc: '取消传播，输出失败清单' },
    ],
    notes: ['取消与超时要贯穿每一层，避免任务悬挂'],
    caption: '下载器的核心不是并发数，而是限流、重试、断点与取消四件事的配合。',
  },
};
