// P6 安全与合规课程配图数据。
module.exports = {
  security_concept_intro: {
    image: 'diagram_sec_concepts.webp',
    alt: '资产、威胁、漏洞与风险的关系',
    title: '安全概念：资产、威胁、漏洞与风险',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['资产', '威胁', '漏洞', '风险'],
    colLabels: ['定义', '例子', '处理方式'],
    cells: [
      { r: 0, c: 0, text: '需要保护的东西' },
      { r: 0, c: 1, text: '数据、账号、服务与声誉' },
      { r: 0, c: 2, text: '先盘点再分级' },
      { r: 1, c: 0, text: '可能造成损害的来源' },
      { r: 1, c: 1, text: '攻击者、恶意软件与误操作' },
      { r: 1, c: 2, text: '分析动机与能力' },
      { r: 2, c: 0, text: '可被利用的弱点' },
      { r: 2, c: 1, text: '弱密码、注入与配置错误' },
      { r: 2, c: 2, text: '修复或缓解' },
      { r: 3, c: 0, text: '威胁利用漏洞造成损失的可能' },
      { r: 3, c: 1, text: '概率乘以影响' },
      { r: 3, c: 2, text: '按优先级投入防护' },
    ],
    notes: ['安全不是零风险，而是把风险降到业务可接受的范围'],
    caption: '先识别资产与威胁，再评估漏洞与影响，最后按风险排序投入资源。',
  },
  password_hash_intro: {
    image: 'diagram_sec_password_hash.webp',
    alt: '加密、哈希与密码哈希的区别',
    title: '密码与哈希：三种机制不要混用',
    type: 'compare',
    columns: [
      { title: '加密与哈希', items: ['加密可逆，需要密钥', '哈希单向，固定长度输出', '哈希用于完整性校验', 'MD5/SHA-1 已不适合安全场景', '普通哈希太快，不适合存密码'] },
      { title: '密码哈希', items: ['加盐防止彩虹表', '慢哈希增加暴力成本', 'bcrypt、scrypt、Argon2', '每个用户独立随机盐', '参数随硬件升级而调整'] },
    ],
    notes: ['永远不要自己设计密码哈希方案，使用成熟库与推荐参数'],
    caption: '加密解决机密性，哈希解决完整性，慢哈希解决密码存储；三者目标完全不同。',
  },
  security_threat_model: {
    image: 'diagram_sec_threat_model.webp',
    alt: 'STRIDE 威胁建模流程',
    title: '威胁建模：用 STRIDE 分类风险',
    type: 'flow',
    steps: [
      { title: '画数据流图', desc: '标注资产、进程、存储与信任边界' },
      { title: '识别威胁', desc: '按 STRIDE 六类逐项提问' },
      { title: '评估风险', desc: '结合可能性与影响排序' },
      { title: '设计缓解', desc: '验证、授权、加密与监控' },
      { title: '持续更新', desc: '架构变化后重新评审' },
    ],
    notes: ['STRIDE：仿冒、篡改、否认、信息泄露、拒绝服务、权限提升'],
    caption: '威胁建模在编码前发现问题，成本远低于上线后修复；关键是围绕信任边界提问。',
  },
  security_owasp_top10: {
    image: 'diagram_sec_owasp.webp',
    alt: 'OWASP Top 10 常见风险与修复',
    title: 'OWASP Top 10：常见 Web 风险速览',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['访问控制', '注入', '加密失败', '配置错误'],
    colLabels: ['典型表现', '修复要点', '验证方式'],
    cells: [
      { r: 0, c: 0, text: '越权访问他人数据' },
      { r: 0, c: 1, text: '服务端强制校验权限' },
      { r: 0, c: 2, text: '多角色越权测试' },
      { r: 1, c: 0, text: 'SQL/命令/模板注入' },
      { r: 1, c: 1, text: '参数化与白名单' },
      { r: 1, c: 2, text: '注入载荷回归' },
      { r: 2, c: 0, text: '明文传输或弱算法' },
      { r: 2, c: 1, text: 'TLS 与强加密套件' },
      { r: 2, c: 2, text: '扫描与配置核查' },
      { r: 3, c: 0, text: '默认口令与开放端口' },
      { r: 3, c: 1, text: '最小化暴露与加固基线' },
      { r: 3, c: 2, text: '基线检查与渗透复测' },
    ],
    notes: ['其余风险包括身份认证失败、组件过期、日志监控不足与 SSRF'],
    caption: 'OWASP 不是清单打卡，而是提醒把校验、权限与配置放在正确的边界。',
  },
  security_secure_coding: {
    image: 'diagram_sec_secure_coding.webp',
    alt: '安全编码的五个实践层次',
    title: '安全编码：把防护落实到边界',
    type: 'layers',
    layers: [
      { title: '输入校验', desc: '类型、范围、长度与白名单', fill: '#eef4ff', stroke: '#6c8ff8' },
      { title: '输出编码', desc: '按上下文编码，防止注入', fill: '#e8f2ff', stroke: '#6c8ff8' },
      { title: '最小权限', desc: '账号、进程与数据访问都收窄', fill: '#e6f7f1', stroke: '#3fae8a' },
      { title: '错误处理', desc: '不泄露内部信息，保留可诊断日志', fill: '#fff4e6', stroke: '#e6a23c' },
      { title: '依赖与配置', desc: '锁定版本，安全默认值', fill: '#fdeeee', stroke: '#d97070' },
    ],
    widths: [0.72, 0.82, 0.9, 1, 0.88],
    caption: '安全编码的核心是边界：所有外部输入都不可信，所有敏感操作都要校验权限。',
  },
  security_auth_session: {
    image: 'diagram_sec_auth_session.webp',
    alt: '会话与令牌安全的关键点',
    title: '认证与会话：Session 与 JWT',
    type: 'compare',
    columns: [
      { title: 'Session', items: ['服务端保存会话状态', '浏览器只持有会话 ID', '注销可立即失效', '需要共享存储支持多实例', 'Cookie 要 HttpOnly 与 Secure'] },
      { title: 'JWT', items: ['签名声明由客户端携带', '服务端无状态校验', '过期时间要短', '刷新令牌单独管理', '注销依赖黑名单或版本号'] },
    ],
    notes: ['密码用慢哈希；令牌校验签名、过期、受众与签发者'],
    caption: 'Session 易失效但需存储，JWT 易扩展但难撤销；按业务对撤销与扩展的要求选择。',
  },
  security_secrets: {
    image: 'diagram_sec_secrets.webp',
    alt: '密钥与配置的安全管理层次',
    title: '密钥管理：不落盘、可轮换、可审计',
    type: 'layers',
    layers: [
      { title: '集中存储', desc: '密钥管理服务或加密配置中心', fill: '#eef4ff', stroke: '#6c8ff8' },
      { title: '最小授权', desc: '按服务与环境保护，禁止共享', fill: '#e8f2ff', stroke: '#6c8ff8' },
      { title: '注入方式', desc: '运行时注入，避免写入镜像与仓库', fill: '#e6f7f1', stroke: '#3fae8a' },
      { title: '轮换策略', desc: '定期轮换，支持双密钥过渡', fill: '#fff4e6', stroke: '#e6a23c' },
      { title: '审计告警', desc: '记录读取与变更，异常访问告警', fill: '#fdeeee', stroke: '#d97070' },
    ],
    widths: [0.72, 0.82, 0.9, 1, 0.9],
    caption: '密钥一旦进入 Git 历史就应视为泄露：立即轮换，而不是只删文件。',
  },
  security_supply_chain: {
    image: 'diagram_sec_supply_chain.webp',
    alt: '软件供应链安全的四个环节',
    title: '供应链安全：从依赖到制品',
    type: 'flow',
    steps: [
      { title: '依赖治理', desc: '锁定版本、扫描漏洞与许可证' },
      { title: '构建可信', desc: '隔离构建环境，限制网络与凭证' },
      { title: '制品签名', desc: '签名镜像与二进制，校验来源' },
      { title: 'SBOM 与追溯', desc: '记录组件清单，快速响应漏洞' },
    ],
    notes: ['依赖扫描要进入 CI 门禁，高危漏洞阻止发布'],
    caption: '供应链攻击利用的是信任链；每一步都要能回答「这个制品由谁、用什么代码构建」。',
  },
  security_container_k8s: {
    image: 'diagram_sec_k8s.webp',
    alt: '容器与 Kubernetes 安全层次',
    title: '容器与 K8s：从镜像到运行时',
    type: 'layers',
    layers: [
      { title: '镜像安全', desc: '最小基础镜像、扫描漏洞与签名', fill: '#eef4ff', stroke: '#6c8ff8' },
      { title: '运行时限制', desc: '非 root、只读文件系统与能力裁剪', fill: '#e8f2ff', stroke: '#6c8ff8' },
      { title: 'RBAC 权限', desc: '按最小权限授予服务账号', fill: '#e6f7f1', stroke: '#3fae8a' },
      { title: '网络策略', desc: '默认拒绝，按需开放东西向流量', fill: '#fff4e6', stroke: '#e6a23c' },
      { title: '审计与准入', desc: '记录 API 调用，准入控制拦截风险配置', fill: '#fdeeee', stroke: '#d97070' },
    ],
    widths: [0.7, 0.86, 0.9, 1, 0.94],
    caption: '容器不是安全边界；命名空间、cgroup 与集群策略共同决定隔离强度。',
  },
  security_cloud: {
    image: 'diagram_sec_cloud.webp',
    alt: '云安全与 IAM 的关键控制点',
    title: '云安全：身份即边界',
    type: 'layers',
    layers: [
      { title: '账号与身份', desc: '组织、账号与联合身份管理', fill: '#eef4ff', stroke: '#6c8ff8' },
      { title: '权限策略', desc: '最小权限、权限边界与条件限制', fill: '#e8f2ff', stroke: '#6c8ff8' },
      { title: '临时凭证', desc: '角色扮演，避免长期 Access Key', fill: '#e6f7f1', stroke: '#3fae8a' },
      { title: '网络与资源', desc: '安全组、私有子网与资源策略', fill: '#fff4e6', stroke: '#e6a23c' },
      { title: '日志与审计', desc: '集中记录云审计日志并告警', fill: '#fdeeee', stroke: '#d97070' },
    ],
    widths: [0.7, 0.86, 0.9, 1, 0.9],
    caption: '云环境的攻击面由配置决定；默认拒绝与持续审计比一次性加固更有效。',
  },
  security_privacy: {
    image: 'diagram_sec_privacy.webp',
    alt: '隐私合规与数据分级流程',
    title: '隐私合规：从分级到用户权利',
    type: 'flow',
    steps: [
      { title: '数据分级', desc: '区分公开、内部、敏感与个人数据' },
      { title: '最小收集', desc: '只收集业务必需字段' },
      { title: '保留期限', desc: '到期删除或匿名化' },
      { title: '访问与共享', desc: '授权、脱敏与第三方评估' },
      { title: '用户权利', desc: '查询、更正、导出与删除' },
    ],
    notes: ['合规要求随地区与行业变化，需保留数据处理记录'],
    caption: '隐私保护的工程落点是分级、最小化、期限与可追溯，而不是一份政策文档。',
  },
  security_fuzzing: {
    image: 'diagram_sec_fuzzing.webp',
    alt: '模糊测试的输入生成与验证流程',
    title: '模糊测试：让程序自己找崩溃',
    type: 'flow',
    steps: [
      { title: '定义目标', desc: '选择解析器、协议或文件格式入口' },
      { title: '生成输入', desc: '变异种子或基于语法生成' },
      { title: '运行与监控', desc: '捕获崩溃、超时与内存错误' },
      { title: '最小化用例', desc: '缩减到可复现的最小输入' },
      { title: '修复与回归', desc: '补测试并加入语料库' },
    ],
    notes: ['差分模糊测试对比多个实现，能发现语义不一致'],
    caption: '模糊测试适合解析外部输入的场景；崩溃用例要进入长期回归语料。',
  },
  security_incident: {
    image: 'diagram_sec_incident.webp',
    alt: '安全事件响应的闭环流程',
    title: '事件响应：发现到复盘的闭环',
    type: 'cycle',
    nodes: [
      { title: '发现', desc: '告警与上报' },
      { title: '隔离', desc: '止损与遏制' },
      { title: '取证', desc: '保留证据链' },
      { title: '恢复', desc: '安全恢复服务' },
      { title: '复盘', desc: '改进防护' },
    ],
    center: '事件响应',
    notes: ['通知与合规上报有时限要求，流程要提前演练'],
    caption: '事件响应的目标是控制影响并保留证据；复盘产出必须转化为可执行的改进项。',
  },
  security_sdl: {
    image: 'diagram_sec_sdl.webp',
    alt: '安全开发生命周期的流程',
    title: 'SDL：把安全串进研发流程',
    type: 'flow',
    steps: [
      { title: '安全需求', desc: '明确资产、合规与威胁场景' },
      { title: '设计评审', desc: '威胁建模与信任边界分析' },
      { title: '编码门禁', desc: 'SAST、依赖扫描与密钥扫描' },
      { title: '测试验证', desc: 'DAST、渗透测试与漏洞复测' },
      { title: '上线监控', desc: '运行时防护与应急响应' },
    ],
    notes: ['安全门禁要有明确标准与豁免流程，否则会被绕过'],
    caption: 'SDL 把安全从左移检查变成持续流程：每个阶段都有输入、输出与责任人。',
  },
  security_project: {
    image: 'diagram_sec_audit_project.webp',
    alt: '安全审计与漏洞修复流程',
    title: '实战安全审计：从建模到复测',
    type: 'flow',
    steps: [
      { title: '威胁建模', desc: '梳理资产、入口与信任边界' },
      { title: '代码审计', desc: '重点看认证、授权、输入与密钥' },
      { title: '漏洞验证', desc: '最小化复现并评估影响' },
      { title: '修复加固', desc: '代码修复、配置调整与回归' },
      { title: '复测与报告', desc: '确认修复，沉淀检查清单' },
    ],
    notes: ['修复要同时覆盖同类问题，避免只改一处复现点'],
    caption: '一次审计的产出不只是漏洞列表，还应包括可复用的建模方法与检查规则。',
  },
};
