// P7 C 语言课程配图数据。
module.exports = {
  c_basics: {
    image: 'diagram_c_build.webp',
    alt: 'C 程序从源码到可执行文件',
    title: 'C 编译流程：四个阶段',
    type: 'flow',
    steps: [
      { title: '预处理', desc: '展开宏与 include 头文件' },
      { title: '编译', desc: '语法分析并生成汇编' },
      { title: '汇编', desc: '生成目标文件 .o' },
      { title: '链接', desc: '合并库与目标文件，解析符号' },
    ],
    notes: ['头文件写声明，源文件写定义，用 include guard 防重复'],
    caption: '理解四阶段，才能解释「未定义引用」与「重复定义」这两类链接错误。',
  },
  c_first_program: {
    image: 'diagram_c_first_program.webp',
    alt: '编译并运行最小 C 程序',
    title: '第一个程序：源码到运行',
    type: 'flow',
    steps: [
      { title: '#include', desc: '引入 stdio.h 等标准头文件' },
      { title: 'main 函数', desc: '程序入口，返回 int 状态码' },
      { title: 'gcc 编译', desc: 'gcc main.c -o app -Wall -Wextra' },
      { title: '运行验证', desc: '执行程序并检查退出码' },
    ],
    notes: ['打开 -Wall -Wextra 能在入门阶段发现大量未定义行为'],
    caption: 'C 程序必须显式编译链接；编译器警告往往指向真实的内存或类型问题。',
  },
  c_variables_io: {
    image: 'diagram_c_variables_io.webp',
    alt: 'C 变量、格式化输入输出与检查',
    title: '变量与输入输出：格式要匹配类型',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['基本类型', 'printf', 'scanf', '返回值检查'],
    colLabels: ['写法', '作用', '注意点'],
    cells: [
      { r: 0, c: 0, text: 'int、double、char' },
      { r: 0, c: 1, text: '声明并初始化变量' },
      { r: 0, c: 2, text: '未初始化变量值不确定' },
      { r: 1, c: 0, text: 'printf("%d\\n", n);' },
      { r: 1, c: 1, text: '按格式串输出值' },
      { r: 1, c: 2, text: '格式符与类型必须匹配' },
      { r: 2, c: 0, text: 'scanf("%d", &n);' },
      { r: 2, c: 1, text: '读取并解析输入' },
      { r: 2, c: 2, text: '忘记取地址符会崩溃' },
      { r: 3, c: 0, text: 'if (scanf(...) != 1)' },
      { r: 3, c: 1, text: '检查解析是否成功' },
      { r: 3, c: 2, text: '输入流错误要处理' },
    ],
    notes: ['scanf 读取字符串要用宽度限制，避免缓冲区溢出'],
    caption: 'C 不替你做类型检查与边界检查，格式化 IO 的每个格式符都要自己负责。',
  },
  c_types: {
    image: 'diagram_c_types.webp',
    alt: 'C 类型、转换与未定义行为',
    title: '类型与转换：宽度和溢出',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['整数宽度', '有符号溢出', '隐式转换', '浮点精度'],
    colLabels: ['规则', '风险', '建议'],
    cells: [
      { r: 0, c: 0, text: 'int 宽度平台相关' },
      { r: 0, c: 1, text: '跨平台假设会出错' },
      { r: 0, c: 2, text: '协议用 stdint.h 固定宽度' },
      { r: 1, c: 0, text: '有符号溢出是未定义行为' },
      { r: 1, c: 1, text: '优化器可能产生意外结果' },
      { r: 1, c: 2, text: '运算前检查范围' },
      { r: 2, c: 0, text: '混合类型自动提升' },
      { r: 2, c: 1, text: '有符号转无符号变极大值' },
      { r: 2, c: 2, text: '显式转换并加注释' },
      { r: 3, c: 0, text: 'float/double 精度有限' },
      { r: 3, c: 1, text: '直接比较相等通常错误' },
      { r: 3, c: 2, text: '用误差范围比较' },
    ],
    notes: ['sizeof 返回 size_t，是无符号类型，减法比较要特别小心'],
    caption: 'C 的类型规则贴近机器：宽度、符号与提升规则必须显式考虑。',
  },
  c_conditions: {
    image: 'diagram_c_conditions.webp',
    alt: 'C 条件分支与常见错误',
    title: '条件判断：if 与 switch',
    type: 'grid',
    rows: 3,
    cols: 3,
    rowLabels: ['if / else', 'switch', '边界判断'],
    colLabels: ['写法', '适用场景', '常见错误'],
    cells: [
      { r: 0, c: 0, text: 'if (score >= 60) { }' },
      { r: 0, c: 1, text: '范围与布尔条件' },
      { r: 0, c: 2, text: '误用 = 代替 ==' },
      { r: 1, c: 0, text: 'switch (code) { case 1: ... }' },
      { r: 1, c: 1, text: '离散整数分支' },
      { r: 1, c: 2, text: '忘记 break 会穿透' },
      { r: 2, c: 0, text: 'if (x > 0 && x < n)' },
      { r: 2, c: 1, text: '数组与循环边界检查' },
      { r: 2, c: 2, text: '差一错误导致越界' },
    ],
    notes: ['枚举与状态码建议用 switch 并开启编译器警告'],
    caption: 'C 的条件表达式没有布尔类型保护，写判断时要把边界与副作用都想清楚。',
  },
  c_loops: {
    image: 'diagram_c_loops.webp',
    alt: 'C 循环结构与边界',
    title: '循环：for、while 与 do-while',
    type: 'grid',
    rows: 3,
    cols: 3,
    rowLabels: ['for', 'while', 'do-while'],
    colLabels: ['写法', '适用场景', '注意点'],
    cells: [
      { r: 0, c: 0, text: 'for (i = 0; i < n; i++)' },
      { r: 0, c: 1, text: '已知次数与索引遍历' },
      { r: 0, c: 2, text: '边界是 < 还是 <=' },
      { r: 1, c: 0, text: 'while (condition) { }' },
      { r: 1, c: 1, text: '条件驱动，次数未知' },
      { r: 1, c: 2, text: '确保条件会变假' },
      { r: 2, c: 0, text: 'do { } while (condition);' },
      { r: 2, c: 1, text: '至少执行一次' },
      { r: 2, c: 2, text: '注意结尾分号' },
    ],
    notes: ['循环不变量能帮助验证边界：每次迭代前后什么条件必须成立'],
    caption: 'C 的循环没有边界检查，越界写入不会当场报错，却可能在别处崩溃。',
  },
  c_functions_intro: {
    image: 'diagram_c_functions.webp',
    alt: 'C 函数的声明、定义与调用栈',
    title: '函数入门：声明、定义与栈帧',
    type: 'layers',
    layers: [
      { title: '函数声明', desc: '头文件中声明签名，供调用方编译', fill: '#eef4ff', stroke: '#6c8ff8' },
      { title: '函数定义', desc: '源文件中实现逻辑', fill: '#e8f2ff', stroke: '#6c8ff8' },
      { title: '参数传递', desc: 'C 只有值传递，传指针才能修改', fill: '#e6f7f1', stroke: '#3fae8a' },
      { title: '栈帧', desc: '局部变量与返回地址在调用栈上', fill: '#fff4e6', stroke: '#e6a23c' },
      { title: '返回值', desc: '返回错误码，调用方必须检查', fill: '#fdeeee', stroke: '#d97070' },
    ],
    widths: [0.72, 0.82, 0.9, 1, 0.86],
    caption: '返回局部变量的地址是悬垂指针；C 的函数边界需要自己维护生命周期。',
  },
  c_control_functions: {
    image: 'diagram_c_control_functions.webp',
    alt: '控制流、函数与作用域',
    title: '控制流与函数：作用域和生命周期',
    type: 'compare',
    columns: [
      { title: '控制流', items: ['if/else 表达范围判断', 'switch 处理离散状态', '循环必须有明确终止条件', 'break 跳出，continue 跳过', 'goto 仅用于统一清理路径'] },
      { title: '函数与作用域', items: ['块作用域决定变量可见性', 'static 延长或限制链接范围', '值传递不会修改实参', '指针参数要说明所有权', '递归注意栈深度'] },
    ],
    notes: ['局部变量未初始化即读取是未定义行为'],
    caption: 'C 把作用域与存储期分开：变量在哪可见、活多久，是两件独立的事。',
  },
  c_arrays_strings: {
    image: 'diagram_c_arrays_strings.webp',
    alt: '数组、字符串与缓冲区安全',
    title: '数组与字符串：边界就是安全线',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['数组', 'C 字符串', '缓冲区', '安全函数'],
    colLabels: ['规则', '风险', '建议'],
    cells: [
      { r: 0, c: 0, text: '下标从 0 开始，长度固定' },
      { r: 0, c: 1, text: '越界读写是未定义行为' },
      { r: 0, c: 2, text: '传递长度并校验下标' },
      { r: 1, c: 0, text: '以 \\0 结尾的字符数组' },
      { r: 1, c: 1, text: '忘记终止符会越界读取' },
      { r: 1, c: 2, text: '预留一个字节放 \\0' },
      { r: 2, c: 0, text: '固定缓冲区容量有限' },
      { r: 2, c: 1, text: 'strcpy/strcat 可能溢出' },
      { r: 2, c: 2, text: '优先 snprintf 等有界函数' },
      { r: 3, c: 0, text: '长度与内容分开管理' },
      { r: 3, c: 1, text: 'off-by-one 最难排查' },
      { r: 3, c: 2, text: '用 ASan 与单元测试验证' },
    ],
    notes: ['memcpy 要求源与目标不重叠，重叠时用 memmove'],
    caption: 'C 字符串没有长度元数据，每次复制与拼接都必须确认剩余空间。',
  },
  c_files: {
    image: 'diagram_c_files.webp',
    alt: 'C 文件操作的完整流程',
    title: '文件操作：打开、读写、检查、关闭',
    type: 'flow',
    steps: [
      { title: 'fopen', desc: '检查返回值是否为 NULL' },
      { title: '读写', desc: '按格式或二进制块处理数据' },
      { title: '错误检查', desc: 'ferror 与 errno 定位原因' },
      { title: 'fclose', desc: '确保数据刷盘并释放句柄' },
    ],
    notes: ['每条失败路径都要释放已获取的资源，避免句柄泄漏'],
    caption: '文件 IO 是典型的资源管理场景：打开成功只是开始，所有路径都要正确关闭。',
  },
  c_debugging: {
    image: 'diagram_c_debugging.webp',
    alt: 'C 调试与内存检查工具链',
    title: '调试与检查：让错误尽早暴露',
    type: 'flow',
    steps: [
      { title: '编译告警', desc: '-Wall -Wextra -Werror 严格检查' },
      { title: 'GDB 调试', desc: '断点、调用栈与变量查看' },
      { title: 'ASan', desc: '检测越界、悬垂与内存泄漏' },
      { title: 'UBSan', desc: '捕获溢出、移位与类型错误' },
      { title: '性能剖析', desc: 'perf 与 gprof 定位热点' },
    ],
    notes: ['Sanitizer 要在测试环境开启，代价是运行速度下降'],
    caption: 'C 的错误常常延迟爆发；用工具在开发阶段捕获，比线上崩溃后再查便宜得多。',
  },
  c_project: {
    image: 'diagram_c_task_project.webp',
    alt: 'C 命令行任务管理器实现流程',
    title: '实战任务管理器：结构化 C 工程',
    type: 'flow',
    steps: [
      { title: '数据结构', desc: '定义任务结构体与动态数组' },
      { title: '命令解析', desc: '解析 add、list、done、remove' },
      { title: '文件持久化', desc: '用文本或二进制格式保存并加载' },
      { title: 'Makefile', desc: '分目标编译并开启告警与 Sanitizer' },
      { title: '测试', desc: '覆盖空输入、越界与损坏文件' },
    ],
    notes: ['字符串与动态内存是 C 项目最容易出错的两处，要集中封装'],
    caption: 'C 项目的质量取决于资源与边界管理；Makefile 与测试让问题可重复暴露。',
  },
};
