// P7 Kotlin 课程配图数据。
module.exports = {
  kotlin_basics: {
    image: 'diagram_kt_basics.webp',
    alt: 'Kotlin 基础与空安全',
    title: 'Kotlin 基础：不可变优先与空安全',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['val / var', '类型推断', '可空类型', '安全调用'],
    colLabels: ['写法', '含义', '建议'],
    cells: [
      { r: 0, c: 0, text: 'val name = "Ada"' },
      { r: 0, c: 1, text: 'val 只读，var 可变' },
      { r: 0, c: 2, text: '默认用 val，需要时再 var' },
      { r: 1, c: 0, text: 'val age = 18' },
      { r: 1, c: 1, text: '编译器推断为 Int' },
      { r: 1, c: 2, text: '接口边界显式写类型' },
      { r: 2, c: 0, text: 'val nick: String?' },
      { r: 2, c: 1, text: '可能为 null 的类型' },
      { r: 2, c: 2, text: '可空性写进类型系统' },
      { r: 3, c: 0, text: 'nick?.length ?: 0' },
      { r: 3, c: 1, text: '安全调用与 Elvis 兜底' },
      { r: 3, c: 2, text: '避免滥用 !! 强制解包' },
    ],
    notes: ['平台类型来自 Java 互操作，边界处要显式判空'],
    caption: 'Kotlin 用 val 与可空类型把「会不会变」和「会不会为空」写进类型。',
  },
  kotlin_first_program: {
    image: 'diagram_kt_first_program.webp',
    alt: '编写并运行第一个 Kotlin 程序',
    title: '第一个程序：从 main 开始',
    type: 'flow',
    steps: [
      { title: '创建文件', desc: 'hello.kt 或使用 Gradle 项目' },
      { title: 'fun main', desc: '程序入口，可接收参数' },
      { title: '编译运行', desc: 'kotlinc 编译或 gradle run' },
      { title: '验证输出', desc: '确认标准输出与退出码' },
    ],
    notes: ['JVM 项目通常由 Gradle 管理依赖与运行任务'],
    caption: 'Kotlin 可以编译为 JVM 字节码、原生代码或 JavaScript，入门先从 JVM 开始。',
  },
  kotlin_variables_null: {
    image: 'diagram_kt_variables_null.webp',
    alt: 'val/var 与可空类型处理',
    title: '变量与空值：两类安全',
    type: 'compare',
    columns: [
      { title: '可变性', items: ['val 是只读引用', 'var 可以重新赋值', '集合只读接口不等于内容不可变', '优先使用不可变数据', '可变状态集中管理'] },
      { title: '空值处理', items: ['String? 表示可能为空', '?. 安全调用短路', '?: 提供默认值', '?.let 只在非空时执行', '!! 仅在确定非空时使用'] },
    ],
    notes: ['编译器的智能转换会在判空之后把类型收窄为非空'],
    caption: 'Kotlin 的空安全不是运行时检查，而是把 null 可能性编码到类型里强制处理。',
  },
  kotlin_conditions: {
    image: 'diagram_kt_conditions.webp',
    alt: 'Kotlin if 与 when 表达式',
    title: '条件判断：if 与 when 都是表达式',
    type: 'grid',
    rows: 3,
    cols: 3,
    rowLabels: ['if / else', 'when', 'when 无参数'],
    colLabels: ['写法', '特点', '注意点'],
    cells: [
      { r: 0, c: 0, text: 'val level = if (score >= 60) "过" else "否"' },
      { r: 0, c: 1, text: '分支返回值，可直接赋值' },
      { r: 0, c: 2, text: '表达式必须覆盖所有分支' },
      { r: 1, c: 0, text: 'when (code) { 1 -> ...; else -> ... }' },
      { r: 1, c: 1, text: '替代 switch，支持多值匹配' },
      { r: 1, c: 2, text: '枚举可省略 else 但需穷尽' },
      { r: 2, c: 0, text: 'when { x > 0 -> ...; else -> ... }' },
      { r: 2, c: 1, text: '任意布尔条件分支' },
      { r: 2, c: 2, text: '条件按顺序求值' },
    ],
    notes: ['when 配合密封类可以实现穷尽分支检查'],
    caption: 'Kotlin 的控制流是表达式：分支直接产生值，减少临时变量与重复赋值。',
  },
  kotlin_loops: {
    image: 'diagram_kt_loops.webp',
    alt: 'Kotlin 循环与范围',
    title: '循环：for、while 与范围',
    type: 'grid',
    rows: 3,
    cols: 3,
    rowLabels: ['for-in', 'while', '范围与步长'],
    colLabels: ['写法', '适用场景', '注意点'],
    cells: [
      { r: 0, c: 0, text: 'for (item in items) { }' },
      { r: 0, c: 1, text: '遍历集合、数组与范围' },
      { r: 0, c: 2, text: '遍历时修改集合要小心' },
      { r: 1, c: 0, text: 'while (condition) { }' },
      { r: 1, c: 1, text: '条件驱动，次数未知' },
      { r: 1, c: 2, text: '确保状态会推进' },
      { r: 2, c: 0, text: 'for (i in 0 until n step 2)' },
      { r: 2, c: 1, text: '范围、递减与步长控制' },
      { r: 2, c: 2, text: 'until 不包含上界' },
    ],
    notes: ['repeat(n) 适合固定次数的简单重复'],
    caption: 'Kotlin 的范围语法让循环边界更直观，但边界包含关系仍要逐一确认。',
  },
  kotlin_functions_intro: {
    image: 'diagram_kt_functions_intro.webp',
    alt: 'Kotlin 函数的参数与返回值',
    title: '函数入门：默认参数与表达式体',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['函数声明', '默认参数', '命名参数', '表达式体'],
    colLabels: ['写法', '作用', '注意点'],
    cells: [
      { r: 0, c: 0, text: 'fun add(a: Int, b: Int): Int' },
      { r: 0, c: 1, text: '参数与返回值都写类型' },
      { r: 0, c: 2, text: 'Unit 返回可省略' },
      { r: 1, c: 0, text: 'fun greet(name: String = "World")' },
      { r: 1, c: 1, text: '调用时可省略参数' },
      { r: 1, c: 2, text: '默认参数减少重载' },
      { r: 2, c: 0, text: 'greet(name = "Ada")' },
      { r: 2, c: 1, text: '提升调用可读性' },
      { r: 2, c: 2, text: '与 Java 互操作要加注解' },
      { r: 3, c: 0, text: 'fun square(x: Int) = x * x' },
      { r: 3, c: 1, text: '单表达式函数更简洁' },
      { r: 3, c: 2, text: '复杂逻辑仍用代码块' },
    ],
    notes: ['扩展函数看起来像成员方法，但本质是静态解析'],
    caption: '默认参数、命名参数与表达式体让 Kotlin 函数接口更紧凑，也更易读。',
  },
  kotlin_functions: {
    image: 'diagram_kt_functions.webp',
    alt: 'Lambda、扩展函数与内联',
    title: '函数进阶：Lambda、扩展与内联',
    type: 'compare',
    columns: [
      { title: 'Lambda 与高阶函数', items: ['函数可以作为参数与返回值', 'trailing lambda 写在括号外', 'it 是单参数默认名', '接收者 lambda 用 this', '高阶函数适合封装流程'] },
      { title: '扩展与内联', items: ['扩展函数为已有类型加能力', '扩展是静态解析，不修改原类', 'inline 减少 lambda 对象开销', 'reified 保留泛型类型信息', '避免在扩展里隐藏副作用'] },
    ],
    notes: ['内联会增大字节码体积，只对热点且含 lambda 的函数使用'],
    caption: 'Kotlin 用扩展与高阶函数扩展表达力，用内联控制抽象成本。',
  },
  kotlin_oop: {
    image: 'diagram_kt_oop.webp',
    alt: 'Kotlin 类、数据类与密封类',
    title: '面向对象：用类型表达领域模型',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['主构造器', '数据类', '密封类', '委托'],
    colLabels: ['写法', '作用', '注意点'],
    cells: [
      { r: 0, c: 0, text: 'class User(val id: Int)' },
      { r: 0, c: 1, text: '声明属性并自动初始化' },
      { r: 0, c: 2, text: 'init 块校验不变量' },
      { r: 1, c: 0, text: 'data class User(...)' },
      { r: 1, c: 1, text: '自动生成 equals/hashCode/copy' },
      { r: 1, c: 2, text: '适合值对象，不适合可变实体' },
      { r: 2, c: 0, text: 'sealed class Result' },
      { r: 2, c: 1, text: '限制子类集合，配合穷尽 when' },
      { r: 2, c: 2, text: '建模有限状态首选' },
      { r: 3, c: 0, text: 'by lazy / by viewModels()' },
      { r: 3, c: 1, text: '把实现委托给其他对象' },
      { r: 3, c: 2, text: '生命周期与线程要清楚' },
    ],
    notes: ['data class 的 copy 是浅拷贝，嵌套可变对象仍共享引用'],
    caption: 'Kotlin 的类型工具足够丰富：用 data class 表达值，用 sealed class 表达状态。',
  },
  kotlin_collections: {
    image: 'diagram_kt_collections.webp',
    alt: '集合操作链与序列惰性求值',
    title: '集合与序列：立即执行与惰性求值',
    type: 'compare',
    columns: [
      { title: '集合操作链', items: ['每个操作立即产生新集合', '链式调用可读性高', '中间结果会分配内存', '数据量较小时性能可接受', 'map/filter/groupBy 常用'] },
      { title: '序列 Sequence', items: ['惰性计算，终端操作才执行', '链式操作不产生中间集合', '适合大数据量与长链', '注意每次遍历都会重新计算', 'asSequence 转换后要 toList'] },
    ],
    notes: ['List 与 MutableList 是接口层面的读写区分，不是内容不可变'],
    caption: '小集合用集合操作更直观，大集合或长链用序列减少中间分配。',
  },
  kotlin_testing: {
    image: 'diagram_kt_testing.webp',
    alt: 'Kotlin 测试与协程测试',
    title: '测试：单元、协程与假对象',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['单元测试', '协程测试', '假对象', '测试调度器'],
    colLabels: ['测什么', '工具', '注意点'],
    cells: [
      { r: 0, c: 0, text: '纯函数与领域逻辑' },
      { r: 0, c: 1, text: 'JUnit 与断言库' },
      { r: 0, c: 2, text: '测试行为而非实现' },
      { r: 1, c: 0, text: '挂起函数与超时' },
      { r: 1, c: 1, text: 'runTest 与虚拟时间' },
      { r: 1, c: 2, text: '不要依赖真实延迟' },
      { r: 2, c: 0, text: '隔离外部依赖' },
      { r: 2, c: 1, text: '手写 Fake 或接口替身' },
      { r: 2, c: 2, text: '假对象要可配置行为' },
      { r: 3, c: 0, text: '确定性调度并发' },
      { r: 3, c: 1, text: 'StandardTestDispatcher' },
      { r: 3, c: 2, text: '避免测试出现随机失败' },
    ],
    notes: ['Android 测试分本地 JVM 测试与设备测试，按反馈速度分层'],
    caption: '协程测试的关键是控制调度与时间，让并发行为可重复、可断言。',
  },
  kotlin_android: {
    image: 'diagram_kt_android.webp',
    alt: 'Kotlin Android 应用的分层架构',
    title: 'Android 架构：分层与生命周期',
    type: 'layers',
    layers: [
      { title: 'UI 层', desc: 'Compose 或 View 渲染状态与事件', fill: '#eef4ff', stroke: '#6c8ff8' },
      { title: 'ViewModel', desc: '保存界面状态，跨配置变更存活', fill: '#e8f2ff', stroke: '#6c8ff8' },
      { title: 'Repository', desc: '统一数据来源，协调网络与缓存', fill: '#e6f7f1', stroke: '#3fae8a' },
      { title: '数据源', desc: 'Room、Retrofit 与本地文件', fill: '#fff4e6', stroke: '#e6a23c' },
      { title: '依赖注入', desc: '构造注入依赖，便于替换与测试', fill: '#fdeeee', stroke: '#d97070' },
    ],
    widths: [0.72, 0.84, 0.9, 1, 0.86],
    caption: 'Android 架构的核心是单向数据流：UI 渲染状态，事件向上传递，数据层负责真相。',
  },
  kotlin_project: {
    image: 'diagram_kt_android_project.webp',
    alt: 'Kotlin Android 客户端的请求链路',
    title: '实战客户端：列表到详情',
    type: 'sequence',
    actors: ['界面', 'ViewModel', 'Repository', '网络与缓存'],
    messages: [
      { from: 0, to: 1, label: '触发加载事件' },
      { from: 1, to: 2, label: '请求列表数据' },
      { from: 2, to: 3, label: '先读缓存，再请求网络' },
      { from: 3, to: 2, label: '返回数据或错误' },
      { from: 2, to: 1, label: '更新状态流' },
      { from: 1, to: 0, label: '渲染列表或错误与重试' },
    ],
    notes: ['加载、成功、空、错误四种状态都要显式建模'],
    caption: '客户端质量取决于状态建模与错误恢复；缓存策略要和网络策略一起设计。',
  },
};
