// P7 移动开发课程配图数据。
module.exports = {
  flutter_widget_intro: {
    image: 'diagram_mobile_flutter_widget.webp',
    alt: 'Flutter Widget 到渲染的流程',
    title: 'Flutter Widget：从声明到屏幕',
    type: 'flow',
    steps: [
      { title: 'Widget', desc: '不可变的界面配置描述' },
      { title: 'Element', desc: '保存位置与状态的实例' },
      { title: 'RenderObject', desc: '负责布局、绘制与命中测试' },
      { title: '屏幕', desc: '合成图层并显示' },
    ],
    notes: ['Widget 频繁重建是正常的，真正昂贵的是布局与绘制'],
    caption: 'Widget 是声明，Element 是实例，RenderObject 是执行者；理解三者才能解释重建。',
  },
  flutter_layout_intro: {
    image: 'diagram_mobile_flutter_layout.webp',
    alt: 'Flutter 布局与约束',
    title: 'Flutter 布局：约束向下，尺寸向上',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['Row / Column', 'Expanded', 'Stack', '约束'],
    colLabels: ['作用', '写法', '注意点'],
    cells: [
      { r: 0, c: 0, text: '主轴排列子组件' },
      { r: 0, c: 1, text: 'mainAxisAlignment / crossAxisAlignment' },
      { r: 0, c: 2, text: '溢出是布局约束问题' },
      { r: 1, c: 0, text: '按比例分配剩余空间' },
      { r: 1, c: 1, text: 'Expanded(flex: 1)' },
      { r: 1, c: 2, text: '必须放在 Flex 子级中' },
      { r: 2, c: 0, text: '层叠定位子组件' },
      { r: 2, c: 1, text: 'Stack + Positioned' },
      { r: 2, c: 2, text: '注意命中测试与溢出' },
      { r: 3, c: 0, text: '父级给子级的尺寸范围' },
      { r: 3, c: 1, text: 'BoxConstraints' },
      { r: 3, c: 2, text: '先理解约束再加 SizedBox' },
    ],
    notes: ['Unbounded height 错误通常来自可滚动组件中的无约束子级'],
    caption: 'Flutter 布局是约束传递：父组件给约束，子组件返回尺寸，最终确定位置。',
  },
  flutter_state: {
    image: 'diagram_mobile_flutter_state.webp',
    alt: '状态分层与重建范围',
    title: 'Flutter 状态：分层与重建范围',
    type: 'compare',
    columns: [
      { title: '状态分层', items: ['局部状态留在组件内部', '跨页面状态放共享层', '状态对象保持不可变', '事件改变状态，视图订阅渲染', '业务逻辑与 UI 分离'] },
      { title: '重建控制', items: ['把 setState 放在最小组件', '用 const 减少重建', '合理拆分无状态子组件', '列表使用稳定 key', '避免在 build 中做重计算'] },
    ],
    notes: ['生命周期回调里 setState 前要检查 mounted'],
    caption: '状态分层决定可维护性，重建范围决定性能；两者要一起设计。',
  },
  flutter_release: {
    image: 'diagram_mobile_flutter_release.webp',
    alt: 'Flutter Android 发布流程',
    title: 'Flutter 发布：签名、构建与检查',
    type: 'flow',
    steps: [
      { title: '正式签名', desc: '配置 keystore 与密钥保护' },
      { title: '构建产物', desc: 'flutter build appbundle 或 apk' },
      { title: '体积优化', desc: '按 ABI 拆分、混淆与资源裁剪' },
      { title: '符号保留', desc: '保存 mapping 与调试符号' },
      { title: '发布清单', desc: '版本号、隐私政策与商店资料' },
    ],
    notes: ['密钥与口令不要提交到仓库，丢失签名将无法更新应用'],
    caption: '发布流程的重点是签名安全、产物可复现与崩溃可追踪。',
  },
  mobile_kotlin: {
    image: 'diagram_mobile_kotlin.webp',
    alt: 'Kotlin Android 开发的关键能力',
    title: 'Kotlin Android：从语言到发布',
    type: 'layers',
    layers: [
      { title: '空安全', desc: '可空类型与安全调用减少崩溃', fill: '#eef4ff', stroke: '#6c8ff8' },
      { title: '协程', desc: '结构化并发与生命周期感知', fill: '#e8f2ff', stroke: '#6c8ff8' },
      { title: '分层架构', desc: 'UI、ViewModel、Repository 与数据源', fill: '#e6f7f1', stroke: '#3fae8a' },
      { title: '依赖注入', desc: '构造注入，便于测试与替换', fill: '#fff4e6', stroke: '#e6a23c' },
      { title: '打包发布', desc: '混淆、签名、ABI 与商店审核', fill: '#fdeeee', stroke: '#d97070' },
    ],
    widths: [0.7, 0.82, 0.94, 0.88, 1],
    caption: 'Android 开发的核心是生命周期与状态管理；Kotlin 的语言特性能减少常见错误。',
  },
  mobile_swift: {
    image: 'diagram_mobile_swift.webp',
    alt: 'Swift 与 iOS 开发的关键能力',
    title: 'Swift iOS：语言与平台能力',
    type: 'layers',
    layers: [
      { title: '可选类型', desc: '空值显式建模与安全解包', fill: '#eef4ff', stroke: '#6c8ff8' },
      { title: '值类型', desc: 'struct 减少共享状态副作用', fill: '#e8f2ff', stroke: '#6c8ff8' },
      { title: 'ARC', desc: '引用计数与循环引用排查', fill: '#e6f7f1', stroke: '#3fae8a' },
      { title: '并发', desc: 'async/await 与 Actor 隔离', fill: '#fff4e6', stroke: '#e6a23c' },
      { title: 'SwiftUI', desc: '状态驱动视图与单向数据流', fill: '#fdeeee', stroke: '#d97070' },
    ],
    widths: [0.7, 0.82, 0.88, 0.94, 1],
    caption: 'iOS 开发的关键是值语义、内存管理与状态流；SwiftUI 把三者统一到声明式模型。',
  },
  mobile_react_native: {
    image: 'diagram_mobile_react_native.webp',
    alt: 'React Native 新架构与性能优化',
    title: 'React Native：新架构与性能',
    type: 'layers',
    layers: [
      { title: 'JSI', desc: 'JS 与原生直接通信，减少桥接序列化', fill: '#eef4ff', stroke: '#6c8ff8' },
      { title: 'Fabric', desc: '新渲染器支持并发与同步布局', fill: '#e8f2ff', stroke: '#6c8ff8' },
      { title: 'Hermes', desc: '优化启动与内存的 JS 引擎', fill: '#e6f7f1', stroke: '#3fae8a' },
      { title: '列表虚拟化', desc: '只渲染可见区域，稳定 key', fill: '#fff4e6', stroke: '#e6a23c' },
      { title: '桥接与原生模块', desc: '复杂计算下沉原生，减少跨端调用', fill: '#fdeeee', stroke: '#d97070' },
    ],
    widths: [0.7, 0.82, 0.9, 1, 0.92],
    caption: 'React Native 的性能取决于减少跨语言调用、控制渲染范围与合理下沉原生能力。',
  },
  mobile_compose: {
    image: 'diagram_mobile_compose.webp',
    alt: 'Jetpack Compose 重组与状态',
    title: 'Compose：重组、状态与副作用',
    type: 'flow',
    steps: [
      { title: '状态变化', desc: 'State 或 ViewModel 发出新值' },
      { title: '重组', desc: '只重新执行读取该状态的组合函数' },
      { title: '状态提升', desc: '把状态上移到共同父级或 ViewModel' },
      { title: '副作用', desc: 'LaunchedEffect 与 remember 处理边界' },
      { title: '范围优化', desc: '用 key 与派生状态减少无效重组' },
    ],
    notes: ['组合函数应保持无副作用且可重复执行'],
    caption: 'Compose 的核心是状态驱动重组：状态位置决定重组范围，副作用必须显式声明。',
  },
  mobile_harmony: {
    image: 'diagram_mobile_harmony.webp',
    alt: '鸿蒙 ArkTS 与 Stage 模型',
    title: '鸿蒙开发：ArkTS、ArkUI 与 Stage',
    type: 'layers',
    layers: [
      { title: 'ArkTS 语言', desc: 'TypeScript 约束子集，强调静态类型', fill: '#eef4ff', stroke: '#6c8ff8' },
      { title: 'ArkUI 声明式', desc: '用状态与组件描述界面', fill: '#e8f2ff', stroke: '#6c8ff8' },
      { title: 'Stage 模型', desc: 'UIAbility 管理生命周期与窗口', fill: '#e6f7f1', stroke: '#3fae8a' },
      { title: '能力与权限', desc: '按需申请系统能力，最小权限', fill: '#fff4e6', stroke: '#e6a23c' },
      { title: '打包发布', desc: '签名、上架与设备兼容验证', fill: '#fdeeee', stroke: '#d97070' },
    ],
    widths: [0.72, 0.84, 0.9, 0.94, 1],
    caption: '鸿蒙应用开发与 Android 类似但生态独立：语言约束、生命周期与权限模型都要重新熟悉。',
  },
  mobile_miniprogram: {
    image: 'diagram_mobile_miniprogram.webp',
    alt: '小程序双线程模型与分包',
    title: '小程序：双线程、setData 与分包',
    type: 'compare',
    columns: [
      { title: '运行时模型', items: ['逻辑层与渲染层分离', '跨线程通信有序列化成本', 'setData 数据量要小', '频繁 setData 会造成卡顿', '长任务要拆分或下沉'] },
      { title: '加载与分包', items: ['主包控制体积上限', '按页面拆分独立分包', '分包预下载提升体验', '首屏关键资源优先加载', '安全边界：不信任客户端校验'] },
    ],
    notes: ['小程序包体与请求域名都有平台限制，要提前规划'],
    caption: '小程序的性能瓶颈主要在跨线程通信与包体；减少 setData 与合理分包收益最大。',
  },
  mobile_performance: {
    image: 'diagram_mobile_performance.webp',
    alt: '移动端性能优化的四个维度',
    title: '移动端性能：四个维度',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['启动', '流畅度', '内存', '包体'],
    colLabels: ['关键指标', '优化手段', '验证方式'],
    cells: [
      { r: 0, c: 0, text: '冷启动时间与首屏可见' },
      { r: 0, c: 1, text: '延迟初始化与异步加载' },
      { r: 0, c: 2, text: '启动埋点与帧时间线' },
      { r: 1, c: 0, text: '帧率与掉帧次数' },
      { r: 1, c: 1, text: '减少过度绘制与主线程任务' },
      { r: 1, c: 2, text: '性能面板与真机测试' },
      { r: 2, c: 0, text: '峰值内存与泄漏' },
      { r: 2, c: 1, text: '图片压缩、缓存与对象复用' },
      { r: 2, c: 2, text: '内存快照与压力测试' },
      { r: 3, c: 0, text: '安装包大小与下载转化' },
      { r: 3, c: 1, text: '资源裁剪、按需下载与混淆' },
      { r: 3, c: 2, text: '构建产物分析与 A/B' },
    ],
    notes: ['性能优化要先建立基线，再针对指标做改动并回归验证'],
    caption: '启动、流畅度、内存与包体相互制约；用数据决定优先级，避免局部优化伤害体验。',
  },
};
