// P7 Swift 课程配图数据。
module.exports = {
  swift_basics: {
    image: 'diagram_swift_basics.webp',
    alt: 'Swift 基础与可选类型',
    title: 'Swift 基础：安全的值与可选类型',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['let / var', '可选类型', '值类型', '错误处理'],
    colLabels: ['写法', '含义', '建议'],
    cells: [
      { r: 0, c: 0, text: 'let name = "Ada"' },
      { r: 0, c: 1, text: 'let 常量，var 变量' },
      { r: 0, c: 2, text: '默认用 let' },
      { r: 1, c: 0, text: 'var nick: String? = nil' },
      { r: 1, c: 1, text: '可能没有值的类型' },
      { r: 1, c: 2, text: '用绑定或 ?? 解包' },
      { r: 2, c: 0, text: 'struct 赋值即复制' },
      { r: 2, c: 1, text: '值语义减少共享副作用' },
      { r: 2, c: 2, text: '模型优先用 struct' },
      { r: 3, c: 0, text: 'try / throws' },
      { r: 3, c: 1, text: '错误必须显式处理' },
      { r: 3, c: 2, text: '区分可恢复与致命错误' },
    ],
    notes: ['隐式解包可选类型要谨慎使用，越界访问会直接崩溃'],
    caption: 'Swift 把空值与错误都编码进类型系统，让编译器提醒你处理每条失败路径。',
  },
  swift_first_program: {
    image: 'diagram_swift_first_program.webp',
    alt: '编写并运行第一个 Swift 程序',
    title: '第一个程序：从源码到运行',
    type: 'flow',
    steps: [
      { title: '创建文件', desc: 'main.swift 或使用 Swift Package' },
      { title: '编写入口', desc: '顶层代码或 @main 入口' },
      { title: '编译运行', desc: 'swift run 或 Xcode 运行' },
      { title: '验证输出', desc: '检查标准输出与退出状态' },
    ],
    notes: ['Swift Package Manager 管理依赖与构建目标'],
    caption: 'Swift 可用于命令行、服务端与 Apple 平台应用；入门先理解编译与运行流程。',
  },
  swift_constants_variables: {
    image: 'diagram_swift_constants_variables.webp',
    alt: 'let 与 var 的区别',
    title: '常量与变量：默认不可变',
    type: 'compare',
    columns: [
      { title: 'let 常量', items: ['初始化后不能重新赋值', '引用不可变但对象可内部变化', '编译器可做更多优化', '适合大多数局部值', '接口参数优先 let'] },
      { title: 'var 变量', items: ['允许重新赋值', '需要可变状态时使用', '作用域应尽量小', '值类型赋值会复制', '引用类型赋值共享实例'] },
    ],
    notes: ['class 实例的 let 只保证引用不变，不保证属性不可变'],
    caption: '默认用 let：不可变数据更容易推理，也减少并发下的共享状态问题。',
  },
  swift_conditions: {
    image: 'diagram_swift_conditions.webp',
    alt: 'Swift 条件、switch 与可选绑定',
    title: '条件判断：if、switch 与可选绑定',
    type: 'grid',
    rows: 3,
    cols: 3,
    rowLabels: ['if / else', 'switch', '可选绑定'],
    colLabels: ['写法', '特点', '注意点'],
    cells: [
      { r: 0, c: 0, text: 'if score >= 60 { } else { }' },
      { r: 0, c: 1, text: '条件必须是 Bool' },
      { r: 0, c: 2, text: '不接受整数作为真值' },
      { r: 1, c: 0, text: 'switch value { case ...: }' },
      { r: 1, c: 1, text: '默认不穿透，必须穷尽' },
      { r: 1, c: 2, text: '用 where 增加条件' },
      { r: 2, c: 0, text: 'if let name = nick { }' },
      { r: 2, c: 1, text: '解包可选并进入非空分支' },
      { r: 2, c: 2, text: 'guard let 适合提前返回' },
    ],
    notes: ['guard 语句要求 else 分支必须退出当前作用域'],
    caption: 'Swift 的 switch 与可选绑定把分支与空值处理变成类型驱动的结构。',
  },
  swift_loops: {
    image: 'diagram_swift_loops.webp',
    alt: 'Swift 循环与范围',
    title: '循环：for-in、while 与范围',
    type: 'grid',
    rows: 3,
    cols: 3,
    rowLabels: ['for-in', 'while / repeat', '范围'],
    colLabels: ['写法', '适用场景', '注意点'],
    cells: [
      { r: 0, c: 0, text: 'for item in items { }' },
      { r: 0, c: 1, text: '遍历集合、字典与范围' },
      { r: 0, c: 2, text: '字典遍历顺序不保证' },
      { r: 1, c: 0, text: 'while / repeat-while' },
      { r: 1, c: 1, text: '条件驱动与至少执行一次' },
      { r: 1, c: 2, text: '确保条件会终止' },
      { r: 2, c: 0, text: 'for i in 0..<n { }' },
      { r: 2, c: 1, text: '半开与闭区间' },
      { r: 2, c: 2, text: '范围越界会直接崩溃' },
    ],
    notes: ['stride 可以设置步长与开闭边界'],
    caption: 'Swift 的范围语法清晰，但越界是运行时陷阱，边界计算要格外小心。',
  },
  swift_functions_intro: {
    image: 'diagram_swift_functions_intro.webp',
    alt: 'Swift 函数参数标签与返回值',
    title: '函数入门：参数标签与返回值',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['函数声明', '参数标签', '默认参数', '返回值'],
    colLabels: ['写法', '作用', '注意点'],
    cells: [
      { r: 0, c: 0, text: 'func add(_ a: Int, _ b: Int) -> Int' },
      { r: 0, c: 1, text: '参数与返回值显式声明' },
      { r: 0, c: 2, text: '单表达式可省略 return' },
      { r: 1, c: 0, text: 'func greet(to name: String)' },
      { r: 1, c: 1, text: '调用点更接近自然语言' },
      { r: 1, c: 2, text: '标签与参数名可不同' },
      { r: 2, c: 0, text: 'func log(_ msg: String = "ok")' },
      { r: 2, c: 1, text: '提供默认行为' },
      { r: 2, c: 2, text: '默认参数要放在末尾' },
      { r: 3, c: 0, text: 'func load() throws -> Data' },
      { r: 3, c: 1, text: '可能失败要显式 throws' },
      { r: 3, c: 2, text: '调用方必须 try 处理' },
    ],
    notes: ['Swift 参数标签让函数调用像句子，提升接口可读性'],
    caption: '函数签名包含标签与错误语义：调用方一眼能看出参数含义与失败可能。',
  },
  swift_functions: {
    image: 'diagram_swift_functions.webp',
    alt: '闭包捕获与协议扩展',
    title: '函数进阶：闭包与协议扩展',
    type: 'compare',
    columns: [
      { title: '闭包', items: ['闭包捕获上下文变量', '尾随闭包语法更清晰', '@escaping 表示逃逸', '捕获列表控制引用语义', '注意循环引用与生命周期'] },
      { title: '协议与扩展', items: ['协议定义能力契约', '扩展提供默认实现', '关联类型表达类型关系', '协议组合用 & 连接', '面向协议编程减少继承'] },
    ],
    notes: ['闭包捕获 self 时用 [weak self] 打破循环引用'],
    caption: '闭包表达行为，协议表达契约；两者都是 Swift 组合优于继承的基础。',
  },
  swift_collections: {
    image: 'diagram_swift_collections.webp',
    alt: 'Swift 集合类型与泛型',
    title: '集合与泛型：选择合适容器',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['Array', 'Dictionary', 'Set', '泛型约束'],
    colLabels: ['结构', '特点', '适用场景'],
    cells: [
      { r: 0, c: 0, text: '有序可重复序列' },
      { r: 0, c: 1, text: '随机访问与顺序遍历' },
      { r: 0, c: 2, text: '列表与顺序数据' },
      { r: 1, c: 0, text: '键值映射' },
      { r: 1, c: 1, text: '按 key 查找平均 O(1)' },
      { r: 1, c: 2, text: '缓存与索引结构' },
      { r: 2, c: 0, text: '无序唯一元素集合' },
      { r: 2, c: 1, text: '去重与集合运算' },
      { r: 2, c: 2, text: '标签与权限集合' },
      { r: 3, c: 0, text: '协议约束与关联类型' },
      { r: 3, c: 1, text: 'same-type 与 where 约束' },
      { r: 3, c: 2, text: '通用算法与容器' },
    ],
    notes: ['Array 是值类型，赋值时复制，但底层有写时复制优化'],
    caption: 'Swift 集合是值类型：赋值语义清晰，但大集合要注意写时复制的实际开销。',
  },
  swift_async: {
    image: 'diagram_swift_async.webp',
    alt: 'Swift 并发模型',
    title: '并发：async/await、Task 与 Actor',
    type: 'sequence',
    actors: ['调用方', 'async 函数', 'Task 调度', 'Actor'],
    messages: [
      { from: 0, to: 1, label: 'await 调用挂起函数' },
      { from: 1, to: 2, label: '挂起并让出执行权' },
      { from: 2, to: 1, label: 'IO 完成后恢复执行' },
      { from: 1, to: 3, label: '访问 Actor 隔离状态' },
      { from: 3, to: 1, label: '串行化访问，避免数据竞争' },
      { from: 0, to: 1, label: 'Task 取消并传播' },
    ],
    notes: ['Sendable 约束跨并发域传递的类型，编译器会检查'],
    caption: 'Swift 并发用 async/await 表达挂起，用 Actor 隔离可变状态，用取消协作终止任务。',
  },
  swift_swiftui: {
    image: 'diagram_swift_swiftui.webp',
    alt: 'SwiftUI 状态与数据流',
    title: 'SwiftUI：状态驱动视图',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['视图', '状态包装器', '数据流', '性能'],
    colLabels: ['作用', '常用写法', '注意点'],
    cells: [
      { r: 0, c: 0, text: '声明式描述界面' },
      { r: 0, c: 1, text: 'struct View { var body: some View }' },
      { r: 0, c: 2, text: '视图是值类型，轻量创建' },
      { r: 1, c: 0, text: '管理可变状态' },
      { r: 1, c: 1, text: '@State、@Binding、@Observable' },
      { r: 1, c: 2, text: '状态归属要清晰' },
      { r: 2, c: 0, text: '数据向下，事件向上' },
      { r: 2, c: 1, text: '单向数据流' },
      { r: 2, c: 2, text: '避免双向绑定滥用' },
      { r: 3, c: 0, text: '控制重绘范围' },
      { r: 3, c: 1, text: '拆分视图与稳定标识' },
      { r: 3, c: 2, text: '用 Instruments 验证' },
    ],
    notes: ['body 中不要做重计算或副作用，保持视图为纯函数'],
    caption: 'SwiftUI 的核心是状态与视图的映射：状态变化触发重算，数据流方向必须明确。',
  },
  swift_testing: {
    image: 'diagram_swift_testing.webp',
    alt: 'Swift 测试与性能验证流程',
    title: '测试：单元、异步与性能',
    type: 'flow',
    steps: [
      { title: 'XCTest 单元测试', desc: '覆盖领域逻辑与边界条件' },
      { title: '依赖注入', desc: '用协议替换网络与存储' },
      { title: '异步测试', desc: 'await 与预期超时处理' },
      { title: '性能测试', desc: 'measure 建立基线' },
      { title: 'Instruments', desc: '定位内存、CPU 与卡顿' },
    ],
    notes: ['测试要覆盖失败路径：超时、空数据与解析错误'],
    caption: '测试与 Instruments 是两种验证：前者保证行为正确，后者保证资源与性能达标。',
  },
  swift_project: {
    image: 'diagram_swift_ios_project.webp',
    alt: 'SwiftUI iOS 客户端的数据流',
    title: '实战 iOS 客户端：列表到详情',
    type: 'sequence',
    actors: ['视图', '视图模型', '服务层', '网络与缓存'],
    messages: [
      { from: 0, to: 1, label: '触发加载任务' },
      { from: 1, to: 2, label: '请求列表数据' },
      { from: 2, to: 3, label: '读取缓存并请求网络' },
      { from: 3, to: 2, label: '返回数据或错误' },
      { from: 2, to: 1, label: '更新可观察状态' },
      { from: 1, to: 0, label: '渲染列表与错误重试' },
    ],
    notes: ['状态恢复：把关键筛选与滚动位置持久化'],
    caption: 'iOS 客户端同样遵循状态建模与分层：视图、视图模型、服务与数据源职责分离。',
  },
};
