// P8 数学基础课程配图数据。
module.exports = {
  math_set_function_intro: {
    image: 'diagram_math_set_function.webp',
    alt: '集合与映射的基本概念',
    title: '集合与函数：数学的语言',
    type: 'compare',
    columns: [
      { title: '集合', items: ['一组确定对象的整体', '元素具有无序与唯一性', '子集、并集、交集与补集', '笛卡尔积生成有序对', '集合运算对应逻辑运算'] },
      { title: '映射与函数', items: ['映射把每个输入对应到一个输出', '定义域是允许的输入集合', '值域是实际输出的集合', '函数是特殊的映射', '单射、满射与一一对应'] },
    ],
    notes: ['机器学习中的特征、标签与模型都可以用集合和映射描述'],
    caption: '集合定义「有哪些对象」，映射定义「如何对应」；这是后续数学结构的起点。',
  },
  math_vectors_matrices: {
    image: 'diagram_math_vectors_matrices.webp',
    alt: '向量点积与矩阵乘法',
    title: '向量与矩阵：形状与运算',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['点积', '余弦相似度', '矩阵乘法', '秩与最小二乘'],
    colLabels: ['定义', '形状规则', '应用'],
    cells: [
      { r: 0, c: 0, text: '对应分量相乘再求和' },
      { r: 0, c: 1, text: '两个长度相同的向量' },
      { r: 0, c: 2, text: '投影、注意力得分' },
      { r: 1, c: 0, text: '点积除以模长乘积' },
      { r: 1, c: 1, text: '结果范围 [-1, 1]' },
      { r: 1, c: 2, text: '文本与向量检索' },
      { r: 2, c: 0, text: '行与列的点积组合' },
      { r: 2, c: 1, text: '(m,n) 乘 (n,p) 得 (m,p)' },
      { r: 2, c: 2, text: '线性变换与神经网络层' },
      { r: 3, c: 0, text: '秩表示独立方向数' },
      { r: 3, c: 1, text: '无解时求近似解' },
      { r: 3, c: 2, text: '降维与回归拟合' },
    ],
    notes: ['矩阵乘法不满足交换律，顺序不同结果不同'],
    caption: '线代的核心是形状与变换：先把维度对齐，再理解每个运算的几何意义。',
  },
  math_eigen_svd: {
    image: 'diagram_math_eigen_svd.webp',
    alt: '特征分解到 SVD 与 PCA',
    title: '特征值、SVD 与降维',
    type: 'layers',
    layers: [
      { title: '特征分解', desc: 'A v = λ v，方向不变只缩放', fill: '#eef4ff', stroke: '#6c8ff8' },
      { title: 'SVD', desc: '任意矩阵分解为旋转、缩放、旋转', fill: '#e8f2ff', stroke: '#6c8ff8' },
      { title: '低秩近似', desc: '保留最大奇异值，压缩信息', fill: '#e6f7f1', stroke: '#3fae8a' },
      { title: 'PCA', desc: '找方差最大的正交方向降维', fill: '#fff4e6', stroke: '#e6a23c' },
      { title: '条件数', desc: '衡量问题对扰动的敏感程度', fill: '#fdeeee', stroke: '#d97070' },
    ],
    widths: [0.72, 0.84, 0.9, 1, 0.88],
    caption: 'SVD 比特征分解更通用；降维的本质是保留主要方向、丢弃噪声与小扰动。',
  },
  math_calculus_gradient: {
    image: 'diagram_math_calculus.webp',
    alt: '梯度下降与反向传播',
    title: '微积分与梯度：模型如何学习',
    type: 'flow',
    steps: [
      { title: '偏导数', desc: '固定其他变量，看单个方向的变化率' },
      { title: '梯度', desc: '指向函数增长最快的方向' },
      { title: '链式法则', desc: '复合函数逐层求导' },
      { title: '反向传播', desc: '从损失反向计算每层梯度' },
      { title: '优化器更新', desc: '按学习率沿负梯度更新参数' },
    ],
    notes: ['学习率过大会震荡，过小会收敛慢；可用调度与自适应优化器'],
    caption: '训练就是沿负梯度方向不断降低损失；链式法则是反向传播的数学基础。',
  },
  math_probability_stats: {
    image: 'diagram_math_probability.webp',
    alt: '假设检验与 A/B 实验流程',
    title: '概率统计：从样本到决策',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['置信区间', '样本量', 'p 值', 'A/B 决策'],
    colLabels: ['含义', '计算要点', '常见误用'],
    cells: [
      { r: 0, c: 0, text: '参数的可能范围' },
      { r: 0, c: 1, text: '标准误与置信水平' },
      { r: 0, c: 2, text: '把区间当作个体范围' },
      { r: 1, c: 0, text: '检测效应所需样本数' },
      { r: 1, c: 1, text: '效应量、方差与功效' },
      { r: 1, c: 2, text: '样本不足就下结论' },
      { r: 2, c: 0, text: '原假设下观测更极端的概率' },
      { r: 2, c: 1, text: '与显著性水平比较' },
      { r: 2, c: 2, text: 'p 值不是效应大小' },
      { r: 3, c: 0, text: '用实验决定是否上线' },
      { r: 3, c: 1, text: '预设指标与停止规则' },
      { r: 3, c: 2, text: '多次偷看导致假阳性' },
    ],
    notes: ['统计显著不等于业务显著，要看效应量与置信区间'],
    caption: '统计是把不确定性量化：先设计实验与样本量，再解释结果，而不是反过来。',
  },
  math_information_theory: {
    image: 'diagram_math_information.webp',
    alt: '熵、交叉熵与 KL 散度',
    title: '信息论：损失函数的来源',
    type: 'compare',
    columns: [
      { title: '熵与困惑度', items: ['熵衡量分布的不确定性', '均匀分布熵最大', '困惑度是熵的指数形式', '语言模型常用困惑度评估', '单位与对数底有关'] },
      { title: '交叉熵与 KL', items: ['交叉熵衡量用预测分布编码真实分布的代价', '分类损失就是交叉熵', 'KL 衡量两个分布的差异', 'KL 非负且不对称', '最小化交叉熵等价最小化 KL'] },
    ],
    notes: ['标签平滑与温度缩放都会改变分布，从而影响损失与置信度'],
    caption: '交叉熵是分类模型的默认损失，理解它就能理解模型在优化什么。',
  },
  math_convex_optimization: {
    image: 'diagram_math_convex.webp',
    alt: '凸优化与正则化',
    title: '凸优化：局部最优即全局最优',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['凸性判定', 'KKT 条件', 'L1/L2 正则', '投影梯度'],
    colLabels: ['含义', '作用', '应用'],
    cells: [
      { r: 0, c: 0, text: '函数图像上任意两点连线在上方' },
      { r: 0, c: 1, text: '保证局部最优是全局最优' },
      { r: 0, c: 2, text: '线性模型与 SVM' },
      { r: 1, c: 0, text: '约束优化的最优性条件' },
      { r: 1, c: 1, text: '判断解是否满足约束' },
      { r: 1, c: 2, text: '对偶问题与支持向量' },
      { r: 2, c: 0, text: 'L1 稀疏，L2 平滑' },
      { r: 2, c: 1, text: '控制过拟合与特征选择' },
      { r: 2, c: 2, text: 'LASSO 与岭回归' },
      { r: 3, c: 0, text: '带约束时先走梯度再投影' },
      { r: 3, c: 1, text: '处理简单约束集合' },
      { r: 3, c: 2, text: '非负约束与稀疏优化' },
    ],
    notes: ['深度学习损失通常非凸，但仍可借助凸优化直觉设计正则与优化策略'],
    caption: '凸性给出最优性保证；正则化用约束控制模型复杂度。',
  },
  math_graph_combinatorics: {
    image: 'diagram_math_graph_combinatorics.webp',
    alt: '图论与组合计数',
    title: '图论与组合：离散结构的计数',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['图与路径', '连通与环', '排列组合', '容斥与错排'],
    colLabels: ['核心概念', '判定条件', '典型问题'],
    cells: [
      { r: 0, c: 0, text: '顶点与边的集合' },
      { r: 0, c: 1, text: '最短路、遍历与拓扑排序' },
      { r: 0, c: 2, text: '依赖调度与路径规划' },
      { r: 1, c: 0, text: '连通分量与欧拉回路' },
      { r: 1, c: 1, text: '奇点个数决定欧拉路径' },
      { r: 1, c: 2, text: '网络结构与环检测' },
      { r: 2, c: 0, text: '有序与无序选择' },
      { r: 2, c: 1, text: '加法与乘法原理' },
      { r: 2, c: 2, text: '概率与算法计数' },
      { r: 3, c: 0, text: '交叠集合的计数' },
      { r: 3, c: 1, text: '容斥原理去重' },
      { r: 3, c: 2, text: '错排与全排列问题' },
    ],
    notes: ['组合计数常用于复杂度分析与概率算法正确性证明'],
    caption: '图论描述关系结构，组合数学提供计数方法；两者是算法分析的共同基础。',
  },
  math_numerical_linear_algebra: {
    image: 'diagram_math_numerical.webp',
    alt: 'LU、QR 与 SVD 的选型',
    title: '数值线代：选对分解方式',
    type: 'compare',
    columns: [
      { title: 'LU 与 QR', items: ['LU 适合解线性方程组', '需要选主元保证稳定', 'QR 正交性强，适合最小二乘', 'QR 数值稳定性通常更好', '稀疏矩阵要用专门算法'] },
      { title: 'SVD 与迭代法', items: ['SVD 最稳定但计算量大', '适合降维、伪逆与秩估计', '迭代法适合大规模稀疏问题', '收敛速度依赖条件数', '条件数大要预处理'] },
    ],
    notes: ['不要直接求逆矩阵，能用分解或求解器就不要显式求逆'],
    caption: '数值计算关注稳定性与复杂度：同一个数学问题，不同算法的误差可能差很多。',
  },
};
