// P8 计算机基础、算法、数据库、AI 与分布式补充配图数据。
module.exports = {
  memory_cache: {
    image: 'diagram_mem_cache.webp',
    alt: '存储层次与缓存局部性',
    title: '内存与缓存：越近越快，越远越大',
    type: 'layers',
    layers: [
      { title: '寄存器', desc: '纳秒级，容量最小，由编译器分配', fill: '#eef4ff', stroke: '#6c8ff8' },
      { title: 'L1 / L2 缓存', desc: '每核私有，命中延迟极低', fill: '#e8f2ff', stroke: '#6c8ff8' },
      { title: 'L3 缓存', desc: '多核共享，容量更大但更慢', fill: '#e6f7f1', stroke: '#3fae8a' },
      { title: '主内存', desc: 'DRAM，容量大但延迟显著', fill: '#fff4e6', stroke: '#e6a23c' },
      { title: 'SSD 与磁盘', desc: '持久化存储，按页与块访问', fill: '#fdeeee', stroke: '#d97070' },
    ],
    widths: [0.62, 0.76, 0.86, 1, 0.94],
    notes: ['局部性：时间上重复访问与空间上相邻访问更易命中'],
    caption: '性能优化的关键是提高缓存命中率：让数据连续、访问集中、避免伪共享。',
  },
  time_complexity: {
    image: 'diagram_algo_time_complexity.webp',
    alt: '常见时间复杂度的增长趋势',
    title: '时间复杂度：规模增长下的趋势',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
    colLabels: ['含义', '典型算法', '数据翻倍时'],
    cells: [
      { r: 0, c: 0, text: '与规模无关' },
      { r: 0, c: 1, text: '数组随机访问、哈希查找' },
      { r: 0, c: 2, text: '耗时基本不变' },
      { r: 1, c: 0, text: '每次缩小一半' },
      { r: 1, c: 1, text: '二分查找、平衡树' },
      { r: 1, c: 2, text: '只增加一个常数步' },
      { r: 2, c: 0, text: '随规模线性增长' },
      { r: 2, c: 1, text: '线性扫描、单层循环' },
      { r: 2, c: 2, text: '耗时约翻倍' },
      { r: 3, c: 0, text: '分治加线性合并' },
      { r: 3, c: 1, text: '归并排序、堆排序' },
      { r: 3, c: 2, text: '耗时略多于翻倍' },
    ],
    notes: ['还有 O(n²)、O(2ⁿ) 与 O(n!)；分析时关注主导项与最坏情况'],
    caption: '大 O 描述增长趋势而非绝对耗时；常数因子在小规模下同样重要。',
  },
  hash_table: {
    image: 'diagram_algo_hash_table.webp',
    alt: '哈希表的冲突处理与扩容',
    title: '哈希表：平均 O(1) 的背后',
    type: 'flow',
    steps: [
      { title: '计算哈希', desc: '把 key 映射到桶下标' },
      { title: '冲突处理', desc: '链地址法或开放寻址' },
      { title: '负载因子', desc: '元素数与桶数之比' },
      { title: '扩容重哈希', desc: '桶数翻倍并重新分布元素' },
      { title: '渐进式迁移', desc: '大表分批迁移避免长停顿' },
    ],
    notes: ['哈希函数要均匀且稳定；恶意构造的 key 会造成退化'],
    caption: '哈希表用空间换时间；负载因子过高会退化到 O(n)，扩容策略决定抖动。',
  },
  transaction: {
    image: 'diagram_db_transaction.webp',
    alt: '事务 ACID 与隔离级别',
    title: '事务：ACID 与隔离级别的取舍',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['原子性', '一致性', '隔离性', '持久性'],
    colLabels: ['保证', '实现机制', '隔离级别影响'],
    cells: [
      { r: 0, c: 0, text: '要么全成功要么全回滚' },
      { r: 0, c: 1, text: 'undo 日志与回滚' },
      { r: 0, c: 2, text: '所有级别都保证' },
      { r: 1, c: 0, text: '约束与业务不变量成立' },
      { r: 1, c: 1, text: '约束检查与锁' },
      { r: 1, c: 2, text: '需要应用层配合' },
      { r: 2, c: 0, text: '并发事务互不干扰' },
      { r: 2, c: 1, text: '锁、MVCC 与快照' },
      { r: 2, c: 2, text: '读未提交到串行化' },
      { r: 3, c: 0, text: '提交后数据不丢失' },
      { r: 3, c: 1, text: 'redo 日志与刷盘' },
      { r: 3, c: 2, text: '取决于持久化配置' },
    ],
    notes: ['隔离级别越高一致性越强，但并发度与吞吐通常越低'],
    caption: '并发异常与隔离级别是事务设计的核心：先明确业务能容忍哪种异常。',
  },
  ai_deep_learning_llm: {
    image: 'diagram_ai_dl_llm.webp',
    alt: '从神经网络到大语言模型',
    title: '深度学习与大语言模型：一脉相承',
    type: 'sequence',
    actors: ['输入数据', '神经网络', 'Transformer', '采样输出'],
    messages: [
      { from: 0, to: 1, label: '特征向量化并前向传播' },
      { from: 1, to: 1, label: '反向传播更新参数' },
      { from: 2, to: 2, label: '注意力机制建模上下文' },
      { from: 2, to: 3, label: '输出下一个 token 概率' },
      { from: 3, to: 2, label: '按温度与 Top-p 采样' },
      { from: 3, to: 0, label: '生成文本可能包含幻觉' },
    ],
    notes: ['温度越高越发散，越低越确定；幻觉来自概率生成而非事实核查'],
    caption: '大语言模型是 Transformer 与海量数据训练的产物；采样参数决定输出的多样性与稳定性。',
  },
  ai_agent_basics: {
    image: 'diagram_ai_agent_basics.webp',
    alt: 'ReAct 循环与工具调用',
    title: 'AI Agent：思考、行动、观察',
    type: 'cycle',
    nodes: [
      { title: '感知', desc: '接收目标与上下文' },
      { title: '推理', desc: '拆解任务并规划' },
      { title: '行动', desc: '调用工具执行' },
      { title: '观察', desc: '读取执行结果' },
      { title: '记忆', desc: '更新状态与经验' },
    ],
    center: 'ReAct 循环',
    notes: ['MCP 统一工具接入协议；权限、超时与预算必须显式控制'],
    caption: 'Agent 与普通对话的区别在于能行动：循环、工具、记忆与护栏缺一不可。',
  },
  distributed_fundamentals: {
    image: 'diagram_dist_fundamentals.webp',
    alt: '分布式系统的核心权衡',
    title: '分布式原理：CAP、复制与一致性',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['CAP', '复制', '一致性模型', '容错'],
    colLabels: ['核心问题', '常见方案', '工程取舍'],
    cells: [
      { r: 0, c: 0, text: '分区时一致性与可用性二选一' },
      { r: 0, c: 1, text: '按业务选择 CP 或 AP' },
      { r: 0, c: 2, text: '没有全局最优解' },
      { r: 1, c: 0, text: '数据在多节点冗余' },
      { r: 1, c: 1, text: '主从、多主与无主复制' },
      { r: 1, c: 2, text: '复制延迟带来读写不一致' },
      { r: 2, c: 0, text: '多副本对读写的承诺' },
      { r: 2, c: 1, text: '线性一致、因果与最终一致' },
      { r: 2, c: 2, text: '按场景选择强度' },
      { r: 3, c: 0, text: '节点故障仍能服务' },
      { r: 3, c: 1, text: '超时、重试、熔断与隔离' },
      { r: 3, c: 2, text: '假设网络与节点都会失败' },
    ],
    notes: ['分布式系统的本质是处理部分失败：没有全局时钟，也没有绝对可靠网络'],
    caption: 'CAP 是极端情况下的取舍；工程上更常见的是在延迟、一致性与可用性之间调平衡。',
  },
  messaging_events: {
    image: 'diagram_dist_messaging.webp',
    alt: '消息队列的投递与消费',
    title: '消息队列：投递语义与幂等',
    type: 'sequence',
    actors: ['生产者', 'Broker', '消费者', '死信队列'],
    messages: [
      { from: 0, to: 1, label: '发送消息并等待确认' },
      { from: 1, to: 1, label: '持久化并按分区追加' },
      { from: 1, to: 2, label: '推送或拉取消息' },
      { from: 2, to: 1, label: '处理成功后提交位点' },
      { from: 2, to: 2, label: '重复投递时按业务键幂等' },
      { from: 1, to: 3, label: '多次失败后转入死信' },
    ],
    notes: ['至少一次投递加幂等消费，是多数业务的可靠组合'],
    caption: '消息队列把同步调用改为异步解耦；投递语义、顺序与幂等必须一起设计。',
  },
  distributed_short_url_project: {
    image: 'diagram_dist_short_url.webp',
    alt: '短链服务的请求链路',
    title: '实战短链服务：发号、缓存与分片',
    type: 'flow',
    steps: [
      { title: '容量估算', desc: '写入量、读取量与存储增长' },
      { title: '发号器', desc: '生成全局唯一短码或自增 ID' },
      { title: '缓存加速', desc: '热点短码优先命中缓存' },
      { title: '分片存储', desc: '按短码哈希分片水平扩展' },
      { title: '限流与统计', desc: '防刷、点击统计与过期清理' },
    ],
    notes: ['短链是读多写少场景，缓存命中率决定整体性能'],
    caption: '短链服务的核心是 ID 生成与读性能；分片键、缓存与过期策略要统一设计。',
  },
  distributed_id: {
    image: 'diagram_dist_id.webp',
    alt: '分布式 ID 生成方案对比',
    title: '分布式 ID：唯一、有序与可用',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['雪花算法', '号段模式', '时钟回拨', '选型维度'],
    colLabels: ['结构', '优点', '风险'],
    cells: [
      { r: 0, c: 0, text: '时间戳 + 机器位 + 序列号' },
      { r: 0, c: 1, text: '趋势递增，性能高' },
      { r: 0, c: 2, text: '依赖机器时钟' },
      { r: 1, c: 0, text: '数据库批量分配 ID 区间' },
      { r: 1, c: 1, text: '减少数据库压力' },
      { r: 1, c: 2, text: '号段浪费与依赖数据库' },
      { r: 2, c: 0, text: '时间倒退导致重复风险' },
      { r: 2, c: 1, text: '等待、备用位或告警' },
      { r: 2, c: 2, text: '必须显式处理而非忽略' },
      { r: 3, c: 0, text: '唯一性、有序性、可用性' },
      { r: 3, c: 1, text: '按业务要求排序强度' },
      { r: 3, c: 2, text: '不要为了严格有序牺牲可用' },
    ],
    notes: ['ID 一旦对外暴露，长度与可读性也要纳入设计'],
    caption: '分布式 ID 的取舍是唯一性、趋势有序与可用性；时钟回拨必须有确定策略。',
  },
  distributed_rate_limit: {
    image: 'diagram_dist_rate_limit.webp',
    alt: '限流与熔断算法对比',
    title: '限流与熔断：保护系统不被压垮',
    type: 'compare',
    columns: [
      { title: '四种限流算法', items: ['固定窗口简单但有临界突刺', '滑动窗口平滑统计', '漏桶以恒定速率流出', '令牌桶允许突发流量', '按维度限流：用户、IP、接口'] },
      { title: '熔断与隔离', items: ['熔断三态：关闭、打开、半开', '失败率与慢调用触发', '舱壁隔离限制资源池', '降级返回缓存或默认值', '限流保护自身，熔断保护下游'] },
    ],
    notes: ['分布式限流需要共享计数或集中决策，注意一致性与性能成本'],
    caption: '限流控制进入速率，熔断阻止故障扩散；两者组合才能在过载时保持核心可用。',
  },
};
