// P8 操作系统课程配图数据。
module.exports = {
  process_thread_intro: {
    image: 'diagram_os_process_intro.webp',
    alt: '进程、线程与上下文切换',
    title: '进程与线程入门：隔离与共享',
    type: 'layers',
    layers: [
      { title: '进程', desc: '独立地址空间与资源集合', fill: '#eef4ff', stroke: '#6c8ff8' },
      { title: '线程', desc: '进程内的执行流，共享地址空间', fill: '#e8f2ff', stroke: '#6c8ff8' },
      { title: '上下文切换', desc: '保存与恢复寄存器、栈与页表', fill: '#e6f7f1', stroke: '#3fae8a' },
      { title: '调度', desc: '按优先级与时间片分配 CPU', fill: '#fff4e6', stroke: '#e6a23c' },
      { title: '并发安全', desc: '共享数据需要同步与可见性保证', fill: '#fdeeee', stroke: '#d97070' },
    ],
    widths: [0.72, 0.84, 0.9, 1, 0.94],
    caption: '进程隔离强、切换贵；线程共享多、切换便宜，但必须自己处理数据竞争。',
  },
  process_thread: {
    image: 'diagram_os_process_thread.webp',
    alt: '进程与线程的区别',
    title: '进程与线程：两种并发单位',
    type: 'compare',
    columns: [
      { title: '进程', items: ['独立地址空间与文件描述符', '进程间通信需要显式机制', '崩溃通常不影响其他进程', '创建与切换开销较大', '适合隔离与多租户'] },
      { title: '线程', items: ['共享进程地址空间与资源', '通信直接但需要同步', '一个线程崩溃可能拖垮进程', '创建与切换开销较小', '适合并行计算与 IO 等待'] },
    ],
    notes: ['协程在用户态调度，切换更轻，但阻塞调用会卡住线程'],
    caption: '选择并发模型先看隔离需求与通信成本；共享越少，同步风险越低。',
  },
  deadlock: {
    image: 'diagram_os_deadlock.webp',
    alt: '死锁的四个必要条件',
    title: '死锁：四个条件同时成立',
    type: 'cycle',
    nodes: [
      { title: '互斥', desc: '资源同一时刻只能被一个持有' },
      { title: '占有并等待', desc: '持有资源同时等待新资源' },
      { title: '不可剥夺', desc: '资源不能被强制抢占' },
      { title: '循环等待', desc: '形成首尾相接的等待环' },
    ],
    center: '死锁',
    notes: ['破坏任一条件即可预防：统一加锁顺序最常用'],
    caption: '排查死锁先拿到线程栈与锁持有关系，再确认等待环与资源归属。',
  },
  virtual_memory: {
    image: 'diagram_os_virtual_memory.webp',
    alt: '虚拟内存与分页机制',
    title: '虚拟内存：分页、页表与置换',
    type: 'layers',
    layers: [
      { title: '虚拟地址', desc: '进程看到的连续地址空间', fill: '#eef4ff', stroke: '#6c8ff8' },
      { title: '分页', desc: '地址拆为页号与页内偏移', fill: '#e8f2ff', stroke: '#6c8ff8' },
      { title: '页表', desc: '虚拟页到物理帧的映射', fill: '#e6f7f1', stroke: '#3fae8a' },
      { title: '缺页中断', desc: '访问未驻留页时触发加载', fill: '#fff4e6', stroke: '#e6a23c' },
      { title: '置换算法', desc: 'LRU 近似选择淘汰页面', fill: '#fdeeee', stroke: '#d97070' },
    ],
    widths: [0.72, 0.82, 0.9, 1, 0.88],
    caption: '虚拟内存提供隔离与超量使用能力；频繁缺页会造成系统抖动。',
  },
  os_filesystem_impl: {
    image: 'diagram_os_filesystem.webp',
    alt: '文件系统与 RAID 的关键机制',
    title: '文件系统实现：inode、日志与 RAID',
    type: 'layers',
    layers: [
      { title: 'inode 与目录', desc: '元数据与多级索引定位数据块', fill: '#eef4ff', stroke: '#6c8ff8' },
      { title: '日志与 COW', desc: '先写日志或写时复制保证一致性', fill: '#e8f2ff', stroke: '#6c8ff8' },
      { title: '缓存与预读', desc: '页缓存减少磁盘随机访问', fill: '#e6f7f1', stroke: '#3fae8a' },
      { title: 'RAID', desc: '镜像、条带与校验权衡性能与可靠', fill: '#fff4e6', stroke: '#e6a23c' },
      { title: 'SSD 特性', desc: '磨损均衡、TRIM 与写放大', fill: '#fdeeee', stroke: '#d97070' },
    ],
    widths: [0.72, 0.84, 0.9, 1, 0.92],
    caption: '文件系统要在性能、空间与崩溃一致性之间取舍；RAID 不是备份。',
  },
  os_kernel_arch: {
    image: 'diagram_os_kernel_arch.webp',
    alt: '宏内核与微内核架构对比',
    title: '内核架构：宏内核与微内核',
    type: 'compare',
    columns: [
      { title: '宏内核', items: ['文件系统、网络与驱动在内核态', '调用路径短，性能高', '模块耦合度高', '一个驱动崩溃可能影响系统', 'Linux 是典型代表'] },
      { title: '微内核', items: ['内核只保留调度与 IPC 等最小功能', '驱动与服务运行在用户态', '隔离性好，故障域小', '跨进程通信带来开销', 'QNX、seL4 是典型代表'] },
    ],
    notes: ['混合内核在性能与隔离之间折中，Windows 与 macOS 属于此类'],
    caption: '内核架构的核心取舍是性能与隔离：内核越小，故障域越小，但通信成本越高。',
  },
  os_rtos: {
    image: 'diagram_os_rtos.webp',
    alt: '实时操作系统的关键概念',
    title: '实时系统：确定性比平均性能更重要',
    type: 'grid',
    rows: 4,
    cols: 3,
    rowLabels: ['硬实时', '软实时', '优先级反转', '调度延迟'],
    colLabels: ['含义', '要求', '常见处理'],
    cells: [
      { r: 0, c: 0, text: '错过截止时间即失败' },
      { r: 0, c: 1, text: '最坏执行时间必须可证明' },
      { r: 0, c: 2, text: '静态优先级与抢占式调度' },
      { r: 1, c: 0, text: '偶尔超时只降低体验' },
      { r: 1, c: 1, text: '统计意义上满足时限' },
      { r: 1, c: 2, text: '尽力而为与降级策略' },
      { r: 2, c: 0, text: '低优先级任务阻塞高优先级' },
      { r: 2, c: 1, text: '导致高优先级错过时限' },
      { r: 2, c: 2, text: '优先级继承或天花板协议' },
      { r: 3, c: 0, text: '事件到任务响应的时间' },
      { r: 3, c: 1, text: '关注最坏值而非平均值' },
      { r: 3, c: 2, text: '减少关中断与不可抢占区' },
    ],
    notes: ['实时不等于快，而是响应时间有上界且可预测'],
    caption: '实时系统的核心指标是最坏情况延迟与抖动，设计要围绕可证明性展开。',
  },
  os_linux_troubleshooting: {
    image: 'diagram_os_linux_troubleshoot.webp',
    alt: 'Linux 性能排查的常用工具链',
    title: 'Linux 排查：从资源到调用栈',
    type: 'flow',
    steps: [
      { title: 'top / htop', desc: '看 CPU、内存与负载概览' },
      { title: 'vmstat', desc: '看上下文切换、交换与 IO 等待' },
      { title: 'iostat', desc: '定位磁盘吞吐、延迟与队列' },
      { title: 'ss / netstat', desc: '查看连接状态与端口占用' },
      { title: 'perf / trace', desc: '定位热点函数与内核事件' },
    ],
    notes: ['先看资源饱和度与错误率，再深入单进程与调用栈'],
    caption: '排查顺序是从全局到局部：先确认瓶颈类型，再用工具验证假设。',
  },
  os_project: {
    image: 'diagram_os_task_project.webp',
    alt: '多线程任务队列的实现要点',
    title: '实战任务队列：四个并发难点',
    type: 'flow',
    steps: [
      { title: '队列与锁', desc: '互斥保护队列，条件变量唤醒' },
      { title: '竞态消除', desc: '确定共享状态与同步边界' },
      { title: '避免死锁', desc: '统一锁顺序，避免持锁等待' },
      { title: '优雅退出', desc: '广播停止信号并回收线程' },
      { title: '背压控制', desc: '队列上限与拒绝策略' },
    ],
    notes: ['优雅退出需要解决「停止后仍有在途任务」的语义'],
    caption: '并发队列的难点是正确性：竞态、死锁、退出与背压缺一不可。',
  },
};
